#ifndef POKEHEARTGOLD_BATTLE_COMMAND_H
#define POKEHEARTGOLD_BATTLE_COMMAND_H

#include "battle/battle.h"
#include "battle/battle_system.h"

// Realistically these should all be static in battle_command.c, but the command table that needs them is in src/battle/overlay_12_0226C3E8.c, a file of its own for the layout of retail's read-only data, so they stay public, and declared here so the compiler does not allow a function without a declaration

BOOL RunBattleScript(BattleSystem *battleSystem, BattleContext *ctx);
int BeatUp_TotalPower(BattleSystem *battleSystem, BattleContext *ctx, int battlerId);
void BattleContext_LandFutureSight(BattleSystem *battleSystem, BattleContext *ctx, int battlerIdTarget);
BOOL BtlCmd_PlayEncounterAnimation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetPokemonEncounter(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PokemonSlideIn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PokemonSendOut(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RecallPokemon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_DeletePokemon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetTrainerEncounter(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ThrowPokeball(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrainerSlideOut(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrainerSlideIn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BackgroundSlideIn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HealthbarSlideIn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HealthbarSlideInDelay(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HealthbarSlideOut(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Wait(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcDamage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcDamageRaw(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintAttackMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintGlobalMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintBufferedMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BufferMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BufferLocalMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayMoveAnimation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayMoveAnimationOnMons(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_FlickerMon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateHealthbarValue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateHealthbar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryFaintMon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayFaintAnimation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitButtonABTime(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlaySound(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CompareVarToValue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CompareMonDataToValue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_FadeOutBattle(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToSubscript(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToEffectScript(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToMoveScript(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcCrit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcExpGain(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_StartGetExpTask(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitGetExpTask(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitGetExpTaskLoop(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ShowParty(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitMonSelection(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SwitchAndUpdateMon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToIfAnySwitches(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_StartCatchMonTask(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitCatchMonTask(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetMultiHit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ChangeStatStage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateMonData(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ClearVolatileStatus(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ToggleVanish(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckAbility(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Random(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateVar2(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateMonDataFromVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Goto(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Call(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CallFromVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetMirrorMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ResetAllStatChanges(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_LockMoveChoice(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UnlockMoveChoice(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetHealthbarStatus(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintTrainerMessage(BattleSystem *battleSystem, BattleContext *ctx);
u32 CalcPrizeMoney(BattleSystem *battleSystem, BattleContext *ctx, int trainerIndex);
BOOL BtlCmd_PayPrizeMoney(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayBattleAnimation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayBattleAnimationOnMons(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayBattleAnimationFromVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintRecallMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintSendOutMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintEncounterMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintFirstSendOutMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintBufferedTrainerMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryConversion(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CompareVarToVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CompareMonDataToVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_AddPayDayMoney(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryLightScreen(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryReflect(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryMist(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryOHKOMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_DivideVarByValue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_DivideVarByVar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryMimic(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Metronome(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryDisable(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Counter(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_MirrorCoat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryEncore(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryConversion2(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySketch(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySleepTalk(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcFlailPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySpite(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryPartyStatusRefresh(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryStealItem(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryProtection(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySubstitute(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryWhirlwind(BattleSystem *battleSystem, BattleContext *ctx);
BOOL TryPickForcedSwitchIn(BattleSystem *battleSystem, BattleContext *ctx, int battlerId);
void TrySetGemBoost(BattleContext *ctx);
BOOL BtlCmd_Transform(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySpikes(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckSpikes(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryPerishSong(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetTurnOrderBySpeed(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToIfValidMon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_EndOfTurnWeatherEffect(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcRolloutPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcFuryCutterPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryAttract(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySafeguard(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_Present(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcMagnitudePower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryReplaceFaintedMon(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RapidSpin(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WeatherHPRecovery(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcHiddenPowerParams(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CopyStatStages(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryFutureSight(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckMoveHit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryTeleport(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BeatUp(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_FollowMe(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryHelpingHand(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySwapItems(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryWish(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryAssist(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySetMagicCoat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_MagicCoat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcRevengeDamageMul(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryBreakScreens(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryYawn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryKnockOff(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcHPFalloffPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryImprison(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryGrudge(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySnatch(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcWeightBasedPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcWeatherBallParams(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryPursuit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ApplyTypeEffectiveness(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IfTurnFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetTurnFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcGyroBallPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryMetalBurst(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcPaybackPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcTrumpCardPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcWringOutPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryMeFirst(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryCopycat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcPunishmentPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySuckerPunch(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckSideCondition(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryFeint(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryPyschoShift(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryLastResort(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryToxicSpikes(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckToxicSpikes(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckIgnorableAbility(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IfSameSide(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GenerateEndOfBattleItem(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrickRoom(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IfMovedThisTurn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckItemHoldEffect(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetItemHoldEffect(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetItemEffectParam(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryCamouflage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetTerrainMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetTerrainSecondaryEffect(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcNaturalGiftParams(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryPluck(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryFling(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_YesNoMenu(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitYesNoResult(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ChoosePokemonMenu(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitPokemonMenuResult(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetLinkBattleResult(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckStealthRock(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckEffectActivation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckChatterActivation(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetCurrentMoveData(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetMosaic(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ChangeForm(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetBattleBackground(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UseBagItem(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryEscape(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ShowBattleStartPartyGauge(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HideBattleStartPartyGauge(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ShowPartyGauge(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HidePartyGauge(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_LoadPartyGaugeGraphics(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_FreePartyGaugeGraphics(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IncrementGameStat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RestoreSprite(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TriggerAbilityOnHit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SpriteToOAM(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_OAMToSprite(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckWhiteout(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BoostRandomStatBy2(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RemoveItem(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryRecycle(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckItemHoldEffectOnHit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintBattleResultMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintEscapeMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PrintForfeitMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckHoldOnWith1HP(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryRestoreStatusOnSwitch(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckSubstitute(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckIgnoreWeather(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetRandomTarget(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckItemHoldEffectOnUTurn(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RefreshSprite(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayMoveHitSound(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_PlayBGM(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckSafariGameDone(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_WaitTime(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckCurMoveIsType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_LoadArchivedMonData(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RefreshMonData(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_222(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_223(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_EndScript(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_NotImplemented(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_AddType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleForestsCurse(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleTrickOrTreat(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToIfThirdType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_AddEntryHazardToQueue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_RemoveEntryHazardFromQueue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_JumpToCurrentEntryHazard(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_StuffCheeks(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GetMonByCottonDownOrder(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SwitchInAbilityCheck(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ChangeExecutionOrderPriority(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ChangePermanentBackground(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfCurrentFieldIsType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_UpdateTerrainOverlay(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfTerrainOverlayIsType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetPsychicTerrainMoveUsedFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfFirstHitOfParentalBond(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfSecondHitOfParentalBond(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetParentalBondFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfCurrentMoveIsValidForParentalBond(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfParentalBondIsActive(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfCanApplyKnockOffBoost(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CanClearPrimalWeather(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryMegaOrUltraBurstDuringPursuit(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoToIfTerastallized(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ActivateParadoxAbility(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ResetParadoxAbility(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_MakeTotem(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryActivateZeroToHero(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetAbilityActivatedFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_AbilityPopup(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetMoveConditionFlag(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetCurrentMoveSwitchingStatus(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TrySynchronizeStatus(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryCureStatusBerry(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BatchUpdateHealthBar(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BatchUpdateHealthBarValue(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BatchFollowupMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_BatchEffectivenessMessage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryStickyWeb(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryAuroraVeil(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ClearAuroraVeil(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckProtectContactMoves(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleRoost(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleSoak(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleMagicPowder(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleBurnUp(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_HandleDoubleShock(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_TryIncinerate(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckCanActivateDefiantOrCompetitive(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetTailwindCounter(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfTailwindActive(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfGrounded(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_SetBindingTurns(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ClearBindingTurns(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcConfusionDamage(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_StrengthSapCalc(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ClearSmog(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IsPursuitActive(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GoBackToBeforeMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_ReduceWeight(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CalcHeavySlamPower(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_IsAttackerLevelLowerThanDefender(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfMovePowerNotZero(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfCurrentAdjustedMoveIsType(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfContactMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_GotoIfSoundMove(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_CheckTargetIsPartner(BattleSystem *battleSystem, BattleContext *ctx);
BOOL BtlCmd_DivideVarByValueRoundUp(BattleSystem *battleSystem, BattleContext *ctx);
int BattleScriptReadWord(BattleContext *ctx);

// battle_command.c's read-only tables, defined in asm/overlay_12_battle_command.s,
// src/battle/overlay_12_0226C2F8.c, asm/overlay_12_0226C324.s,
// src/battle/overlay_12_0226C3E8.c and src/battle/overlay_12_0226CA4C.c, in
// that order, which is retail's.
typedef struct TempStatsStruct {
    u32 stats[6];
} TempStatsStruct;

extern const u8 sTrumpCardPowerTable[5];
extern const u16 sProtectSuccessChance[7];
extern const u8 sFlailDamageTable[6][2];
extern const u16 sPickupTable2[11];
extern const TempStatsStruct ov12_0226C33C;
extern const TempStatsStruct ov12_0226C354;
extern const TempStatsStruct ov12_0226C36C;
extern const TempStatsStruct ov12_0226C384;
extern const u16 sLowKickDamageTable[6][2];
extern const u16 sNaturePowerMoveTable[13];
extern const u8 sSafariCatchRateStages[13][2];
extern const u16 sMoonBallPokemon[6];
extern const u16 sPickupTable1[18];
extern const ManagedSpriteTemplate sLevelUpNameplateTemplate;
extern const ManagedSpriteTemplate sPokeIconTemplate;
extern const u32 sSecretPowerEffectTable[13];
extern const u16 sPrizeMoneyTbl[0x81][2];
extern const BtlCmdFunc sBattleScriptCommandTable[];
extern const u8 sPickupWeightTable[9];
extern const u8 sHoneyGatherChanceTable[10];
extern const u8 sCamouflageTypeTable[13];

#endif
