#ifndef POKEHEARTGOLD_CONSTANTS_FOLLOW_MON_IDX_H
#define POKEHEARTGOLD_CONSTANTS_FOLLOW_MON_IDX_H

#define FOLLOWER_MON_NONE            0
#define FOLLOWER_MON_BULBASAUR       0
#define FOLLOWER_MON_IVYSAUR         1
#define FOLLOWER_MON_VENUSAUR        2
#define FOLLOWER_MON_VENUSAUR_F      3
#define FOLLOWER_MON_CHARMANDER      4
#define FOLLOWER_MON_CHARMELEON      5
#define FOLLOWER_MON_CHARIZARD       6
#define FOLLOWER_MON_SQUIRTLE        7
#define FOLLOWER_MON_WARTORTLE       8
#define FOLLOWER_MON_BLASTOISE       9
#define FOLLOWER_MON_CATERPIE        10
#define FOLLOWER_MON_METAPOD         11
#define FOLLOWER_MON_BUTTERFREE      12
#define FOLLOWER_MON_WEEDLE          13
#define FOLLOWER_MON_KAKUNA          14
#define FOLLOWER_MON_BEEDRILL        15
#define FOLLOWER_MON_PIDGEY          16
#define FOLLOWER_MON_PIDGEOTTO       17
#define FOLLOWER_MON_PIDGEOT         18
#define FOLLOWER_MON_RATTATA         19
#define FOLLOWER_MON_RATICATE        20
#define FOLLOWER_MON_SPEAROW         21
#define FOLLOWER_MON_FEAROW          22
#define FOLLOWER_MON_EKANS           23
#define FOLLOWER_MON_ARBOK           24
#define FOLLOWER_MON_PIKACHU         25
#define FOLLOWER_MON_PIKACHU_F       26
#define FOLLOWER_MON_RAICHU          27
#define FOLLOWER_MON_SANDSHREW       28
#define FOLLOWER_MON_SANDSLASH       29
#define FOLLOWER_MON_NIDORAN_F       30
#define FOLLOWER_MON_NIDORINA        31
#define FOLLOWER_MON_NIDOQUEEN       32
#define FOLLOWER_MON_NIDORAN_M       33
#define FOLLOWER_MON_NIDORINO        34
#define FOLLOWER_MON_NIDOKING        35
#define FOLLOWER_MON_CLEFAIRY        36
#define FOLLOWER_MON_CLEFABLE        37
#define FOLLOWER_MON_VULPIX          38
#define FOLLOWER_MON_NINETALES       39
#define FOLLOWER_MON_JIGGLYPUFF      40
#define FOLLOWER_MON_WIGGLYTUFF      41
#define FOLLOWER_MON_ZUBAT           42
#define FOLLOWER_MON_GOLBAT          43
#define FOLLOWER_MON_ODDISH          44
#define FOLLOWER_MON_GLOOM           45
#define FOLLOWER_MON_VILEPLUME       46
#define FOLLOWER_MON_PARAS           47
#define FOLLOWER_MON_PARASECT        48
#define FOLLOWER_MON_VENONAT         49
#define FOLLOWER_MON_VENOMOTH        50
#define FOLLOWER_MON_DIGLETT         51
#define FOLLOWER_MON_DUGTRIO         52
#define FOLLOWER_MON_MEOWTH          53
#define FOLLOWER_MON_PERSIAN         54
#define FOLLOWER_MON_PSYDUCK         55
#define FOLLOWER_MON_GOLDUCK         56
#define FOLLOWER_MON_MANKEY          57
#define FOLLOWER_MON_PRIMEAPE        58
#define FOLLOWER_MON_GROWLITHE       59
#define FOLLOWER_MON_ARCANINE        60
#define FOLLOWER_MON_POLIWAG         61
#define FOLLOWER_MON_POLIWHIRL       62
#define FOLLOWER_MON_POLIWRATH       63
#define FOLLOWER_MON_ABRA            64
#define FOLLOWER_MON_KADABRA         65
#define FOLLOWER_MON_ALAKAZAM        66
#define FOLLOWER_MON_MACHOP          67
#define FOLLOWER_MON_MACHOKE         68
#define FOLLOWER_MON_MACHAMP         69
#define FOLLOWER_MON_BELLSPROUT      70
#define FOLLOWER_MON_WEEPINBELL      71
#define FOLLOWER_MON_VICTREEBEL      72
#define FOLLOWER_MON_TENTACOOL       73
#define FOLLOWER_MON_TENTACRUEL      74
#define FOLLOWER_MON_GEODUDE         75
#define FOLLOWER_MON_GRAVELER        76
#define FOLLOWER_MON_GOLEM           77
#define FOLLOWER_MON_PONYTA          78
#define FOLLOWER_MON_RAPIDASH        79
#define FOLLOWER_MON_SLOWPOKE        80
#define FOLLOWER_MON_SLOWBRO         81
#define FOLLOWER_MON_MAGNEMITE       82
#define FOLLOWER_MON_MAGNETON        83
#define FOLLOWER_MON_FARFETCHD       84
#define FOLLOWER_MON_DODUO           85
#define FOLLOWER_MON_DODRIO          86
#define FOLLOWER_MON_SEEL            87
#define FOLLOWER_MON_DEWGONG         88
#define FOLLOWER_MON_GRIMER          89
#define FOLLOWER_MON_MUK             90
#define FOLLOWER_MON_SHELLDER        91
#define FOLLOWER_MON_CLOYSTER        92
#define FOLLOWER_MON_GASTLY          93
#define FOLLOWER_MON_HAUNTER         94
#define FOLLOWER_MON_GENGAR          95
#define FOLLOWER_MON_ONIX            96
#define FOLLOWER_MON_DROWZEE         97
#define FOLLOWER_MON_HYPNO           98
#define FOLLOWER_MON_KRABBY          99
#define FOLLOWER_MON_KINGLER         100
#define FOLLOWER_MON_VOLTORB         101
#define FOLLOWER_MON_ELECTRODE       102
#define FOLLOWER_MON_EXEGGCUTE       103
#define FOLLOWER_MON_EXEGGUTOR       104
#define FOLLOWER_MON_CUBONE          105
#define FOLLOWER_MON_MAROWAK         106
#define FOLLOWER_MON_HITMONLEE       107
#define FOLLOWER_MON_HITMONCHAN      108
#define FOLLOWER_MON_LICKITUNG       109
#define FOLLOWER_MON_KOFFING         110
#define FOLLOWER_MON_WEEZING         111
#define FOLLOWER_MON_RHYHORN         112
#define FOLLOWER_MON_RHYDON          113
#define FOLLOWER_MON_CHANSEY         114
#define FOLLOWER_MON_TANGELA         115
#define FOLLOWER_MON_KANGASKHAN      116
#define FOLLOWER_MON_HORSEA          117
#define FOLLOWER_MON_SEADRA          118
#define FOLLOWER_MON_GOLDEEN         119
#define FOLLOWER_MON_SEAKING         120
#define FOLLOWER_MON_STARYU          121
#define FOLLOWER_MON_STARMIE         122
#define FOLLOWER_MON_MR_MIME         123
#define FOLLOWER_MON_SCYTHER         124
#define FOLLOWER_MON_JYNX            125
#define FOLLOWER_MON_ELECTABUZZ      126
#define FOLLOWER_MON_MAGMAR          127
#define FOLLOWER_MON_PINSIR          128
#define FOLLOWER_MON_TAUROS          129
#define FOLLOWER_MON_MAGIKARP        130
#define FOLLOWER_MON_GYARADOS        131
#define FOLLOWER_MON_LAPRAS          132
#define FOLLOWER_MON_DITTO           133
#define FOLLOWER_MON_EEVEE           134
#define FOLLOWER_MON_VAPOREON        135
#define FOLLOWER_MON_JOLTEON         136
#define FOLLOWER_MON_FLAREON         137
#define FOLLOWER_MON_PORYGON         138
#define FOLLOWER_MON_OMANYTE         139
#define FOLLOWER_MON_OMASTAR         140
#define FOLLOWER_MON_KABUTO          141
#define FOLLOWER_MON_KABUTOPS        142
#define FOLLOWER_MON_AERODACTYL      143
#define FOLLOWER_MON_SNORLAX         144
#define FOLLOWER_MON_ARTICUNO        145
#define FOLLOWER_MON_ZAPDOS          146
#define FOLLOWER_MON_MOLTRES         147
#define FOLLOWER_MON_DRATINI         148
#define FOLLOWER_MON_DRAGONAIR       149
#define FOLLOWER_MON_DRAGONITE       150
#define FOLLOWER_MON_MEWTWO          151
#define FOLLOWER_MON_MEW             152
#define FOLLOWER_MON_CHIKORITA       153
#define FOLLOWER_MON_BAYLEEF         154
#define FOLLOWER_MON_MEGANIUM        155
#define FOLLOWER_MON_MEGANIUM_F      156
#define FOLLOWER_MON_CYNDAQUIL       157
#define FOLLOWER_MON_QUILAVA         158
#define FOLLOWER_MON_TYPHLOSION      159
#define FOLLOWER_MON_TOTODILE        160
#define FOLLOWER_MON_CROCONAW        161
#define FOLLOWER_MON_FERALIGATR      162
#define FOLLOWER_MON_SENTRET         163
#define FOLLOWER_MON_FURRET          164
#define FOLLOWER_MON_HOOTHOOT        165
#define FOLLOWER_MON_NOCTOWL         166
#define FOLLOWER_MON_LEDYBA          167
#define FOLLOWER_MON_LEDIAN          168
#define FOLLOWER_MON_SPINARAK        169
#define FOLLOWER_MON_ARIADOS         170
#define FOLLOWER_MON_CROBAT          171
#define FOLLOWER_MON_CHINCHOU        172
#define FOLLOWER_MON_LANTURN         173
#define FOLLOWER_MON_PICHU           174
#define FOLLOWER_MON_PICHU_SPIKY     175
#define FOLLOWER_MON_CLEFFA          176
#define FOLLOWER_MON_IGGLYBUFF       177
#define FOLLOWER_MON_TOGEPI          178
#define FOLLOWER_MON_TOGETIC         179
#define FOLLOWER_MON_NATU            180
#define FOLLOWER_MON_XATU            181
#define FOLLOWER_MON_MAREEP          182
#define FOLLOWER_MON_FLAAFFY         183
#define FOLLOWER_MON_AMPHAROS        184
#define FOLLOWER_MON_BELLOSSOM       185
#define FOLLOWER_MON_MARILL          186
#define FOLLOWER_MON_AZUMARILL       187
#define FOLLOWER_MON_SUDOWOODO       188
#define FOLLOWER_MON_POLITOED        189
#define FOLLOWER_MON_HOPPIP          190
#define FOLLOWER_MON_SKIPLOOM        191
#define FOLLOWER_MON_JUMPLUFF        192
#define FOLLOWER_MON_AIPOM           193
#define FOLLOWER_MON_SUNKERN         194
#define FOLLOWER_MON_SUNFLORA        195
#define FOLLOWER_MON_YANMA           196
#define FOLLOWER_MON_WOOPER          197
#define FOLLOWER_MON_QUAGSIRE        198
#define FOLLOWER_MON_ESPEON          199
#define FOLLOWER_MON_UMBREON         200
#define FOLLOWER_MON_MURKROW         201
#define FOLLOWER_MON_SLOWKING        202
#define FOLLOWER_MON_MISDREAVUS      203
#define FOLLOWER_MON_UNOWN_A         204
#define FOLLOWER_MON_UNOWN_B         205
#define FOLLOWER_MON_UNOWN_C         206
#define FOLLOWER_MON_UNOWN_D         207
#define FOLLOWER_MON_UNOWN_E         208
#define FOLLOWER_MON_UNOWN_F         209
#define FOLLOWER_MON_UNOWN_G         210
#define FOLLOWER_MON_UNOWN_H         211
#define FOLLOWER_MON_UNOWN_I         212
#define FOLLOWER_MON_UNOWN_J         213
#define FOLLOWER_MON_UNOWN_K         214
#define FOLLOWER_MON_UNOWN_L         215
#define FOLLOWER_MON_UNOWN_M         216
#define FOLLOWER_MON_UNOWN_N         217
#define FOLLOWER_MON_UNOWN_O         218
#define FOLLOWER_MON_UNOWN_P         219
#define FOLLOWER_MON_UNOWN_Q         220
#define FOLLOWER_MON_UNOWN_R         221
#define FOLLOWER_MON_UNOWN_S         222
#define FOLLOWER_MON_UNOWN_T         223
#define FOLLOWER_MON_UNOWN_U         224
#define FOLLOWER_MON_UNOWN_V         225
#define FOLLOWER_MON_UNOWN_W         226
#define FOLLOWER_MON_UNOWN_X         227
#define FOLLOWER_MON_UNOWN_Y         228
#define FOLLOWER_MON_UNOWN_Z         229
#define FOLLOWER_MON_UNOWN_QMARK     230
#define FOLLOWER_MON_UNOWN_EXCL      231
#define FOLLOWER_MON_WOBBUFFET       232
#define FOLLOWER_MON_WOBBUFFET_F     233
#define FOLLOWER_MON_GIRAFARIG       234
#define FOLLOWER_MON_PINECO          235
#define FOLLOWER_MON_FORRETRESS      236
#define FOLLOWER_MON_DUNSPARCE       237
#define FOLLOWER_MON_GLIGAR          238
#define FOLLOWER_MON_STEELIX         239
#define FOLLOWER_MON_STEELIX_F       240
#define FOLLOWER_MON_SNUBBULL        241
#define FOLLOWER_MON_GRANBULL        242
#define FOLLOWER_MON_QWILFISH        243
#define FOLLOWER_MON_SCIZOR          244
#define FOLLOWER_MON_SHUCKLE         245
#define FOLLOWER_MON_HERACROSS       246
#define FOLLOWER_MON_HERACROSS_F     247
#define FOLLOWER_MON_SNEASEL         248
#define FOLLOWER_MON_TEDDIURSA       249
#define FOLLOWER_MON_URSARING        250
#define FOLLOWER_MON_SLUGMA          251
#define FOLLOWER_MON_MAGCARGO        252
#define FOLLOWER_MON_SWINUB          253
#define FOLLOWER_MON_PILOSWINE       254
#define FOLLOWER_MON_CORSOLA         255
#define FOLLOWER_MON_REMORAID        256
#define FOLLOWER_MON_OCTILLERY       257
#define FOLLOWER_MON_DELIBIRD        258
#define FOLLOWER_MON_MANTINE         259
#define FOLLOWER_MON_SKARMORY        260
#define FOLLOWER_MON_HOUNDOUR        261
#define FOLLOWER_MON_HOUNDOOM        262
#define FOLLOWER_MON_KINGDRA         263
#define FOLLOWER_MON_PHANPY          264
#define FOLLOWER_MON_DONPHAN         265
#define FOLLOWER_MON_PORYGON2        266
#define FOLLOWER_MON_STANTLER        267
#define FOLLOWER_MON_SMEARGLE        268
#define FOLLOWER_MON_TYROGUE         269
#define FOLLOWER_MON_HITMONTOP       270
#define FOLLOWER_MON_SMOOCHUM        271
#define FOLLOWER_MON_ELEKID          272
#define FOLLOWER_MON_MAGBY           273
#define FOLLOWER_MON_MILTANK         274
#define FOLLOWER_MON_BLISSEY         275
#define FOLLOWER_MON_RAIKOU          276
#define FOLLOWER_MON_ENTEI           277
#define FOLLOWER_MON_SUICUNE         278
#define FOLLOWER_MON_LARVITAR        279
#define FOLLOWER_MON_PUPITAR         280
#define FOLLOWER_MON_TYRANITAR       281
#define FOLLOWER_MON_LUGIA           282
#define FOLLOWER_MON_HO_OH           283
#define FOLLOWER_MON_CELEBI          284
#define FOLLOWER_MON_TREECKO         285
#define FOLLOWER_MON_GROVYLE         286
#define FOLLOWER_MON_SCEPTILE        287
#define FOLLOWER_MON_TORCHIC         288
#define FOLLOWER_MON_COMBUSKEN       289
#define FOLLOWER_MON_BLAZIKEN        290
#define FOLLOWER_MON_MUDKIP          291
#define FOLLOWER_MON_MARSHTOMP       292
#define FOLLOWER_MON_SWAMPERT        293
#define FOLLOWER_MON_POOCHYENA       294
#define FOLLOWER_MON_MIGHTYENA       295
#define FOLLOWER_MON_ZIGZAGOON       296
#define FOLLOWER_MON_LINOONE         297
#define FOLLOWER_MON_WURMPLE         298
#define FOLLOWER_MON_SILCOON         299
#define FOLLOWER_MON_BEAUTIFLY       300
#define FOLLOWER_MON_CASCOON         301
#define FOLLOWER_MON_DUSTOX          302
#define FOLLOWER_MON_LOTAD           303
#define FOLLOWER_MON_LOMBRE          304
#define FOLLOWER_MON_LUDICOLO        305
#define FOLLOWER_MON_SEEDOT          306
#define FOLLOWER_MON_NUZLEAF         307
#define FOLLOWER_MON_SHIFTRY         308
#define FOLLOWER_MON_TAILLOW         309
#define FOLLOWER_MON_SWELLOW         310
#define FOLLOWER_MON_WINGULL         311
#define FOLLOWER_MON_PELIPPER        312
#define FOLLOWER_MON_RALTS           313
#define FOLLOWER_MON_KIRLIA          314
#define FOLLOWER_MON_GARDEVOIR       315
#define FOLLOWER_MON_SURSKIT         316
#define FOLLOWER_MON_MASQUERAIN      317
#define FOLLOWER_MON_SHROOMISH       318
#define FOLLOWER_MON_BRELOOM         319
#define FOLLOWER_MON_SLAKOTH         320
#define FOLLOWER_MON_VIGOROTH        321
#define FOLLOWER_MON_SLAKING         322
#define FOLLOWER_MON_NINCADA         323
#define FOLLOWER_MON_NINJASK         324
#define FOLLOWER_MON_SHEDINJA        325
#define FOLLOWER_MON_WHISMUR         326
#define FOLLOWER_MON_LOUDRED         327
#define FOLLOWER_MON_EXPLOUD         328
#define FOLLOWER_MON_MAKUHITA        329
#define FOLLOWER_MON_HARIYAMA        330
#define FOLLOWER_MON_AZURILL         331
#define FOLLOWER_MON_NOSEPASS        332
#define FOLLOWER_MON_SKITTY          333
#define FOLLOWER_MON_DELCATTY        334
#define FOLLOWER_MON_SABLEYE         335
#define FOLLOWER_MON_MAWILE          336
#define FOLLOWER_MON_ARON            337
#define FOLLOWER_MON_LAIRON          338
#define FOLLOWER_MON_AGGRON          339
#define FOLLOWER_MON_MEDITITE        340
#define FOLLOWER_MON_MEDICHAM        341
#define FOLLOWER_MON_ELECTRIKE       342
#define FOLLOWER_MON_MANECTRIC       343
#define FOLLOWER_MON_PLUSLE          344
#define FOLLOWER_MON_MINUN           345
#define FOLLOWER_MON_VOLBEAT         346
#define FOLLOWER_MON_ILLUMISE        347
#define FOLLOWER_MON_ROSELIA         348
#define FOLLOWER_MON_GULPIN          349
#define FOLLOWER_MON_SWALOT          350
#define FOLLOWER_MON_CARVANHA        351
#define FOLLOWER_MON_SHARPEDO        352
#define FOLLOWER_MON_WAILMER         353
#define FOLLOWER_MON_WAILORD         354
#define FOLLOWER_MON_NUMEL           355
#define FOLLOWER_MON_CAMERUPT        356
#define FOLLOWER_MON_TORKOAL         357
#define FOLLOWER_MON_SPOINK          358
#define FOLLOWER_MON_GRUMPIG         359
#define FOLLOWER_MON_SPINDA          360
#define FOLLOWER_MON_TRAPINCH        361
#define FOLLOWER_MON_VIBRAVA         362
#define FOLLOWER_MON_FLYGON          363
#define FOLLOWER_MON_CACNEA          364
#define FOLLOWER_MON_CACTURNE        365
#define FOLLOWER_MON_SWABLU          366
#define FOLLOWER_MON_ALTARIA         367
#define FOLLOWER_MON_ZANGOOSE        368
#define FOLLOWER_MON_SEVIPER         369
#define FOLLOWER_MON_LUNATONE        370
#define FOLLOWER_MON_SOLROCK         371
#define FOLLOWER_MON_BARBOACH        372
#define FOLLOWER_MON_WHISCASH        373
#define FOLLOWER_MON_CORPHISH        374
#define FOLLOWER_MON_CRAWDAUNT       375
#define FOLLOWER_MON_BALTOY          376
#define FOLLOWER_MON_CLAYDOL         377
#define FOLLOWER_MON_LILEEP          378
#define FOLLOWER_MON_CRADILY         379
#define FOLLOWER_MON_ANORITH         380
#define FOLLOWER_MON_ARMALDO         381
#define FOLLOWER_MON_FEEBAS          382
#define FOLLOWER_MON_MILOTIC         383
#define FOLLOWER_MON_CASTFORM        384
#define FOLLOWER_MON_KECLEON         385
#define FOLLOWER_MON_SHUPPET         386
#define FOLLOWER_MON_BANETTE         387
#define FOLLOWER_MON_DUSKULL         388
#define FOLLOWER_MON_DUSCLOPS        389
#define FOLLOWER_MON_TROPIUS         390
#define FOLLOWER_MON_CHIMECHO        391
#define FOLLOWER_MON_ABSOL           392
#define FOLLOWER_MON_WYNAUT          393
#define FOLLOWER_MON_SNORUNT         394
#define FOLLOWER_MON_GLALIE          395
#define FOLLOWER_MON_SPHEAL          396
#define FOLLOWER_MON_SEALEO          397
#define FOLLOWER_MON_WALREIN         398
#define FOLLOWER_MON_CLAMPERL        399
#define FOLLOWER_MON_HUNTAIL         400
#define FOLLOWER_MON_GOREBYSS        401
#define FOLLOWER_MON_RELICANTH       402
#define FOLLOWER_MON_LUVDISC         403
#define FOLLOWER_MON_BAGON           404
#define FOLLOWER_MON_SHELGON         405
#define FOLLOWER_MON_SALAMENCE       406
#define FOLLOWER_MON_BELDUM          407
#define FOLLOWER_MON_METANG          408
#define FOLLOWER_MON_METAGROSS       409
#define FOLLOWER_MON_REGIROCK        410
#define FOLLOWER_MON_REGICE          411
#define FOLLOWER_MON_REGISTEEL       412
#define FOLLOWER_MON_LATIAS          413
#define FOLLOWER_MON_LATIOS          414
#define FOLLOWER_MON_KYOGRE          415
#define FOLLOWER_MON_GROUDON         416
#define FOLLOWER_MON_RAYQUAZA        417
#define FOLLOWER_MON_JIRACHI         418
#define FOLLOWER_MON_DEOXYS          419
#define FOLLOWER_MON_DEOXYS_ATK      420
#define FOLLOWER_MON_DEOXYS_DEF      421
#define FOLLOWER_MON_DEOXYS_SPD      422
#define FOLLOWER_MON_TURTWIG         423
#define FOLLOWER_MON_GROTLE          424
#define FOLLOWER_MON_TORTERRA        425
#define FOLLOWER_MON_CHIMCHAR        426
#define FOLLOWER_MON_MONFERNO        427
#define FOLLOWER_MON_INFERNAPE       428
#define FOLLOWER_MON_PIPLUP          429
#define FOLLOWER_MON_PRINPLUP        430
#define FOLLOWER_MON_EMPOLEON        431
#define FOLLOWER_MON_STARLY          432
#define FOLLOWER_MON_STARAVIA        433
#define FOLLOWER_MON_STARAPTOR       434
#define FOLLOWER_MON_BIDOOF          435
#define FOLLOWER_MON_BIBAREL         436
#define FOLLOWER_MON_KRICKETOT       437
#define FOLLOWER_MON_KRICKETUNE      438
#define FOLLOWER_MON_SHINX           439
#define FOLLOWER_MON_LUXIO           440
#define FOLLOWER_MON_LUXRAY          441
#define FOLLOWER_MON_BUDEW           442
#define FOLLOWER_MON_ROSERADE        443
#define FOLLOWER_MON_CRANIDOS        444
#define FOLLOWER_MON_RAMPARDOS       445
#define FOLLOWER_MON_SHIELDON        446
#define FOLLOWER_MON_BASTIODON       447
#define FOLLOWER_MON_BURMY           448
#define FOLLOWER_MON_BURMY_SANDY     449
#define FOLLOWER_MON_BURMY_TRASH     450
#define FOLLOWER_MON_WORMADAM        451
#define FOLLOWER_MON_WORMADAM_SANDY  452
#define FOLLOWER_MON_WORMADAM_TRASH  453
#define FOLLOWER_MON_MOTHIM          454
#define FOLLOWER_MON_COMBEE          455
#define FOLLOWER_MON_COMBEE_F        456
#define FOLLOWER_MON_VESPIQUEN       457
#define FOLLOWER_MON_PACHIRISU       458
#define FOLLOWER_MON_BUIZEL          459
#define FOLLOWER_MON_FLOATZEL        460
#define FOLLOWER_MON_CHERUBI         461
#define FOLLOWER_MON_CHERRIM         462
#define FOLLOWER_MON_SHELLOS_WEST    463
#define FOLLOWER_MON_SHELLOS_EAST    464
#define FOLLOWER_MON_GASTRODON_WEST  465
#define FOLLOWER_MON_GASTRODON_EAST  466
#define FOLLOWER_MON_AMBIPOM         467
#define FOLLOWER_MON_DRIFLOON        468
#define FOLLOWER_MON_DRIFBLIM        469
#define FOLLOWER_MON_BUNEARY         470
#define FOLLOWER_MON_LOPUNNY         471
#define FOLLOWER_MON_MISMAGIUS       472
#define FOLLOWER_MON_HONCHKROW       473
#define FOLLOWER_MON_GLAMEOW         474
#define FOLLOWER_MON_PURUGLY         475
#define FOLLOWER_MON_CHINGLING       476
#define FOLLOWER_MON_STUNKY          477
#define FOLLOWER_MON_SKUNTANK        478
#define FOLLOWER_MON_BRONZOR         479
#define FOLLOWER_MON_BRONZONG        480
#define FOLLOWER_MON_BONSLY          481
#define FOLLOWER_MON_MIME_JR         482
#define FOLLOWER_MON_HAPPINY         483
#define FOLLOWER_MON_CHATOT          484
#define FOLLOWER_MON_SPIRITOMB       485
#define FOLLOWER_MON_GIBLE           486
#define FOLLOWER_MON_GIBLE_F         487
#define FOLLOWER_MON_GABITE          488
#define FOLLOWER_MON_GABITE_F        489
#define FOLLOWER_MON_GARCHOMP        490
#define FOLLOWER_MON_GARCHOMP_F      491
#define FOLLOWER_MON_MUNCHLAX        492
#define FOLLOWER_MON_RIOLU           493
#define FOLLOWER_MON_LUCARIO         494
#define FOLLOWER_MON_HIPPOPOTAS      495
#define FOLLOWER_MON_HIPPOPOTAS_F    496
#define FOLLOWER_MON_HIPPOWDON       497
#define FOLLOWER_MON_HIPPOWDON_F     498
#define FOLLOWER_MON_SKORUPI         499
#define FOLLOWER_MON_DRAPION         500
#define FOLLOWER_MON_CROAGUNK        501
#define FOLLOWER_MON_TOXICROAK       502
#define FOLLOWER_MON_CARNIVINE       503
#define FOLLOWER_MON_FINNEON         504
#define FOLLOWER_MON_LUMINEON        505
#define FOLLOWER_MON_MANTYKE         506
#define FOLLOWER_MON_SNOVER          507
#define FOLLOWER_MON_ABOMASNOW       508
#define FOLLOWER_MON_WEAVILE         509
#define FOLLOWER_MON_MAGNEZONE       510
#define FOLLOWER_MON_LICKILICKY      511
#define FOLLOWER_MON_RHYPERIOR       512
#define FOLLOWER_MON_TANGROWTH       513
#define FOLLOWER_MON_ELECTIVIRE      514
#define FOLLOWER_MON_MAGMORTAR       515
#define FOLLOWER_MON_TOGEKISS        516
#define FOLLOWER_MON_YANMEGA         517
#define FOLLOWER_MON_LEAFEON         518
#define FOLLOWER_MON_GLACEON         519
#define FOLLOWER_MON_GLISCOR         520
#define FOLLOWER_MON_MAMOSWINE       521
#define FOLLOWER_MON_PORYGON_Z       522
#define FOLLOWER_MON_GALLADE         523
#define FOLLOWER_MON_PROBOPASS       524
#define FOLLOWER_MON_DUSKNOIR        525
#define FOLLOWER_MON_FROSLASS        526
#define FOLLOWER_MON_ROTOM           527
#define FOLLOWER_MON_ROTOM_HEAT      528
#define FOLLOWER_MON_ROTOM_WASH      529
#define FOLLOWER_MON_ROTOM_FROST     530
#define FOLLOWER_MON_ROTOM_FAN       531
#define FOLLOWER_MON_ROTOM_MOW       532
#define FOLLOWER_MON_UXIE            533
#define FOLLOWER_MON_MESPRIT         534
#define FOLLOWER_MON_AZELF           535
#define FOLLOWER_MON_DIALGA          536
#define FOLLOWER_MON_PALKIA          537
#define FOLLOWER_MON_HEATRAN         538
#define FOLLOWER_MON_REGIGIGAS       539
#define FOLLOWER_MON_GIRATINA        540
#define FOLLOWER_MON_GIRATINA_ORIGIN 541
#define FOLLOWER_MON_CRESSELIA       542
#define FOLLOWER_MON_PHIONE          543
#define FOLLOWER_MON_MANAPHY         544
#define FOLLOWER_MON_DARKRAI         545
#define FOLLOWER_MON_SHAYMIN         546
#define FOLLOWER_MON_SHAYMIN_SKY     547
#define FOLLOWER_MON_ARCEUS_NORMAL   548
#define FOLLOWER_MON_ARCEUS_FIGHTING 549
#define FOLLOWER_MON_ARCEUS_FLYING   550
#define FOLLOWER_MON_ARCEUS_POISON   551
#define FOLLOWER_MON_ARCEUS_GROUND   552
#define FOLLOWER_MON_ARCEUS_ROCK     553
#define FOLLOWER_MON_ARCEUS_BUG      554
#define FOLLOWER_MON_ARCEUS_GHOST    555
#define FOLLOWER_MON_ARCEUS_STEEL    556
#define FOLLOWER_MON_ARCEUS_MYSTERY  557
#define FOLLOWER_MON_ARCEUS_FIRE     558
#define FOLLOWER_MON_ARCEUS_WATER    559
#define FOLLOWER_MON_ARCEUS_GRASS    560
#define FOLLOWER_MON_ARCEUS_ELECTRIC 561
#define FOLLOWER_MON_ARCEUS_PSYCHIC  562
#define FOLLOWER_MON_ARCEUS_ICE      563
#define FOLLOWER_MON_ARCEUS_DRAGON   564
#define FOLLOWER_MON_ARCEUS_DARK     565

// The species New Gold adds; tools/newgold/import/import_followers.py
#define FOLLOWER_MON_LILLIPUP                     566
#define FOLLOWER_MON_HERDIER                      567
#define FOLLOWER_MON_STOUTLAND                    568
#define FOLLOWER_MON_PURRLOIN                     569
#define FOLLOWER_MON_LIEPARD                      570
#define FOLLOWER_MON_TYMPOLE                      571
#define FOLLOWER_MON_PALPITOAD                    572
#define FOLLOWER_MON_SEISMITOAD                   573
#define FOLLOWER_MON_SEWADDLE                     574
#define FOLLOWER_MON_SWADLOON                     575
#define FOLLOWER_MON_LEAVANNY                     576
#define FOLLOWER_MON_YAMASK                       577
#define FOLLOWER_MON_COFAGRIGUS                   578
#define FOLLOWER_MON_TRUBBISH                     579
#define FOLLOWER_MON_GARBODOR                     580
#define FOLLOWER_MON_EMOLGA                       581
#define FOLLOWER_MON_KARRABLAST                   582
#define FOLLOWER_MON_ESCAVALIER                   583
#define FOLLOWER_MON_FOONGUS                      584
#define FOLLOWER_MON_AMOONGUSS                    585
#define FOLLOWER_MON_JOLTIK                       586
#define FOLLOWER_MON_GALVANTULA                   587
#define FOLLOWER_MON_FERROSEED                    588
#define FOLLOWER_MON_FERROTHORN                   589
#define FOLLOWER_MON_KLINK                        590
#define FOLLOWER_MON_KLANG                        591
#define FOLLOWER_MON_KLINKLANG                    592
#define FOLLOWER_MON_ELGYEM                       593
#define FOLLOWER_MON_BEHEEYEM                     594
#define FOLLOWER_MON_LITWICK                      595
#define FOLLOWER_MON_LAMPENT                      596
#define FOLLOWER_MON_CHANDELURE                   597
#define FOLLOWER_MON_SHELMET                      598
#define FOLLOWER_MON_ACCELGOR                     599
#define FOLLOWER_MON_BOUFFALANT                   600
#define FOLLOWER_MON_BUNNELBY                     601
#define FOLLOWER_MON_DIGGERSBY                    602
#define FOLLOWER_MON_FLETCHLING                   603
#define FOLLOWER_MON_FLETCHINDER                  604
#define FOLLOWER_MON_TALONFLAME                   605
#define FOLLOWER_MON_LITLEO                       606
#define FOLLOWER_MON_PYROAR                       607
#define FOLLOWER_MON_ESPURR                       608
#define FOLLOWER_MON_MEOWSTIC                     609
#define FOLLOWER_MON_SYLVEON                      610
#define FOLLOWER_MON_DEDENNE                      611
#define FOLLOWER_MON_PHANTUMP                     612
#define FOLLOWER_MON_TREVENANT                    613
#define FOLLOWER_MON_PUMPKABOO                    614
#define FOLLOWER_MON_GOURGEIST                    615
#define FOLLOWER_MON_NOIBAT                       616
#define FOLLOWER_MON_NOIVERN                      617
#define FOLLOWER_MON_APPLIN                       618
#define FOLLOWER_MON_FLAPPLE                      619
#define FOLLOWER_MON_APPLETUN                     620
#define FOLLOWER_MON_SIZZLIPEDE                   621
#define FOLLOWER_MON_CENTISKORCH                  622
#define FOLLOWER_MON_WYRDEER                      623
#define FOLLOWER_MON_KLEAVOR                      624
#define FOLLOWER_MON_URSALUNA                     625
#define FOLLOWER_MON_ANNIHILAPE                   626
#define FOLLOWER_MON_FARIGIRAF                    627
#define FOLLOWER_MON_DUDUNSPARCE                  628
#define FOLLOWER_MON_DIPPLIN                      629
#define FOLLOWER_MON_HYDRAPPLE                    630
#define FOLLOWER_MON_SLOWPOKE_GALARIAN            631
#define FOLLOWER_MON_SLOWBRO_GALARIAN             632
#define FOLLOWER_MON_VICTINI                      633
#define FOLLOWER_MON_SNIVY                        634
#define FOLLOWER_MON_SERVINE                      635
#define FOLLOWER_MON_SERPERIOR                    636
#define FOLLOWER_MON_TEPIG                        637
#define FOLLOWER_MON_PIGNITE                      638
#define FOLLOWER_MON_EMBOAR                       639
#define FOLLOWER_MON_OSHAWOTT                     640
#define FOLLOWER_MON_DEWOTT                       641
#define FOLLOWER_MON_SAMUROTT                     642
#define FOLLOWER_MON_PATRAT                       643
#define FOLLOWER_MON_WATCHOG                      644
#define FOLLOWER_MON_PANSAGE                      645
#define FOLLOWER_MON_SIMISAGE                     646
#define FOLLOWER_MON_PANSEAR                      647
#define FOLLOWER_MON_SIMISEAR                     648
#define FOLLOWER_MON_PANPOUR                      649
#define FOLLOWER_MON_SIMIPOUR                     650
#define FOLLOWER_MON_MUNNA                        651
#define FOLLOWER_MON_MUSHARNA                     652
#define FOLLOWER_MON_PIDOVE                       653
#define FOLLOWER_MON_TRANQUILL                    654
#define FOLLOWER_MON_UNFEZANT                     655
#define FOLLOWER_MON_BLITZLE                      656
#define FOLLOWER_MON_ZEBSTRIKA                    657
#define FOLLOWER_MON_ROGGENROLA                   658
#define FOLLOWER_MON_BOLDORE                      659
#define FOLLOWER_MON_GIGALITH                     660
#define FOLLOWER_MON_WOOBAT                       661
#define FOLLOWER_MON_SWOOBAT                      662
#define FOLLOWER_MON_DRILBUR                      663
#define FOLLOWER_MON_EXCADRILL                    664
#define FOLLOWER_MON_AUDINO                       665
#define FOLLOWER_MON_TIMBURR                      666
#define FOLLOWER_MON_GURDURR                      667
#define FOLLOWER_MON_CONKELDURR                   668
#define FOLLOWER_MON_THROH                        669
#define FOLLOWER_MON_SAWK                         670
#define FOLLOWER_MON_VENIPEDE                     671
#define FOLLOWER_MON_WHIRLIPEDE                   672
#define FOLLOWER_MON_SCOLIPEDE                    673
#define FOLLOWER_MON_COTTONEE                     674
#define FOLLOWER_MON_WHIMSICOTT                   675
#define FOLLOWER_MON_PETILIL                      676
#define FOLLOWER_MON_LILLIGANT                    677
#define FOLLOWER_MON_BASCULIN                     678
#define FOLLOWER_MON_SANDILE                      679
#define FOLLOWER_MON_KROKOROK                     680
#define FOLLOWER_MON_KROOKODILE                   681
#define FOLLOWER_MON_DARUMAKA                     682
#define FOLLOWER_MON_DARMANITAN                   683
#define FOLLOWER_MON_MARACTUS                     684
#define FOLLOWER_MON_DWEBBLE                      685
#define FOLLOWER_MON_CRUSTLE                      686
#define FOLLOWER_MON_SCRAGGY                      687
#define FOLLOWER_MON_SCRAFTY                      688
#define FOLLOWER_MON_SIGILYPH                     689
#define FOLLOWER_MON_TIRTOUGA                     690
#define FOLLOWER_MON_CARRACOSTA                   691
#define FOLLOWER_MON_ARCHEN                       692
#define FOLLOWER_MON_ARCHEOPS                     693
#define FOLLOWER_MON_ZORUA                        694
#define FOLLOWER_MON_ZOROARK                      695
#define FOLLOWER_MON_MINCCINO                     696
#define FOLLOWER_MON_CINCCINO                     697
#define FOLLOWER_MON_GOTHITA                      698
#define FOLLOWER_MON_GOTHORITA                    699
#define FOLLOWER_MON_GOTHITELLE                   700
#define FOLLOWER_MON_SOLOSIS                      701
#define FOLLOWER_MON_DUOSION                      702
#define FOLLOWER_MON_REUNICLUS                    703
#define FOLLOWER_MON_DUCKLETT                     704
#define FOLLOWER_MON_SWANNA                       705
#define FOLLOWER_MON_VANILLITE                    706
#define FOLLOWER_MON_VANILLISH                    707
#define FOLLOWER_MON_VANILLUXE                    708
#define FOLLOWER_MON_DEERLING                     709
#define FOLLOWER_MON_SAWSBUCK                     710
#define FOLLOWER_MON_FRILLISH                     711
#define FOLLOWER_MON_JELLICENT                    712
#define FOLLOWER_MON_ALOMOMOLA                    713
#define FOLLOWER_MON_TYNAMO                       714
#define FOLLOWER_MON_EELEKTRIK                    715
#define FOLLOWER_MON_EELEKTROSS                   716
#define FOLLOWER_MON_AXEW                         717
#define FOLLOWER_MON_FRAXURE                      718
#define FOLLOWER_MON_HAXORUS                      719
#define FOLLOWER_MON_CUBCHOO                      720
#define FOLLOWER_MON_BEARTIC                      721
#define FOLLOWER_MON_CRYOGONAL                    722
#define FOLLOWER_MON_STUNFISK                     723
#define FOLLOWER_MON_MIENFOO                      724
#define FOLLOWER_MON_MIENSHAO                     725
#define FOLLOWER_MON_DRUDDIGON                    726
#define FOLLOWER_MON_GOLETT                       727
#define FOLLOWER_MON_GOLURK                       728
#define FOLLOWER_MON_PAWNIARD                     729
#define FOLLOWER_MON_BISHARP                      730
#define FOLLOWER_MON_RUFFLET                      731
#define FOLLOWER_MON_BRAVIARY                     732
#define FOLLOWER_MON_VULLABY                      733
#define FOLLOWER_MON_MANDIBUZZ                    734
#define FOLLOWER_MON_HEATMOR                      735
#define FOLLOWER_MON_DURANT                       736
#define FOLLOWER_MON_DEINO                        737
#define FOLLOWER_MON_ZWEILOUS                     738
#define FOLLOWER_MON_HYDREIGON                    739
#define FOLLOWER_MON_LARVESTA                     740
#define FOLLOWER_MON_VOLCARONA                    741
#define FOLLOWER_MON_COBALION                     742
#define FOLLOWER_MON_TERRAKION                    743
#define FOLLOWER_MON_VIRIZION                     744
#define FOLLOWER_MON_TORNADUS                     745
#define FOLLOWER_MON_THUNDURUS                    746
#define FOLLOWER_MON_RESHIRAM                     747
#define FOLLOWER_MON_ZEKROM                       748
#define FOLLOWER_MON_LANDORUS                     749
#define FOLLOWER_MON_KYUREM                       750
#define FOLLOWER_MON_KELDEO                       751
#define FOLLOWER_MON_MELOETTA                     752
#define FOLLOWER_MON_GENESECT                     753
#define FOLLOWER_MON_CHESPIN                      754
#define FOLLOWER_MON_QUILLADIN                    755
#define FOLLOWER_MON_CHESNAUGHT                   756
#define FOLLOWER_MON_FENNEKIN                     757
#define FOLLOWER_MON_BRAIXEN                      758
#define FOLLOWER_MON_DELPHOX                      759
#define FOLLOWER_MON_FROAKIE                      760
#define FOLLOWER_MON_FROGADIER                    761
#define FOLLOWER_MON_GRENINJA                     762
#define FOLLOWER_MON_SCATTERBUG                   763
#define FOLLOWER_MON_SPEWPA                       764
#define FOLLOWER_MON_VIVILLON                     765
#define FOLLOWER_MON_FLABEBE                      766
#define FOLLOWER_MON_FLOETTE                      767
#define FOLLOWER_MON_FLORGES                      768
#define FOLLOWER_MON_SKIDDO                       769
#define FOLLOWER_MON_GOGOAT                       770
#define FOLLOWER_MON_PANCHAM                      771
#define FOLLOWER_MON_PANGORO                      772
#define FOLLOWER_MON_FURFROU                      773
#define FOLLOWER_MON_HONEDGE                      774
#define FOLLOWER_MON_DOUBLADE                     775
#define FOLLOWER_MON_AEGISLASH                    776
#define FOLLOWER_MON_SPRITZEE                     777
#define FOLLOWER_MON_AROMATISSE                   778
#define FOLLOWER_MON_SWIRLIX                      779
#define FOLLOWER_MON_SLURPUFF                     780
#define FOLLOWER_MON_INKAY                        781
#define FOLLOWER_MON_MALAMAR                      782
#define FOLLOWER_MON_BINACLE                      783
#define FOLLOWER_MON_BARBARACLE                   784
#define FOLLOWER_MON_SKRELP                       785
#define FOLLOWER_MON_DRAGALGE                     786
#define FOLLOWER_MON_CLAUNCHER                    787
#define FOLLOWER_MON_CLAWITZER                    788
#define FOLLOWER_MON_HELIOPTILE                   789
#define FOLLOWER_MON_HELIOLISK                    790
#define FOLLOWER_MON_TYRUNT                       791
#define FOLLOWER_MON_TYRANTRUM                    792
#define FOLLOWER_MON_AMAURA                       793
#define FOLLOWER_MON_AURORUS                      794
#define FOLLOWER_MON_HAWLUCHA                     795
#define FOLLOWER_MON_CARBINK                      796
#define FOLLOWER_MON_GOOMY                        797
#define FOLLOWER_MON_SLIGGOO                      798
#define FOLLOWER_MON_GOODRA                       799
#define FOLLOWER_MON_KLEFKI                       800
#define FOLLOWER_MON_BERGMITE                     801
#define FOLLOWER_MON_AVALUGG                      802
#define FOLLOWER_MON_XERNEAS                      803
#define FOLLOWER_MON_YVELTAL                      804
#define FOLLOWER_MON_ZYGARDE                      805
#define FOLLOWER_MON_DIANCIE                      806
#define FOLLOWER_MON_HOOPA                        807
#define FOLLOWER_MON_VOLCANION                    808
#define FOLLOWER_MON_ROWLET                       809
#define FOLLOWER_MON_DARTRIX                      810
#define FOLLOWER_MON_DECIDUEYE                    811
#define FOLLOWER_MON_LITTEN                       812
#define FOLLOWER_MON_TORRACAT                     813
#define FOLLOWER_MON_INCINEROAR                   814
#define FOLLOWER_MON_POPPLIO                      815
#define FOLLOWER_MON_BRIONNE                      816
#define FOLLOWER_MON_PRIMARINA                    817
#define FOLLOWER_MON_PIKIPEK                      818
#define FOLLOWER_MON_TRUMBEAK                     819
#define FOLLOWER_MON_TOUCANNON                    820
#define FOLLOWER_MON_YUNGOOS                      821
#define FOLLOWER_MON_GUMSHOOS                     822
#define FOLLOWER_MON_GRUBBIN                      823
#define FOLLOWER_MON_CHARJABUG                    824
#define FOLLOWER_MON_VIKAVOLT                     825
#define FOLLOWER_MON_CRABRAWLER                   826
#define FOLLOWER_MON_CRABOMINABLE                 827
#define FOLLOWER_MON_ORICORIO                     828
#define FOLLOWER_MON_CUTIEFLY                     829
#define FOLLOWER_MON_RIBOMBEE                     830
#define FOLLOWER_MON_ROCKRUFF                     831
#define FOLLOWER_MON_LYCANROC                     832
#define FOLLOWER_MON_WISHIWASHI                   833
#define FOLLOWER_MON_MAREANIE                     834
#define FOLLOWER_MON_TOXAPEX                      835
#define FOLLOWER_MON_MUDBRAY                      836
#define FOLLOWER_MON_MUDSDALE                     837
#define FOLLOWER_MON_DEWPIDER                     838
#define FOLLOWER_MON_ARAQUANID                    839
#define FOLLOWER_MON_FOMANTIS                     840
#define FOLLOWER_MON_LURANTIS                     841
#define FOLLOWER_MON_MORELULL                     842
#define FOLLOWER_MON_SHIINOTIC                    843
#define FOLLOWER_MON_SALANDIT                     844
#define FOLLOWER_MON_SALAZZLE                     845
#define FOLLOWER_MON_STUFFUL                      846
#define FOLLOWER_MON_BEWEAR                       847
#define FOLLOWER_MON_BOUNSWEET                    848
#define FOLLOWER_MON_STEENEE                      849
#define FOLLOWER_MON_TSAREENA                     850
#define FOLLOWER_MON_COMFEY                       851
#define FOLLOWER_MON_ORANGURU                     852
#define FOLLOWER_MON_PASSIMIAN                    853
#define FOLLOWER_MON_WIMPOD                       854
#define FOLLOWER_MON_GOLISOPOD                    855
#define FOLLOWER_MON_SANDYGAST                    856
#define FOLLOWER_MON_PALOSSAND                    857
#define FOLLOWER_MON_PYUKUMUKU                    858
#define FOLLOWER_MON_TYPE_NULL                    859
#define FOLLOWER_MON_SILVALLY                     860
#define FOLLOWER_MON_MINIOR                       861
#define FOLLOWER_MON_KOMALA                       862
#define FOLLOWER_MON_TURTONATOR                   863
#define FOLLOWER_MON_TOGEDEMARU                   864
#define FOLLOWER_MON_MIMIKYU                      865
#define FOLLOWER_MON_BRUXISH                      866
#define FOLLOWER_MON_DRAMPA                       867
#define FOLLOWER_MON_DHELMISE                     868
#define FOLLOWER_MON_JANGMO_O                     869
#define FOLLOWER_MON_HAKAMO_O                     870
#define FOLLOWER_MON_KOMMO_O                      871
#define FOLLOWER_MON_TAPU_KOKO                    872
#define FOLLOWER_MON_TAPU_LELE                    873
#define FOLLOWER_MON_TAPU_BULU                    874
#define FOLLOWER_MON_TAPU_FINI                    875
#define FOLLOWER_MON_COSMOG                       876
#define FOLLOWER_MON_COSMOEM                      877
#define FOLLOWER_MON_SOLGALEO                     878
#define FOLLOWER_MON_LUNALA                       879
#define FOLLOWER_MON_NIHILEGO                     880
#define FOLLOWER_MON_BUZZWOLE                     881
#define FOLLOWER_MON_PHEROMOSA                    882
#define FOLLOWER_MON_XURKITREE                    883
#define FOLLOWER_MON_CELESTEELA                   884
#define FOLLOWER_MON_KARTANA                      885
#define FOLLOWER_MON_GUZZLORD                     886
#define FOLLOWER_MON_NECROZMA                     887
#define FOLLOWER_MON_MAGEARNA                     888
#define FOLLOWER_MON_MARSHADOW                    889
#define FOLLOWER_MON_POIPOLE                      890
#define FOLLOWER_MON_NAGANADEL                    891
#define FOLLOWER_MON_STAKATAKA                    892
#define FOLLOWER_MON_BLACEPHALON                  893
#define FOLLOWER_MON_ZERAORA                      894
#define FOLLOWER_MON_MELTAN                       895
#define FOLLOWER_MON_MELMETAL                     896
#define FOLLOWER_MON_GROOKEY                      897
#define FOLLOWER_MON_THWACKEY                     898
#define FOLLOWER_MON_RILLABOOM                    899
#define FOLLOWER_MON_SCORBUNNY                    900
#define FOLLOWER_MON_RABOOT                       901
#define FOLLOWER_MON_CINDERACE                    902
#define FOLLOWER_MON_SOBBLE                       903
#define FOLLOWER_MON_DRIZZILE                     904
#define FOLLOWER_MON_INTELEON                     905
#define FOLLOWER_MON_SKWOVET                      906
#define FOLLOWER_MON_GREEDENT                     907
#define FOLLOWER_MON_ROOKIDEE                     908
#define FOLLOWER_MON_CORVISQUIRE                  909
#define FOLLOWER_MON_CORVIKNIGHT                  910
#define FOLLOWER_MON_BLIPBUG                      911
#define FOLLOWER_MON_DOTTLER                      912
#define FOLLOWER_MON_ORBEETLE                     913
#define FOLLOWER_MON_NICKIT                       914
#define FOLLOWER_MON_THIEVUL                      915
#define FOLLOWER_MON_GOSSIFLEUR                   916
#define FOLLOWER_MON_ELDEGOSS                     917
#define FOLLOWER_MON_WOOLOO                       918
#define FOLLOWER_MON_DUBWOOL                      919
#define FOLLOWER_MON_CHEWTLE                      920
#define FOLLOWER_MON_DREDNAW                      921
#define FOLLOWER_MON_YAMPER                       922
#define FOLLOWER_MON_BOLTUND                      923
#define FOLLOWER_MON_ROLYCOLY                     924
#define FOLLOWER_MON_CARKOL                       925
#define FOLLOWER_MON_COALOSSAL                    926
#define FOLLOWER_MON_SILICOBRA                    927
#define FOLLOWER_MON_SANDACONDA                   928
#define FOLLOWER_MON_CRAMORANT                    929
#define FOLLOWER_MON_ARROKUDA                     930
#define FOLLOWER_MON_BARRASKEWDA                  931
#define FOLLOWER_MON_TOXEL                        932
#define FOLLOWER_MON_TOXTRICITY                   933
#define FOLLOWER_MON_CLOBBOPUS                    934
#define FOLLOWER_MON_GRAPPLOCT                    935
#define FOLLOWER_MON_SINISTEA                     936
#define FOLLOWER_MON_POLTEAGEIST                  937
#define FOLLOWER_MON_HATENNA                      938
#define FOLLOWER_MON_HATTREM                      939
#define FOLLOWER_MON_HATTERENE                    940
#define FOLLOWER_MON_IMPIDIMP                     941
#define FOLLOWER_MON_MORGREM                      942
#define FOLLOWER_MON_GRIMMSNARL                   943
#define FOLLOWER_MON_OBSTAGOON                    944
#define FOLLOWER_MON_PERRSERKER                   945
#define FOLLOWER_MON_CURSOLA                      946
#define FOLLOWER_MON_SIRFETCHD                    947
#define FOLLOWER_MON_MR_RIME                      948
#define FOLLOWER_MON_RUNERIGUS                    949
#define FOLLOWER_MON_MILCERY                      950
#define FOLLOWER_MON_ALCREMIE                     951
#define FOLLOWER_MON_FALINKS                      952
#define FOLLOWER_MON_PINCURCHIN                   953
#define FOLLOWER_MON_SNOM                         954
#define FOLLOWER_MON_FROSMOTH                     955
#define FOLLOWER_MON_STONJOURNER                  956
#define FOLLOWER_MON_EISCUE                       957
#define FOLLOWER_MON_INDEEDEE                     958
#define FOLLOWER_MON_MORPEKO                      959
#define FOLLOWER_MON_CUFANT                       960
#define FOLLOWER_MON_COPPERAJAH                   961
#define FOLLOWER_MON_DRACOZOLT                    962
#define FOLLOWER_MON_ARCTOZOLT                    963
#define FOLLOWER_MON_DRACOVISH                    964
#define FOLLOWER_MON_ARCTOVISH                    965
#define FOLLOWER_MON_DURALUDON                    966
#define FOLLOWER_MON_DREEPY                       967
#define FOLLOWER_MON_DRAKLOAK                     968
#define FOLLOWER_MON_DRAGAPULT                    969
#define FOLLOWER_MON_ZACIAN                       970
#define FOLLOWER_MON_ZAMAZENTA                    971
#define FOLLOWER_MON_ETERNATUS                    972
#define FOLLOWER_MON_KUBFU                        973
#define FOLLOWER_MON_URSHIFU                      974
#define FOLLOWER_MON_ZARUDE                       975
#define FOLLOWER_MON_REGIELEKI                    976
#define FOLLOWER_MON_REGIDRAGO                    977
#define FOLLOWER_MON_GLASTRIER                    978
#define FOLLOWER_MON_SPECTRIER                    979
#define FOLLOWER_MON_CALYREX                      980
#define FOLLOWER_MON_BASCULEGION                  981
#define FOLLOWER_MON_SNEASLER                     982
#define FOLLOWER_MON_OVERQWIL                     983
#define FOLLOWER_MON_ENAMORUS                     984
#define FOLLOWER_MON_SPRIGATITO                   985
#define FOLLOWER_MON_FLORAGATO                    986
#define FOLLOWER_MON_MEOWSCARADA                  987
#define FOLLOWER_MON_FUECOCO                      988
#define FOLLOWER_MON_CROCALOR                     989
#define FOLLOWER_MON_SKELEDIRGE                   990
#define FOLLOWER_MON_QUAXLY                       991
#define FOLLOWER_MON_QUAXWELL                     992
#define FOLLOWER_MON_QUAQUAVAL                    993
#define FOLLOWER_MON_LECHONK                      994
#define FOLLOWER_MON_OINKOLOGNE                   995
#define FOLLOWER_MON_TAROUNTULA                   996
#define FOLLOWER_MON_SPIDOPS                      997
#define FOLLOWER_MON_NYMBLE                       998
#define FOLLOWER_MON_LOKIX                        999
#define FOLLOWER_MON_PAWMI                        1000
#define FOLLOWER_MON_PAWMO                        1001
#define FOLLOWER_MON_PAWMOT                       1002
#define FOLLOWER_MON_TANDEMAUS                    1003
#define FOLLOWER_MON_MAUSHOLD                     1004
#define FOLLOWER_MON_FIDOUGH                      1005
#define FOLLOWER_MON_DACHSBUN                     1006
#define FOLLOWER_MON_SMOLIV                       1007
#define FOLLOWER_MON_DOLLIV                       1008
#define FOLLOWER_MON_ARBOLIVA                     1009
#define FOLLOWER_MON_SQUAWKABILLY                 1010
#define FOLLOWER_MON_NACLI                        1011
#define FOLLOWER_MON_NACLSTACK                    1012
#define FOLLOWER_MON_GARGANACL                    1013
#define FOLLOWER_MON_CHARCADET                    1014
#define FOLLOWER_MON_ARMAROUGE                    1015
#define FOLLOWER_MON_CERULEDGE                    1016
#define FOLLOWER_MON_TADBULB                      1017
#define FOLLOWER_MON_BELLIBOLT                    1018
#define FOLLOWER_MON_WATTREL                      1019
#define FOLLOWER_MON_KILOWATTREL                  1020
#define FOLLOWER_MON_MASCHIFF                     1021
#define FOLLOWER_MON_MABOSSTIFF                   1022
#define FOLLOWER_MON_SHROODLE                     1023
#define FOLLOWER_MON_GRAFAIAI                     1024
#define FOLLOWER_MON_BRAMBLIN                     1025
#define FOLLOWER_MON_BRAMBLEGHAST                 1026
#define FOLLOWER_MON_TOEDSCOOL                    1027
#define FOLLOWER_MON_TOEDSCRUEL                   1028
#define FOLLOWER_MON_KLAWF                        1029
#define FOLLOWER_MON_CAPSAKID                     1030
#define FOLLOWER_MON_SCOVILLAIN                   1031
#define FOLLOWER_MON_RELLOR                       1032
#define FOLLOWER_MON_RABSCA                       1033
#define FOLLOWER_MON_FLITTLE                      1034
#define FOLLOWER_MON_ESPATHRA                     1035
#define FOLLOWER_MON_TINKATINK                    1036
#define FOLLOWER_MON_TINKATUFF                    1037
#define FOLLOWER_MON_TINKATON                     1038
#define FOLLOWER_MON_WIGLETT                      1039
#define FOLLOWER_MON_WUGTRIO                      1040
#define FOLLOWER_MON_BOMBIRDIER                   1041
#define FOLLOWER_MON_FINIZEN                      1042
#define FOLLOWER_MON_PALAFIN                      1043
#define FOLLOWER_MON_VAROOM                       1044
#define FOLLOWER_MON_REVAVROOM                    1045
#define FOLLOWER_MON_CYCLIZAR                     1046
#define FOLLOWER_MON_ORTHWORM                     1047
#define FOLLOWER_MON_GLIMMET                      1048
#define FOLLOWER_MON_GLIMMORA                     1049
#define FOLLOWER_MON_GREAVARD                     1050
#define FOLLOWER_MON_HOUNDSTONE                   1051
#define FOLLOWER_MON_FLAMIGO                      1052
#define FOLLOWER_MON_CETODDLE                     1053
#define FOLLOWER_MON_CETITAN                      1054
#define FOLLOWER_MON_VELUZA                       1055
#define FOLLOWER_MON_DONDOZO                      1056
#define FOLLOWER_MON_TATSUGIRI                    1057
#define FOLLOWER_MON_CLODSIRE                     1058
#define FOLLOWER_MON_KINGAMBIT                    1059
#define FOLLOWER_MON_GREAT_TUSK                   1060
#define FOLLOWER_MON_SCREAM_TAIL                  1061
#define FOLLOWER_MON_BRUTE_BONNET                 1062
#define FOLLOWER_MON_FLUTTER_MANE                 1063
#define FOLLOWER_MON_SLITHER_WING                 1064
#define FOLLOWER_MON_SANDY_SHOCKS                 1065
#define FOLLOWER_MON_IRON_TREADS                  1066
#define FOLLOWER_MON_IRON_BUNDLE                  1067
#define FOLLOWER_MON_IRON_HANDS                   1068
#define FOLLOWER_MON_IRON_JUGULIS                 1069
#define FOLLOWER_MON_IRON_MOTH                    1070
#define FOLLOWER_MON_IRON_THORNS                  1071
#define FOLLOWER_MON_FRIGIBAX                     1072
#define FOLLOWER_MON_ARCTIBAX                     1073
#define FOLLOWER_MON_BAXCALIBUR                   1074
#define FOLLOWER_MON_GIMMIGHOUL                   1075
#define FOLLOWER_MON_GHOLDENGO                    1076
#define FOLLOWER_MON_WO_CHIEN                     1077
#define FOLLOWER_MON_CHIEN_PAO                    1078
#define FOLLOWER_MON_TING_LU                      1079
#define FOLLOWER_MON_CHI_YU                       1080
#define FOLLOWER_MON_ROARING_MOON                 1081
#define FOLLOWER_MON_IRON_VALIANT                 1082
#define FOLLOWER_MON_KORAIDON                     1083
#define FOLLOWER_MON_MIRAIDON                     1084
#define FOLLOWER_MON_WALKING_WAKE                 1085
#define FOLLOWER_MON_IRON_LEAVES                  1086
#define FOLLOWER_MON_POLTCHAGEIST                 1087
#define FOLLOWER_MON_SINISTCHA                    1088
#define FOLLOWER_MON_OKIDOGI                      1089
#define FOLLOWER_MON_MUNKIDORI                    1090
#define FOLLOWER_MON_FEZANDIPITI                  1091
#define FOLLOWER_MON_OGERPON                      1092
#define FOLLOWER_MON_ARCHALUDON                   1093
#define FOLLOWER_MON_GOUGING_FIRE                 1094
#define FOLLOWER_MON_RAGING_BOLT                  1095
#define FOLLOWER_MON_IRON_BOULDER                 1096
#define FOLLOWER_MON_IRON_CROWN                   1097
#define FOLLOWER_MON_TERAPAGOS                    1098
#define FOLLOWER_MON_PECHARUNT                    1099
#define FOLLOWER_MON_RATTATA_ALOLAN               1100
#define FOLLOWER_MON_RATICATE_ALOLAN              1101
#define FOLLOWER_MON_RAICHU_ALOLAN                1102
#define FOLLOWER_MON_SANDSHREW_ALOLAN             1103
#define FOLLOWER_MON_SANDSLASH_ALOLAN             1104
#define FOLLOWER_MON_VULPIX_ALOLAN                1105
#define FOLLOWER_MON_NINETALES_ALOLAN             1106
#define FOLLOWER_MON_DIGLETT_ALOLAN               1107
#define FOLLOWER_MON_DUGTRIO_ALOLAN               1108
#define FOLLOWER_MON_MEOWTH_ALOLAN                1109
#define FOLLOWER_MON_PERSIAN_ALOLAN               1110
#define FOLLOWER_MON_GEODUDE_ALOLAN               1111
#define FOLLOWER_MON_GRAVELER_ALOLAN              1112
#define FOLLOWER_MON_GOLEM_ALOLAN                 1113
#define FOLLOWER_MON_GRIMER_ALOLAN                1114
#define FOLLOWER_MON_MUK_ALOLAN                   1115
#define FOLLOWER_MON_EXEGGUTOR_ALOLAN             1116
#define FOLLOWER_MON_MAROWAK_ALOLAN               1117
#define FOLLOWER_MON_MEOWTH_GALARIAN              1118
#define FOLLOWER_MON_PONYTA_GALARIAN              1119
#define FOLLOWER_MON_RAPIDASH_GALARIAN            1120
#define FOLLOWER_MON_FARFETCHD_GALARIAN           1121
#define FOLLOWER_MON_WEEZING_GALARIAN             1122
#define FOLLOWER_MON_MR_MIME_GALARIAN             1123
#define FOLLOWER_MON_ARTICUNO_GALARIAN            1124
#define FOLLOWER_MON_ZAPDOS_GALARIAN              1125
#define FOLLOWER_MON_MOLTRES_GALARIAN             1126
#define FOLLOWER_MON_SLOWKING_GALARIAN            1127
#define FOLLOWER_MON_CORSOLA_GALARIAN             1128
#define FOLLOWER_MON_ZIGZAGOON_GALARIAN           1129
#define FOLLOWER_MON_LINOONE_GALARIAN             1130
#define FOLLOWER_MON_DARUMAKA_GALARIAN            1131
#define FOLLOWER_MON_DARMANITAN_GALARIAN          1132
#define FOLLOWER_MON_YAMASK_GALARIAN              1133
#define FOLLOWER_MON_STUNFISK_GALARIAN            1134
#define FOLLOWER_MON_PIKACHU_COSPLAY              1135
#define FOLLOWER_MON_PIKACHU_ROCK_STAR            1136
#define FOLLOWER_MON_PIKACHU_BELLE                1137
#define FOLLOWER_MON_PIKACHU_POP_STAR             1138
#define FOLLOWER_MON_PIKACHU_PH_D                 1139
#define FOLLOWER_MON_PIKACHU_LIBRE                1140
#define FOLLOWER_MON_PIKACHU_ORIGINAL_CAP         1141
#define FOLLOWER_MON_PIKACHU_HOENN_CAP            1142
#define FOLLOWER_MON_PIKACHU_SINNOH_CAP           1143
#define FOLLOWER_MON_PIKACHU_UNOVA_CAP            1144
#define FOLLOWER_MON_PIKACHU_KALOS_CAP            1145
#define FOLLOWER_MON_PIKACHU_ALOLA_CAP            1146
#define FOLLOWER_MON_PIKACHU_PARTNER_CAP          1147
#define FOLLOWER_MON_PIKACHU_WORLD_CAP            1148
#define FOLLOWER_MON_CASTFORM_SUNNY               1149
#define FOLLOWER_MON_CASTFORM_RAINY               1150
#define FOLLOWER_MON_CASTFORM_SNOWY               1151
#define FOLLOWER_MON_SHELLOS_EAST_SEA             1152
#define FOLLOWER_MON_GASTRODON_EAST_SEA           1153
#define FOLLOWER_MON_DIALGA_ORIGIN                1154
#define FOLLOWER_MON_PALKIA_ORIGIN                1155
#define FOLLOWER_MON_BASCULIN_BLUE_STRIPED        1156
#define FOLLOWER_MON_BASCULIN_WHITE_STRIPED       1157
#define FOLLOWER_MON_DARMANITAN_ZEN_MODE          1158
#define FOLLOWER_MON_DARMANITAN_ZEN_MODE_GALARIAN 1159
#define FOLLOWER_MON_DEERLING_SUMMER              1160
#define FOLLOWER_MON_DEERLING_AUTUMN              1161
#define FOLLOWER_MON_DEERLING_WINTER              1162
#define FOLLOWER_MON_SAWSBUCK_SUMMER              1163
#define FOLLOWER_MON_SAWSBUCK_AUTUMN              1164
#define FOLLOWER_MON_SAWSBUCK_WINTER              1165
#define FOLLOWER_MON_TORNADUS_THERIAN             1166
#define FOLLOWER_MON_THUNDURUS_THERIAN            1167
#define FOLLOWER_MON_LANDORUS_THERIAN             1168
#define FOLLOWER_MON_KYUREM_WHITE                 1169
#define FOLLOWER_MON_KYUREM_BLACK                 1170
#define FOLLOWER_MON_KELDEO_RESOLUTE              1171
#define FOLLOWER_MON_MELOETTA_PIROUETTE           1172
#define FOLLOWER_MON_GENESECT_DOUSE_DRIVE         1173
#define FOLLOWER_MON_GENESECT_SHOCK_DRIVE         1174
#define FOLLOWER_MON_GENESECT_BURN_DRIVE          1175
#define FOLLOWER_MON_GENESECT_CHILL_DRIVE         1176
#define FOLLOWER_MON_VIVILLON_POLAR               1177
#define FOLLOWER_MON_VIVILLON_TUNDRA              1178
#define FOLLOWER_MON_VIVILLON_CONTINENTAL         1179
#define FOLLOWER_MON_VIVILLON_GARDEN              1180
#define FOLLOWER_MON_VIVILLON_ELEGANT             1181
#define FOLLOWER_MON_VIVILLON_MEADOW              1182
#define FOLLOWER_MON_VIVILLON_MODERN              1183
#define FOLLOWER_MON_VIVILLON_MARINE              1184
#define FOLLOWER_MON_VIVILLON_ARCHIPELAGO         1185
#define FOLLOWER_MON_VIVILLON_HIGH_PLAINS         1186
#define FOLLOWER_MON_VIVILLON_SANDSTORM           1187
#define FOLLOWER_MON_VIVILLON_RIVER               1188
#define FOLLOWER_MON_VIVILLON_MONSOON             1189
#define FOLLOWER_MON_VIVILLON_SAVANNA             1190
#define FOLLOWER_MON_VIVILLON_SUN                 1191
#define FOLLOWER_MON_VIVILLON_OCEAN               1192
#define FOLLOWER_MON_VIVILLON_JUNGLE              1193
#define FOLLOWER_MON_VIVILLON_FANCY               1194
#define FOLLOWER_MON_VIVILLON_POKE_BALL           1195
#define FOLLOWER_MON_FLABEBE_YELLOW_FLOWER        1196
#define FOLLOWER_MON_FLABEBE_ORANGE_FLOWER        1197
#define FOLLOWER_MON_FLABEBE_BLUE_FLOWER          1198
#define FOLLOWER_MON_FLABEBE_WHITE_FLOWER         1199
#define FOLLOWER_MON_FLOETTE_YELLOW_FLOWER        1200
#define FOLLOWER_MON_FLOETTE_ORANGE_FLOWER        1201
#define FOLLOWER_MON_FLOETTE_BLUE_FLOWER          1202
#define FOLLOWER_MON_FLOETTE_WHITE_FLOWER         1203
#define FOLLOWER_MON_FLOETTE_ETERNAL_FLOWER       1204
#define FOLLOWER_MON_FLORGES_YELLOW_FLOWER        1205
#define FOLLOWER_MON_FLORGES_ORANGE_FLOWER        1206
#define FOLLOWER_MON_FLORGES_BLUE_FLOWER          1207
#define FOLLOWER_MON_FLORGES_WHITE_FLOWER         1208
#define FOLLOWER_MON_FURFROU_HEART                1209
#define FOLLOWER_MON_FURFROU_STAR                 1210
#define FOLLOWER_MON_FURFROU_DIAMOND              1211
#define FOLLOWER_MON_FURFROU_DEBUTANTE            1212
#define FOLLOWER_MON_FURFROU_MATRON               1213
#define FOLLOWER_MON_FURFROU_DANDY                1214
#define FOLLOWER_MON_FURFROU_LA_REINE             1215
#define FOLLOWER_MON_FURFROU_KABUKI               1216
#define FOLLOWER_MON_FURFROU_PHARAOH              1217
#define FOLLOWER_MON_PUMPKABOO_SMALL              1218
#define FOLLOWER_MON_PUMPKABOO_LARGE              1219
#define FOLLOWER_MON_PUMPKABOO_SUPER              1220
#define FOLLOWER_MON_GOURGEIST_SMALL              1221
#define FOLLOWER_MON_GOURGEIST_LARGE              1222
#define FOLLOWER_MON_GOURGEIST_SUPER              1223
#define FOLLOWER_MON_ZYGARDE_10                   1224
#define FOLLOWER_MON_ZYGARDE_10_POWER_CONSTRUCT   1225
#define FOLLOWER_MON_ZYGARDE_50_POWER_CONSTRUCT   1226
#define FOLLOWER_MON_ZYGARDE_10_COMPLETE          1227
#define FOLLOWER_MON_ZYGARDE_50_COMPLETE          1228
#define FOLLOWER_MON_HOOPA_UNBOUND                1229
#define FOLLOWER_MON_ORICORIO_POM_POM             1230
#define FOLLOWER_MON_ORICORIO_PAU                 1231
#define FOLLOWER_MON_ORICORIO_SENSU               1232
#define FOLLOWER_MON_ROCKRUFF_OWN_TEMPO           1233
#define FOLLOWER_MON_LYCANROC_MIDNIGHT            1234
#define FOLLOWER_MON_LYCANROC_DUSK                1235
#define FOLLOWER_MON_WISHIWASHI_SCHOOL            1236
#define FOLLOWER_MON_MINIOR_METEOR_ORANGE         1237
#define FOLLOWER_MON_MINIOR_METEOR_YELLOW         1238
#define FOLLOWER_MON_MINIOR_METEOR_GREEN          1239
#define FOLLOWER_MON_MINIOR_METEOR_BLUE           1240
#define FOLLOWER_MON_MINIOR_METEOR_INDIGO         1241
#define FOLLOWER_MON_MINIOR_METEOR_VIOLET         1242
#define FOLLOWER_MON_NECROZMA_DUSK_MANE           1243
#define FOLLOWER_MON_NECROZMA_DAWN_WINGS          1244
#define FOLLOWER_MON_MAGEARNA_ORIGINAL            1245
#define FOLLOWER_MON_PIKACHU_PARTNER              1246
#define FOLLOWER_MON_EEVEE_PARTNER                1247
#define FOLLOWER_MON_TOXTRICITY_LOW_KEY           1248
#define FOLLOWER_MON_SINISTEA_ANTIQUE             1249
#define FOLLOWER_MON_POLTEAGEIST_ANTIQUE          1250
#define FOLLOWER_MON_ALCREMIE_BERRY_SWEET         1251
#define FOLLOWER_MON_ALCREMIE_LOVE_SWEET          1252
#define FOLLOWER_MON_ALCREMIE_STAR_SWEET          1253
#define FOLLOWER_MON_ALCREMIE_CLOVER_SWEET        1254
#define FOLLOWER_MON_ALCREMIE_FLOWER_SWEET        1255
#define FOLLOWER_MON_ALCREMIE_RIBBON_SWEET        1256
#define FOLLOWER_MON_URSHIFU_RAPID_STRIKE         1257
#define FOLLOWER_MON_ZARUDE_DADA                  1258
#define FOLLOWER_MON_CALYREX_ICE_RIDER            1259
#define FOLLOWER_MON_CALYREX_SHADOW_RIDER         1260
#define FOLLOWER_MON_ENAMORUS_THERIAN             1261
#define FOLLOWER_MON_GROWLITHE_HISUIAN            1262
#define FOLLOWER_MON_ARCANINE_HISUIAN             1263
#define FOLLOWER_MON_VOLTORB_HISUIAN              1264
#define FOLLOWER_MON_ELECTRODE_HISUIAN            1265
#define FOLLOWER_MON_TYPHLOSION_HISUIAN           1266
#define FOLLOWER_MON_QWILFISH_HISUIAN             1267
#define FOLLOWER_MON_SNEASEL_HISUIAN              1268
#define FOLLOWER_MON_SAMUROTT_HISUIAN             1269
#define FOLLOWER_MON_LILLIGANT_HISUIAN            1270
#define FOLLOWER_MON_ZORUA_HISUIAN                1271
#define FOLLOWER_MON_ZOROARK_HISUIAN              1272
#define FOLLOWER_MON_BRAVIARY_HISUIAN             1273
#define FOLLOWER_MON_SLIGGOO_HISUIAN              1274
#define FOLLOWER_MON_GOODRA_HISUIAN               1275
#define FOLLOWER_MON_AVALUGG_HISUIAN              1276
#define FOLLOWER_MON_DECIDUEYE_HISUIAN            1277
#define FOLLOWER_MON_UNFEZANT_FEMALE              1278
#define FOLLOWER_MON_FRILLISH_FEMALE              1279
#define FOLLOWER_MON_JELLICENT_FEMALE             1280
#define FOLLOWER_MON_PYROAR_FEMALE                1281
#define FOLLOWER_MON_MEOWSTIC_FEMALE              1282
#define FOLLOWER_MON_INDEEDEE_FEMALE              1283
#define FOLLOWER_MON_BASCULEGION_FEMALE           1284
#define FOLLOWER_MON_MAUSHOLD_FAMILY_OF_THREE     1285
#define FOLLOWER_MON_SQUAWKABILLY_BLUE_PLUMAGE    1286
#define FOLLOWER_MON_SQUAWKABILLY_YELLOW_PLUMAGE  1287
#define FOLLOWER_MON_SQUAWKABILLY_WHITE_PLUMAGE   1288
#define FOLLOWER_MON_TATSUGIRI_DROOPY             1289
#define FOLLOWER_MON_TATSUGIRI_STRETCHY           1290
#define FOLLOWER_MON_DUDUNSPARCE_THREE_SEGMENT    1291
#define FOLLOWER_MON_GIMMIGHOUL_ROAMING           1292
#define FOLLOWER_MON_WOOPER_PALDEAN               1293
#define FOLLOWER_MON_TAUROS_COMBAT                1294
#define FOLLOWER_MON_TAUROS_BLAZE                 1295
#define FOLLOWER_MON_TAUROS_AQUA                  1296
#define FOLLOWER_MON_OINKOLOGNE_FEMALE            1297
#define FOLLOWER_MON_REVAVROOM_SEGIN              1298
#define FOLLOWER_MON_REVAVROOM_SCHEDAR            1299
#define FOLLOWER_MON_REVAVROOM_NAVI               1300
#define FOLLOWER_MON_REVAVROOM_RUCHBAH            1301
#define FOLLOWER_MON_REVAVROOM_CAPH               1302
#define FOLLOWER_MON_OGERPON_WELLSPRING_MASK      1303
#define FOLLOWER_MON_OGERPON_HEARTHFLAME_MASK     1304
#define FOLLOWER_MON_OGERPON_CORNERSTONE_MASK     1305
#define FOLLOWER_MON_URSALUNA_BLOODMOON           1306

#endif // POKEHEARTGOLD_CONSTANTS_FOLLOW_MON_IDX_H
