#ifndef POKEHEARTGOLD_CONSTANTS_SPECIES_H
#define POKEHEARTGOLD_CONSTANTS_SPECIES_H

#define SPECIES_NONE       0
#define SPECIES_BULBASAUR  1
#define SPECIES_IVYSAUR    2
#define SPECIES_VENUSAUR   3
#define SPECIES_CHARMANDER 4
#define SPECIES_CHARMELEON 5
#define SPECIES_CHARIZARD  6
#define SPECIES_SQUIRTLE   7
#define SPECIES_WARTORTLE  8
#define SPECIES_BLASTOISE  9
#define SPECIES_CATERPIE   10
#define SPECIES_METAPOD    11
#define SPECIES_BUTTERFREE 12
#define SPECIES_WEEDLE     13
#define SPECIES_KAKUNA     14
#define SPECIES_BEEDRILL   15
#define SPECIES_PIDGEY     16
#define SPECIES_PIDGEOTTO  17
#define SPECIES_PIDGEOT    18
#define SPECIES_RATTATA    19
#define SPECIES_RATICATE   20
#define SPECIES_SPEAROW    21
#define SPECIES_FEAROW     22
#define SPECIES_EKANS      23
#define SPECIES_ARBOK      24
#define SPECIES_PIKACHU    25
#define SPECIES_RAICHU     26
#define SPECIES_SANDSHREW  27
#define SPECIES_SANDSLASH  28
#define SPECIES_NIDORAN_F  29
#define SPECIES_NIDORINA   30
#define SPECIES_NIDOQUEEN  31
#define SPECIES_NIDORAN_M  32
#define SPECIES_NIDORINO   33
#define SPECIES_NIDOKING   34
#define SPECIES_CLEFAIRY   35
#define SPECIES_CLEFABLE   36
#define SPECIES_VULPIX     37
#define SPECIES_NINETALES  38
#define SPECIES_JIGGLYPUFF 39
#define SPECIES_WIGGLYTUFF 40
#define SPECIES_ZUBAT      41
#define SPECIES_GOLBAT     42
#define SPECIES_ODDISH     43
#define SPECIES_GLOOM      44
#define SPECIES_VILEPLUME  45
#define SPECIES_PARAS      46
#define SPECIES_PARASECT   47
#define SPECIES_VENONAT    48
#define SPECIES_VENOMOTH   49
#define SPECIES_DIGLETT    50
#define SPECIES_DUGTRIO    51
#define SPECIES_MEOWTH     52
#define SPECIES_PERSIAN    53
#define SPECIES_PSYDUCK    54
#define SPECIES_GOLDUCK    55
#define SPECIES_MANKEY     56
#define SPECIES_PRIMEAPE   57
#define SPECIES_GROWLITHE  58
#define SPECIES_ARCANINE   59
#define SPECIES_POLIWAG    60
#define SPECIES_POLIWHIRL  61
#define SPECIES_POLIWRATH  62
#define SPECIES_ABRA       63
#define SPECIES_KADABRA    64
#define SPECIES_ALAKAZAM   65
#define SPECIES_MACHOP     66
#define SPECIES_MACHOKE    67
#define SPECIES_MACHAMP    68
#define SPECIES_BELLSPROUT 69
#define SPECIES_WEEPINBELL 70
#define SPECIES_VICTREEBEL 71
#define SPECIES_TENTACOOL  72
#define SPECIES_TENTACRUEL 73
#define SPECIES_GEODUDE    74
#define SPECIES_GRAVELER   75
#define SPECIES_GOLEM      76
#define SPECIES_PONYTA     77
#define SPECIES_RAPIDASH   78
#define SPECIES_SLOWPOKE   79
#define SPECIES_SLOWBRO    80
#define SPECIES_MAGNEMITE  81
#define SPECIES_MAGNETON   82
#define SPECIES_FARFETCHD  83
#define SPECIES_DODUO      84
#define SPECIES_DODRIO     85
#define SPECIES_SEEL       86
#define SPECIES_DEWGONG    87
#define SPECIES_GRIMER     88
#define SPECIES_MUK        89
#define SPECIES_SHELLDER   90
#define SPECIES_CLOYSTER   91
#define SPECIES_GASTLY     92
#define SPECIES_HAUNTER    93
#define SPECIES_GENGAR     94
#define SPECIES_ONIX       95
#define SPECIES_DROWZEE    96
#define SPECIES_HYPNO      97
#define SPECIES_KRABBY     98
#define SPECIES_KINGLER    99
#define SPECIES_VOLTORB    100
#define SPECIES_ELECTRODE  101
#define SPECIES_EXEGGCUTE  102
#define SPECIES_EXEGGUTOR  103
#define SPECIES_CUBONE     104
#define SPECIES_MAROWAK    105
#define SPECIES_HITMONLEE  106
#define SPECIES_HITMONCHAN 107
#define SPECIES_LICKITUNG  108
#define SPECIES_KOFFING    109
#define SPECIES_WEEZING    110
#define SPECIES_RHYHORN    111
#define SPECIES_RHYDON     112
#define SPECIES_CHANSEY    113
#define SPECIES_TANGELA    114
#define SPECIES_KANGASKHAN 115
#define SPECIES_HORSEA     116
#define SPECIES_SEADRA     117
#define SPECIES_GOLDEEN    118
#define SPECIES_SEAKING    119
#define SPECIES_STARYU     120
#define SPECIES_STARMIE    121
#define SPECIES_MR_MIME    122
#define SPECIES_SCYTHER    123
#define SPECIES_JYNX       124
#define SPECIES_ELECTABUZZ 125
#define SPECIES_MAGMAR     126
#define SPECIES_PINSIR     127
#define SPECIES_TAUROS     128
#define SPECIES_MAGIKARP   129
#define SPECIES_GYARADOS   130
#define SPECIES_LAPRAS     131
#define SPECIES_DITTO      132
#define SPECIES_EEVEE      133
#define SPECIES_VAPOREON   134
#define SPECIES_JOLTEON    135
#define SPECIES_FLAREON    136
#define SPECIES_PORYGON    137
#define SPECIES_OMANYTE    138
#define SPECIES_OMASTAR    139
#define SPECIES_KABUTO     140
#define SPECIES_KABUTOPS   141
#define SPECIES_AERODACTYL 142
#define SPECIES_SNORLAX    143
#define SPECIES_ARTICUNO   144
#define SPECIES_ZAPDOS     145
#define SPECIES_MOLTRES    146
#define SPECIES_DRATINI    147
#define SPECIES_DRAGONAIR  148
#define SPECIES_DRAGONITE  149
#define SPECIES_MEWTWO     150
#define SPECIES_MEW        151

#define KANTO_DEX_COUNT SPECIES_MEW

#define SPECIES_CHIKORITA  152
#define SPECIES_BAYLEEF    153
#define SPECIES_MEGANIUM   154
#define SPECIES_CYNDAQUIL  155
#define SPECIES_QUILAVA    156
#define SPECIES_TYPHLOSION 157
#define SPECIES_TOTODILE   158
#define SPECIES_CROCONAW   159
#define SPECIES_FERALIGATR 160
#define SPECIES_SENTRET    161
#define SPECIES_FURRET     162
#define SPECIES_HOOTHOOT   163
#define SPECIES_NOCTOWL    164
#define SPECIES_LEDYBA     165
#define SPECIES_LEDIAN     166
#define SPECIES_SPINARAK   167
#define SPECIES_ARIADOS    168
#define SPECIES_CROBAT     169
#define SPECIES_CHINCHOU   170
#define SPECIES_LANTURN    171
#define SPECIES_PICHU      172
#define SPECIES_CLEFFA     173
#define SPECIES_IGGLYBUFF  174
#define SPECIES_TOGEPI     175
#define SPECIES_TOGETIC    176
#define SPECIES_NATU       177
#define SPECIES_XATU       178
#define SPECIES_MAREEP     179
#define SPECIES_FLAAFFY    180
#define SPECIES_AMPHAROS   181
#define SPECIES_BELLOSSOM  182
#define SPECIES_MARILL     183
#define SPECIES_AZUMARILL  184
#define SPECIES_SUDOWOODO  185
#define SPECIES_POLITOED   186
#define SPECIES_HOPPIP     187
#define SPECIES_SKIPLOOM   188
#define SPECIES_JUMPLUFF   189
#define SPECIES_AIPOM      190
#define SPECIES_SUNKERN    191
#define SPECIES_SUNFLORA   192
#define SPECIES_YANMA      193
#define SPECIES_WOOPER     194
#define SPECIES_QUAGSIRE   195
#define SPECIES_ESPEON     196
#define SPECIES_UMBREON    197
#define SPECIES_MURKROW    198
#define SPECIES_SLOWKING   199
#define SPECIES_MISDREAVUS 200
#define SPECIES_UNOWN      201
#define SPECIES_WOBBUFFET  202
#define SPECIES_GIRAFARIG  203
#define SPECIES_PINECO     204
#define SPECIES_FORRETRESS 205
#define SPECIES_DUNSPARCE  206
#define SPECIES_GLIGAR     207
#define SPECIES_STEELIX    208
#define SPECIES_SNUBBULL   209
#define SPECIES_GRANBULL   210
#define SPECIES_QWILFISH   211
#define SPECIES_SCIZOR     212
#define SPECIES_SHUCKLE    213
#define SPECIES_HERACROSS  214
#define SPECIES_SNEASEL    215
#define SPECIES_TEDDIURSA  216
#define SPECIES_URSARING   217
#define SPECIES_SLUGMA     218
#define SPECIES_MAGCARGO   219
#define SPECIES_SWINUB     220
#define SPECIES_PILOSWINE  221
#define SPECIES_CORSOLA    222
#define SPECIES_REMORAID   223
#define SPECIES_OCTILLERY  224
#define SPECIES_DELIBIRD   225
#define SPECIES_MANTINE    226
#define SPECIES_SKARMORY   227
#define SPECIES_HOUNDOUR   228
#define SPECIES_HOUNDOOM   229
#define SPECIES_KINGDRA    230
#define SPECIES_PHANPY     231
#define SPECIES_DONPHAN    232
#define SPECIES_PORYGON2   233
#define SPECIES_STANTLER   234
#define SPECIES_SMEARGLE   235
#define SPECIES_TYROGUE    236
#define SPECIES_HITMONTOP  237
#define SPECIES_SMOOCHUM   238
#define SPECIES_ELEKID     239
#define SPECIES_MAGBY      240
#define SPECIES_MILTANK    241
#define SPECIES_BLISSEY    242
#define SPECIES_RAIKOU     243
#define SPECIES_ENTEI      244
#define SPECIES_SUICUNE    245
#define SPECIES_LARVITAR   246
#define SPECIES_PUPITAR    247
#define SPECIES_TYRANITAR  248
#define SPECIES_LUGIA      249
#define SPECIES_HO_OH      250
#define SPECIES_CELEBI     251

#define JOHTO_DEX_COUNT SPECIES_CELEBI

#define SPECIES_TREECKO    252
#define SPECIES_GROVYLE    253
#define SPECIES_SCEPTILE   254
#define SPECIES_TORCHIC    255
#define SPECIES_COMBUSKEN  256
#define SPECIES_BLAZIKEN   257
#define SPECIES_MUDKIP     258
#define SPECIES_MARSHTOMP  259
#define SPECIES_SWAMPERT   260
#define SPECIES_POOCHYENA  261
#define SPECIES_MIGHTYENA  262
#define SPECIES_ZIGZAGOON  263
#define SPECIES_LINOONE    264
#define SPECIES_WURMPLE    265
#define SPECIES_SILCOON    266
#define SPECIES_BEAUTIFLY  267
#define SPECIES_CASCOON    268
#define SPECIES_DUSTOX     269
#define SPECIES_LOTAD      270
#define SPECIES_LOMBRE     271
#define SPECIES_LUDICOLO   272
#define SPECIES_SEEDOT     273
#define SPECIES_NUZLEAF    274
#define SPECIES_SHIFTRY    275
#define SPECIES_TAILLOW    276
#define SPECIES_SWELLOW    277
#define SPECIES_WINGULL    278
#define SPECIES_PELIPPER   279
#define SPECIES_RALTS      280
#define SPECIES_KIRLIA     281
#define SPECIES_GARDEVOIR  282
#define SPECIES_SURSKIT    283
#define SPECIES_MASQUERAIN 284
#define SPECIES_SHROOMISH  285
#define SPECIES_BRELOOM    286
#define SPECIES_SLAKOTH    287
#define SPECIES_VIGOROTH   288
#define SPECIES_SLAKING    289
#define SPECIES_NINCADA    290
#define SPECIES_NINJASK    291
#define SPECIES_SHEDINJA   292
#define SPECIES_WHISMUR    293
#define SPECIES_LOUDRED    294
#define SPECIES_EXPLOUD    295
#define SPECIES_MAKUHITA   296
#define SPECIES_HARIYAMA   297
#define SPECIES_AZURILL    298
#define SPECIES_NOSEPASS   299
#define SPECIES_SKITTY     300
#define SPECIES_DELCATTY   301
#define SPECIES_SABLEYE    302
#define SPECIES_MAWILE     303
#define SPECIES_ARON       304
#define SPECIES_LAIRON     305
#define SPECIES_AGGRON     306
#define SPECIES_MEDITITE   307
#define SPECIES_MEDICHAM   308
#define SPECIES_ELECTRIKE  309
#define SPECIES_MANECTRIC  310
#define SPECIES_PLUSLE     311
#define SPECIES_MINUN      312
#define SPECIES_VOLBEAT    313
#define SPECIES_ILLUMISE   314
#define SPECIES_ROSELIA    315
#define SPECIES_GULPIN     316
#define SPECIES_SWALOT     317
#define SPECIES_CARVANHA   318
#define SPECIES_SHARPEDO   319
#define SPECIES_WAILMER    320
#define SPECIES_WAILORD    321
#define SPECIES_NUMEL      322
#define SPECIES_CAMERUPT   323
#define SPECIES_TORKOAL    324
#define SPECIES_SPOINK     325
#define SPECIES_GRUMPIG    326
#define SPECIES_SPINDA     327
#define SPECIES_TRAPINCH   328
#define SPECIES_VIBRAVA    329
#define SPECIES_FLYGON     330
#define SPECIES_CACNEA     331
#define SPECIES_CACTURNE   332
#define SPECIES_SWABLU     333
#define SPECIES_ALTARIA    334
#define SPECIES_ZANGOOSE   335
#define SPECIES_SEVIPER    336
#define SPECIES_LUNATONE   337
#define SPECIES_SOLROCK    338
#define SPECIES_BARBOACH   339
#define SPECIES_WHISCASH   340
#define SPECIES_CORPHISH   341
#define SPECIES_CRAWDAUNT  342
#define SPECIES_BALTOY     343
#define SPECIES_CLAYDOL    344
#define SPECIES_LILEEP     345
#define SPECIES_CRADILY    346
#define SPECIES_ANORITH    347
#define SPECIES_ARMALDO    348
#define SPECIES_FEEBAS     349
#define SPECIES_MILOTIC    350
#define SPECIES_CASTFORM   351
#define SPECIES_KECLEON    352
#define SPECIES_SHUPPET    353
#define SPECIES_BANETTE    354
#define SPECIES_DUSKULL    355
#define SPECIES_DUSCLOPS   356
#define SPECIES_TROPIUS    357
#define SPECIES_CHIMECHO   358
#define SPECIES_ABSOL      359
#define SPECIES_WYNAUT     360
#define SPECIES_SNORUNT    361
#define SPECIES_GLALIE     362
#define SPECIES_SPHEAL     363
#define SPECIES_SEALEO     364
#define SPECIES_WALREIN    365
#define SPECIES_CLAMPERL   366
#define SPECIES_HUNTAIL    367
#define SPECIES_GOREBYSS   368
#define SPECIES_RELICANTH  369
#define SPECIES_LUVDISC    370
#define SPECIES_BAGON      371
#define SPECIES_SHELGON    372
#define SPECIES_SALAMENCE  373
#define SPECIES_BELDUM     374
#define SPECIES_METANG     375
#define SPECIES_METAGROSS  376
#define SPECIES_REGIROCK   377
#define SPECIES_REGICE     378
#define SPECIES_REGISTEEL  379
#define SPECIES_LATIAS     380
#define SPECIES_LATIOS     381
#define SPECIES_KYOGRE     382
#define SPECIES_GROUDON    383
#define SPECIES_RAYQUAZA   384
#define SPECIES_JIRACHI    385
#define SPECIES_DEOXYS     386

#define HOENN_DEX_COUNT SPECIES_DEOXYS

#define SPECIES_TURTWIG    387
#define SPECIES_GROTLE     388
#define SPECIES_TORTERRA   389
#define SPECIES_CHIMCHAR   390
#define SPECIES_MONFERNO   391
#define SPECIES_INFERNAPE  392
#define SPECIES_PIPLUP     393
#define SPECIES_PRINPLUP   394
#define SPECIES_EMPOLEON   395
#define SPECIES_STARLY     396
#define SPECIES_STARAVIA   397
#define SPECIES_STARAPTOR  398
#define SPECIES_BIDOOF     399
#define SPECIES_BIBAREL    400
#define SPECIES_KRICKETOT  401
#define SPECIES_KRICKETUNE 402
#define SPECIES_SHINX      403
#define SPECIES_LUXIO      404
#define SPECIES_LUXRAY     405
#define SPECIES_BUDEW      406
#define SPECIES_ROSERADE   407
#define SPECIES_CRANIDOS   408
#define SPECIES_RAMPARDOS  409
#define SPECIES_SHIELDON   410
#define SPECIES_BASTIODON  411
#define SPECIES_BURMY      412
#define SPECIES_WORMADAM   413
#define SPECIES_MOTHIM     414
#define SPECIES_COMBEE     415
#define SPECIES_VESPIQUEN  416
#define SPECIES_PACHIRISU  417
#define SPECIES_BUIZEL     418
#define SPECIES_FLOATZEL   419
#define SPECIES_CHERUBI    420
#define SPECIES_CHERRIM    421
#define SPECIES_SHELLOS    422
#define SPECIES_GASTRODON  423
#define SPECIES_AMBIPOM    424
#define SPECIES_DRIFLOON   425
#define SPECIES_DRIFBLIM   426
#define SPECIES_BUNEARY    427
#define SPECIES_LOPUNNY    428
#define SPECIES_MISMAGIUS  429
#define SPECIES_HONCHKROW  430
#define SPECIES_GLAMEOW    431
#define SPECIES_PURUGLY    432
#define SPECIES_CHINGLING  433
#define SPECIES_STUNKY     434
#define SPECIES_SKUNTANK   435
#define SPECIES_BRONZOR    436
#define SPECIES_BRONZONG   437
#define SPECIES_BONSLY     438
#define SPECIES_MIME_JR    439
#define SPECIES_HAPPINY    440
#define SPECIES_CHATOT     441
#define SPECIES_SPIRITOMB  442
#define SPECIES_GIBLE      443
#define SPECIES_GABITE     444
#define SPECIES_GARCHOMP   445
#define SPECIES_MUNCHLAX   446
#define SPECIES_RIOLU      447
#define SPECIES_LUCARIO    448
#define SPECIES_HIPPOPOTAS 449
#define SPECIES_HIPPOWDON  450
#define SPECIES_SKORUPI    451
#define SPECIES_DRAPION    452
#define SPECIES_CROAGUNK   453
#define SPECIES_TOXICROAK  454
#define SPECIES_CARNIVINE  455
#define SPECIES_FINNEON    456
#define SPECIES_LUMINEON   457
#define SPECIES_MANTYKE    458
#define SPECIES_SNOVER     459
#define SPECIES_ABOMASNOW  460
#define SPECIES_WEAVILE    461
#define SPECIES_MAGNEZONE  462
#define SPECIES_LICKILICKY 463
#define SPECIES_RHYPERIOR  464
#define SPECIES_TANGROWTH  465
#define SPECIES_ELECTIVIRE 466
#define SPECIES_MAGMORTAR  467
#define SPECIES_TOGEKISS   468
#define SPECIES_YANMEGA    469
#define SPECIES_LEAFEON    470
#define SPECIES_GLACEON    471
#define SPECIES_GLISCOR    472
#define SPECIES_MAMOSWINE  473
#define SPECIES_PORYGON_Z  474
#define SPECIES_GALLADE    475
#define SPECIES_PROBOPASS  476
#define SPECIES_DUSKNOIR   477
#define SPECIES_FROSLASS   478
#define SPECIES_ROTOM      479
#define SPECIES_UXIE       480
#define SPECIES_MESPRIT    481
#define SPECIES_AZELF      482
#define SPECIES_DIALGA     483
#define SPECIES_PALKIA     484
#define SPECIES_HEATRAN    485
#define SPECIES_REGIGIGAS  486
#define SPECIES_GIRATINA   487
#define SPECIES_CRESSELIA  488
#define SPECIES_PHIONE     489
#define SPECIES_MANAPHY    490
#define SPECIES_DARKRAI    491
#define SPECIES_SHAYMIN    492
#define SPECIES_ARCEUS     493

#define MAX_SPECIES SPECIES_ARCEUS


#define SPECIES_EGG             494
#define SPECIES_BAD_EGG         495
#define SPECIES_DEOXYS_ATK      496
#define SPECIES_DEOXYS_DEF      497
#define SPECIES_DEOXYS_SPD      498
#define SPECIES_WORMADAM_SANDY  499
#define SPECIES_WORMADAM_TRASH  500
#define SPECIES_GIRATINA_ORIGIN 501
#define SPECIES_SHAYMIN_SKY     502
#define SPECIES_ROTOM_HEAT      503
#define SPECIES_ROTOM_WASH      504
#define SPECIES_ROTOM_FROST     505
#define SPECIES_ROTOM_FAN       506
#define SPECIES_ROTOM_MOW       507

// The species New Gold reaches beyond HGSS. They are appended rather than
// placed at their National Dex numbers, which 494 to 507 already use for the
// egg, the bad egg and the alternate forms: every identifier a save, a table
// or an interface already expects keeps its place, and the Dex number stops
// being the same thing as the species identifier.
#define SPECIES_LILLIPUP        508
#define SPECIES_HERDIER         509
#define SPECIES_STOUTLAND       510
#define SPECIES_PURRLOIN        511
#define SPECIES_LIEPARD         512
#define SPECIES_TYMPOLE         513
#define SPECIES_PALPITOAD       514
#define SPECIES_SEISMITOAD      515
#define SPECIES_SEWADDLE        516
#define SPECIES_SWADLOON        517
#define SPECIES_LEAVANNY        518
#define SPECIES_YAMASK          519
#define SPECIES_COFAGRIGUS      520
#define SPECIES_TRUBBISH        521
#define SPECIES_GARBODOR        522
#define SPECIES_EMOLGA          523
#define SPECIES_KARRABLAST      524
#define SPECIES_ESCAVALIER      525
#define SPECIES_FOONGUS         526
#define SPECIES_AMOONGUSS       527
#define SPECIES_JOLTIK          528
#define SPECIES_GALVANTULA      529
#define SPECIES_FERROSEED       530
#define SPECIES_FERROTHORN      531
#define SPECIES_KLINK           532
#define SPECIES_KLANG           533
#define SPECIES_KLINKLANG       534
#define SPECIES_ELGYEM          535
#define SPECIES_BEHEEYEM        536
#define SPECIES_LITWICK         537
#define SPECIES_LAMPENT         538
#define SPECIES_CHANDELURE      539
#define SPECIES_SHELMET         540
#define SPECIES_ACCELGOR        541
#define SPECIES_BOUFFALANT      542
#define SPECIES_BUNNELBY        543
#define SPECIES_DIGGERSBY       544
#define SPECIES_FLETCHLING      545
#define SPECIES_FLETCHINDER     546
#define SPECIES_TALONFLAME      547
#define SPECIES_LITLEO          548
#define SPECIES_PYROAR          549
#define SPECIES_ESPURR          550
#define SPECIES_MEOWSTIC        551
#define SPECIES_SYLVEON         552
#define SPECIES_DEDENNE         553
#define SPECIES_PHANTUMP        554
#define SPECIES_TREVENANT       555
#define SPECIES_PUMPKABOO       556
#define SPECIES_GOURGEIST       557
#define SPECIES_NOIBAT          558
#define SPECIES_NOIVERN         559
#define SPECIES_APPLIN          560
#define SPECIES_FLAPPLE         561
#define SPECIES_APPLETUN        562
#define SPECIES_SIZZLIPEDE      563
#define SPECIES_CENTISKORCH     564
#define SPECIES_WYRDEER         565
#define SPECIES_KLEAVOR         566
#define SPECIES_URSALUNA        567
#define SPECIES_ANNIHILAPE      568
#define SPECIES_FARIGIRAF       569
#define SPECIES_DUDUNSPARCE     570
#define SPECIES_DIPPLIN         571
#define SPECIES_HYDRAPPLE       572
// Two regional forms, which New Gold's trainers use as species in their own
// right rather than as forms of the Johto Slowpoke line.
#define SPECIES_SLOWPOKE_GALARIAN 573
#define SPECIES_SLOWBRO_GALARIAN  574

// Everything else the reference defines, in National Dex order. The rule
// is no longer "only what the game reaches": New Gold is developed on this
// repository now, so any of these can be put in Trainers.c without asking
// for an import first. See docs/newgold/SCOPE.md.
#define SPECIES_VICTINI                  575
#define SPECIES_SNIVY                    576
#define SPECIES_SERVINE                  577
#define SPECIES_SERPERIOR                578
#define SPECIES_TEPIG                    579
#define SPECIES_PIGNITE                  580
#define SPECIES_EMBOAR                   581
#define SPECIES_OSHAWOTT                 582
#define SPECIES_DEWOTT                   583
#define SPECIES_SAMUROTT                 584
#define SPECIES_PATRAT                   585
#define SPECIES_WATCHOG                  586
#define SPECIES_PANSAGE                  587
#define SPECIES_SIMISAGE                 588
#define SPECIES_PANSEAR                  589
#define SPECIES_SIMISEAR                 590
#define SPECIES_PANPOUR                  591
#define SPECIES_SIMIPOUR                 592
#define SPECIES_MUNNA                    593
#define SPECIES_MUSHARNA                 594
#define SPECIES_PIDOVE                   595
#define SPECIES_TRANQUILL                596
#define SPECIES_UNFEZANT                 597
#define SPECIES_BLITZLE                  598
#define SPECIES_ZEBSTRIKA                599
#define SPECIES_ROGGENROLA               600
#define SPECIES_BOLDORE                  601
#define SPECIES_GIGALITH                 602
#define SPECIES_WOOBAT                   603
#define SPECIES_SWOOBAT                  604
#define SPECIES_DRILBUR                  605
#define SPECIES_EXCADRILL                606
#define SPECIES_AUDINO                   607
#define SPECIES_TIMBURR                  608
#define SPECIES_GURDURR                  609
#define SPECIES_CONKELDURR               610
#define SPECIES_THROH                    611
#define SPECIES_SAWK                     612
#define SPECIES_VENIPEDE                 613
#define SPECIES_WHIRLIPEDE               614
#define SPECIES_SCOLIPEDE                615
#define SPECIES_COTTONEE                 616
#define SPECIES_WHIMSICOTT               617
#define SPECIES_PETILIL                  618
#define SPECIES_LILLIGANT                619
#define SPECIES_BASCULIN                 620
#define SPECIES_SANDILE                  621
#define SPECIES_KROKOROK                 622
#define SPECIES_KROOKODILE               623
#define SPECIES_DARUMAKA                 624
#define SPECIES_DARMANITAN               625
#define SPECIES_MARACTUS                 626
#define SPECIES_DWEBBLE                  627
#define SPECIES_CRUSTLE                  628
#define SPECIES_SCRAGGY                  629
#define SPECIES_SCRAFTY                  630
#define SPECIES_SIGILYPH                 631
#define SPECIES_TIRTOUGA                 632
#define SPECIES_CARRACOSTA               633
#define SPECIES_ARCHEN                   634
#define SPECIES_ARCHEOPS                 635
#define SPECIES_ZORUA                    636
#define SPECIES_ZOROARK                  637
#define SPECIES_MINCCINO                 638
#define SPECIES_CINCCINO                 639
#define SPECIES_GOTHITA                  640
#define SPECIES_GOTHORITA                641
#define SPECIES_GOTHITELLE               642
#define SPECIES_SOLOSIS                  643
#define SPECIES_DUOSION                  644
#define SPECIES_REUNICLUS                645
#define SPECIES_DUCKLETT                 646
#define SPECIES_SWANNA                   647
#define SPECIES_VANILLITE                648
#define SPECIES_VANILLISH                649
#define SPECIES_VANILLUXE                650
#define SPECIES_DEERLING                 651
#define SPECIES_SAWSBUCK                 652
#define SPECIES_FRILLISH                 653
#define SPECIES_JELLICENT                654
#define SPECIES_ALOMOMOLA                655
#define SPECIES_TYNAMO                   656
#define SPECIES_EELEKTRIK                657
#define SPECIES_EELEKTROSS               658
#define SPECIES_AXEW                     659
#define SPECIES_FRAXURE                  660
#define SPECIES_HAXORUS                  661
#define SPECIES_CUBCHOO                  662
#define SPECIES_BEARTIC                  663
#define SPECIES_CRYOGONAL                664
#define SPECIES_STUNFISK                 665
#define SPECIES_MIENFOO                  666
#define SPECIES_MIENSHAO                 667
#define SPECIES_DRUDDIGON                668
#define SPECIES_GOLETT                   669
#define SPECIES_GOLURK                   670
#define SPECIES_PAWNIARD                 671
#define SPECIES_BISHARP                  672
#define SPECIES_RUFFLET                  673
#define SPECIES_BRAVIARY                 674
#define SPECIES_VULLABY                  675
#define SPECIES_MANDIBUZZ                676
#define SPECIES_HEATMOR                  677
#define SPECIES_DURANT                   678
#define SPECIES_DEINO                    679
#define SPECIES_ZWEILOUS                 680
#define SPECIES_HYDREIGON                681
#define SPECIES_LARVESTA                 682
#define SPECIES_VOLCARONA                683
#define SPECIES_COBALION                 684
#define SPECIES_TERRAKION                685
#define SPECIES_VIRIZION                 686
#define SPECIES_TORNADUS                 687
#define SPECIES_THUNDURUS                688
#define SPECIES_RESHIRAM                 689
#define SPECIES_ZEKROM                   690
#define SPECIES_LANDORUS                 691
#define SPECIES_KYUREM                   692
#define SPECIES_KELDEO                   693
#define SPECIES_MELOETTA                 694
#define SPECIES_GENESECT                 695
#define SPECIES_CHESPIN                  696
#define SPECIES_QUILLADIN                697
#define SPECIES_CHESNAUGHT               698
#define SPECIES_FENNEKIN                 699
#define SPECIES_BRAIXEN                  700
#define SPECIES_DELPHOX                  701
#define SPECIES_FROAKIE                  702
#define SPECIES_FROGADIER                703
#define SPECIES_GRENINJA                 704
#define SPECIES_SCATTERBUG               705
#define SPECIES_SPEWPA                   706
#define SPECIES_VIVILLON                 707
#define SPECIES_FLABEBE                  708
#define SPECIES_FLOETTE                  709
#define SPECIES_FLORGES                  710
#define SPECIES_SKIDDO                   711
#define SPECIES_GOGOAT                   712
#define SPECIES_PANCHAM                  713
#define SPECIES_PANGORO                  714
#define SPECIES_FURFROU                  715
#define SPECIES_HONEDGE                  716
#define SPECIES_DOUBLADE                 717
#define SPECIES_AEGISLASH                718
#define SPECIES_SPRITZEE                 719
#define SPECIES_AROMATISSE               720
#define SPECIES_SWIRLIX                  721
#define SPECIES_SLURPUFF                 722
#define SPECIES_INKAY                    723
#define SPECIES_MALAMAR                  724
#define SPECIES_BINACLE                  725
#define SPECIES_BARBARACLE               726
#define SPECIES_SKRELP                   727
#define SPECIES_DRAGALGE                 728
#define SPECIES_CLAUNCHER                729
#define SPECIES_CLAWITZER                730
#define SPECIES_HELIOPTILE               731
#define SPECIES_HELIOLISK                732
#define SPECIES_TYRUNT                   733
#define SPECIES_TYRANTRUM                734
#define SPECIES_AMAURA                   735
#define SPECIES_AURORUS                  736
#define SPECIES_HAWLUCHA                 737
#define SPECIES_CARBINK                  738
#define SPECIES_GOOMY                    739
#define SPECIES_SLIGGOO                  740
#define SPECIES_GOODRA                   741
#define SPECIES_KLEFKI                   742
#define SPECIES_BERGMITE                 743
#define SPECIES_AVALUGG                  744
#define SPECIES_XERNEAS                  745
#define SPECIES_YVELTAL                  746
#define SPECIES_ZYGARDE                  747
#define SPECIES_DIANCIE                  748
#define SPECIES_HOOPA                    749
#define SPECIES_VOLCANION                750
#define SPECIES_ROWLET                   751
#define SPECIES_DARTRIX                  752
#define SPECIES_DECIDUEYE                753
#define SPECIES_LITTEN                   754
#define SPECIES_TORRACAT                 755
#define SPECIES_INCINEROAR               756
#define SPECIES_POPPLIO                  757
#define SPECIES_BRIONNE                  758
#define SPECIES_PRIMARINA                759
#define SPECIES_PIKIPEK                  760
#define SPECIES_TRUMBEAK                 761
#define SPECIES_TOUCANNON                762
#define SPECIES_YUNGOOS                  763
#define SPECIES_GUMSHOOS                 764
#define SPECIES_GRUBBIN                  765
#define SPECIES_CHARJABUG                766
#define SPECIES_VIKAVOLT                 767
#define SPECIES_CRABRAWLER               768
#define SPECIES_CRABOMINABLE             769
#define SPECIES_ORICORIO                 770
#define SPECIES_CUTIEFLY                 771
#define SPECIES_RIBOMBEE                 772
#define SPECIES_ROCKRUFF                 773
#define SPECIES_LYCANROC                 774
#define SPECIES_WISHIWASHI               775
#define SPECIES_MAREANIE                 776
#define SPECIES_TOXAPEX                  777
#define SPECIES_MUDBRAY                  778
#define SPECIES_MUDSDALE                 779
#define SPECIES_DEWPIDER                 780
#define SPECIES_ARAQUANID                781
#define SPECIES_FOMANTIS                 782
#define SPECIES_LURANTIS                 783
#define SPECIES_MORELULL                 784
#define SPECIES_SHIINOTIC                785
#define SPECIES_SALANDIT                 786
#define SPECIES_SALAZZLE                 787
#define SPECIES_STUFFUL                  788
#define SPECIES_BEWEAR                   789
#define SPECIES_BOUNSWEET                790
#define SPECIES_STEENEE                  791
#define SPECIES_TSAREENA                 792
#define SPECIES_COMFEY                   793
#define SPECIES_ORANGURU                 794
#define SPECIES_PASSIMIAN                795
#define SPECIES_WIMPOD                   796
#define SPECIES_GOLISOPOD                797
#define SPECIES_SANDYGAST                798
#define SPECIES_PALOSSAND                799
#define SPECIES_PYUKUMUKU                800
#define SPECIES_TYPE_NULL                801
#define SPECIES_SILVALLY                 802
#define SPECIES_MINIOR                   803
#define SPECIES_KOMALA                   804
#define SPECIES_TURTONATOR               805
#define SPECIES_TOGEDEMARU               806
#define SPECIES_MIMIKYU                  807
#define SPECIES_BRUXISH                  808
#define SPECIES_DRAMPA                   809
#define SPECIES_DHELMISE                 810
#define SPECIES_JANGMO_O                 811
#define SPECIES_HAKAMO_O                 812
#define SPECIES_KOMMO_O                  813
#define SPECIES_TAPU_KOKO                814
#define SPECIES_TAPU_LELE                815
#define SPECIES_TAPU_BULU                816
#define SPECIES_TAPU_FINI                817
#define SPECIES_COSMOG                   818
#define SPECIES_COSMOEM                  819
#define SPECIES_SOLGALEO                 820
#define SPECIES_LUNALA                   821
#define SPECIES_NIHILEGO                 822
#define SPECIES_BUZZWOLE                 823
#define SPECIES_PHEROMOSA                824
#define SPECIES_XURKITREE                825
#define SPECIES_CELESTEELA               826
#define SPECIES_KARTANA                  827
#define SPECIES_GUZZLORD                 828
#define SPECIES_NECROZMA                 829
#define SPECIES_MAGEARNA                 830
#define SPECIES_MARSHADOW                831
#define SPECIES_POIPOLE                  832
#define SPECIES_NAGANADEL                833
#define SPECIES_STAKATAKA                834
#define SPECIES_BLACEPHALON              835
#define SPECIES_ZERAORA                  836
#define SPECIES_MELTAN                   837
#define SPECIES_MELMETAL                 838
#define SPECIES_GROOKEY                  839
#define SPECIES_THWACKEY                 840
#define SPECIES_RILLABOOM                841
#define SPECIES_SCORBUNNY                842
#define SPECIES_RABOOT                   843
#define SPECIES_CINDERACE                844
#define SPECIES_SOBBLE                   845
#define SPECIES_DRIZZILE                 846
#define SPECIES_INTELEON                 847
#define SPECIES_SKWOVET                  848
#define SPECIES_GREEDENT                 849
#define SPECIES_ROOKIDEE                 850
#define SPECIES_CORVISQUIRE              851
#define SPECIES_CORVIKNIGHT              852
#define SPECIES_BLIPBUG                  853
#define SPECIES_DOTTLER                  854
#define SPECIES_ORBEETLE                 855
#define SPECIES_NICKIT                   856
#define SPECIES_THIEVUL                  857
#define SPECIES_GOSSIFLEUR               858
#define SPECIES_ELDEGOSS                 859
#define SPECIES_WOOLOO                   860
#define SPECIES_DUBWOOL                  861
#define SPECIES_CHEWTLE                  862
#define SPECIES_DREDNAW                  863
#define SPECIES_YAMPER                   864
#define SPECIES_BOLTUND                  865
#define SPECIES_ROLYCOLY                 866
#define SPECIES_CARKOL                   867
#define SPECIES_COALOSSAL                868
#define SPECIES_SILICOBRA                869
#define SPECIES_SANDACONDA               870
#define SPECIES_CRAMORANT                871
#define SPECIES_ARROKUDA                 872
#define SPECIES_BARRASKEWDA              873
#define SPECIES_TOXEL                    874
#define SPECIES_TOXTRICITY               875
#define SPECIES_CLOBBOPUS                876
#define SPECIES_GRAPPLOCT                877
#define SPECIES_SINISTEA                 878
#define SPECIES_POLTEAGEIST              879
#define SPECIES_HATENNA                  880
#define SPECIES_HATTREM                  881
#define SPECIES_HATTERENE                882
#define SPECIES_IMPIDIMP                 883
#define SPECIES_MORGREM                  884
#define SPECIES_GRIMMSNARL               885
#define SPECIES_OBSTAGOON                886
#define SPECIES_PERRSERKER               887
#define SPECIES_CURSOLA                  888
#define SPECIES_SIRFETCHD                889
#define SPECIES_MR_RIME                  890
#define SPECIES_RUNERIGUS                891
#define SPECIES_MILCERY                  892
#define SPECIES_ALCREMIE                 893
#define SPECIES_FALINKS                  894
#define SPECIES_PINCURCHIN               895
#define SPECIES_SNOM                     896
#define SPECIES_FROSMOTH                 897
#define SPECIES_STONJOURNER              898
#define SPECIES_EISCUE                   899
#define SPECIES_INDEEDEE                 900
#define SPECIES_MORPEKO                  901
#define SPECIES_CUFANT                   902
#define SPECIES_COPPERAJAH               903
#define SPECIES_DRACOZOLT                904
#define SPECIES_ARCTOZOLT                905
#define SPECIES_DRACOVISH                906
#define SPECIES_ARCTOVISH                907
#define SPECIES_DURALUDON                908
#define SPECIES_DREEPY                   909
#define SPECIES_DRAKLOAK                 910
#define SPECIES_DRAGAPULT                911
#define SPECIES_ZACIAN                   912
#define SPECIES_ZAMAZENTA                913
#define SPECIES_ETERNATUS                914
#define SPECIES_KUBFU                    915
#define SPECIES_URSHIFU                  916
#define SPECIES_ZARUDE                   917
#define SPECIES_REGIELEKI                918
#define SPECIES_REGIDRAGO                919
#define SPECIES_GLASTRIER                920
#define SPECIES_SPECTRIER                921
#define SPECIES_CALYREX                  922
#define SPECIES_BASCULEGION              923
#define SPECIES_SNEASLER                 924
#define SPECIES_OVERQWIL                 925
#define SPECIES_ENAMORUS                 926
#define SPECIES_SPRIGATITO               927
#define SPECIES_FLORAGATO                928
#define SPECIES_MEOWSCARADA              929
#define SPECIES_FUECOCO                  930
#define SPECIES_CROCALOR                 931
#define SPECIES_SKELEDIRGE               932
#define SPECIES_QUAXLY                   933
#define SPECIES_QUAXWELL                 934
#define SPECIES_QUAQUAVAL                935
#define SPECIES_LECHONK                  936
#define SPECIES_OINKOLOGNE               937
#define SPECIES_TAROUNTULA               938
#define SPECIES_SPIDOPS                  939
#define SPECIES_NYMBLE                   940
#define SPECIES_LOKIX                    941
#define SPECIES_PAWMI                    942
#define SPECIES_PAWMO                    943
#define SPECIES_PAWMOT                   944
#define SPECIES_TANDEMAUS                945
#define SPECIES_MAUSHOLD                 946
#define SPECIES_FIDOUGH                  947
#define SPECIES_DACHSBUN                 948
#define SPECIES_SMOLIV                   949
#define SPECIES_DOLLIV                   950
#define SPECIES_ARBOLIVA                 951
#define SPECIES_SQUAWKABILLY             952
#define SPECIES_NACLI                    953
#define SPECIES_NACLSTACK                954
#define SPECIES_GARGANACL                955
#define SPECIES_CHARCADET                956
#define SPECIES_ARMAROUGE                957
#define SPECIES_CERULEDGE                958
#define SPECIES_TADBULB                  959
#define SPECIES_BELLIBOLT                960
#define SPECIES_WATTREL                  961
#define SPECIES_KILOWATTREL              962
#define SPECIES_MASCHIFF                 963
#define SPECIES_MABOSSTIFF               964
#define SPECIES_SHROODLE                 965
#define SPECIES_GRAFAIAI                 966
#define SPECIES_BRAMBLIN                 967
#define SPECIES_BRAMBLEGHAST             968
#define SPECIES_TOEDSCOOL                969
#define SPECIES_TOEDSCRUEL               970
#define SPECIES_KLAWF                    971
#define SPECIES_CAPSAKID                 972
#define SPECIES_SCOVILLAIN               973
#define SPECIES_RELLOR                   974
#define SPECIES_RABSCA                   975
#define SPECIES_FLITTLE                  976
#define SPECIES_ESPATHRA                 977
#define SPECIES_TINKATINK                978
#define SPECIES_TINKATUFF                979
#define SPECIES_TINKATON                 980
#define SPECIES_WIGLETT                  981
#define SPECIES_WUGTRIO                  982
#define SPECIES_BOMBIRDIER               983
#define SPECIES_FINIZEN                  984
#define SPECIES_PALAFIN                  985
#define SPECIES_VAROOM                   986
#define SPECIES_REVAVROOM                987
#define SPECIES_CYCLIZAR                 988
#define SPECIES_ORTHWORM                 989
#define SPECIES_GLIMMET                  990
#define SPECIES_GLIMMORA                 991
#define SPECIES_GREAVARD                 992
#define SPECIES_HOUNDSTONE               993
#define SPECIES_FLAMIGO                  994
#define SPECIES_CETODDLE                 995
#define SPECIES_CETITAN                  996
#define SPECIES_VELUZA                   997
#define SPECIES_DONDOZO                  998
#define SPECIES_TATSUGIRI                999
#define SPECIES_CLODSIRE                 1000
#define SPECIES_KINGAMBIT                1001
#define SPECIES_GREAT_TUSK               1002
#define SPECIES_SCREAM_TAIL              1003
#define SPECIES_BRUTE_BONNET             1004
#define SPECIES_FLUTTER_MANE             1005
#define SPECIES_SLITHER_WING             1006
#define SPECIES_SANDY_SHOCKS             1007
#define SPECIES_IRON_TREADS              1008
#define SPECIES_IRON_BUNDLE              1009
#define SPECIES_IRON_HANDS               1010
#define SPECIES_IRON_JUGULIS             1011
#define SPECIES_IRON_MOTH                1012
#define SPECIES_IRON_THORNS              1013
#define SPECIES_FRIGIBAX                 1014
#define SPECIES_ARCTIBAX                 1015
#define SPECIES_BAXCALIBUR               1016
#define SPECIES_GIMMIGHOUL               1017
#define SPECIES_GHOLDENGO                1018
#define SPECIES_WO_CHIEN                 1019
#define SPECIES_CHIEN_PAO                1020
#define SPECIES_TING_LU                  1021
#define SPECIES_CHI_YU                   1022
#define SPECIES_ROARING_MOON             1023
#define SPECIES_IRON_VALIANT             1024
#define SPECIES_KORAIDON                 1025
#define SPECIES_MIRAIDON                 1026
#define SPECIES_WALKING_WAKE             1027
#define SPECIES_IRON_LEAVES              1028
#define SPECIES_POLTCHAGEIST             1029
#define SPECIES_SINISTCHA                1030
#define SPECIES_OKIDOGI                  1031
#define SPECIES_MUNKIDORI                1032
#define SPECIES_FEZANDIPITI              1033
#define SPECIES_OGERPON                  1034
#define SPECIES_ARCHALUDON               1035
#define SPECIES_GOUGING_FIRE             1036
#define SPECIES_RAGING_BOLT              1037
#define SPECIES_IRON_BOULDER             1038
#define SPECIES_IRON_CROWN               1039
#define SPECIES_TERAPAGOS                1040
#define SPECIES_PECHARUNT                1041

#define SPECIES_MEGA_VENUSAUR   1042
#define SPECIES_MEGA_CHARIZARD_X 1043
#define SPECIES_MEGA_CHARIZARD_Y 1044
#define SPECIES_MEGA_BLASTOISE  1045
#define SPECIES_MEGA_BEEDRILL   1046
#define SPECIES_MEGA_PIDGEOT    1047
#define SPECIES_MEGA_ALAKAZAM   1048
#define SPECIES_MEGA_SLOWBRO    1049
#define SPECIES_MEGA_GENGAR     1050
#define SPECIES_MEGA_KANGASKHAN 1051
#define SPECIES_MEGA_PINSIR     1052
#define SPECIES_MEGA_GYARADOS   1053
#define SPECIES_MEGA_AERODACTYL 1054
#define SPECIES_MEGA_MEWTWO_X   1055
#define SPECIES_MEGA_MEWTWO_Y   1056
#define SPECIES_MEGA_AMPHAROS   1057
#define SPECIES_MEGA_STEELIX    1058
#define SPECIES_MEGA_SCIZOR     1059
#define SPECIES_MEGA_HERACROSS  1060
#define SPECIES_MEGA_HOUNDOOM   1061
#define SPECIES_MEGA_TYRANITAR  1062
#define SPECIES_MEGA_SCEPTILE   1063
#define SPECIES_MEGA_BLAZIKEN   1064
#define SPECIES_MEGA_SWAMPERT   1065
#define SPECIES_MEGA_GARDEVOIR  1066
#define SPECIES_MEGA_SABLEYE    1067
#define SPECIES_MEGA_MAWILE     1068
#define SPECIES_MEGA_AGGRON     1069
#define SPECIES_MEGA_MEDICHAM   1070
#define SPECIES_MEGA_MANECTRIC  1071
#define SPECIES_MEGA_SHARPEDO   1072
#define SPECIES_MEGA_CAMERUPT   1073
#define SPECIES_MEGA_ALTARIA    1074
#define SPECIES_MEGA_BANETTE    1075
#define SPECIES_MEGA_ABSOL      1076
#define SPECIES_MEGA_GLALIE     1077
#define SPECIES_MEGA_SALAMENCE  1078
#define SPECIES_MEGA_METAGROSS  1079
#define SPECIES_MEGA_LATIAS     1080
#define SPECIES_MEGA_LATIOS     1081
#define SPECIES_MEGA_RAYQUAZA   1082
#define SPECIES_MEGA_LOPUNNY    1083
#define SPECIES_MEGA_GARCHOMP   1084
#define SPECIES_MEGA_LUCARIO    1085
#define SPECIES_MEGA_ABOMASNOW  1086
#define SPECIES_MEGA_GALLADE    1087
#define SPECIES_MEGA_AUDINO     1088
#define SPECIES_MEGA_DIANCIE    1089
#define SPECIES_KYOGRE_PRIMAL   1090
#define SPECIES_GROUDON_PRIMAL  1091
#define SPECIES_RATTATA_ALOLAN  1092
#define SPECIES_RATICATE_ALOLAN 1093
#define SPECIES_RAICHU_ALOLAN   1094
#define SPECIES_SANDSHREW_ALOLAN 1095
#define SPECIES_SANDSLASH_ALOLAN 1096
#define SPECIES_VULPIX_ALOLAN   1097
#define SPECIES_NINETALES_ALOLAN 1098
#define SPECIES_DIGLETT_ALOLAN  1099
#define SPECIES_DUGTRIO_ALOLAN  1100
#define SPECIES_MEOWTH_ALOLAN   1101
#define SPECIES_PERSIAN_ALOLAN  1102
#define SPECIES_GEODUDE_ALOLAN  1103
#define SPECIES_GRAVELER_ALOLAN 1104
#define SPECIES_GOLEM_ALOLAN    1105
#define SPECIES_GRIMER_ALOLAN   1106
#define SPECIES_MUK_ALOLAN      1107
#define SPECIES_EXEGGUTOR_ALOLAN 1108
#define SPECIES_MAROWAK_ALOLAN  1109
#define SPECIES_RATICATE_ALOLAN_LARGE 1110
#define SPECIES_MAROWAK_ALOLAN_LARGE 1111
#define SPECIES_GUMSHOOS_LARGE  1112
#define SPECIES_VIKAVOLT_LARGE  1113
#define SPECIES_RIBOMBEE_LARGE  1114
#define SPECIES_ARAQUANID_LARGE 1115
#define SPECIES_LURANTIS_LARGE  1116
#define SPECIES_SALAZZLE_LARGE  1117
#define SPECIES_TOGEDEMARU_LARGE 1118
#define SPECIES_MIMIKYU_LARGE   1119
#define SPECIES_MIMIKYU_BUSTED_LARGE 1120
#define SPECIES_KOMMO_O_LARGE   1121
#define SPECIES_MEOWTH_GALARIAN 1122
#define SPECIES_PONYTA_GALARIAN 1123
#define SPECIES_RAPIDASH_GALARIAN 1124
#define SPECIES_FARFETCHD_GALARIAN 1125
#define SPECIES_WEEZING_GALARIAN 1126
#define SPECIES_MR_MIME_GALARIAN 1127
#define SPECIES_ARTICUNO_GALARIAN 1128
#define SPECIES_ZAPDOS_GALARIAN 1129
#define SPECIES_MOLTRES_GALARIAN 1130
#define SPECIES_SLOWKING_GALARIAN 1131
#define SPECIES_CORSOLA_GALARIAN 1132
#define SPECIES_ZIGZAGOON_GALARIAN 1133
#define SPECIES_LINOONE_GALARIAN 1134
#define SPECIES_DARUMAKA_GALARIAN 1135
#define SPECIES_DARMANITAN_GALARIAN 1136
#define SPECIES_YAMASK_GALARIAN 1137
#define SPECIES_STUNFISK_GALARIAN 1138
#define SPECIES_PIKACHU_COSPLAY 1139
#define SPECIES_PIKACHU_ROCK_STAR 1140
#define SPECIES_PIKACHU_BELLE   1141
#define SPECIES_PIKACHU_POP_STAR 1142
#define SPECIES_PIKACHU_PH_D    1143
#define SPECIES_PIKACHU_LIBRE   1144
#define SPECIES_PIKACHU_ORIGINAL_CAP 1145
#define SPECIES_PIKACHU_HOENN_CAP 1146
#define SPECIES_PIKACHU_SINNOH_CAP 1147
#define SPECIES_PIKACHU_UNOVA_CAP 1148
#define SPECIES_PIKACHU_KALOS_CAP 1149
#define SPECIES_PIKACHU_ALOLA_CAP 1150
#define SPECIES_PIKACHU_PARTNER_CAP 1151
#define SPECIES_PIKACHU_WORLD_CAP 1152
#define SPECIES_CASTFORM_SUNNY  1153
#define SPECIES_CASTFORM_RAINY  1154
#define SPECIES_CASTFORM_SNOWY  1155
#define SPECIES_CHERRIM_SUNSHINE 1156
#define SPECIES_SHELLOS_EAST_SEA 1157
#define SPECIES_GASTRODON_EAST_SEA 1158
#define SPECIES_DIALGA_ORIGIN   1159
#define SPECIES_PALKIA_ORIGIN   1160
#define SPECIES_BASCULIN_BLUE_STRIPED 1161
#define SPECIES_BASCULIN_WHITE_STRIPED 1162
#define SPECIES_DARMANITAN_ZEN_MODE 1163
#define SPECIES_DARMANITAN_ZEN_MODE_GALARIAN 1164
#define SPECIES_DEERLING_SUMMER 1165
#define SPECIES_DEERLING_AUTUMN 1166
#define SPECIES_DEERLING_WINTER 1167
#define SPECIES_SAWSBUCK_SUMMER 1168
#define SPECIES_SAWSBUCK_AUTUMN 1169
#define SPECIES_SAWSBUCK_WINTER 1170
#define SPECIES_TORNADUS_THERIAN 1171
#define SPECIES_THUNDURUS_THERIAN 1172
#define SPECIES_LANDORUS_THERIAN 1173
#define SPECIES_KYUREM_WHITE    1174
#define SPECIES_KYUREM_BLACK    1175
#define SPECIES_KELDEO_RESOLUTE 1176
#define SPECIES_MELOETTA_PIROUETTE 1177
#define SPECIES_GENESECT_DOUSE_DRIVE 1178
#define SPECIES_GENESECT_SHOCK_DRIVE 1179
#define SPECIES_GENESECT_BURN_DRIVE 1180
#define SPECIES_GENESECT_CHILL_DRIVE 1181
#define SPECIES_GRENINJA_BATTLE_BOND 1182
#define SPECIES_GRENINJA_ASH    1183
#define SPECIES_VIVILLON_POLAR  1184
#define SPECIES_VIVILLON_TUNDRA 1185
#define SPECIES_VIVILLON_CONTINENTAL 1186
#define SPECIES_VIVILLON_GARDEN 1187
#define SPECIES_VIVILLON_ELEGANT 1188
#define SPECIES_VIVILLON_MEADOW 1189
#define SPECIES_VIVILLON_MODERN 1190
#define SPECIES_VIVILLON_MARINE 1191
#define SPECIES_VIVILLON_ARCHIPELAGO 1192
#define SPECIES_VIVILLON_HIGH_PLAINS 1193
#define SPECIES_VIVILLON_SANDSTORM 1194
#define SPECIES_VIVILLON_RIVER  1195
#define SPECIES_VIVILLON_MONSOON 1196
#define SPECIES_VIVILLON_SAVANNA 1197
#define SPECIES_VIVILLON_SUN    1198
#define SPECIES_VIVILLON_OCEAN  1199
#define SPECIES_VIVILLON_JUNGLE 1200
#define SPECIES_VIVILLON_FANCY  1201
#define SPECIES_VIVILLON_POKE_BALL 1202
#define SPECIES_FLABEBE_YELLOW_FLOWER 1203
#define SPECIES_FLABEBE_ORANGE_FLOWER 1204
#define SPECIES_FLABEBE_BLUE_FLOWER 1205
#define SPECIES_FLABEBE_WHITE_FLOWER 1206
#define SPECIES_FLOETTE_YELLOW_FLOWER 1207
#define SPECIES_FLOETTE_ORANGE_FLOWER 1208
#define SPECIES_FLOETTE_BLUE_FLOWER 1209
#define SPECIES_FLOETTE_WHITE_FLOWER 1210
#define SPECIES_FLOETTE_ETERNAL_FLOWER 1211
#define SPECIES_FLORGES_YELLOW_FLOWER 1212
#define SPECIES_FLORGES_ORANGE_FLOWER 1213
#define SPECIES_FLORGES_BLUE_FLOWER 1214
#define SPECIES_FLORGES_WHITE_FLOWER 1215
#define SPECIES_FURFROU_HEART   1216
#define SPECIES_FURFROU_STAR    1217
#define SPECIES_FURFROU_DIAMOND 1218
#define SPECIES_FURFROU_DEBUTANTE 1219
#define SPECIES_FURFROU_MATRON  1220
#define SPECIES_FURFROU_DANDY   1221
#define SPECIES_FURFROU_LA_REINE 1222
#define SPECIES_FURFROU_KABUKI  1223
#define SPECIES_FURFROU_PHARAOH 1224
#define SPECIES_AEGISLASH_BLADE 1225
#define SPECIES_PUMPKABOO_SMALL 1226
#define SPECIES_PUMPKABOO_LARGE 1227
#define SPECIES_PUMPKABOO_SUPER 1228
#define SPECIES_GOURGEIST_SMALL 1229
#define SPECIES_GOURGEIST_LARGE 1230
#define SPECIES_GOURGEIST_SUPER 1231
#define SPECIES_XERNEAS_ACTIVE  1232
#define SPECIES_ZYGARDE_10      1233
#define SPECIES_ZYGARDE_10_POWER_CONSTRUCT 1234
#define SPECIES_ZYGARDE_50_POWER_CONSTRUCT 1235
#define SPECIES_ZYGARDE_10_COMPLETE 1236
#define SPECIES_ZYGARDE_50_COMPLETE 1237
#define SPECIES_HOOPA_UNBOUND   1238
#define SPECIES_ORICORIO_POM_POM 1239
#define SPECIES_ORICORIO_PAU    1240
#define SPECIES_ORICORIO_SENSU  1241
#define SPECIES_ROCKRUFF_OWN_TEMPO 1242
#define SPECIES_LYCANROC_MIDNIGHT 1243
#define SPECIES_LYCANROC_DUSK   1244
#define SPECIES_WISHIWASHI_SCHOOL 1245
#define SPECIES_MINIOR_METEOR_ORANGE 1246
#define SPECIES_MINIOR_METEOR_YELLOW 1247
#define SPECIES_MINIOR_METEOR_GREEN 1248
#define SPECIES_MINIOR_METEOR_BLUE 1249
#define SPECIES_MINIOR_METEOR_INDIGO 1250
#define SPECIES_MINIOR_METEOR_VIOLET 1251
#define SPECIES_MINIOR_CORE_RED 1252
#define SPECIES_MINIOR_CORE_ORANGE 1253
#define SPECIES_MINIOR_CORE_YELLOW 1254
#define SPECIES_MINIOR_CORE_GREEN 1255
#define SPECIES_MINIOR_CORE_BLUE 1256
#define SPECIES_MINIOR_CORE_INDIGO 1257
#define SPECIES_MINIOR_CORE_VIOLET 1258
#define SPECIES_MIMIKYU_BUSTED  1259
#define SPECIES_NECROZMA_DUSK_MANE 1260
#define SPECIES_NECROZMA_DAWN_WINGS 1261
#define SPECIES_NECROZMA_ULTRA_DUSK_MANE 1262
#define SPECIES_NECROZMA_ULTRA_DAWN_WINGS 1263
#define SPECIES_MAGEARNA_ORIGINAL 1264
#define SPECIES_PIKACHU_PARTNER 1265
#define SPECIES_EEVEE_PARTNER   1266
#define SPECIES_CRAMORANT_GULPING 1267
#define SPECIES_CRAMORANT_GORGING 1268
#define SPECIES_TOXTRICITY_LOW_KEY 1269
#define SPECIES_SINISTEA_ANTIQUE 1270
#define SPECIES_POLTEAGEIST_ANTIQUE 1271
#define SPECIES_ALCREMIE_BERRY_SWEET 1272
#define SPECIES_ALCREMIE_LOVE_SWEET 1273
#define SPECIES_ALCREMIE_STAR_SWEET 1274
#define SPECIES_ALCREMIE_CLOVER_SWEET 1275
#define SPECIES_ALCREMIE_FLOWER_SWEET 1276
#define SPECIES_ALCREMIE_RIBBON_SWEET 1277
#define SPECIES_EISCUE_NOICE_FACE 1278
#define SPECIES_MORPEKO_HANGRY  1279
#define SPECIES_ZACIAN_CROWNED  1280
#define SPECIES_ZAMAZENTA_CROWNED 1281
#define SPECIES_ETERNATUS_ETERNAMAX 1282
#define SPECIES_URSHIFU_RAPID_STRIKE 1283
#define SPECIES_ZARUDE_DADA     1284
#define SPECIES_CALYREX_ICE_RIDER 1285
#define SPECIES_CALYREX_SHADOW_RIDER 1286
#define SPECIES_ENAMORUS_THERIAN 1287
#define SPECIES_GROWLITHE_HISUIAN 1288
#define SPECIES_ARCANINE_HISUIAN 1289
#define SPECIES_VOLTORB_HISUIAN 1290
#define SPECIES_ELECTRODE_HISUIAN 1291
#define SPECIES_TYPHLOSION_HISUIAN 1292
#define SPECIES_QWILFISH_HISUIAN 1293
#define SPECIES_SNEASEL_HISUIAN 1294
#define SPECIES_SAMUROTT_HISUIAN 1295
#define SPECIES_LILLIGANT_HISUIAN 1296
#define SPECIES_ZORUA_HISUIAN   1297
#define SPECIES_ZOROARK_HISUIAN 1298
#define SPECIES_BRAVIARY_HISUIAN 1299
#define SPECIES_SLIGGOO_HISUIAN 1300
#define SPECIES_GOODRA_HISUIAN  1301
#define SPECIES_AVALUGG_HISUIAN 1302
#define SPECIES_DECIDUEYE_HISUIAN 1303
#define SPECIES_KLEAVOR_LORD    1304
#define SPECIES_LILLIGANT_LADY  1305
#define SPECIES_ARCANINE_LORD   1306
#define SPECIES_ELECTRODE_LORD  1307
#define SPECIES_AVALUGG_LORD    1308
#define SPECIES_UNFEZANT_FEMALE 1309
#define SPECIES_FRILLISH_FEMALE 1310
#define SPECIES_JELLICENT_FEMALE 1311
#define SPECIES_PYROAR_FEMALE   1312
#define SPECIES_MEOWSTIC_FEMALE 1313
#define SPECIES_INDEEDEE_FEMALE 1314
#define SPECIES_BASCULEGION_FEMALE 1315
#define SPECIES_MAUSHOLD_FAMILY_OF_THREE 1316
#define SPECIES_SQUAWKABILLY_BLUE_PLUMAGE 1317
#define SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE 1318
#define SPECIES_SQUAWKABILLY_WHITE_PLUMAGE 1319
#define SPECIES_PALAFIN_HERO    1320
#define SPECIES_TATSUGIRI_DROOPY 1321
#define SPECIES_TATSUGIRI_STRETCHY 1322
#define SPECIES_DUDUNSPARCE_THREE_SEGMENT 1323
#define SPECIES_GIMMIGHOUL_ROAMING 1324
#define SPECIES_WOOPER_PALDEAN  1325
#define SPECIES_TAUROS_COMBAT   1326
#define SPECIES_TAUROS_BLAZE    1327
#define SPECIES_TAUROS_AQUA     1328
#define SPECIES_OINKOLOGNE_FEMALE 1329
#define SPECIES_REVAVROOM_SEGIN 1330
#define SPECIES_REVAVROOM_SCHEDAR 1331
#define SPECIES_REVAVROOM_NAVI  1332
#define SPECIES_REVAVROOM_RUCHBAH 1333
#define SPECIES_REVAVROOM_CAPH  1334
#define SPECIES_KORAIDON_LIMITED_BUILD 1335
#define SPECIES_KORAIDON_SPRINTING_BUILD 1336
#define SPECIES_KORAIDON_SWIMMING_BUILD 1337
#define SPECIES_KORAIDON_GLIDING_BUILD 1338
#define SPECIES_MIRAIDON_LOW_POWER_MODE 1339
#define SPECIES_MIRAIDON_DRIVE_MODE 1340
#define SPECIES_MIRAIDON_AQUATIC_MODE 1341
#define SPECIES_MIRAIDON_GLIDE_MODE 1342
#define SPECIES_POLTCHAGEIST_MASTERPIECE 1343
#define SPECIES_SINISTCHA_MASTERPIECE 1344
#define SPECIES_OGERPON_WELLSPRING_MASK 1345
#define SPECIES_OGERPON_HEARTHFLAME_MASK 1346
#define SPECIES_OGERPON_CORNERSTONE_MASK 1347
#define SPECIES_OGERPON_TEAL_MASK_TERASTAL 1348
#define SPECIES_OGERPON_WELLSPRING_MASK_TERASTAL 1349
#define SPECIES_OGERPON_HEARTHFLAME_MASK_TERASTAL 1350
#define SPECIES_OGERPON_CORNERSTONE_MASK_TERASTAL 1351
#define SPECIES_URSALUNA_BLOODMOON 1352
#define SPECIES_TERAPAGOS_TERASTAL 1353
#define SPECIES_TERAPAGOS_STELLAR 1354
#define SPECIES_GIGANTAMAX_VENUSAUR 1355
#define SPECIES_GIGANTAMAX_CHARIZARD 1356
#define SPECIES_GIGANTAMAX_BLASTOISE 1357
#define SPECIES_GIGANTAMAX_BUTTERFREE 1358
#define SPECIES_GIGANTAMAX_PIKACHU 1359
#define SPECIES_GIGANTAMAX_MEOWTH 1360
#define SPECIES_GIGANTAMAX_MACHAMP 1361
#define SPECIES_GIGANTAMAX_GENGAR 1362
#define SPECIES_GIGANTAMAX_KINGLER 1363
#define SPECIES_GIGANTAMAX_LAPRAS 1364
#define SPECIES_GIGANTAMAX_EEVEE 1365
#define SPECIES_GIGANTAMAX_SNORLAX 1366
#define SPECIES_GIGANTAMAX_GARBODOR 1367
#define SPECIES_GIGANTAMAX_MELMETAL 1368
#define SPECIES_GIGANTAMAX_RILLABOOM 1369
#define SPECIES_GIGANTAMAX_CINDERACE 1370
#define SPECIES_GIGANTAMAX_INTELEON 1371
#define SPECIES_GIGANTAMAX_CORVIKNIGHT 1372
#define SPECIES_GIGANTAMAX_ORBEETLE 1373
#define SPECIES_GIGANTAMAX_DREDNAW 1374
#define SPECIES_GIGANTAMAX_COALOSSAL 1375
#define SPECIES_GIGANTAMAX_FLAPPLE 1376
#define SPECIES_GIGANTAMAX_APPLETUN 1377
#define SPECIES_GIGANTAMAX_SANDACONDA 1378
#define SPECIES_GIGANTAMAX_TOXTRICITY 1379
#define SPECIES_GIGANTAMAX_TOXTRICITY_LOW_KEY 1380
#define SPECIES_GIGANTAMAX_CENTISKORCH 1381
#define SPECIES_GIGANTAMAX_HATTERENE 1382
#define SPECIES_GIGANTAMAX_GRIMMSNARL 1383
#define SPECIES_GIGANTAMAX_ALCREMIE 1384
#define SPECIES_GIGANTAMAX_COPPERAJAH 1385
#define SPECIES_GIGANTAMAX_DURALUDON 1386
#define SPECIES_GIGANTAMAX_URSHIFU 1387
#define SPECIES_GIGANTAMAX_URSHIFU_RAPID_STRIKE 1388
#define SPECIES_MEGA_RAICHU_X   1389
#define SPECIES_MEGA_RAICHU_Y   1390
#define SPECIES_MEGA_CLEFABLE   1391
#define SPECIES_MEGA_VICTREEBEL 1392
#define SPECIES_MEGA_STARMIE    1393
#define SPECIES_MEGA_DRAGONITE  1394
#define SPECIES_MEGA_MEGANIUM   1395
#define SPECIES_MEGA_FERALIGATR 1396
#define SPECIES_MEGA_SKARMORY   1397
#define SPECIES_MEGA_CHIMECHO   1398
#define SPECIES_MEGA_ABSOL_Z    1399
#define SPECIES_MEGA_STARAPTOR  1400
#define SPECIES_MEGA_GARCHOMP_Z 1401
#define SPECIES_MEGA_LUCARIO_Z  1402
#define SPECIES_MEGA_FROSLASS   1403
#define SPECIES_MEGA_HEATRAN    1404
#define SPECIES_MEGA_DARKRAI    1405
#define SPECIES_MEGA_EMBOAR     1406
#define SPECIES_MEGA_EXCADRILL  1407
#define SPECIES_MEGA_SCOLIPEDE  1408
#define SPECIES_MEGA_SCRAFTY    1409
#define SPECIES_MEGA_EELEKTROSS 1410
#define SPECIES_MEGA_CHANDELURE 1411
#define SPECIES_MEGA_GOLURK     1412
#define SPECIES_MEGA_CHESNAUGHT 1413
#define SPECIES_MEGA_DELPHOX    1414
#define SPECIES_MEGA_GRENINJA   1415
#define SPECIES_MEGA_PYROAR     1416
#define SPECIES_MEGA_FLOETTE    1417
#define SPECIES_MEGA_MEOWSTIC   1418
#define SPECIES_MEGA_MEOWSTIC_FEMALE 1419
#define SPECIES_MEGA_MALAMAR    1420
#define SPECIES_MEGA_BARBARACLE 1421
#define SPECIES_MEGA_DRAGALGE   1422
#define SPECIES_MEGA_HAWLUCHA   1423
#define SPECIES_MEGA_ZYGARDE    1424
#define SPECIES_MEGA_CRABOMINABLE 1425
#define SPECIES_MEGA_GOLISOPOD  1426
#define SPECIES_MEGA_DRAMPA     1427
#define SPECIES_MEGA_MAGEARNA   1428
#define SPECIES_MEGA_MAGEARNA_ORIGINAL 1429
#define SPECIES_MEGA_ZERAORA    1430
#define SPECIES_MEGA_FALINKS    1431
#define SPECIES_MEGA_SCOVILLAIN 1432
#define SPECIES_MEGA_GLIMMORA   1433
#define SPECIES_MEGA_TATSUGIRI  1434
#define SPECIES_MEGA_TATSUGIRI_DROOPY 1435
#define SPECIES_MEGA_TATSUGIRI_STRETCHY 1436
#define SPECIES_MEGA_BAXCALIBUR 1437

#define NUM_SPECIES SPECIES_MEGA_BAXCALIBUR

// The highest species with a Dex entry. HeartGold's own stop at Arceus and
// the fourteen identifiers after it are the egg and the alternate forms,
// which are not Dex numbers; the species New Gold adds come after those and
// are, so the Dex reaches to the end of the list and skips the middle.
// The forms the reference numbers as species -- megas, regional forms,
// Gigantamax and the rest -- come after the last real species and are not
// Dex numbers either. The species importer keeps NUM_SPECIES on the last
// name; this one stays on the last Pokemon the Dex has a page for.
#define LAST_DEX_SPECIES   SPECIES_PECHARUNT
#define NATIONAL_DEX_COUNT LAST_DEX_SPECIES
#define FIRST_DEX_GAP      SPECIES_EGG
#define LAST_DEX_GAP       SPECIES_ROTOM_MOW
#define NUM_DEX_GAP        (LAST_DEX_GAP - FIRST_DEX_GAP + 1)

#define SPECIES_MANAPHY_EGG SPECIES_BAD_EGG

#endif // POKEHEARTGOLD_CONSTANTS_SPECIES_H
