#ifndef POKEHEARTGOLD_CONSTANTS_SPRITES_H
#define POKEHEARTGOLD_CONSTANTS_SPRITES_H

#define SPRITE_HERO                            0
#define SPRITE_BABYBOY1                        1
#define SPRITE_BABYGIRL1                       2
#define SPRITE_BOY1                            3
#define SPRITE_BOY2                            4
#define SPRITE_BOY3                            5
#define SPRITE_GIRL1                           6
#define SPRITE_GIRL2                           7
#define SPRITE_GIRL3                           8
#define SPRITE_MAN1                            9
#define SPRITE_MAN2                            10
#define SPRITE_MAN3                            11
#define SPRITE_WOMAN1                          12
#define SPRITE_WOMAN2                          13
#define SPRITE_WOMAN3                          14
#define SPRITE_MIDDLEMAN1                      15
#define SPRITE_MIDDLEWOMAN1                    16
#define SPRITE_OLDMAN1                         17
#define SPRITE_OLDWOMAN1                       18
#define SPRITE_BIGMAN                          19
#define SPRITE_MOUNT                           20
#define SPRITE_CYCLEHERO                       21
#define SPRITE_REPORTER                        22
#define SPRITE_CAMERAMAN                       23
#define SPRITE_SHOPM1                          24
#define SPRITE_SHOPW1                          25
#define SPRITE_ASSISTANTM                      29
#define SPRITE_ASSISTANTW                      30
#define SPRITE_BADMAN                          31
#define SPRITE_SKIERW                          33
#define SPRITE_POLICEMAN                       34
#define SPRITE_IDOL                            35
#define SPRITE_GENTLEMAN                       36
#define SPRITE_LADY                            37
#define SPRITE_CYCLEM                          38
#define SPRITE_CYCLEW                          39
#define SPRITE_WORKMAN                         40
#define SPRITE_FARMER                          41
#define SPRITE_COWGIRL                         42
#define SPRITE_CLOWN                           43
#define SPRITE_ARTIST                          44
#define SPRITE_SPORTSMAN                       45
#define SPRITE_EXPLORE                         50
#define SPRITE_FIGHTER                         51
#define SPRITE_CAMPBOY                         52
#define SPRITE_PICNICGIRL                      53
#define SPRITE_FISHING                         54
#define SPRITE_AMBRELLA                        55
#define SPRITE_SEAMAN                          56
#define SPRITE_WAITER                          59
#define SPRITE_WAITRESS                        60
#define SPRITE_GORGGEOUSM                      62
#define SPRITE_GORGGEOUSW                      63
#define SPRITE_MAN5                            68
#define SPRITE_WOMAN5                          69
#define SPRITE_MYSTERY                         70
#define SPRITE_PIKACHU                         71
#define SPRITE_ROCK                            84
#define SPRITE_BREAKROCK                       85
#define SPRITE_TREE                            86
#define SPRITE_MONSTARBALL                     87
#define SPRITE_HEROINE                         97
#define SPRITE_CYCLEHEROINE                    98
#define SPRITE_DOCTOR                          99
#define SPRITE_LEADER1                         126
#define SPRITE_LEADER2                         127
#define SPRITE_LEADER3                         128
#define SPRITE_LEADER4                         129
#define SPRITE_LEADER5                         130
#define SPRITE_LEADER6                         131
#define SPRITE_LEADER7                         132
#define SPRITE_LEADER8                         133
#define SPRITE_SEVEN1                          141
#define SPRITE_SEVEN2                          142
#define SPRITE_SEVEN3                          143
#define SPRITE_SEVEN4                          144
#define SPRITE_SEVEN5                          145
#define SPRITE_GSBOY1                          146
#define SPRITE_GSRIVEL                         148
#define SPRITE_SUNGLASSES                      168
#define SPRITE_TOWERBOSS                       169
#define SPRITE_MAID                            175
#define SPRITE_SPHERO                          176
#define SPRITE_SPHEROINE                       177
#define SPRITE_SWIMHERO                        178
#define SPRITE_SWIMHEROINE                     179
#define SPRITE_WATERHERO                       180
#define SPRITE_WATERHEROINE                    181
#define SPRITE_BABYBOY1_2                      183
#define SPRITE_FISHINGHERO                     188
#define SPRITE_FISH_HEROINE                    189
#define SPRITE_DELIVERY                        193
#define SPRITE_POKEHERO                        196
#define SPRITE_POKEHEROINE                     197
#define SPRITE_SAVEHERO                        198
#define SPRITE_SAVEHEROINE                     199
#define SPRITE_BANZAIHERO                      200
#define SPRITE_BANZAIHEROINE                   201
#define SPRITE_POKEWALL                        210
#define SPRITE_RED                             211
#define SPRITE_THIEF                           218
#define SPRITE_ITAKO                           219
#define SPRITE_BOZU                            220
#define SPRITE_ROCKETW                         221
#define SPRITE_ROCKETM                         222
#define SPRITE_RKANBUW                         223
#define SPRITE_RKANBUM                         224
#define SPRITE_BOARDER                         225
#define SPRITE_FIRE                            227
#define SPRITE_GANG                            229
#define SPRITE_DANCER                          232
#define SPRITE_GANTETSU                        233
#define SPRITE_MONO_PIP                        234
#define SPRITE_MASAKI                          235
#define SPRITE_CAPTAIN                         236
#define SPRITE_RGYARADOSU                      237
#define SPRITE_HERO_2                          238
#define SPRITE_HEROINE_2                       239
#define SPRITE_LADDERHERO                      248
#define SPRITE_LADDERHEROINE                   249
#define SPRITE_ITAKO_                          250
#define SPRITE_GATE_RIGHT                      251
#define SPRITE_GATE_LEFT                       252
#define SPRITE_BABYBOY1_5                      253
#define SPRITE_GATE_TOP                        254
#define SPRITE_GATE_BOTTOM                     255
#define SPRITE_BABYBOY1_8                      256
#define SPRITE_BABYBOY1_9                      257
#define SPRITE_RHERO                           258
#define SPRITE_RHEROINE                        259
#define SPRITE_RBANZAIHERO                     260
#define SPRITE_RBANZAIINE                      261
#define SPRITE_BONGURI                         262
#define SPRITE_BONGURI_R                       263
#define SPRITE_BONGURI_Y                       264
#define SPRITE_BONGURI_B                       265
#define SPRITE_BONGURI_G                       266
#define SPRITE_BONGURI_P                       267
#define SPRITE_BONGURI_W                       268
#define SPRITE_BONGURI_BK                      269
#define SPRITE_BONMI_R                         270
#define SPRITE_BONMI_Y                         271
#define SPRITE_BONMI_B                         272
#define SPRITE_BONMI_G                         273
#define SPRITE_BONMI_P                         274
#define SPRITE_BONMI_W                         275
#define SPRITE_BONMI_BK                        276
#define SPRITE_BRAINS1                         277
#define SPRITE_BRAINS2                         278
#define SPRITE_BRAINS3                         279
#define SPRITE_BRAINS4                         280
#define SPRITE_PRINCESS                        281
#define SPRITE_BFSM                            282
#define SPRITE_BFSW1                           283
#define SPRITE_BFSW2                           284
#define SPRITE_WIFISM                          285
#define SPRITE_WIFISF                          286
#define SPRITE_AJI_PERU                        287
#define SPRITE_BABYBOY1_10                     288
#define SPRITE_BABYBOY1_11                     289
#define SPRITE_LEAG_DOOR2                      290
#define SPRITE_BABYBOY1_12                     291
#define SPRITE_BABYBOY1_13                     292
#define SPRITE_RKANBUM2                        293
#define SPRITE_RKANBUM3                        294
#define SPRITE_PL_BOY01C                       295
#define SPRITE_PL_GIRL01C                      296
#define SPRITE_SAVERHERO                       297
#define SPRITE_SAVERHEROINE                    298
#define SPRITE_DELIVERY2                       299
#define SPRITE_GSBABYBOY1                      315
#define SPRITE_GSBABYGIRL1                     316
#define SPRITE_GSBOY2                          317
#define SPRITE_GSBOY3                          318
#define SPRITE_GSGIRL1                         319
#define SPRITE_GSGIRL2                         320
#define SPRITE_GSGIRL3                         321
#define SPRITE_GSMAN1                          322
#define SPRITE_GSMAN2                          323
#define SPRITE_GSMAN3                          324
#define SPRITE_GSWOMAN1                        325
#define SPRITE_GSWOMAN2                        326
#define SPRITE_GSWOMAN3                        327
#define SPRITE_GSMIDDLEMAN1                    328
#define SPRITE_MIDDLEWOMAN1_2                  329
#define SPRITE_GSOLDMAN1                       330
#define SPRITE_GSOLDWOMAN1                     331
#define SPRITE_GSBIGMAN                        332
#define SPRITE_MOUNT_2                         333
#define SPRITE_SHOPM1_2                        334
#define SPRITE_PCWOMAN1                        335
#define SPRITE_PCWOMAN2                        336
#define SPRITE_PCWOMAN3                        337
#define SPRITE_GSASSISTANTM                    338
#define SPRITE_GSGENTLEMAN                     341
#define SPRITE_GSSWIMMERM                      342
#define SPRITE_GSSWIMMERW                      343
#define SPRITE_GSFIGHTER                       344
#define SPRITE_CAMPBOY_2                       345
#define SPRITE_PICNICGIRL_2                    346
#define SPRITE_FISHING_2                       347
#define SPRITE_SEAMAN_2                        348
#define SPRITE_STOP                            349
#define SPRITE_GTOROPHY                        350
#define SPRITE_MYSTERY_2                       351
#define SPRITE_GSLEADER1                       352
#define SPRITE_GSLEADER2                       353
#define SPRITE_GSLEADER3                       354
#define SPRITE_GSLEADER4                       355
#define SPRITE_GSLEADER5                       356
#define SPRITE_GSLEADER6                       357
#define SPRITE_GSLEADER7                       358
#define SPRITE_GSLEADER8                       359
#define SPRITE_GSBIGFOUR1                      360
#define SPRITE_GSBIGFOUR2                      361
#define SPRITE_GSBIGFOUR3                      362
#define SPRITE_GSBIGFOUR4                      363
#define SPRITE_WATARU                          364
#define SPRITE_GSMAMA                          365
#define SPRITE_OOKIDO                          366
#define SPRITE_GSDSBOY                         367
#define SPRITE_GSLEADER9                       368
#define SPRITE_GSLEADER10                      369
#define SPRITE_GSLEADER11                      370
#define SPRITE_GSLEADER12                      371
#define SPRITE_GSLEADER13                      372
#define SPRITE_GSLEADER14                      373
#define SPRITE_GSLEADER15                      374
#define SPRITE_GSLEADER16                      375
#define SPRITE_STOROPHY                        376
#define SPRITE_MANIA                           377
#define SPRITE_JUGGRER                         378
#define SPRITE_BTOROPHY                        379
#define SPRITE_JUPETTA                         380
#define SPRITE_USOKKY                          381
#define SPRITE_MINAKI                          382
#define SPRITE_THLONOWNER                      383
#define SPRITE_INSTRUCTOR                      384
#define SPRITE_SAKAKI                          385
#define SPRITE_SUIT                            386
#define SPRITE_CHOUROU                         387
#define SPRITE_KURUMI                          389
#define SPRITE_RAPURASU                        390
#define SPRITE_NANAMI                          392
#define SPRITE_REDMAMA                         393
#define SPRITE_COUNTERM                        394
#define SPRITE_KABIGON                         395
#define SPRITE_MEDAL                           396
#define SPRITE_SCROLL                          397
#define SPRITE_SIGNSHOES                       398
#define SPRITE_SIGNCLOTHES                     399
#define SPRITE_SIGNFLAG                        400
#define SPRITE_SIGNPOKEGEAR                    401
#define SPRITE_SIGNBALL                        402
#define SPRITE_STATUEHERO                      403
#define SPRITE_STATUEHEROINE                   404
#define SPRITE_ICE                             406
#define SPRITE_PKTHHERO                        407
#define SPRITE_PKTHHEROINE                     408
#define SPRITE_ROTOMF                          409
#define SPRITE_ROTOMS                          410
#define SPRITE_ROTOMI                          411
#define SPRITE_ROTOMW                          412
#define SPRITE_ROTOMG                          413
#define SPRITE_YADON                           414
#define SPRITE_FOLLOWER_MON                    415
#define SPRITE_FOLLOWER_MON_2                  416
#define SPRITE_FOLLOWER_MON_3                  417
#define SPRITE_FOLLOWER_MON_4                  418
#define SPRITE_FOLLOWER_MON_5                  419
#define SPRITE_FOLLOWER_MON_6                  420
#define SPRITE_DAIGO                           421
#define SPRITE_CHAMPION                        422
#define SPRITE_SHAKEHERO                       423
#define SPRITE_SHAKEHEROINE                    424
#define SPRITE_HOU_OBJ01                       425
#define SPRITE_LUG_OBJ01                       426
#define SPRITE_GSWOMAN6                        427
#define SPRITE_FOLLOWER_MON_BULBASAUR          428
#define SPRITE_FOLLOWER_MON_IVYSAUR            429
#define SPRITE_FOLLOWER_MON_VENUSAUR           430
#define SPRITE_FOLLOWER_MON_VENUSAUR_F         431
#define SPRITE_FOLLOWER_MON_CHARMANDER         432
#define SPRITE_FOLLOWER_MON_CHARMELEON         433
#define SPRITE_FOLLOWER_MON_CHARIZARD          434
#define SPRITE_FOLLOWER_MON_SQUIRTLE           435
#define SPRITE_FOLLOWER_MON_WARTORTLE          436
#define SPRITE_FOLLOWER_MON_BLASTOISE          437
#define SPRITE_FOLLOWER_MON_CATERPIE           438
#define SPRITE_FOLLOWER_MON_METAPOD            439
#define SPRITE_FOLLOWER_MON_BUTTERFREE         440
#define SPRITE_FOLLOWER_MON_WEEDLE             441
#define SPRITE_FOLLOWER_MON_KAKUNA             442
#define SPRITE_FOLLOWER_MON_BEEDRILL           443
#define SPRITE_FOLLOWER_MON_PIDGEY             444
#define SPRITE_FOLLOWER_MON_PIDGEOTTO          445
#define SPRITE_FOLLOWER_MON_PIDGEOT            446
#define SPRITE_FOLLOWER_MON_RATTATA            447
#define SPRITE_FOLLOWER_MON_RATICATE           448
#define SPRITE_FOLLOWER_MON_SPEAROW            449
#define SPRITE_FOLLOWER_MON_FEAROW             450
#define SPRITE_FOLLOWER_MON_EKANS              451
#define SPRITE_FOLLOWER_MON_ARBOK              452
#define SPRITE_FOLLOWER_MON_PIKACHU            453
#define SPRITE_FOLLOWER_MON_PIKACHU_F          454
#define SPRITE_FOLLOWER_MON_RAICHU             455
#define SPRITE_FOLLOWER_MON_SANDSHREW          456
#define SPRITE_FOLLOWER_MON_SANDSLASH          457
#define SPRITE_FOLLOWER_MON_NIDORAN_F          458
#define SPRITE_FOLLOWER_MON_NIDORINA           459
#define SPRITE_FOLLOWER_MON_NIDOQUEEN          460
#define SPRITE_FOLLOWER_MON_NIDORAN_M          461
#define SPRITE_FOLLOWER_MON_NIDORINO           462
#define SPRITE_FOLLOWER_MON_NIDOKING           463
#define SPRITE_FOLLOWER_MON_CLEFAIRY           464
#define SPRITE_FOLLOWER_MON_CLEFABLE           465
#define SPRITE_FOLLOWER_MON_VULPIX             466
#define SPRITE_FOLLOWER_MON_NINETALES          467
#define SPRITE_FOLLOWER_MON_JIGGLYPUFF         468
#define SPRITE_FOLLOWER_MON_WIGGLYTUFF         469
#define SPRITE_FOLLOWER_MON_ZUBAT              470
#define SPRITE_FOLLOWER_MON_GOLBAT             471
#define SPRITE_FOLLOWER_MON_ODDISH             472
#define SPRITE_FOLLOWER_MON_GLOOM              473
#define SPRITE_FOLLOWER_MON_VILEPLUME          474
#define SPRITE_FOLLOWER_MON_PARAS              475
#define SPRITE_FOLLOWER_MON_PARASECT           476
#define SPRITE_FOLLOWER_MON_VENONAT            477
#define SPRITE_FOLLOWER_MON_VENOMOTH           478
#define SPRITE_FOLLOWER_MON_DIGLETT            479
#define SPRITE_FOLLOWER_MON_DUGTRIO            480
#define SPRITE_FOLLOWER_MON_MEOWTH             481
#define SPRITE_FOLLOWER_MON_PERSIAN            482
#define SPRITE_FOLLOWER_MON_PSYDUCK            483
#define SPRITE_FOLLOWER_MON_GOLDUCK            484
#define SPRITE_FOLLOWER_MON_MANKEY             485
#define SPRITE_FOLLOWER_MON_PRIMEAPE           486
#define SPRITE_FOLLOWER_MON_GROWLITHE          487
#define SPRITE_FOLLOWER_MON_ARCANINE           488
#define SPRITE_FOLLOWER_MON_POLIWAG            489
#define SPRITE_FOLLOWER_MON_POLIWHIRL          490
#define SPRITE_FOLLOWER_MON_POLIWRATH          491
#define SPRITE_FOLLOWER_MON_ABRA               492
#define SPRITE_FOLLOWER_MON_KADABRA            493
#define SPRITE_FOLLOWER_MON_ALAKAZAM           494
#define SPRITE_FOLLOWER_MON_MACHOP             495
#define SPRITE_FOLLOWER_MON_MACHOKE            496
#define SPRITE_FOLLOWER_MON_MACHAMP            497
#define SPRITE_FOLLOWER_MON_BELLSPROUT         498
#define SPRITE_FOLLOWER_MON_WEEPINBELL         499
#define SPRITE_FOLLOWER_MON_VICTREEBEL         500
#define SPRITE_FOLLOWER_MON_TENTACOOL          501
#define SPRITE_FOLLOWER_MON_TENTACRUEL         502
#define SPRITE_FOLLOWER_MON_GEODUDE            503
#define SPRITE_FOLLOWER_MON_GRAVELER           504
#define SPRITE_FOLLOWER_MON_GOLEM              505
#define SPRITE_FOLLOWER_MON_PONYTA             506
#define SPRITE_FOLLOWER_MON_RAPIDASH           507
#define SPRITE_FOLLOWER_MON_SLOWPOKE           508
#define SPRITE_FOLLOWER_MON_SLOWBRO            509
#define SPRITE_FOLLOWER_MON_MAGNEMITE          510
#define SPRITE_FOLLOWER_MON_MAGNETON           511
#define SPRITE_FOLLOWER_MON_FARFETCHD          512
#define SPRITE_FOLLOWER_MON_DODUO              513
#define SPRITE_FOLLOWER_MON_DODRIO             514
#define SPRITE_FOLLOWER_MON_SEEL               515
#define SPRITE_FOLLOWER_MON_DEWGONG            516
#define SPRITE_FOLLOWER_MON_GRIMER             517
#define SPRITE_FOLLOWER_MON_MUK                518
#define SPRITE_FOLLOWER_MON_SHELLDER           519
#define SPRITE_FOLLOWER_MON_CLOYSTER           520
#define SPRITE_FOLLOWER_MON_GASTLY             521
#define SPRITE_FOLLOWER_MON_HAUNTER            522
#define SPRITE_FOLLOWER_MON_GENGAR             523
#define SPRITE_FOLLOWER_MON_ONIX               524
#define SPRITE_FOLLOWER_MON_DROWZEE            525
#define SPRITE_FOLLOWER_MON_HYPNO              526
#define SPRITE_FOLLOWER_MON_KRABBY             527
#define SPRITE_FOLLOWER_MON_KINGLER            528
#define SPRITE_FOLLOWER_MON_VOLTORB            529
#define SPRITE_FOLLOWER_MON_ELECTRODE          530
#define SPRITE_FOLLOWER_MON_EXEGGCUTE          531
#define SPRITE_FOLLOWER_MON_EXEGGUTOR          532
#define SPRITE_FOLLOWER_MON_CUBONE             533
#define SPRITE_FOLLOWER_MON_MAROWAK            534
#define SPRITE_FOLLOWER_MON_HITMONLEE          535
#define SPRITE_FOLLOWER_MON_HITMONCHAN         536
#define SPRITE_FOLLOWER_MON_LICKITUNG          537
#define SPRITE_FOLLOWER_MON_KOFFING            538
#define SPRITE_FOLLOWER_MON_WEEZING            539
#define SPRITE_FOLLOWER_MON_RHYHORN            540
#define SPRITE_FOLLOWER_MON_RHYDON             541
#define SPRITE_FOLLOWER_MON_CHANSEY            542
#define SPRITE_FOLLOWER_MON_TANGELA            543
#define SPRITE_FOLLOWER_MON_KANGASKHAN         544
#define SPRITE_FOLLOWER_MON_HORSEA             545
#define SPRITE_FOLLOWER_MON_SEADRA             546
#define SPRITE_FOLLOWER_MON_GOLDEEN            547
#define SPRITE_FOLLOWER_MON_SEAKING            548
#define SPRITE_FOLLOWER_MON_STARYU             549
#define SPRITE_FOLLOWER_MON_STARMIE            550
#define SPRITE_FOLLOWER_MON_MR_MIME            551
#define SPRITE_FOLLOWER_MON_SCYTHER            552
#define SPRITE_FOLLOWER_MON_JYNX               553
#define SPRITE_FOLLOWER_MON_ELECTABUZZ         554
#define SPRITE_FOLLOWER_MON_MAGMAR             555
#define SPRITE_FOLLOWER_MON_PINSIR             556
#define SPRITE_FOLLOWER_MON_TAUROS             557
#define SPRITE_FOLLOWER_MON_MAGIKARP           558
#define SPRITE_FOLLOWER_MON_GYARADOS           559
#define SPRITE_FOLLOWER_MON_LAPRAS             560
#define SPRITE_FOLLOWER_MON_DITTO              561
#define SPRITE_FOLLOWER_MON_EEVEE              562
#define SPRITE_FOLLOWER_MON_VAPOREON           563
#define SPRITE_FOLLOWER_MON_JOLTEON            564
#define SPRITE_FOLLOWER_MON_FLAREON            565
#define SPRITE_FOLLOWER_MON_PORYGON            566
#define SPRITE_FOLLOWER_MON_OMANYTE            567
#define SPRITE_FOLLOWER_MON_OMASTAR            568
#define SPRITE_FOLLOWER_MON_KABUTO             569
#define SPRITE_FOLLOWER_MON_KABUTOPS           570
#define SPRITE_FOLLOWER_MON_AERODACTYL         571
#define SPRITE_FOLLOWER_MON_SNORLAX            572
#define SPRITE_FOLLOWER_MON_ARTICUNO           573
#define SPRITE_FOLLOWER_MON_ZAPDOS             574
#define SPRITE_FOLLOWER_MON_MOLTRES            575
#define SPRITE_FOLLOWER_MON_DRATINI            576
#define SPRITE_FOLLOWER_MON_DRAGONAIR          577
#define SPRITE_FOLLOWER_MON_DRAGONITE          578
#define SPRITE_FOLLOWER_MON_MEWTWO             579
#define SPRITE_FOLLOWER_MON_MEW                580
#define SPRITE_FOLLOWER_MON_CHIKORITA          581
#define SPRITE_FOLLOWER_MON_BAYLEEF            582
#define SPRITE_FOLLOWER_MON_MEGANIUM           583
#define SPRITE_FOLLOWER_MON_MEGANIUM_F         584
#define SPRITE_FOLLOWER_MON_CYNDAQUIL          585
#define SPRITE_FOLLOWER_MON_QUILAVA            586
#define SPRITE_FOLLOWER_MON_TYPHLOSION         587
#define SPRITE_FOLLOWER_MON_TOTODILE           588
#define SPRITE_FOLLOWER_MON_CROCONAW           589
#define SPRITE_FOLLOWER_MON_FERALIGATR         590
#define SPRITE_FOLLOWER_MON_SENTRET            591
#define SPRITE_FOLLOWER_MON_FURRET             592
#define SPRITE_FOLLOWER_MON_HOOTHOOT           593
#define SPRITE_FOLLOWER_MON_NOCTOWL            594
#define SPRITE_FOLLOWER_MON_LEDYBA             595
#define SPRITE_FOLLOWER_MON_LEDIAN             596
#define SPRITE_FOLLOWER_MON_SPINARAK           597
#define SPRITE_FOLLOWER_MON_ARIADOS            598
#define SPRITE_FOLLOWER_MON_CROBAT             599
#define SPRITE_FOLLOWER_MON_CHINCHOU           600
#define SPRITE_FOLLOWER_MON_LANTURN            601
#define SPRITE_FOLLOWER_MON_PICHU              602
#define SPRITE_FOLLOWER_MON_PICHU_SPIKY        603
#define SPRITE_FOLLOWER_MON_CLEFFA             604
#define SPRITE_FOLLOWER_MON_IGGLYBUFF          605
#define SPRITE_FOLLOWER_MON_TOGEPI             606
#define SPRITE_FOLLOWER_MON_TOGETIC            607
#define SPRITE_FOLLOWER_MON_NATU               608
#define SPRITE_FOLLOWER_MON_XATU               609
#define SPRITE_FOLLOWER_MON_MAREEP             610
#define SPRITE_FOLLOWER_MON_FLAAFFY            611
#define SPRITE_FOLLOWER_MON_AMPHAROS           612
#define SPRITE_FOLLOWER_MON_BELLOSSOM          613
#define SPRITE_FOLLOWER_MON_MARILL             614
#define SPRITE_FOLLOWER_MON_AZUMARILL          615
#define SPRITE_FOLLOWER_MON_SUDOWOODO          616
#define SPRITE_FOLLOWER_MON_POLITOED           617
#define SPRITE_FOLLOWER_MON_HOPPIP             618
#define SPRITE_FOLLOWER_MON_SKIPLOOM           619
#define SPRITE_FOLLOWER_MON_JUMPLUFF           620
#define SPRITE_FOLLOWER_MON_AIPOM              621
#define SPRITE_FOLLOWER_MON_SUNKERN            622
#define SPRITE_FOLLOWER_MON_SUNFLORA           623
#define SPRITE_FOLLOWER_MON_YANMA              624
#define SPRITE_FOLLOWER_MON_WOOPER             625
#define SPRITE_FOLLOWER_MON_QUAGSIRE           626
#define SPRITE_FOLLOWER_MON_ESPEON             627
#define SPRITE_FOLLOWER_MON_UMBREON            628
#define SPRITE_FOLLOWER_MON_MURKROW            629
#define SPRITE_FOLLOWER_MON_SLOWKING           630
#define SPRITE_FOLLOWER_MON_MISDREAVUS         631
#define SPRITE_FOLLOWER_MON_UNOWN_A            632
#define SPRITE_FOLLOWER_MON_UNOWN_B            633
#define SPRITE_FOLLOWER_MON_UNOWN_C            634
#define SPRITE_FOLLOWER_MON_UNOWN_D            635
#define SPRITE_FOLLOWER_MON_UNOWN_E            636
#define SPRITE_FOLLOWER_MON_UNOWN_F            637
#define SPRITE_FOLLOWER_MON_UNOWN_G            638
#define SPRITE_FOLLOWER_MON_UNOWN_H            639
#define SPRITE_FOLLOWER_MON_UNOWN_I            640
#define SPRITE_FOLLOWER_MON_UNOWN_J            641
#define SPRITE_FOLLOWER_MON_UNOWN_K            642
#define SPRITE_FOLLOWER_MON_UNOWN_L            643
#define SPRITE_FOLLOWER_MON_UNOWN_M            644
#define SPRITE_FOLLOWER_MON_UNOWN_N            645
#define SPRITE_FOLLOWER_MON_UNOWN_O            646
#define SPRITE_FOLLOWER_MON_UNOWN_P            647
#define SPRITE_FOLLOWER_MON_UNOWN_Q            648
#define SPRITE_FOLLOWER_MON_UNOWN_R            649
#define SPRITE_FOLLOWER_MON_UNOWN_S            650
#define SPRITE_FOLLOWER_MON_UNOWN_T            651
#define SPRITE_FOLLOWER_MON_UNOWN_U            652
#define SPRITE_FOLLOWER_MON_UNOWN_V            653
#define SPRITE_FOLLOWER_MON_UNOWN_W            654
#define SPRITE_FOLLOWER_MON_UNOWN_X            655
#define SPRITE_FOLLOWER_MON_UNOWN_Y            656
#define SPRITE_FOLLOWER_MON_UNOWN_Z            657
#define SPRITE_FOLLOWER_MON_UNOWN_QMARK        658
#define SPRITE_FOLLOWER_MON_UNOWN_EXCL         659
#define SPRITE_FOLLOWER_MON_WOBBUFFET          660
#define SPRITE_FOLLOWER_MON_WOBBUFFET_F        661
#define SPRITE_FOLLOWER_MON_GIRAFARIG          662
#define SPRITE_FOLLOWER_MON_PINECO             663
#define SPRITE_FOLLOWER_MON_FORRETRESS         664
#define SPRITE_FOLLOWER_MON_DUNSPARCE          665
#define SPRITE_FOLLOWER_MON_GLIGAR             666
#define SPRITE_FOLLOWER_MON_STEELIX            667
#define SPRITE_FOLLOWER_MON_STEELIX_F          668
#define SPRITE_FOLLOWER_MON_SNUBBULL           669
#define SPRITE_FOLLOWER_MON_GRANBULL           670
#define SPRITE_FOLLOWER_MON_QWILFISH           671
#define SPRITE_FOLLOWER_MON_SCIZOR             672
#define SPRITE_FOLLOWER_MON_SHUCKLE            673
#define SPRITE_FOLLOWER_MON_HERACROSS          674
#define SPRITE_FOLLOWER_MON_HERACROSS_F        675
#define SPRITE_FOLLOWER_MON_SNEASEL            676
#define SPRITE_FOLLOWER_MON_TEDDIURSA          677
#define SPRITE_FOLLOWER_MON_URSARING           678
#define SPRITE_FOLLOWER_MON_SLUGMA             679
#define SPRITE_FOLLOWER_MON_MAGCARGO           680
#define SPRITE_FOLLOWER_MON_SWINUB             681
#define SPRITE_FOLLOWER_MON_PILOSWINE          682
#define SPRITE_FOLLOWER_MON_CORSOLA            683
#define SPRITE_FOLLOWER_MON_REMORAID           684
#define SPRITE_FOLLOWER_MON_OCTILLERY          685
#define SPRITE_FOLLOWER_MON_DELIBIRD           686
#define SPRITE_FOLLOWER_MON_MANTINE            687
#define SPRITE_FOLLOWER_MON_SKARMORY           688
#define SPRITE_FOLLOWER_MON_HOUNDOUR           689
#define SPRITE_FOLLOWER_MON_HOUNDOOM           690
#define SPRITE_FOLLOWER_MON_KINGDRA            691
#define SPRITE_FOLLOWER_MON_PHANPY             692
#define SPRITE_FOLLOWER_MON_DONPHAN            693
#define SPRITE_FOLLOWER_MON_PORYGON2           694
#define SPRITE_FOLLOWER_MON_STANTLER           695
#define SPRITE_FOLLOWER_MON_SMEARGLE           696
#define SPRITE_FOLLOWER_MON_TYROGUE            697
#define SPRITE_FOLLOWER_MON_HITMONTOP          698
#define SPRITE_FOLLOWER_MON_SMOOCHUM           699
#define SPRITE_FOLLOWER_MON_ELEKID             700
#define SPRITE_FOLLOWER_MON_MAGBY              701
#define SPRITE_FOLLOWER_MON_MILTANK            702
#define SPRITE_FOLLOWER_MON_BLISSEY            703
#define SPRITE_FOLLOWER_MON_RAIKOU             704
#define SPRITE_FOLLOWER_MON_ENTEI              705
#define SPRITE_FOLLOWER_MON_SUICUNE            706
#define SPRITE_FOLLOWER_MON_LARVITAR           707
#define SPRITE_FOLLOWER_MON_PUPITAR            708
#define SPRITE_FOLLOWER_MON_TYRANITAR          709
#define SPRITE_FOLLOWER_MON_LUGIA              710
#define SPRITE_FOLLOWER_MON_HO_OH              711
#define SPRITE_FOLLOWER_MON_CELEBI             712
#define SPRITE_FOLLOWER_MON_TREECKO            713
#define SPRITE_FOLLOWER_MON_GROVYLE            714
#define SPRITE_FOLLOWER_MON_SCEPTILE           715
#define SPRITE_FOLLOWER_MON_TORCHIC            716
#define SPRITE_FOLLOWER_MON_COMBUSKEN          717
#define SPRITE_FOLLOWER_MON_BLAZIKEN           718
#define SPRITE_FOLLOWER_MON_MUDKIP             719
#define SPRITE_FOLLOWER_MON_MARSHTOMP          720
#define SPRITE_FOLLOWER_MON_SWAMPERT           721
#define SPRITE_FOLLOWER_MON_POOCHYENA          722
#define SPRITE_FOLLOWER_MON_MIGHTYENA          723
#define SPRITE_FOLLOWER_MON_ZIGZAGOON          724
#define SPRITE_FOLLOWER_MON_LINOONE            725
#define SPRITE_FOLLOWER_MON_WURMPLE            726
#define SPRITE_FOLLOWER_MON_SILCOON            727
#define SPRITE_FOLLOWER_MON_BEAUTIFLY          728
#define SPRITE_FOLLOWER_MON_CASCOON            729
#define SPRITE_FOLLOWER_MON_DUSTOX             730
#define SPRITE_FOLLOWER_MON_LOTAD              731
#define SPRITE_FOLLOWER_MON_LOMBRE             732
#define SPRITE_FOLLOWER_MON_LUDICOLO           733
#define SPRITE_FOLLOWER_MON_SEEDOT             734
#define SPRITE_FOLLOWER_MON_NUZLEAF            735
#define SPRITE_FOLLOWER_MON_SHIFTRY            736
#define SPRITE_FOLLOWER_MON_TAILLOW            737
#define SPRITE_FOLLOWER_MON_SWELLOW            738
#define SPRITE_FOLLOWER_MON_WINGULL            739
#define SPRITE_FOLLOWER_MON_PELIPPER           740
#define SPRITE_FOLLOWER_MON_RALTS              741
#define SPRITE_FOLLOWER_MON_KIRLIA             742
#define SPRITE_FOLLOWER_MON_GARDEVOIR          743
#define SPRITE_FOLLOWER_MON_SURSKIT            744
#define SPRITE_FOLLOWER_MON_MASQUERAIN         745
#define SPRITE_FOLLOWER_MON_SHROOMISH          746
#define SPRITE_FOLLOWER_MON_BRELOOM            747
#define SPRITE_FOLLOWER_MON_SLAKOTH            748
#define SPRITE_FOLLOWER_MON_VIGOROTH           749
#define SPRITE_FOLLOWER_MON_SLAKING            750
#define SPRITE_FOLLOWER_MON_NINCADA            751
#define SPRITE_FOLLOWER_MON_NINJASK            752
#define SPRITE_FOLLOWER_MON_SHEDINJA           753
#define SPRITE_FOLLOWER_MON_WHISMUR            754
#define SPRITE_FOLLOWER_MON_LOUDRED            755
#define SPRITE_FOLLOWER_MON_EXPLOUD            756
#define SPRITE_FOLLOWER_MON_MAKUHITA           757
#define SPRITE_FOLLOWER_MON_HARIYAMA           758
#define SPRITE_FOLLOWER_MON_AZURILL            759
#define SPRITE_FOLLOWER_MON_NOSEPASS           760
#define SPRITE_FOLLOWER_MON_SKITTY             761
#define SPRITE_FOLLOWER_MON_DELCATTY           762
#define SPRITE_FOLLOWER_MON_SABLEYE            763
#define SPRITE_FOLLOWER_MON_MAWILE             764
#define SPRITE_FOLLOWER_MON_ARON               765
#define SPRITE_FOLLOWER_MON_LAIRON             766
#define SPRITE_FOLLOWER_MON_AGGRON             767
#define SPRITE_FOLLOWER_MON_MEDITITE           768
#define SPRITE_FOLLOWER_MON_MEDICHAM           769
#define SPRITE_FOLLOWER_MON_ELECTRIKE          770
#define SPRITE_FOLLOWER_MON_MANECTRIC          771
#define SPRITE_FOLLOWER_MON_PLUSLE             772
#define SPRITE_FOLLOWER_MON_MINUN              773
#define SPRITE_FOLLOWER_MON_VOLBEAT            774
#define SPRITE_FOLLOWER_MON_ILLUMISE           775
#define SPRITE_FOLLOWER_MON_ROSELIA            776
#define SPRITE_FOLLOWER_MON_GULPIN             777
#define SPRITE_FOLLOWER_MON_SWALOT             778
#define SPRITE_FOLLOWER_MON_CARVANHA           779
#define SPRITE_FOLLOWER_MON_SHARPEDO           780
#define SPRITE_FOLLOWER_MON_WAILMER            781
#define SPRITE_FOLLOWER_MON_WAILORD            782
#define SPRITE_FOLLOWER_MON_NUMEL              783
#define SPRITE_FOLLOWER_MON_CAMERUPT           784
#define SPRITE_FOLLOWER_MON_TORKOAL            785
#define SPRITE_FOLLOWER_MON_SPOINK             786
#define SPRITE_FOLLOWER_MON_GRUMPIG            787
#define SPRITE_FOLLOWER_MON_SPINDA             788
#define SPRITE_FOLLOWER_MON_TRAPINCH           789
#define SPRITE_FOLLOWER_MON_VIBRAVA            790
#define SPRITE_FOLLOWER_MON_FLYGON             791
#define SPRITE_FOLLOWER_MON_CACNEA             792
#define SPRITE_FOLLOWER_MON_CACTURNE           793
#define SPRITE_FOLLOWER_MON_SWABLU             794
#define SPRITE_FOLLOWER_MON_ALTARIA            795
#define SPRITE_FOLLOWER_MON_ZANGOOSE           796
#define SPRITE_FOLLOWER_MON_SEVIPER            797
#define SPRITE_FOLLOWER_MON_LUNATONE           798
#define SPRITE_FOLLOWER_MON_SOLROCK            799
#define SPRITE_FOLLOWER_MON_BARBOACH           800
#define SPRITE_FOLLOWER_MON_WHISCASH           801
#define SPRITE_FOLLOWER_MON_CORPHISH           802
#define SPRITE_FOLLOWER_MON_CRAWDAUNT          803
#define SPRITE_FOLLOWER_MON_BALTOY             804
#define SPRITE_FOLLOWER_MON_CLAYDOL            805
#define SPRITE_FOLLOWER_MON_LILEEP             806
#define SPRITE_FOLLOWER_MON_CRADILY            807
#define SPRITE_FOLLOWER_MON_ANORITH            808
#define SPRITE_FOLLOWER_MON_ARMALDO            809
#define SPRITE_FOLLOWER_MON_FEEBAS             810
#define SPRITE_FOLLOWER_MON_MILOTIC            811
#define SPRITE_FOLLOWER_MON_CASTFORM           812
#define SPRITE_FOLLOWER_MON_KECLEON            813
#define SPRITE_FOLLOWER_MON_SHUPPET            814
#define SPRITE_FOLLOWER_MON_BANETTE            815
#define SPRITE_FOLLOWER_MON_DUSKULL            816
#define SPRITE_FOLLOWER_MON_DUSCLOPS           817
#define SPRITE_FOLLOWER_MON_TROPIUS            818
#define SPRITE_FOLLOWER_MON_CHIMECHO           819
#define SPRITE_FOLLOWER_MON_ABSOL              820
#define SPRITE_FOLLOWER_MON_WYNAUT             821
#define SPRITE_FOLLOWER_MON_SNORUNT            822
#define SPRITE_FOLLOWER_MON_GLALIE             823
#define SPRITE_FOLLOWER_MON_SPHEAL             824
#define SPRITE_FOLLOWER_MON_SEALEO             825
#define SPRITE_FOLLOWER_MON_WALREIN            826
#define SPRITE_FOLLOWER_MON_CLAMPERL           827
#define SPRITE_FOLLOWER_MON_HUNTAIL            828
#define SPRITE_FOLLOWER_MON_GOREBYSS           829
#define SPRITE_FOLLOWER_MON_RELICANTH          830
#define SPRITE_FOLLOWER_MON_LUVDISC            831
#define SPRITE_FOLLOWER_MON_BAGON              832
#define SPRITE_FOLLOWER_MON_SHELGON            833
#define SPRITE_FOLLOWER_MON_SALAMENCE          834
#define SPRITE_FOLLOWER_MON_BELDUM             835
#define SPRITE_FOLLOWER_MON_METANG             836
#define SPRITE_FOLLOWER_MON_METAGROSS          837
#define SPRITE_FOLLOWER_MON_REGIROCK           838
#define SPRITE_FOLLOWER_MON_REGICE             839
#define SPRITE_FOLLOWER_MON_REGISTEEL          840
#define SPRITE_FOLLOWER_MON_LATIAS             841
#define SPRITE_FOLLOWER_MON_LATIOS             842
#define SPRITE_FOLLOWER_MON_KYOGRE             843
#define SPRITE_FOLLOWER_MON_GROUDON            844
#define SPRITE_FOLLOWER_MON_RAYQUAZA           845
#define SPRITE_FOLLOWER_MON_JIRACHI            846
#define SPRITE_FOLLOWER_MON_DEOXYS             847
#define SPRITE_FOLLOWER_MON_DEOXYS_ATK         848
#define SPRITE_FOLLOWER_MON_DEOXYS_DEF         849
#define SPRITE_FOLLOWER_MON_DEOXYS_SPD         850
#define SPRITE_FOLLOWER_MON_TURTWIG            851
#define SPRITE_FOLLOWER_MON_GROTLE             852
#define SPRITE_FOLLOWER_MON_TORTERRA           853
#define SPRITE_FOLLOWER_MON_CHIMCHAR           854
#define SPRITE_FOLLOWER_MON_MONFERNO           855
#define SPRITE_FOLLOWER_MON_INFERNAPE          856
#define SPRITE_FOLLOWER_MON_PIPLUP             857
#define SPRITE_FOLLOWER_MON_PRINPLUP           858
#define SPRITE_FOLLOWER_MON_EMPOLEON           859
#define SPRITE_FOLLOWER_MON_STARLY             860
#define SPRITE_FOLLOWER_MON_STARAVIA           861
#define SPRITE_FOLLOWER_MON_STARAPTOR          862
#define SPRITE_FOLLOWER_MON_BIDOOF             863
#define SPRITE_FOLLOWER_MON_BIBAREL            864
#define SPRITE_FOLLOWER_MON_KRICKETOT          865
#define SPRITE_FOLLOWER_MON_KRICKETUNE         866
#define SPRITE_FOLLOWER_MON_SHINX              867
#define SPRITE_FOLLOWER_MON_LUXIO              868
#define SPRITE_FOLLOWER_MON_LUXRAY             869
#define SPRITE_FOLLOWER_MON_BUDEW              870
#define SPRITE_FOLLOWER_MON_ROSERADE           871
#define SPRITE_FOLLOWER_MON_CRANIDOS           872
#define SPRITE_FOLLOWER_MON_RAMPARDOS          873
#define SPRITE_FOLLOWER_MON_SHIELDON           874
#define SPRITE_FOLLOWER_MON_BASTIODON          875
#define SPRITE_FOLLOWER_MON_BURMY              876
#define SPRITE_FOLLOWER_MON_BURMY_SANDY        877
#define SPRITE_FOLLOWER_MON_BURMY_TRASH        878
#define SPRITE_FOLLOWER_MON_WORMADAM           879
#define SPRITE_FOLLOWER_MON_WORMADAM_SANDY     880
#define SPRITE_FOLLOWER_MON_WORMADAM_TRASH     881
#define SPRITE_FOLLOWER_MON_MOTHIM             882
#define SPRITE_FOLLOWER_MON_COMBEE             883
#define SPRITE_FOLLOWER_MON_COMBEE_F           884
#define SPRITE_FOLLOWER_MON_VESPIQUEN          885
#define SPRITE_FOLLOWER_MON_PACHIRISU          886
#define SPRITE_FOLLOWER_MON_BUIZEL             887
#define SPRITE_FOLLOWER_MON_FLOATZEL           888
#define SPRITE_FOLLOWER_MON_CHERUBI            889
#define SPRITE_FOLLOWER_MON_CHERRIM            890
#define SPRITE_FOLLOWER_MON_SHELLOS_WEST       891
#define SPRITE_FOLLOWER_MON_SHELLOS_EAST       892
#define SPRITE_FOLLOWER_MON_GASTRODON_WEST     893
#define SPRITE_FOLLOWER_MON_GASTRODON_EAST     894
#define SPRITE_FOLLOWER_MON_AMBIPOM            895
#define SPRITE_FOLLOWER_MON_DRIFLOON           896
#define SPRITE_FOLLOWER_MON_DRIFBLIM           897
#define SPRITE_FOLLOWER_MON_BUNEARY            898
#define SPRITE_FOLLOWER_MON_LOPUNNY            899
#define SPRITE_FOLLOWER_MON_MISMAGIUS          900
#define SPRITE_FOLLOWER_MON_HONCHKROW          901
#define SPRITE_FOLLOWER_MON_GLAMEOW            902
#define SPRITE_FOLLOWER_MON_PURUGLY            903
#define SPRITE_FOLLOWER_MON_CHINGLING          904
#define SPRITE_FOLLOWER_MON_STUNKY             905
#define SPRITE_FOLLOWER_MON_SKUNTANK           906
#define SPRITE_FOLLOWER_MON_BRONZOR            907
#define SPRITE_FOLLOWER_MON_BRONZONG           908
#define SPRITE_FOLLOWER_MON_BONSLY             909
#define SPRITE_FOLLOWER_MON_MIME_JR            910
#define SPRITE_FOLLOWER_MON_HAPPINY            911
#define SPRITE_FOLLOWER_MON_CHATOT             912
#define SPRITE_FOLLOWER_MON_SPIRITOMB          913
#define SPRITE_FOLLOWER_MON_GIBLE              914
#define SPRITE_FOLLOWER_MON_GIBLE_F            915
#define SPRITE_FOLLOWER_MON_GABITE             916
#define SPRITE_FOLLOWER_MON_GABITE_F           917
#define SPRITE_FOLLOWER_MON_GARCHOMP           918
#define SPRITE_FOLLOWER_MON_GARCHOMP_F         919
#define SPRITE_FOLLOWER_MON_MUNCHLAX           920
#define SPRITE_FOLLOWER_MON_RIOLU              921
#define SPRITE_FOLLOWER_MON_LUCARIO            922
#define SPRITE_FOLLOWER_MON_HIPPOPOTAS         923
#define SPRITE_FOLLOWER_MON_HIPPOPOTAS_F       924
#define SPRITE_FOLLOWER_MON_HIPPOWDON          925
#define SPRITE_FOLLOWER_MON_HIPPOWDON_F        926
#define SPRITE_FOLLOWER_MON_SKORUPI            927
#define SPRITE_FOLLOWER_MON_DRAPION            928
#define SPRITE_FOLLOWER_MON_CROAGUNK           929
#define SPRITE_FOLLOWER_MON_TOXICROAK          930
#define SPRITE_FOLLOWER_MON_CARNIVINE          931
#define SPRITE_FOLLOWER_MON_FINNEON            932
#define SPRITE_FOLLOWER_MON_LUMINEON           933
#define SPRITE_FOLLOWER_MON_MANTYKE            934
#define SPRITE_FOLLOWER_MON_SNOVER             935
#define SPRITE_FOLLOWER_MON_ABOMASNOW          936
#define SPRITE_FOLLOWER_MON_WEAVILE            937
#define SPRITE_FOLLOWER_MON_MAGNEZONE          938
#define SPRITE_FOLLOWER_MON_LICKILICKY         939
#define SPRITE_FOLLOWER_MON_RHYPERIOR          940
#define SPRITE_FOLLOWER_MON_TANGROWTH          941
#define SPRITE_FOLLOWER_MON_ELECTIVIRE         942
#define SPRITE_FOLLOWER_MON_MAGMORTAR          943
#define SPRITE_FOLLOWER_MON_TOGEKISS           944
#define SPRITE_FOLLOWER_MON_YANMEGA            945
#define SPRITE_FOLLOWER_MON_LEAFEON            946
#define SPRITE_FOLLOWER_MON_GLACEON            947
#define SPRITE_FOLLOWER_MON_GLISCOR            948
#define SPRITE_FOLLOWER_MON_MAMOSWINE          949
#define SPRITE_FOLLOWER_MON_PORYGON_Z          950
#define SPRITE_FOLLOWER_MON_GALLADE            951
#define SPRITE_FOLLOWER_MON_PROBOPASS          952
#define SPRITE_FOLLOWER_MON_DUSKNOIR           953
#define SPRITE_FOLLOWER_MON_FROSLASS           954
#define SPRITE_FOLLOWER_MON_ROTOM              955
#define SPRITE_FOLLOWER_MON_ROTOM_HEAT         956
#define SPRITE_FOLLOWER_MON_ROTOM_WASH         957
#define SPRITE_FOLLOWER_MON_ROTOM_FROST        958
#define SPRITE_FOLLOWER_MON_ROTOM_FAN          959
#define SPRITE_FOLLOWER_MON_ROTOM_MOW          960
#define SPRITE_FOLLOWER_MON_UXIE               961
#define SPRITE_FOLLOWER_MON_MESPRIT            962
#define SPRITE_FOLLOWER_MON_AZELF              963
#define SPRITE_FOLLOWER_MON_DIALGA             964
#define SPRITE_FOLLOWER_MON_PALKIA             965
#define SPRITE_FOLLOWER_MON_HEATRAN            966
#define SPRITE_FOLLOWER_MON_REGIGIGAS          967
#define SPRITE_FOLLOWER_MON_GIRATINA           968
#define SPRITE_FOLLOWER_MON_GIRATINA_ORIGIN    969
#define SPRITE_FOLLOWER_MON_CRESSELIA          970
#define SPRITE_FOLLOWER_MON_PHIONE             971
#define SPRITE_FOLLOWER_MON_MANAPHY            972
#define SPRITE_FOLLOWER_MON_DARKRAI            973
#define SPRITE_FOLLOWER_MON_SHAYMIN            974
#define SPRITE_FOLLOWER_MON_SHAYMIN_SKY        975
#define SPRITE_FOLLOWER_MON_ARCEUS_NORMAL      976
#define SPRITE_FOLLOWER_MON_ARCEUS_FIGHTING    977
#define SPRITE_FOLLOWER_MON_ARCEUS_FLYING      978
#define SPRITE_FOLLOWER_MON_ARCEUS_POISON      979
#define SPRITE_FOLLOWER_MON_ARCEUS_GROUND      980
#define SPRITE_FOLLOWER_MON_ARCEUS_ROCK        981
#define SPRITE_FOLLOWER_MON_ARCEUS_BUG         982
#define SPRITE_FOLLOWER_MON_ARCEUS_GHOST       983
#define SPRITE_FOLLOWER_MON_ARCEUS_STEEL       984
#define SPRITE_FOLLOWER_MON_ARCEUS_MYSTERY     985
#define SPRITE_FOLLOWER_MON_ARCEUS_FIRE        986
#define SPRITE_FOLLOWER_MON_ARCEUS_WATER       987
#define SPRITE_FOLLOWER_MON_ARCEUS_GRASS       988
#define SPRITE_FOLLOWER_MON_ARCEUS_ELECTRIC    989
#define SPRITE_FOLLOWER_MON_ARCEUS_PSYCHIC     990
#define SPRITE_FOLLOWER_MON_ARCEUS_ICE         991
#define SPRITE_FOLLOWER_MON_ARCEUS_DRAGON      992
#define SPRITE_FOLLOWER_MON_ARCEUS_DARK        993
#define SPRITE_FOLLOWER_MON_STATIC_BUTTERFREE  994
#define SPRITE_FOLLOWER_MON_STATIC_PIDGEY      995
#define SPRITE_FOLLOWER_MON_STATIC_RATTATA     996
#define SPRITE_FOLLOWER_MON_STATIC_SPEAROW     997
#define SPRITE_FOLLOWER_MON_STATIC_FEAROW      998
#define SPRITE_FOLLOWER_MON_STATIC_PIKACHU     999
#define SPRITE_FOLLOWER_MON_STATIC_NIDORAN_F   1000
#define SPRITE_FOLLOWER_MON_STATIC_NIDORAN_M   1001
#define SPRITE_FOLLOWER_MON_STATIC_NIDORINO    1002
#define SPRITE_FOLLOWER_MON_STATIC_CLEFAIRY    1003
#define SPRITE_FOLLOWER_MON_STATIC_JIGGLYPUFF  1004
#define SPRITE_FOLLOWER_MON_STATIC_ZUBAT       1005
#define SPRITE_FOLLOWER_MON_STATIC_ODDISH      1006
#define SPRITE_FOLLOWER_MON_STATIC_DIGLETT     1007
#define SPRITE_FOLLOWER_MON_STATIC_MEOWTH      1008
#define SPRITE_FOLLOWER_MON_STATIC_PERSIAN     1009
#define SPRITE_FOLLOWER_MON_STATIC_PSYDUCK     1010
#define SPRITE_FOLLOWER_MON_STATIC_POLIWRATH   1011
#define SPRITE_FOLLOWER_MON_STATIC_ABRA        1012
#define SPRITE_FOLLOWER_MON_STATIC_MACHOP      1013
#define SPRITE_FOLLOWER_MON_STATIC_MACHOKE     1014
#define SPRITE_FOLLOWER_MON_STATIC_SLOWPOKE    1015
#define SPRITE_FOLLOWER_MON_STATIC_SLOWBRO     1016
#define SPRITE_FOLLOWER_MON_STATIC_FARFETCHD   1017
#define SPRITE_FOLLOWER_MON_STATIC_DODRIO      1018
#define SPRITE_FOLLOWER_MON_STATIC_ELECTRODE   1019
#define SPRITE_FOLLOWER_MON_STATIC_RHYDON      1020
#define SPRITE_FOLLOWER_MON_STATIC_CHANSEY     1021
#define SPRITE_FOLLOWER_MON_STATIC_KANGASKHAN  1022
#define SPRITE_FOLLOWER_MON_STATIC_LAPRAS      1023
#define SPRITE_FOLLOWER_MON_STATIC_ARTICUNO    1024
#define SPRITE_FOLLOWER_MON_STATIC_ZAPDOS      1025
#define SPRITE_FOLLOWER_MON_STATIC_MOLTRES     1026
#define SPRITE_FOLLOWER_MON_STATIC_DRATINI     1027
#define SPRITE_FOLLOWER_MON_STATIC_DRAGONITE   1028
#define SPRITE_FOLLOWER_MON_STATIC_MEWTWO      1029
#define SPRITE_FOLLOWER_MON_STATIC_BAYLEEF     1030
#define SPRITE_FOLLOWER_MON_STATIC_AMPHAROS    1031
#define SPRITE_FOLLOWER_MON_STATIC_MARILL      1032
#define SPRITE_FOLLOWER_MON_STATIC_AIPOM       1033
#define SPRITE_FOLLOWER_MON_STATIC_MURKROW     1034
#define SPRITE_FOLLOWER_MON_STATIC_MILTANK     1035
#define SPRITE_FOLLOWER_MON_STATIC_BLISSEY     1036
#define SPRITE_FOLLOWER_MON_STATIC_RAIKOU      1037
#define SPRITE_FOLLOWER_MON_STATIC_ENTEI       1038
#define SPRITE_FOLLOWER_MON_STATIC_SUICUNE     1039
#define SPRITE_FOLLOWER_MON_STATIC_CELEBI      1040
#define SPRITE_FOLLOWER_MON_STATIC_LATIAS      1041
#define SPRITE_FOLLOWER_MON_STATIC_LATIOS      1042
#define SPRITE_FOLLOWER_MON_STATIC_KYOGRE      1043
#define SPRITE_FOLLOWER_MON_STATIC_GROUDON     1044
#define SPRITE_FOLLOWER_MON_STATIC_RAYQUAZA    1045
#define SPRITE_FOLLOWER_MON_STATIC_PICHU_SPIKY 1046
#define SPRITE_FOLLOWER_MON_STATIC_MEGANIUM    1047
#define SPRITE_FOLLOWER_MON_STATIC_TYPHLOSION  1048
#define SPRITE_FOLLOWER_MON_STATIC_FERALIGATR  1049

// The species New Gold adds; tools/newgold/import/import_followers.py
#define SPRITE_FOLLOWER_MON_LILLIPUP                     1050
#define SPRITE_FOLLOWER_MON_HERDIER                      1051
#define SPRITE_FOLLOWER_MON_STOUTLAND                    1052
#define SPRITE_FOLLOWER_MON_PURRLOIN                     1053
#define SPRITE_FOLLOWER_MON_LIEPARD                      1054
#define SPRITE_FOLLOWER_MON_TYMPOLE                      1055
#define SPRITE_FOLLOWER_MON_PALPITOAD                    1056
#define SPRITE_FOLLOWER_MON_SEISMITOAD                   1057
#define SPRITE_FOLLOWER_MON_SEWADDLE                     1058
#define SPRITE_FOLLOWER_MON_SWADLOON                     1059
#define SPRITE_FOLLOWER_MON_LEAVANNY                     1060
#define SPRITE_FOLLOWER_MON_YAMASK                       1061
#define SPRITE_FOLLOWER_MON_COFAGRIGUS                   1062
#define SPRITE_FOLLOWER_MON_TRUBBISH                     1063
#define SPRITE_FOLLOWER_MON_GARBODOR                     1064
#define SPRITE_FOLLOWER_MON_EMOLGA                       1065
#define SPRITE_FOLLOWER_MON_KARRABLAST                   1066
#define SPRITE_FOLLOWER_MON_ESCAVALIER                   1067
#define SPRITE_FOLLOWER_MON_FOONGUS                      1068
#define SPRITE_FOLLOWER_MON_AMOONGUSS                    1069
#define SPRITE_FOLLOWER_MON_JOLTIK                       1070
#define SPRITE_FOLLOWER_MON_GALVANTULA                   1071
#define SPRITE_FOLLOWER_MON_FERROSEED                    1072
#define SPRITE_FOLLOWER_MON_FERROTHORN                   1073
#define SPRITE_FOLLOWER_MON_KLINK                        1074
#define SPRITE_FOLLOWER_MON_KLANG                        1075
#define SPRITE_FOLLOWER_MON_KLINKLANG                    1076
#define SPRITE_FOLLOWER_MON_ELGYEM                       1077
#define SPRITE_FOLLOWER_MON_BEHEEYEM                     1078
#define SPRITE_FOLLOWER_MON_LITWICK                      1079
#define SPRITE_FOLLOWER_MON_LAMPENT                      1080
#define SPRITE_FOLLOWER_MON_CHANDELURE                   1081
#define SPRITE_FOLLOWER_MON_SHELMET                      1082
#define SPRITE_FOLLOWER_MON_ACCELGOR                     1083
#define SPRITE_FOLLOWER_MON_BOUFFALANT                   1084
#define SPRITE_FOLLOWER_MON_BUNNELBY                     1085
#define SPRITE_FOLLOWER_MON_DIGGERSBY                    1086
#define SPRITE_FOLLOWER_MON_FLETCHLING                   1087
#define SPRITE_FOLLOWER_MON_FLETCHINDER                  1088
#define SPRITE_FOLLOWER_MON_TALONFLAME                   1089
#define SPRITE_FOLLOWER_MON_LITLEO                       1090
#define SPRITE_FOLLOWER_MON_PYROAR                       1091
#define SPRITE_FOLLOWER_MON_ESPURR                       1092
#define SPRITE_FOLLOWER_MON_MEOWSTIC                     1093
#define SPRITE_FOLLOWER_MON_SYLVEON                      1094
#define SPRITE_FOLLOWER_MON_DEDENNE                      1095
#define SPRITE_FOLLOWER_MON_PHANTUMP                     1096
#define SPRITE_FOLLOWER_MON_TREVENANT                    1097
#define SPRITE_FOLLOWER_MON_PUMPKABOO                    1098
#define SPRITE_FOLLOWER_MON_GOURGEIST                    1099
#define SPRITE_FOLLOWER_MON_NOIBAT                       1100
#define SPRITE_FOLLOWER_MON_NOIVERN                      1101
#define SPRITE_FOLLOWER_MON_APPLIN                       1102
#define SPRITE_FOLLOWER_MON_FLAPPLE                      1103
#define SPRITE_FOLLOWER_MON_APPLETUN                     1104
#define SPRITE_FOLLOWER_MON_SIZZLIPEDE                   1105
#define SPRITE_FOLLOWER_MON_CENTISKORCH                  1106
#define SPRITE_FOLLOWER_MON_WYRDEER                      1107
#define SPRITE_FOLLOWER_MON_KLEAVOR                      1108
#define SPRITE_FOLLOWER_MON_URSALUNA                     1109
#define SPRITE_FOLLOWER_MON_ANNIHILAPE                   1110
#define SPRITE_FOLLOWER_MON_FARIGIRAF                    1111
#define SPRITE_FOLLOWER_MON_DUDUNSPARCE                  1112
#define SPRITE_FOLLOWER_MON_DIPPLIN                      1113
#define SPRITE_FOLLOWER_MON_HYDRAPPLE                    1114
#define SPRITE_FOLLOWER_MON_SLOWPOKE_GALARIAN            1115
#define SPRITE_FOLLOWER_MON_SLOWBRO_GALARIAN             1116
#define SPRITE_FOLLOWER_MON_VICTINI                      1117
#define SPRITE_FOLLOWER_MON_SNIVY                        1118
#define SPRITE_FOLLOWER_MON_SERVINE                      1119
#define SPRITE_FOLLOWER_MON_SERPERIOR                    1120
#define SPRITE_FOLLOWER_MON_TEPIG                        1121
#define SPRITE_FOLLOWER_MON_PIGNITE                      1122
#define SPRITE_FOLLOWER_MON_EMBOAR                       1123
#define SPRITE_FOLLOWER_MON_OSHAWOTT                     1124
#define SPRITE_FOLLOWER_MON_DEWOTT                       1125
#define SPRITE_FOLLOWER_MON_SAMUROTT                     1126
#define SPRITE_FOLLOWER_MON_PATRAT                       1127
#define SPRITE_FOLLOWER_MON_WATCHOG                      1128
#define SPRITE_FOLLOWER_MON_PANSAGE                      1129
#define SPRITE_FOLLOWER_MON_SIMISAGE                     1130
#define SPRITE_FOLLOWER_MON_PANSEAR                      1131
#define SPRITE_FOLLOWER_MON_SIMISEAR                     1132
#define SPRITE_FOLLOWER_MON_PANPOUR                      1133
#define SPRITE_FOLLOWER_MON_SIMIPOUR                     1134
#define SPRITE_FOLLOWER_MON_MUNNA                        1135
#define SPRITE_FOLLOWER_MON_MUSHARNA                     1136
#define SPRITE_FOLLOWER_MON_PIDOVE                       1137
#define SPRITE_FOLLOWER_MON_TRANQUILL                    1138
#define SPRITE_FOLLOWER_MON_UNFEZANT                     1139
#define SPRITE_FOLLOWER_MON_BLITZLE                      1140
#define SPRITE_FOLLOWER_MON_ZEBSTRIKA                    1141
#define SPRITE_FOLLOWER_MON_ROGGENROLA                   1142
#define SPRITE_FOLLOWER_MON_BOLDORE                      1143
#define SPRITE_FOLLOWER_MON_GIGALITH                     1144
#define SPRITE_FOLLOWER_MON_WOOBAT                       1145
#define SPRITE_FOLLOWER_MON_SWOOBAT                      1146
#define SPRITE_FOLLOWER_MON_DRILBUR                      1147
#define SPRITE_FOLLOWER_MON_EXCADRILL                    1148
#define SPRITE_FOLLOWER_MON_AUDINO                       1149
#define SPRITE_FOLLOWER_MON_TIMBURR                      1150
#define SPRITE_FOLLOWER_MON_GURDURR                      1151
#define SPRITE_FOLLOWER_MON_CONKELDURR                   1152
#define SPRITE_FOLLOWER_MON_THROH                        1153
#define SPRITE_FOLLOWER_MON_SAWK                         1154
#define SPRITE_FOLLOWER_MON_VENIPEDE                     1155
#define SPRITE_FOLLOWER_MON_WHIRLIPEDE                   1156
#define SPRITE_FOLLOWER_MON_SCOLIPEDE                    1157
#define SPRITE_FOLLOWER_MON_COTTONEE                     1158
#define SPRITE_FOLLOWER_MON_WHIMSICOTT                   1159
#define SPRITE_FOLLOWER_MON_PETILIL                      1160
#define SPRITE_FOLLOWER_MON_LILLIGANT                    1161
#define SPRITE_FOLLOWER_MON_BASCULIN                     1162
#define SPRITE_FOLLOWER_MON_SANDILE                      1163
#define SPRITE_FOLLOWER_MON_KROKOROK                     1164
#define SPRITE_FOLLOWER_MON_KROOKODILE                   1165
#define SPRITE_FOLLOWER_MON_DARUMAKA                     1166
#define SPRITE_FOLLOWER_MON_DARMANITAN                   1167
#define SPRITE_FOLLOWER_MON_MARACTUS                     1168
#define SPRITE_FOLLOWER_MON_DWEBBLE                      1169
#define SPRITE_FOLLOWER_MON_CRUSTLE                      1170
#define SPRITE_FOLLOWER_MON_SCRAGGY                      1171
#define SPRITE_FOLLOWER_MON_SCRAFTY                      1172
#define SPRITE_FOLLOWER_MON_SIGILYPH                     1173
#define SPRITE_FOLLOWER_MON_TIRTOUGA                     1174
#define SPRITE_FOLLOWER_MON_CARRACOSTA                   1175
#define SPRITE_FOLLOWER_MON_ARCHEN                       1176
#define SPRITE_FOLLOWER_MON_ARCHEOPS                     1177
#define SPRITE_FOLLOWER_MON_ZORUA                        1178
#define SPRITE_FOLLOWER_MON_ZOROARK                      1179
#define SPRITE_FOLLOWER_MON_MINCCINO                     1180
#define SPRITE_FOLLOWER_MON_CINCCINO                     1181
#define SPRITE_FOLLOWER_MON_GOTHITA                      1182
#define SPRITE_FOLLOWER_MON_GOTHORITA                    1183
#define SPRITE_FOLLOWER_MON_GOTHITELLE                   1184
#define SPRITE_FOLLOWER_MON_SOLOSIS                      1185
#define SPRITE_FOLLOWER_MON_DUOSION                      1186
#define SPRITE_FOLLOWER_MON_REUNICLUS                    1187
#define SPRITE_FOLLOWER_MON_DUCKLETT                     1188
#define SPRITE_FOLLOWER_MON_SWANNA                       1189
#define SPRITE_FOLLOWER_MON_VANILLITE                    1190
#define SPRITE_FOLLOWER_MON_VANILLISH                    1191
#define SPRITE_FOLLOWER_MON_VANILLUXE                    1192
#define SPRITE_FOLLOWER_MON_DEERLING                     1193
#define SPRITE_FOLLOWER_MON_SAWSBUCK                     1194
#define SPRITE_FOLLOWER_MON_FRILLISH                     1195
#define SPRITE_FOLLOWER_MON_JELLICENT                    1196
#define SPRITE_FOLLOWER_MON_ALOMOMOLA                    1197
#define SPRITE_FOLLOWER_MON_TYNAMO                       1198
#define SPRITE_FOLLOWER_MON_EELEKTRIK                    1199
#define SPRITE_FOLLOWER_MON_EELEKTROSS                   1200
#define SPRITE_FOLLOWER_MON_AXEW                         1201
#define SPRITE_FOLLOWER_MON_FRAXURE                      1202
#define SPRITE_FOLLOWER_MON_HAXORUS                      1203
#define SPRITE_FOLLOWER_MON_CUBCHOO                      1204
#define SPRITE_FOLLOWER_MON_BEARTIC                      1205
#define SPRITE_FOLLOWER_MON_CRYOGONAL                    1206
#define SPRITE_FOLLOWER_MON_STUNFISK                     1207
#define SPRITE_FOLLOWER_MON_MIENFOO                      1208
#define SPRITE_FOLLOWER_MON_MIENSHAO                     1209
#define SPRITE_FOLLOWER_MON_DRUDDIGON                    1210
#define SPRITE_FOLLOWER_MON_GOLETT                       1211
#define SPRITE_FOLLOWER_MON_GOLURK                       1212
#define SPRITE_FOLLOWER_MON_PAWNIARD                     1213
#define SPRITE_FOLLOWER_MON_BISHARP                      1214
#define SPRITE_FOLLOWER_MON_RUFFLET                      1215
#define SPRITE_FOLLOWER_MON_BRAVIARY                     1216
#define SPRITE_FOLLOWER_MON_VULLABY                      1217
#define SPRITE_FOLLOWER_MON_MANDIBUZZ                    1218
#define SPRITE_FOLLOWER_MON_HEATMOR                      1219
#define SPRITE_FOLLOWER_MON_DURANT                       1220
#define SPRITE_FOLLOWER_MON_DEINO                        1221
#define SPRITE_FOLLOWER_MON_ZWEILOUS                     1222
#define SPRITE_FOLLOWER_MON_HYDREIGON                    1223
#define SPRITE_FOLLOWER_MON_LARVESTA                     1224
#define SPRITE_FOLLOWER_MON_VOLCARONA                    1225
#define SPRITE_FOLLOWER_MON_COBALION                     1226
#define SPRITE_FOLLOWER_MON_TERRAKION                    1227
#define SPRITE_FOLLOWER_MON_VIRIZION                     1228
#define SPRITE_FOLLOWER_MON_TORNADUS                     1229
#define SPRITE_FOLLOWER_MON_THUNDURUS                    1230
#define SPRITE_FOLLOWER_MON_RESHIRAM                     1231
#define SPRITE_FOLLOWER_MON_ZEKROM                       1232
#define SPRITE_FOLLOWER_MON_LANDORUS                     1233
#define SPRITE_FOLLOWER_MON_KYUREM                       1234
#define SPRITE_FOLLOWER_MON_KELDEO                       1235
#define SPRITE_FOLLOWER_MON_MELOETTA                     1236
#define SPRITE_FOLLOWER_MON_GENESECT                     1237
#define SPRITE_FOLLOWER_MON_CHESPIN                      1238
#define SPRITE_FOLLOWER_MON_QUILLADIN                    1239
#define SPRITE_FOLLOWER_MON_CHESNAUGHT                   1240
#define SPRITE_FOLLOWER_MON_FENNEKIN                     1241
#define SPRITE_FOLLOWER_MON_BRAIXEN                      1242
#define SPRITE_FOLLOWER_MON_DELPHOX                      1243
#define SPRITE_FOLLOWER_MON_FROAKIE                      1244
#define SPRITE_FOLLOWER_MON_FROGADIER                    1245
#define SPRITE_FOLLOWER_MON_GRENINJA                     1246
#define SPRITE_FOLLOWER_MON_SCATTERBUG                   1247
#define SPRITE_FOLLOWER_MON_SPEWPA                       1248
#define SPRITE_FOLLOWER_MON_VIVILLON                     1249
#define SPRITE_FOLLOWER_MON_FLABEBE                      1250
#define SPRITE_FOLLOWER_MON_FLOETTE                      1251
#define SPRITE_FOLLOWER_MON_FLORGES                      1252
#define SPRITE_FOLLOWER_MON_SKIDDO                       1253
#define SPRITE_FOLLOWER_MON_GOGOAT                       1254
#define SPRITE_FOLLOWER_MON_PANCHAM                      1255
#define SPRITE_FOLLOWER_MON_PANGORO                      1256
#define SPRITE_FOLLOWER_MON_FURFROU                      1257
#define SPRITE_FOLLOWER_MON_HONEDGE                      1258
#define SPRITE_FOLLOWER_MON_DOUBLADE                     1259
#define SPRITE_FOLLOWER_MON_AEGISLASH                    1260
#define SPRITE_FOLLOWER_MON_SPRITZEE                     1261
#define SPRITE_FOLLOWER_MON_AROMATISSE                   1262
#define SPRITE_FOLLOWER_MON_SWIRLIX                      1263
#define SPRITE_FOLLOWER_MON_SLURPUFF                     1264
#define SPRITE_FOLLOWER_MON_INKAY                        1265
#define SPRITE_FOLLOWER_MON_MALAMAR                      1266
#define SPRITE_FOLLOWER_MON_BINACLE                      1267
#define SPRITE_FOLLOWER_MON_BARBARACLE                   1268
#define SPRITE_FOLLOWER_MON_SKRELP                       1269
#define SPRITE_FOLLOWER_MON_DRAGALGE                     1270
#define SPRITE_FOLLOWER_MON_CLAUNCHER                    1271
#define SPRITE_FOLLOWER_MON_CLAWITZER                    1272
#define SPRITE_FOLLOWER_MON_HELIOPTILE                   1273
#define SPRITE_FOLLOWER_MON_HELIOLISK                    1274
#define SPRITE_FOLLOWER_MON_TYRUNT                       1275
#define SPRITE_FOLLOWER_MON_TYRANTRUM                    1276
#define SPRITE_FOLLOWER_MON_AMAURA                       1277
#define SPRITE_FOLLOWER_MON_AURORUS                      1278
#define SPRITE_FOLLOWER_MON_HAWLUCHA                     1279
#define SPRITE_FOLLOWER_MON_CARBINK                      1280
#define SPRITE_FOLLOWER_MON_GOOMY                        1281
#define SPRITE_FOLLOWER_MON_SLIGGOO                      1282
#define SPRITE_FOLLOWER_MON_GOODRA                       1283
#define SPRITE_FOLLOWER_MON_KLEFKI                       1284
#define SPRITE_FOLLOWER_MON_BERGMITE                     1285
#define SPRITE_FOLLOWER_MON_AVALUGG                      1286
#define SPRITE_FOLLOWER_MON_XERNEAS                      1287
#define SPRITE_FOLLOWER_MON_YVELTAL                      1288
#define SPRITE_FOLLOWER_MON_ZYGARDE                      1289
#define SPRITE_FOLLOWER_MON_DIANCIE                      1290
#define SPRITE_FOLLOWER_MON_HOOPA                        1291
#define SPRITE_FOLLOWER_MON_VOLCANION                    1292
#define SPRITE_FOLLOWER_MON_ROWLET                       1293
#define SPRITE_FOLLOWER_MON_DARTRIX                      1294
#define SPRITE_FOLLOWER_MON_DECIDUEYE                    1295
#define SPRITE_FOLLOWER_MON_LITTEN                       1296
#define SPRITE_FOLLOWER_MON_TORRACAT                     1297
#define SPRITE_FOLLOWER_MON_INCINEROAR                   1298
#define SPRITE_FOLLOWER_MON_POPPLIO                      1299
#define SPRITE_FOLLOWER_MON_BRIONNE                      1300
#define SPRITE_FOLLOWER_MON_PRIMARINA                    1301
#define SPRITE_FOLLOWER_MON_PIKIPEK                      1302
#define SPRITE_FOLLOWER_MON_TRUMBEAK                     1303
#define SPRITE_FOLLOWER_MON_TOUCANNON                    1304
#define SPRITE_FOLLOWER_MON_YUNGOOS                      1305
#define SPRITE_FOLLOWER_MON_GUMSHOOS                     1306
#define SPRITE_FOLLOWER_MON_GRUBBIN                      1307
#define SPRITE_FOLLOWER_MON_CHARJABUG                    1308
#define SPRITE_FOLLOWER_MON_VIKAVOLT                     1309
#define SPRITE_FOLLOWER_MON_CRABRAWLER                   1310
#define SPRITE_FOLLOWER_MON_CRABOMINABLE                 1311
#define SPRITE_FOLLOWER_MON_ORICORIO                     1312
#define SPRITE_FOLLOWER_MON_CUTIEFLY                     1313
#define SPRITE_FOLLOWER_MON_RIBOMBEE                     1314
#define SPRITE_FOLLOWER_MON_ROCKRUFF                     1315
#define SPRITE_FOLLOWER_MON_LYCANROC                     1316
#define SPRITE_FOLLOWER_MON_WISHIWASHI                   1317
#define SPRITE_FOLLOWER_MON_MAREANIE                     1318
#define SPRITE_FOLLOWER_MON_TOXAPEX                      1319
#define SPRITE_FOLLOWER_MON_MUDBRAY                      1320
#define SPRITE_FOLLOWER_MON_MUDSDALE                     1321
#define SPRITE_FOLLOWER_MON_DEWPIDER                     1322
#define SPRITE_FOLLOWER_MON_ARAQUANID                    1323
#define SPRITE_FOLLOWER_MON_FOMANTIS                     1324
#define SPRITE_FOLLOWER_MON_LURANTIS                     1325
#define SPRITE_FOLLOWER_MON_MORELULL                     1326
#define SPRITE_FOLLOWER_MON_SHIINOTIC                    1327
#define SPRITE_FOLLOWER_MON_SALANDIT                     1328
#define SPRITE_FOLLOWER_MON_SALAZZLE                     1329
#define SPRITE_FOLLOWER_MON_STUFFUL                      1330
#define SPRITE_FOLLOWER_MON_BEWEAR                       1331
#define SPRITE_FOLLOWER_MON_BOUNSWEET                    1332
#define SPRITE_FOLLOWER_MON_STEENEE                      1333
#define SPRITE_FOLLOWER_MON_TSAREENA                     1334
#define SPRITE_FOLLOWER_MON_COMFEY                       1335
#define SPRITE_FOLLOWER_MON_ORANGURU                     1336
#define SPRITE_FOLLOWER_MON_PASSIMIAN                    1337
#define SPRITE_FOLLOWER_MON_WIMPOD                       1338
#define SPRITE_FOLLOWER_MON_GOLISOPOD                    1339
#define SPRITE_FOLLOWER_MON_SANDYGAST                    1340
#define SPRITE_FOLLOWER_MON_PALOSSAND                    1341
#define SPRITE_FOLLOWER_MON_PYUKUMUKU                    1342
#define SPRITE_FOLLOWER_MON_TYPE_NULL                    1343
#define SPRITE_FOLLOWER_MON_SILVALLY                     1344
#define SPRITE_FOLLOWER_MON_MINIOR                       1345
#define SPRITE_FOLLOWER_MON_KOMALA                       1346
#define SPRITE_FOLLOWER_MON_TURTONATOR                   1347
#define SPRITE_FOLLOWER_MON_TOGEDEMARU                   1348
#define SPRITE_FOLLOWER_MON_MIMIKYU                      1349
#define SPRITE_FOLLOWER_MON_BRUXISH                      1350
#define SPRITE_FOLLOWER_MON_DRAMPA                       1351
#define SPRITE_FOLLOWER_MON_DHELMISE                     1352
#define SPRITE_FOLLOWER_MON_JANGMO_O                     1353
#define SPRITE_FOLLOWER_MON_HAKAMO_O                     1354
#define SPRITE_FOLLOWER_MON_KOMMO_O                      1355
#define SPRITE_FOLLOWER_MON_TAPU_KOKO                    1356
#define SPRITE_FOLLOWER_MON_TAPU_LELE                    1357
#define SPRITE_FOLLOWER_MON_TAPU_BULU                    1358
#define SPRITE_FOLLOWER_MON_TAPU_FINI                    1359
#define SPRITE_FOLLOWER_MON_COSMOG                       1360
#define SPRITE_FOLLOWER_MON_COSMOEM                      1361
#define SPRITE_FOLLOWER_MON_SOLGALEO                     1362
#define SPRITE_FOLLOWER_MON_LUNALA                       1363
#define SPRITE_FOLLOWER_MON_NIHILEGO                     1364
#define SPRITE_FOLLOWER_MON_BUZZWOLE                     1365
#define SPRITE_FOLLOWER_MON_PHEROMOSA                    1366
#define SPRITE_FOLLOWER_MON_XURKITREE                    1367
#define SPRITE_FOLLOWER_MON_CELESTEELA                   1368
#define SPRITE_FOLLOWER_MON_KARTANA                      1369
#define SPRITE_FOLLOWER_MON_GUZZLORD                     1370
#define SPRITE_FOLLOWER_MON_NECROZMA                     1371
#define SPRITE_FOLLOWER_MON_MAGEARNA                     1372
#define SPRITE_FOLLOWER_MON_MARSHADOW                    1373
#define SPRITE_FOLLOWER_MON_POIPOLE                      1374
#define SPRITE_FOLLOWER_MON_NAGANADEL                    1375
#define SPRITE_FOLLOWER_MON_STAKATAKA                    1376
#define SPRITE_FOLLOWER_MON_BLACEPHALON                  1377
#define SPRITE_FOLLOWER_MON_ZERAORA                      1378
#define SPRITE_FOLLOWER_MON_MELTAN                       1379
#define SPRITE_FOLLOWER_MON_MELMETAL                     1380
#define SPRITE_FOLLOWER_MON_GROOKEY                      1381
#define SPRITE_FOLLOWER_MON_THWACKEY                     1382
#define SPRITE_FOLLOWER_MON_RILLABOOM                    1383
#define SPRITE_FOLLOWER_MON_SCORBUNNY                    1384
#define SPRITE_FOLLOWER_MON_RABOOT                       1385
#define SPRITE_FOLLOWER_MON_CINDERACE                    1386
#define SPRITE_FOLLOWER_MON_SOBBLE                       1387
#define SPRITE_FOLLOWER_MON_DRIZZILE                     1388
#define SPRITE_FOLLOWER_MON_INTELEON                     1389
#define SPRITE_FOLLOWER_MON_SKWOVET                      1390
#define SPRITE_FOLLOWER_MON_GREEDENT                     1391
#define SPRITE_FOLLOWER_MON_ROOKIDEE                     1392
#define SPRITE_FOLLOWER_MON_CORVISQUIRE                  1393
#define SPRITE_FOLLOWER_MON_CORVIKNIGHT                  1394
#define SPRITE_FOLLOWER_MON_BLIPBUG                      1395
#define SPRITE_FOLLOWER_MON_DOTTLER                      1396
#define SPRITE_FOLLOWER_MON_ORBEETLE                     1397
#define SPRITE_FOLLOWER_MON_NICKIT                       1398
#define SPRITE_FOLLOWER_MON_THIEVUL                      1399
#define SPRITE_FOLLOWER_MON_GOSSIFLEUR                   1400
#define SPRITE_FOLLOWER_MON_ELDEGOSS                     1401
#define SPRITE_FOLLOWER_MON_WOOLOO                       1402
#define SPRITE_FOLLOWER_MON_DUBWOOL                      1403
#define SPRITE_FOLLOWER_MON_CHEWTLE                      1404
#define SPRITE_FOLLOWER_MON_DREDNAW                      1405
#define SPRITE_FOLLOWER_MON_YAMPER                       1406
#define SPRITE_FOLLOWER_MON_BOLTUND                      1407
#define SPRITE_FOLLOWER_MON_ROLYCOLY                     1408
#define SPRITE_FOLLOWER_MON_CARKOL                       1409
#define SPRITE_FOLLOWER_MON_COALOSSAL                    1410
#define SPRITE_FOLLOWER_MON_SILICOBRA                    1411
#define SPRITE_FOLLOWER_MON_SANDACONDA                   1412
#define SPRITE_FOLLOWER_MON_CRAMORANT                    1413
#define SPRITE_FOLLOWER_MON_ARROKUDA                     1414
#define SPRITE_FOLLOWER_MON_BARRASKEWDA                  1415
#define SPRITE_FOLLOWER_MON_TOXEL                        1416
#define SPRITE_FOLLOWER_MON_TOXTRICITY                   1417
#define SPRITE_FOLLOWER_MON_CLOBBOPUS                    1418
#define SPRITE_FOLLOWER_MON_GRAPPLOCT                    1419
#define SPRITE_FOLLOWER_MON_SINISTEA                     1420
#define SPRITE_FOLLOWER_MON_POLTEAGEIST                  1421
#define SPRITE_FOLLOWER_MON_HATENNA                      1422
#define SPRITE_FOLLOWER_MON_HATTREM                      1423
#define SPRITE_FOLLOWER_MON_HATTERENE                    1424
#define SPRITE_FOLLOWER_MON_IMPIDIMP                     1425
#define SPRITE_FOLLOWER_MON_MORGREM                      1426
#define SPRITE_FOLLOWER_MON_GRIMMSNARL                   1427
#define SPRITE_FOLLOWER_MON_OBSTAGOON                    1428
#define SPRITE_FOLLOWER_MON_PERRSERKER                   1429
#define SPRITE_FOLLOWER_MON_CURSOLA                      1430
#define SPRITE_FOLLOWER_MON_SIRFETCHD                    1431
#define SPRITE_FOLLOWER_MON_MR_RIME                      1432
#define SPRITE_FOLLOWER_MON_RUNERIGUS                    1433
#define SPRITE_FOLLOWER_MON_MILCERY                      1434
#define SPRITE_FOLLOWER_MON_ALCREMIE                     1435
#define SPRITE_FOLLOWER_MON_FALINKS                      1436
#define SPRITE_FOLLOWER_MON_PINCURCHIN                   1437
#define SPRITE_FOLLOWER_MON_SNOM                         1438
#define SPRITE_FOLLOWER_MON_FROSMOTH                     1439
#define SPRITE_FOLLOWER_MON_STONJOURNER                  1440
#define SPRITE_FOLLOWER_MON_EISCUE                       1441
#define SPRITE_FOLLOWER_MON_INDEEDEE                     1442
#define SPRITE_FOLLOWER_MON_MORPEKO                      1443
#define SPRITE_FOLLOWER_MON_CUFANT                       1444
#define SPRITE_FOLLOWER_MON_COPPERAJAH                   1445
#define SPRITE_FOLLOWER_MON_DRACOZOLT                    1446
#define SPRITE_FOLLOWER_MON_ARCTOZOLT                    1447
#define SPRITE_FOLLOWER_MON_DRACOVISH                    1448
#define SPRITE_FOLLOWER_MON_ARCTOVISH                    1449
#define SPRITE_FOLLOWER_MON_DURALUDON                    1450
#define SPRITE_FOLLOWER_MON_DREEPY                       1451
#define SPRITE_FOLLOWER_MON_DRAKLOAK                     1452
#define SPRITE_FOLLOWER_MON_DRAGAPULT                    1453
#define SPRITE_FOLLOWER_MON_ZACIAN                       1454
#define SPRITE_FOLLOWER_MON_ZAMAZENTA                    1455
#define SPRITE_FOLLOWER_MON_ETERNATUS                    1456
#define SPRITE_FOLLOWER_MON_KUBFU                        1457
#define SPRITE_FOLLOWER_MON_URSHIFU                      1458
#define SPRITE_FOLLOWER_MON_ZARUDE                       1459
#define SPRITE_FOLLOWER_MON_REGIELEKI                    1460
#define SPRITE_FOLLOWER_MON_REGIDRAGO                    1461
#define SPRITE_FOLLOWER_MON_GLASTRIER                    1462
#define SPRITE_FOLLOWER_MON_SPECTRIER                    1463
#define SPRITE_FOLLOWER_MON_CALYREX                      1464
#define SPRITE_FOLLOWER_MON_BASCULEGION                  1465
#define SPRITE_FOLLOWER_MON_SNEASLER                     1466
#define SPRITE_FOLLOWER_MON_OVERQWIL                     1467
#define SPRITE_FOLLOWER_MON_ENAMORUS                     1468
#define SPRITE_FOLLOWER_MON_SPRIGATITO                   1469
#define SPRITE_FOLLOWER_MON_FLORAGATO                    1470
#define SPRITE_FOLLOWER_MON_MEOWSCARADA                  1471
#define SPRITE_FOLLOWER_MON_FUECOCO                      1472
#define SPRITE_FOLLOWER_MON_CROCALOR                     1473
#define SPRITE_FOLLOWER_MON_SKELEDIRGE                   1474
#define SPRITE_FOLLOWER_MON_QUAXLY                       1475
#define SPRITE_FOLLOWER_MON_QUAXWELL                     1476
#define SPRITE_FOLLOWER_MON_QUAQUAVAL                    1477
#define SPRITE_FOLLOWER_MON_LECHONK                      1478
#define SPRITE_FOLLOWER_MON_OINKOLOGNE                   1479
#define SPRITE_FOLLOWER_MON_TAROUNTULA                   1480
#define SPRITE_FOLLOWER_MON_SPIDOPS                      1481
#define SPRITE_FOLLOWER_MON_NYMBLE                       1482
#define SPRITE_FOLLOWER_MON_LOKIX                        1483
#define SPRITE_FOLLOWER_MON_PAWMI                        1484
#define SPRITE_FOLLOWER_MON_PAWMO                        1485
#define SPRITE_FOLLOWER_MON_PAWMOT                       1486
#define SPRITE_FOLLOWER_MON_TANDEMAUS                    1487
#define SPRITE_FOLLOWER_MON_MAUSHOLD                     1488
#define SPRITE_FOLLOWER_MON_FIDOUGH                      1489
#define SPRITE_FOLLOWER_MON_DACHSBUN                     1490
#define SPRITE_FOLLOWER_MON_SMOLIV                       1491
#define SPRITE_FOLLOWER_MON_DOLLIV                       1492
#define SPRITE_FOLLOWER_MON_ARBOLIVA                     1493
#define SPRITE_FOLLOWER_MON_SQUAWKABILLY                 1494
#define SPRITE_FOLLOWER_MON_NACLI                        1495
#define SPRITE_FOLLOWER_MON_NACLSTACK                    1496
#define SPRITE_FOLLOWER_MON_GARGANACL                    1497
#define SPRITE_FOLLOWER_MON_CHARCADET                    1498
#define SPRITE_FOLLOWER_MON_ARMAROUGE                    1499
#define SPRITE_FOLLOWER_MON_CERULEDGE                    1500
#define SPRITE_FOLLOWER_MON_TADBULB                      1501
#define SPRITE_FOLLOWER_MON_BELLIBOLT                    1502
#define SPRITE_FOLLOWER_MON_WATTREL                      1503
#define SPRITE_FOLLOWER_MON_KILOWATTREL                  1504
#define SPRITE_FOLLOWER_MON_MASCHIFF                     1505
#define SPRITE_FOLLOWER_MON_MABOSSTIFF                   1506
#define SPRITE_FOLLOWER_MON_SHROODLE                     1507
#define SPRITE_FOLLOWER_MON_GRAFAIAI                     1508
#define SPRITE_FOLLOWER_MON_BRAMBLIN                     1509
#define SPRITE_FOLLOWER_MON_BRAMBLEGHAST                 1510
#define SPRITE_FOLLOWER_MON_TOEDSCOOL                    1511
#define SPRITE_FOLLOWER_MON_TOEDSCRUEL                   1512
#define SPRITE_FOLLOWER_MON_KLAWF                        1513
#define SPRITE_FOLLOWER_MON_CAPSAKID                     1514
#define SPRITE_FOLLOWER_MON_SCOVILLAIN                   1515
#define SPRITE_FOLLOWER_MON_RELLOR                       1516
#define SPRITE_FOLLOWER_MON_RABSCA                       1517
#define SPRITE_FOLLOWER_MON_FLITTLE                      1518
#define SPRITE_FOLLOWER_MON_ESPATHRA                     1519
#define SPRITE_FOLLOWER_MON_TINKATINK                    1520
#define SPRITE_FOLLOWER_MON_TINKATUFF                    1521
#define SPRITE_FOLLOWER_MON_TINKATON                     1522
#define SPRITE_FOLLOWER_MON_WIGLETT                      1523
#define SPRITE_FOLLOWER_MON_WUGTRIO                      1524
#define SPRITE_FOLLOWER_MON_BOMBIRDIER                   1525
#define SPRITE_FOLLOWER_MON_FINIZEN                      1526
#define SPRITE_FOLLOWER_MON_PALAFIN                      1527
#define SPRITE_FOLLOWER_MON_VAROOM                       1528
#define SPRITE_FOLLOWER_MON_REVAVROOM                    1529
#define SPRITE_FOLLOWER_MON_CYCLIZAR                     1530
#define SPRITE_FOLLOWER_MON_ORTHWORM                     1531
#define SPRITE_FOLLOWER_MON_GLIMMET                      1532
#define SPRITE_FOLLOWER_MON_GLIMMORA                     1533
#define SPRITE_FOLLOWER_MON_GREAVARD                     1534
#define SPRITE_FOLLOWER_MON_HOUNDSTONE                   1535
#define SPRITE_FOLLOWER_MON_FLAMIGO                      1536
#define SPRITE_FOLLOWER_MON_CETODDLE                     1537
#define SPRITE_FOLLOWER_MON_CETITAN                      1538
#define SPRITE_FOLLOWER_MON_VELUZA                       1539
#define SPRITE_FOLLOWER_MON_DONDOZO                      1540
#define SPRITE_FOLLOWER_MON_TATSUGIRI                    1541
#define SPRITE_FOLLOWER_MON_CLODSIRE                     1542
#define SPRITE_FOLLOWER_MON_KINGAMBIT                    1543
#define SPRITE_FOLLOWER_MON_GREAT_TUSK                   1544
#define SPRITE_FOLLOWER_MON_SCREAM_TAIL                  1545
#define SPRITE_FOLLOWER_MON_BRUTE_BONNET                 1546
#define SPRITE_FOLLOWER_MON_FLUTTER_MANE                 1547
#define SPRITE_FOLLOWER_MON_SLITHER_WING                 1548
#define SPRITE_FOLLOWER_MON_SANDY_SHOCKS                 1549
#define SPRITE_FOLLOWER_MON_IRON_TREADS                  1550
#define SPRITE_FOLLOWER_MON_IRON_BUNDLE                  1551
#define SPRITE_FOLLOWER_MON_IRON_HANDS                   1552
#define SPRITE_FOLLOWER_MON_IRON_JUGULIS                 1553
#define SPRITE_FOLLOWER_MON_IRON_MOTH                    1554
#define SPRITE_FOLLOWER_MON_IRON_THORNS                  1555
#define SPRITE_FOLLOWER_MON_FRIGIBAX                     1556
#define SPRITE_FOLLOWER_MON_ARCTIBAX                     1557
#define SPRITE_FOLLOWER_MON_BAXCALIBUR                   1558
#define SPRITE_FOLLOWER_MON_GIMMIGHOUL                   1559
#define SPRITE_FOLLOWER_MON_GHOLDENGO                    1560
#define SPRITE_FOLLOWER_MON_WO_CHIEN                     1561
#define SPRITE_FOLLOWER_MON_CHIEN_PAO                    1562
#define SPRITE_FOLLOWER_MON_TING_LU                      1563
#define SPRITE_FOLLOWER_MON_CHI_YU                       1564
#define SPRITE_FOLLOWER_MON_ROARING_MOON                 1565
#define SPRITE_FOLLOWER_MON_IRON_VALIANT                 1566
#define SPRITE_FOLLOWER_MON_KORAIDON                     1567
#define SPRITE_FOLLOWER_MON_MIRAIDON                     1568
#define SPRITE_FOLLOWER_MON_WALKING_WAKE                 1569
#define SPRITE_FOLLOWER_MON_IRON_LEAVES                  1570
#define SPRITE_FOLLOWER_MON_POLTCHAGEIST                 1571
#define SPRITE_FOLLOWER_MON_SINISTCHA                    1572
#define SPRITE_FOLLOWER_MON_OKIDOGI                      1573
#define SPRITE_FOLLOWER_MON_MUNKIDORI                    1574
#define SPRITE_FOLLOWER_MON_FEZANDIPITI                  1575
#define SPRITE_FOLLOWER_MON_OGERPON                      1576
#define SPRITE_FOLLOWER_MON_ARCHALUDON                   1577
#define SPRITE_FOLLOWER_MON_GOUGING_FIRE                 1578
#define SPRITE_FOLLOWER_MON_RAGING_BOLT                  1579
#define SPRITE_FOLLOWER_MON_IRON_BOULDER                 1580
#define SPRITE_FOLLOWER_MON_IRON_CROWN                   1581
#define SPRITE_FOLLOWER_MON_TERAPAGOS                    1582
#define SPRITE_FOLLOWER_MON_PECHARUNT                    1583
#define SPRITE_FOLLOWER_MON_RATTATA_ALOLAN               1584
#define SPRITE_FOLLOWER_MON_RATICATE_ALOLAN              1585
#define SPRITE_FOLLOWER_MON_RAICHU_ALOLAN                1586
#define SPRITE_FOLLOWER_MON_SANDSHREW_ALOLAN             1587
#define SPRITE_FOLLOWER_MON_SANDSLASH_ALOLAN             1588
#define SPRITE_FOLLOWER_MON_VULPIX_ALOLAN                1589
#define SPRITE_FOLLOWER_MON_NINETALES_ALOLAN             1590
#define SPRITE_FOLLOWER_MON_DIGLETT_ALOLAN               1591
#define SPRITE_FOLLOWER_MON_DUGTRIO_ALOLAN               1592
#define SPRITE_FOLLOWER_MON_MEOWTH_ALOLAN                1593
#define SPRITE_FOLLOWER_MON_PERSIAN_ALOLAN               1594
#define SPRITE_FOLLOWER_MON_GEODUDE_ALOLAN               1595
#define SPRITE_FOLLOWER_MON_GRAVELER_ALOLAN              1596
#define SPRITE_FOLLOWER_MON_GOLEM_ALOLAN                 1597
#define SPRITE_FOLLOWER_MON_GRIMER_ALOLAN                1598
#define SPRITE_FOLLOWER_MON_MUK_ALOLAN                   1599
#define SPRITE_FOLLOWER_MON_EXEGGUTOR_ALOLAN             1600
#define SPRITE_FOLLOWER_MON_MAROWAK_ALOLAN               1601
#define SPRITE_FOLLOWER_MON_MEOWTH_GALARIAN              1602
#define SPRITE_FOLLOWER_MON_PONYTA_GALARIAN              1603
#define SPRITE_FOLLOWER_MON_RAPIDASH_GALARIAN            1604
#define SPRITE_FOLLOWER_MON_FARFETCHD_GALARIAN           1605
#define SPRITE_FOLLOWER_MON_WEEZING_GALARIAN             1606
#define SPRITE_FOLLOWER_MON_MR_MIME_GALARIAN             1607
#define SPRITE_FOLLOWER_MON_ARTICUNO_GALARIAN            1608
#define SPRITE_FOLLOWER_MON_ZAPDOS_GALARIAN              1609
#define SPRITE_FOLLOWER_MON_MOLTRES_GALARIAN             1610
#define SPRITE_FOLLOWER_MON_SLOWKING_GALARIAN            1611
#define SPRITE_FOLLOWER_MON_CORSOLA_GALARIAN             1612
#define SPRITE_FOLLOWER_MON_ZIGZAGOON_GALARIAN           1613
#define SPRITE_FOLLOWER_MON_LINOONE_GALARIAN             1614
#define SPRITE_FOLLOWER_MON_DARUMAKA_GALARIAN            1615
#define SPRITE_FOLLOWER_MON_DARMANITAN_GALARIAN          1616
#define SPRITE_FOLLOWER_MON_YAMASK_GALARIAN              1617
#define SPRITE_FOLLOWER_MON_STUNFISK_GALARIAN            1618
#define SPRITE_FOLLOWER_MON_PIKACHU_COSPLAY              1619
#define SPRITE_FOLLOWER_MON_PIKACHU_ROCK_STAR            1620
#define SPRITE_FOLLOWER_MON_PIKACHU_BELLE                1621
#define SPRITE_FOLLOWER_MON_PIKACHU_POP_STAR             1622
#define SPRITE_FOLLOWER_MON_PIKACHU_PH_D                 1623
#define SPRITE_FOLLOWER_MON_PIKACHU_LIBRE                1624
#define SPRITE_FOLLOWER_MON_PIKACHU_ORIGINAL_CAP         1625
#define SPRITE_FOLLOWER_MON_PIKACHU_HOENN_CAP            1626
#define SPRITE_FOLLOWER_MON_PIKACHU_SINNOH_CAP           1627
#define SPRITE_FOLLOWER_MON_PIKACHU_UNOVA_CAP            1628
#define SPRITE_FOLLOWER_MON_PIKACHU_KALOS_CAP            1629
#define SPRITE_FOLLOWER_MON_PIKACHU_ALOLA_CAP            1630
#define SPRITE_FOLLOWER_MON_PIKACHU_PARTNER_CAP          1631
#define SPRITE_FOLLOWER_MON_PIKACHU_WORLD_CAP            1632
#define SPRITE_FOLLOWER_MON_CASTFORM_SUNNY               1633
#define SPRITE_FOLLOWER_MON_CASTFORM_RAINY               1634
#define SPRITE_FOLLOWER_MON_CASTFORM_SNOWY               1635
#define SPRITE_FOLLOWER_MON_SHELLOS_EAST_SEA             1636
#define SPRITE_FOLLOWER_MON_GASTRODON_EAST_SEA           1637
#define SPRITE_FOLLOWER_MON_DIALGA_ORIGIN                1638
#define SPRITE_FOLLOWER_MON_PALKIA_ORIGIN                1639
#define SPRITE_FOLLOWER_MON_BASCULIN_BLUE_STRIPED        1640
#define SPRITE_FOLLOWER_MON_BASCULIN_WHITE_STRIPED       1641
#define SPRITE_FOLLOWER_MON_DARMANITAN_ZEN_MODE          1642
#define SPRITE_FOLLOWER_MON_DARMANITAN_ZEN_MODE_GALARIAN 1643
#define SPRITE_FOLLOWER_MON_DEERLING_SUMMER              1644
#define SPRITE_FOLLOWER_MON_DEERLING_AUTUMN              1645
#define SPRITE_FOLLOWER_MON_DEERLING_WINTER              1646
#define SPRITE_FOLLOWER_MON_SAWSBUCK_SUMMER              1647
#define SPRITE_FOLLOWER_MON_SAWSBUCK_AUTUMN              1648
#define SPRITE_FOLLOWER_MON_SAWSBUCK_WINTER              1649
#define SPRITE_FOLLOWER_MON_TORNADUS_THERIAN             1650
#define SPRITE_FOLLOWER_MON_THUNDURUS_THERIAN            1651
#define SPRITE_FOLLOWER_MON_LANDORUS_THERIAN             1652
#define SPRITE_FOLLOWER_MON_KYUREM_WHITE                 1653
#define SPRITE_FOLLOWER_MON_KYUREM_BLACK                 1654
#define SPRITE_FOLLOWER_MON_KELDEO_RESOLUTE              1655
#define SPRITE_FOLLOWER_MON_MELOETTA_PIROUETTE           1656
#define SPRITE_FOLLOWER_MON_GENESECT_DOUSE_DRIVE         1657
#define SPRITE_FOLLOWER_MON_GENESECT_SHOCK_DRIVE         1658
#define SPRITE_FOLLOWER_MON_GENESECT_BURN_DRIVE          1659
#define SPRITE_FOLLOWER_MON_GENESECT_CHILL_DRIVE         1660
#define SPRITE_FOLLOWER_MON_VIVILLON_POLAR               1661
#define SPRITE_FOLLOWER_MON_VIVILLON_TUNDRA              1662
#define SPRITE_FOLLOWER_MON_VIVILLON_CONTINENTAL         1663
#define SPRITE_FOLLOWER_MON_VIVILLON_GARDEN              1664
#define SPRITE_FOLLOWER_MON_VIVILLON_ELEGANT             1665
#define SPRITE_FOLLOWER_MON_VIVILLON_MEADOW              1666
#define SPRITE_FOLLOWER_MON_VIVILLON_MODERN              1667
#define SPRITE_FOLLOWER_MON_VIVILLON_MARINE              1668
#define SPRITE_FOLLOWER_MON_VIVILLON_ARCHIPELAGO         1669
#define SPRITE_FOLLOWER_MON_VIVILLON_HIGH_PLAINS         1670
#define SPRITE_FOLLOWER_MON_VIVILLON_SANDSTORM           1671
#define SPRITE_FOLLOWER_MON_VIVILLON_RIVER               1672
#define SPRITE_FOLLOWER_MON_VIVILLON_MONSOON             1673
#define SPRITE_FOLLOWER_MON_VIVILLON_SAVANNA             1674
#define SPRITE_FOLLOWER_MON_VIVILLON_SUN                 1675
#define SPRITE_FOLLOWER_MON_VIVILLON_OCEAN               1676
#define SPRITE_FOLLOWER_MON_VIVILLON_JUNGLE              1677
#define SPRITE_FOLLOWER_MON_VIVILLON_FANCY               1678
#define SPRITE_FOLLOWER_MON_VIVILLON_POKE_BALL           1679
#define SPRITE_FOLLOWER_MON_FLABEBE_YELLOW_FLOWER        1680
#define SPRITE_FOLLOWER_MON_FLABEBE_ORANGE_FLOWER        1681
#define SPRITE_FOLLOWER_MON_FLABEBE_BLUE_FLOWER          1682
#define SPRITE_FOLLOWER_MON_FLABEBE_WHITE_FLOWER         1683
#define SPRITE_FOLLOWER_MON_FLOETTE_YELLOW_FLOWER        1684
#define SPRITE_FOLLOWER_MON_FLOETTE_ORANGE_FLOWER        1685
#define SPRITE_FOLLOWER_MON_FLOETTE_BLUE_FLOWER          1686
#define SPRITE_FOLLOWER_MON_FLOETTE_WHITE_FLOWER         1687
#define SPRITE_FOLLOWER_MON_FLOETTE_ETERNAL_FLOWER       1688
#define SPRITE_FOLLOWER_MON_FLORGES_YELLOW_FLOWER        1689
#define SPRITE_FOLLOWER_MON_FLORGES_ORANGE_FLOWER        1690
#define SPRITE_FOLLOWER_MON_FLORGES_BLUE_FLOWER          1691
#define SPRITE_FOLLOWER_MON_FLORGES_WHITE_FLOWER         1692
#define SPRITE_FOLLOWER_MON_FURFROU_HEART                1693
#define SPRITE_FOLLOWER_MON_FURFROU_STAR                 1694
#define SPRITE_FOLLOWER_MON_FURFROU_DIAMOND              1695
#define SPRITE_FOLLOWER_MON_FURFROU_DEBUTANTE            1696
#define SPRITE_FOLLOWER_MON_FURFROU_MATRON               1697
#define SPRITE_FOLLOWER_MON_FURFROU_DANDY                1698
#define SPRITE_FOLLOWER_MON_FURFROU_LA_REINE             1699
#define SPRITE_FOLLOWER_MON_FURFROU_KABUKI               1700
#define SPRITE_FOLLOWER_MON_FURFROU_PHARAOH              1701
#define SPRITE_FOLLOWER_MON_PUMPKABOO_SMALL              1702
#define SPRITE_FOLLOWER_MON_PUMPKABOO_LARGE              1703
#define SPRITE_FOLLOWER_MON_PUMPKABOO_SUPER              1704
#define SPRITE_FOLLOWER_MON_GOURGEIST_SMALL              1705
#define SPRITE_FOLLOWER_MON_GOURGEIST_LARGE              1706
#define SPRITE_FOLLOWER_MON_GOURGEIST_SUPER              1707
#define SPRITE_FOLLOWER_MON_ZYGARDE_10                   1708
#define SPRITE_FOLLOWER_MON_ZYGARDE_10_POWER_CONSTRUCT   1709
#define SPRITE_FOLLOWER_MON_ZYGARDE_50_POWER_CONSTRUCT   1710
#define SPRITE_FOLLOWER_MON_ZYGARDE_10_COMPLETE          1711
#define SPRITE_FOLLOWER_MON_ZYGARDE_50_COMPLETE          1712
#define SPRITE_FOLLOWER_MON_HOOPA_UNBOUND                1713
#define SPRITE_FOLLOWER_MON_ORICORIO_POM_POM             1714
#define SPRITE_FOLLOWER_MON_ORICORIO_PAU                 1715
#define SPRITE_FOLLOWER_MON_ORICORIO_SENSU               1716
#define SPRITE_FOLLOWER_MON_ROCKRUFF_OWN_TEMPO           1717
#define SPRITE_FOLLOWER_MON_LYCANROC_MIDNIGHT            1718
#define SPRITE_FOLLOWER_MON_LYCANROC_DUSK                1719
#define SPRITE_FOLLOWER_MON_WISHIWASHI_SCHOOL            1720
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_ORANGE         1721
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_YELLOW         1722
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_GREEN          1723
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_BLUE           1724
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_INDIGO         1725
#define SPRITE_FOLLOWER_MON_MINIOR_METEOR_VIOLET         1726
#define SPRITE_FOLLOWER_MON_NECROZMA_DUSK_MANE           1727
#define SPRITE_FOLLOWER_MON_NECROZMA_DAWN_WINGS          1728
#define SPRITE_FOLLOWER_MON_MAGEARNA_ORIGINAL            1729
#define SPRITE_FOLLOWER_MON_PIKACHU_PARTNER              1730
#define SPRITE_FOLLOWER_MON_EEVEE_PARTNER                1731
#define SPRITE_FOLLOWER_MON_TOXTRICITY_LOW_KEY           1732
#define SPRITE_FOLLOWER_MON_SINISTEA_ANTIQUE             1733
#define SPRITE_FOLLOWER_MON_POLTEAGEIST_ANTIQUE          1734
#define SPRITE_FOLLOWER_MON_ALCREMIE_BERRY_SWEET         1735
#define SPRITE_FOLLOWER_MON_ALCREMIE_LOVE_SWEET          1736
#define SPRITE_FOLLOWER_MON_ALCREMIE_STAR_SWEET          1737
#define SPRITE_FOLLOWER_MON_ALCREMIE_CLOVER_SWEET        1738
#define SPRITE_FOLLOWER_MON_ALCREMIE_FLOWER_SWEET        1739
#define SPRITE_FOLLOWER_MON_ALCREMIE_RIBBON_SWEET        1740
#define SPRITE_FOLLOWER_MON_URSHIFU_RAPID_STRIKE         1741
#define SPRITE_FOLLOWER_MON_ZARUDE_DADA                  1742
#define SPRITE_FOLLOWER_MON_CALYREX_ICE_RIDER            1743
#define SPRITE_FOLLOWER_MON_CALYREX_SHADOW_RIDER         1744
#define SPRITE_FOLLOWER_MON_ENAMORUS_THERIAN             1745
#define SPRITE_FOLLOWER_MON_GROWLITHE_HISUIAN            1746
#define SPRITE_FOLLOWER_MON_ARCANINE_HISUIAN             1747
#define SPRITE_FOLLOWER_MON_VOLTORB_HISUIAN              1748
#define SPRITE_FOLLOWER_MON_ELECTRODE_HISUIAN            1749
#define SPRITE_FOLLOWER_MON_TYPHLOSION_HISUIAN           1750
#define SPRITE_FOLLOWER_MON_QWILFISH_HISUIAN             1751
#define SPRITE_FOLLOWER_MON_SNEASEL_HISUIAN              1752
#define SPRITE_FOLLOWER_MON_SAMUROTT_HISUIAN             1753
#define SPRITE_FOLLOWER_MON_LILLIGANT_HISUIAN            1754
#define SPRITE_FOLLOWER_MON_ZORUA_HISUIAN                1755
#define SPRITE_FOLLOWER_MON_ZOROARK_HISUIAN              1756
#define SPRITE_FOLLOWER_MON_BRAVIARY_HISUIAN             1757
#define SPRITE_FOLLOWER_MON_SLIGGOO_HISUIAN              1758
#define SPRITE_FOLLOWER_MON_GOODRA_HISUIAN               1759
#define SPRITE_FOLLOWER_MON_AVALUGG_HISUIAN              1760
#define SPRITE_FOLLOWER_MON_DECIDUEYE_HISUIAN            1761
#define SPRITE_FOLLOWER_MON_UNFEZANT_FEMALE              1762
#define SPRITE_FOLLOWER_MON_FRILLISH_FEMALE              1763
#define SPRITE_FOLLOWER_MON_JELLICENT_FEMALE             1764
#define SPRITE_FOLLOWER_MON_PYROAR_FEMALE                1765
#define SPRITE_FOLLOWER_MON_MEOWSTIC_FEMALE              1766
#define SPRITE_FOLLOWER_MON_INDEEDEE_FEMALE              1767
#define SPRITE_FOLLOWER_MON_BASCULEGION_FEMALE           1768
#define SPRITE_FOLLOWER_MON_MAUSHOLD_FAMILY_OF_THREE     1769
#define SPRITE_FOLLOWER_MON_SQUAWKABILLY_BLUE_PLUMAGE    1770
#define SPRITE_FOLLOWER_MON_SQUAWKABILLY_YELLOW_PLUMAGE  1771
#define SPRITE_FOLLOWER_MON_SQUAWKABILLY_WHITE_PLUMAGE   1772
#define SPRITE_FOLLOWER_MON_TATSUGIRI_DROOPY             1773
#define SPRITE_FOLLOWER_MON_TATSUGIRI_STRETCHY           1774
#define SPRITE_FOLLOWER_MON_DUDUNSPARCE_THREE_SEGMENT    1775
#define SPRITE_FOLLOWER_MON_GIMMIGHOUL_ROAMING           1776
#define SPRITE_FOLLOWER_MON_WOOPER_PALDEAN               1777
#define SPRITE_FOLLOWER_MON_TAUROS_COMBAT                1778
#define SPRITE_FOLLOWER_MON_TAUROS_BLAZE                 1779
#define SPRITE_FOLLOWER_MON_TAUROS_AQUA                  1780
#define SPRITE_FOLLOWER_MON_OINKOLOGNE_FEMALE            1781
#define SPRITE_FOLLOWER_MON_REVAVROOM_SEGIN              1782
#define SPRITE_FOLLOWER_MON_REVAVROOM_SCHEDAR            1783
#define SPRITE_FOLLOWER_MON_REVAVROOM_NAVI               1784
#define SPRITE_FOLLOWER_MON_REVAVROOM_RUCHBAH            1785
#define SPRITE_FOLLOWER_MON_REVAVROOM_CAPH               1786
#define SPRITE_FOLLOWER_MON_OGERPON_WELLSPRING_MASK      1787
#define SPRITE_FOLLOWER_MON_OGERPON_HEARTHFLAME_MASK     1788
#define SPRITE_FOLLOWER_MON_OGERPON_CORNERSTONE_MASK     1789
#define SPRITE_FOLLOWER_MON_URSALUNA_BLOODMOON           1790
#define SPRITE_FOLLOWER_MON_ADDED_FIRST                  1050
#define SPRITE_FOLLOWER_MON_ADDED_LAST                   1790

#define SPRITE_CAMERA_FOCUS                    8192

#define SPRITE_VAR_0  100
#define SPRITE_VAR_1  101
#define SPRITE_VAR_2  102
#define SPRITE_VAR_3  103
#define SPRITE_VAR_4  104
#define SPRITE_VAR_5  105
#define SPRITE_VAR_6  106
#define SPRITE_VAR_7  107
#define SPRITE_VAR_8  108
#define SPRITE_VAR_9  109
#define SPRITE_VAR_10 110
#define SPRITE_VAR_11 111
#define SPRITE_VAR_12 112
#define SPRITE_VAR_13 113
#define SPRITE_VAR_14 114
#define SPRITE_VAR_15 115

#endif // POKEHEARTGOLD_CONSTANTS_SPRITES_H
