// Template: a save-editor feature: research, two builders in turn, review lenses, fix (the story steps and the town map, 2026-09-24).
// Kept from .rounds/editor-story/saveui-story-map-wf_fade9d67-842.js; tools/newgold/rounds/README.md says how a round runs.
export const meta = {
  name: 'saveui-story-map',
  description: "Save editor: story-event checkboxes in the trainer tab, a TM/HM list with have/quantity, and a Position tab with a searchable map picker, a two-region minimap in sync, and safe preset coordinates -- all read from the tree",
  phases: [
    { title: 'Research', detail: 'story flags; the bag\'s machines; the region maps, map sections and safe spawn points' },
    { title: 'Build', detail: 'trainer checkboxes and machines list, then the Position tab with the minimap' },
    { title: 'Review', detail: 'the page as Paolo uses it; everything from the tree' },
    { title: 'Fix', detail: 'the confirmed findings' },
  ],
}

// Where things were on the machine these ran on; set them for yours.
const HOME_ = '/home/paolo'
const TREE = `${HOME_}/hgss-newgold`                     // the main tree, branch newgold
const WORKTREES = `${HOME_}/hgss-worktrees`              // one git worktree per agent
const ROUNDS = `${WORKTREES}/.rounds`                    // rows, reports, scratch: on disk, never /tmp
const MEMORY = `${HOME_}/.claude/projects/-home-paolo-Porting-HGSS/memory`
const ENV = `${HOME_}/hgss-build/env.sh`                 // the project's own wine
const SAVES = `${HOME_}/hgss-saves`                      // Paolo's saves: scratch copies only
const REF = `${HOME_}/Porting HGSS/hg-engine-newgold-reference`
const CAPPED = `${TREE}/tools/newgold/devkit/capped`     // every heavy command runs under it
const MERGE_TOOLS = `${TREE}/tools/newgold/rounds`
const WT = `${WORKTREES}/editor`
const SCR = `${ROUNDS}/editor-story`
const CONTEXT = `
PROJECT: ${TREE} is pokeheartgold (HeartGold decompilation) with hg-engine and konefr's New Gold ported into it. Paolo (Italian; the UI is Italian) edits saves with the save editor: tools/newgold/devkit/saveui.py (a local http.server page, saveui.html; tabs Allenatore, Squadra e box, Borsa, Pokedex, Posizione, Flag e variabili, Info) over tools/newgold/devkit/savedit.py (the save as a library: set_badges, set_flag/set_var by the names in include/constants/flags.h and vars.h, set_position(map, x, y, dir) which writes the position and the warp with FLAG_UNK_966 so Continue takes the game's warp path, on_map, map_table, pockets/put_in_pocket, set_dex...). README tools/newgold/devkit/README.md; tests tests/newgold/test_savedit.py and test_saveui.py. Read both code files and the README in full first, and the memory notes ${MEMORY}/hgss-save-editor-reads-the-tree.md and hgss-scratch-on-disk.md.

PAOLO'S RULE ON DATA: every game datum the editor shows, offers or enforces is READ FROM THE TREE as it is at that moment (headers, .c tables, .json/.csv, the files the build packs, or the build outputs make produced from them), re-read when those files change -- never a copied table or a list typed into the Python or the page -- "so that if one day I widen the map or add places, the save editor follows by itself, as it already does for moves and Pokemon". Italian UI words may be written in the page, keyed by the tree's constant names.

PAOLO'S REQUEST (Italian, 2026-09-24): "nell'editor di salvataggi aggiungiamo anche delle spunte nella scheda allenatore per le scarpe da corsa e altra roba simile (o sono oggetti)? insomma le flag degli eventi della storia come le medaglie devo poterle selezionare io, perche' ora non ho modo di attivarle nella ui e ci sono alcune cose che se sto provando certi punti della storia mi servono; per MT e MN metti gia' tipo l'elenco come hai fatto per il pokedex dove posso selezionare con la spunta se ce l'ho o meno e in caso la quantita'; per il teletrasporto nella scheda posizione metti un menu' a tendina piu' capibile nello stesso stile di quello delle mosse dei pokemon nella scheda squadra e anche una minimappa delle due regioni che mi mostra la posizione del personaggio e sulla quale posso spostare il cursore per avere direttamente il percorso o simili (la scelta menu' a tendina e posizione deve essere sincronizzata con la minimappa); quando lo sposto o seleziono tipo una citta' si deve caricare un preset di coordinate in modo che non rischio di mettere delle posizioni invalide (tieni la modifica che si puo' fare con messaggio di errore come c'e' gia' ma aggiungi anche il preset); anche qui le cose devono essere lette dalla rom in modo tale che se un domani allargo la mappa, aggiungo luoghi o simili si aggiorna anche il modificatore di salvataggi in automatico."

RULES: work only in the worktree ${WT} (branch editor-story from newgold 277ea753d; its build/heartgold.us and build/heartgold.us.diag hold links to the main tree's main.sbin/main.elf, enough for savedit's layout; test_saveui's built-ROM check needs a real ROM file: copy ${TREE}/build/heartgold.us/pokeheartgold.us.nds with 'cp --reflink=auto' into ${WT}/build/heartgold.us/ while you test and delete it after). Never touch ${TREE}'s working tree, never push, never make/wine. Never modify ${SAVES} or any build/*.sav -- scratch copies under ${SCR}/. Scratch server: SAVEUI_CONFIG=<scratch>/settings.json SAVEUI_DRY_RUN=1 python3 tools/newgold/devkit/saveui.py --library <scratch copy of ${SAVES}> --port <free port 88xx> --no-browser, started through ${CAPPED} and stopped by its PID (never pkill -f / pgrep -f with a pattern in your own command line -- it kills your shell); Paolo's own editor may be on 8765: never touch it. Run tests through capped too (TMPDIR under ${SCR}/tmp, except test_saveui which needs the real /tmp). The reference ${REF} is read only through git at d0380a487 (engine) or 1fa3c9366 (konefr). Commits: short lowercase subject 'devkit: ...', plain prose body, last line 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>'. Python standard library only; the page stays one vanilla HTML/JS file (no CDN).`

const RESEARCH = [
  { key: 'flags', prompt: `RESEARCH: STORY FLAGS. Find which flags and variables are the story's own switches a tester would toggle, and how the game uses each: the running shoes (in HGSS they are PlayerSaveData.hasRunningShoes in include/player_avatar.h, not a flag nor an item -- find where the save keeps it and who sets it), the Pokedex and national Dex, the Pokegear and its cards (map, phone, radio, the expansion cards), the Bicycle/other key items that are really flags, the badges (already in the page), each HM's field use (which badge/flag enables it), the rival's name/encounters?, the story milestones the scripts test (the Elite Four beaten, Red, the S.S. Aqua, the Kanto power plant, Team Rocket's takeover -- VAR_SCENE_ROCKET_TAKEOVER, VAR_MIDGAME_BADGES --, the Burned Tower, the Sprout Tower's FLAG_UNK_076, the Azalea Rockets, the level cap's milestones in GetLevelCap, the Kimono girls, the legendaries' events). Read include/constants/flags.h and vars.h (names and comments), the scripts in files/fielddata/script/scr_seq/*.s that set them, and src/ where the system flags are read (e.g. 'FLAG_SYS_'). Propose how the editor can LIST them from the tree without a typed list: e.g. every FLAG_SYS_* and a group derived from the scripts (flags a script sets with SetFlag after a GiveItem/fanfare/trainer battle of a leader), each with an Italian label derived from its name; say which flags need a variable set with them to be consistent (a badge's VAR_MIDGAME_BADGES, the level cap's pairs) and which are dangerous to toggle alone. Report the list with names, numbers, what each does, the source file:line, and the grouping rule.` },
  { key: 'machines', prompt: `RESEARCH: THE BAG'S MACHINES. Find how the bag keeps TMs and HMs in this tree (the TMs/HMs pocket's size and slots in include -- the bag struct --, the item ids of TM01.., HM01.., any TR or TM past 92 after the 340-machine change: tools/newgold/import/import_machines.py and the machine-to-move table the game uses, sTMHMMoves or its successor; item_data.csv), whether a TM is consumed in this game (Gen 4 TMs are single use, HMs infinite; hg-engine may make TMs reusable -- read the engine's config at d0380a487/1fa3c9366 and this tree's code where a TM is used, and say what this game does), the quantity limit (BAG_TMHM_QUANTITY_MAX in savedit), and how savedit and the page already read and write the pocket (savedit.pockets, pocket_at, put_in_pocket, the Borsa tab). Report: the list the editor should show (machine number, item, move name and type, from the tree), what 'have it' and 'quantity' mean for a TM and an HM here, and how writing them keeps the pocket valid (sorted? order?).` },
  { key: 'map', prompt: `RESEARCH: THE REGION MAPS, MAP SECTIONS AND SAFE SPAWNS. (1) The minimap: find the town map the Pokegear/Fly screen draws for Johto and Kanto -- its graphics (PNG sources in the tree, or the NCGR/NCLR/NSCR it is built from, and which files), and the table that places each map section (MAPSEC) on it (coordinates and size in the town map's tiles: search src/ and files/ for the Pokegear map app and the fly map, 'mapsec', 'townmap', 'pokegear/map') -- so the page can draw the two regions from the tree's own art and place/highlight every map section at its coordinates, and map a click on the minimap to the map section under it. Say how the page can get the images (a PNG the tree has, or decoding the built NCGR/NCLR/NSCR in Python standard library -- zlib/struct only) and whether any map section has no place on the town map. (2) Map to map section: savedit.map_table gives every map by id with its section name; find the map header field that names its section (src/data/map_headers.h), so a click on a section can offer its maps (a city has several: the town, its buildings). (3) Safe preset coordinates for a map: where the game itself puts the player -- the heal/fly spawn for towns (the fly destinations table, sFlyWarpsTable or its HG name, and the respawn/healing locations), and for other maps a warp's arrival tile (zone_event json 'warps' in files/fielddata/eventdata/zone_event/*.json: the player arrives standing on the warp tile or next to it -- find how the game offsets it), or a map's first walkable tile from the map's collision/permission data (the land data in files/fielddata/land_data? and savedit.on_map / map_chunks). Say which rule gives a valid tile for every map (test a few: a town, a route, a cave floor, a building interior, a gym), and how to check a coordinate is walkable, not just inside the map (the permission/collision bits). Report the data sources with file paths and formats, and a plan the builder can follow.` },
]

phase('Research')
const research = await parallel(RESEARCH.map(r => () => agent(`${CONTEXT}\n\n${r.prompt}\n\nRead-only: do not edit the worktree. Report findings with file:line evidence and a concrete plan.`, { label: `research:${r.key}`, phase: 'Research' })))
const R = research.map((r, i) => `=== ${RESEARCH[i].key}\n${r}`).join('\n\n')

phase('Build')
const b1 = await agent(`${CONTEXT}\n\nThe research:\n${R}\n\nYOUR JOB (part 1 of 2 -- another agent builds the Position tab after you): (a) the Allenatore tab gets a 'Storia' section of checkboxes for the story's switches -- the running shoes and the rest the flags research lists -- grouped (Oggetti e strumenti di gioco / Medaglie e capipalestra / Momenti della storia / Pokedex e Pokegear...), each with an Italian label and a one-line explanation, all LISTED FROM THE TREE by the research's grouping rule (no typed list of flags: a rule over flags.h/scripts; Italian labels may be a dictionary keyed by constant name, with the constant's own name shown for any flag the dictionary lacks); the badges are ALREADY in the Allenatore tab: do not add a second badge list -- beside each badge show the gym's own steps as their own checkboxes, in the order the gym's script sets them (e.g. Whitney: leader beaten -- VAR_UNK_410A / FLAG_UNK_084 and the juniors' trainer flags -- , the badge, the TM received; Morty's Burned Tower prerequisite; Chuck's...), so Paolo can put a save in any step BETWEEN them, e.g. 'Whitney beaten but the badge not given yet'; ticking the badge offers to tick the steps before it (as the script would have), never forces it; the same for other multi-step story events (each step its own checkbox, in script order). Paolo asked (2026-09-24): 'posso spuntare che ho battuto whitney ma che non mi ha ancora dato la medaglia in modo che provo la quest di sudowoodo?' -- note in the UI, where it matters, what the game actually checks: the Goldenrod Flower Shop gives the SquirtBottle only with the Plain Badge (CheckBadge BADGE_PLAIN in scr_seq_0896_T25R0601.s) and Route 36's Sudowoodo needs the SquirtBottle in the bag; ticking one that needs a companion (a variable, another flag) sets the companion too, as the game would, or says so; the existing 'Flag e variabili' tab stays for everything else. (b) The Borsa tab (or a section of it) gets the machines as a list like the Pokedex tab's: every TM/HM/TR the tree has, with number, move name and type, a checkbox 'ce l'ho' and a quantity where quantity means something in this game (the research says), writing the pocket as the game keeps it. savedit gets the library functions (tested), saveui the API ops (tested), the page the UI. Commits of one thing each; run test_save*.py. Report the commits and what Paolo will see.`, { label: 'build:story-machines', phase: 'Build' })

const b2 = await agent(`${CONTEXT}\n\nThe research:\n${R}\n\nPart 1's report (another agent built the story checkboxes and the machines list; build on its commits):\n${b1}\n\nYOUR JOB (part 2): the Posizione tab. (a) The map field becomes a searchable dropdown in the same style as the Pokemon dialog's move fields (a combobox with a list, keyboard and mouse, Italian), listing every map from the tree (savedit.map_table) grouped or labelled by its map section (city, route, cave...) and region. (b) A minimap of the two regions, Johto and Kanto, drawn from the tree's own town-map art (the research says where and how -- decode in Python stdlib if it is only NCGR/NCLR/NSCR, served by saveui as a PNG it builds and caches by the files' mtimes), with the player's current position marked (its map section highlighted), a hover highlight of the section under the cursor with its name, and a click that picks that section's main map (a town's outdoor map, a route) -- in sync both ways with the dropdown (picking in the dropdown highlights the minimap; clicking the minimap fills the dropdown). (c) Picking a map loads a PRESET coordinate the game itself would use (fly/heal spawn for towns, a warp arrival for others, as the research found) and a direction; the manual X/Y/direction fields stay, with the existing error message for an invalid position -- and the check becomes 'walkable', not just 'inside the map', if the research found the permission data. (d) Everything read from the tree (maps, sections, art, spawns), re-read when the files change. savedit gets the library functions (tested: a preset for a town, a route, a cave, an interior, each walkable), saveui the endpoints (tested), the page the UI. Check it in the browser pane (mcp__Claude_Browser__* tools) on a scratch server with a scratch copy of the saves: pick a city in the dropdown, see the minimap, click a route on the minimap, save, reload and see the new position. Commits of one thing each; run test_save*.py. Report the commits and what Paolo will see.`, { label: 'build:position', phase: 'Build' })

const FINDINGS = { type: 'object', properties: {
  lens: { type: 'string' },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] },
    title: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'title', 'evidence', 'fix'] } },
  checked: { type: 'string' },
}, required: ['lens', 'findings', 'checked'] }
const LENSES = [
  { key: 'page', prompt: `LENS: THE PAGE AS PAOLO USES IT, in the browser pane (mcp__Claude_Browser__* tools) on your own scratch server and scratch saves: the story checkboxes (tick the running shoes and a milestone, save, reload, and check the save with savedit AND that the game would read it -- the flag bit in the save's flags block; boot the save in the diagnostics harness if you can, capped, and see the flag/the B-dash state in RAM), the machines list (have/quantity for a TM and an HM, save, reload, the pocket as the game keeps it), the Position tab (the dropdown's search and keyboard, the minimap's highlight/hover/click, their sync both ways, the preset after a pick, a manual invalid coordinate refused with its message, save and reload, and -- if you can -- boot the save in the diagnostics harness with tools/newgold/devkit/diag and check the player arrives on that map at that tile, not off the map). Report every broken, confusing or slow behaviour with steps.` },
  { key: 'tree', prompt: `LENS: DOES EVERYTHING COME FROM THE TREE, NOW? Grep the new code in savedit.py, saveui.py and saveui.html for any list, table, number, coordinate or name of game data typed in rather than read from the tree (flags, machines, maps, map sections, town-map coordinates, spawn points, art). Then prove it: on a scratch COPY of the files the editor reads (point the editor at the copy or monkeypatch its paths in a python session), add a flag to a story group's source, a machine, a map/map section/fly point, move a section on the town map -- and check the library and a scratch server follow without another edit. Also check correctness against the game: a preset coordinate for every map is walkable by the game's own permission data (or say why not checkable), the machines' pocket order is the game's, a story checkbox's companion flags/vars match what the scripts set together.` },
]
phase('Review')
const reviews = await parallel(LENSES.map(l => () => agent(`${CONTEXT}\n\nThe two builders' reports:\n${b1}\n\n${b2}\n\n${l.prompt}\n\nDo NOT fix anything and do NOT commit: findings only, each with the evidence you observed.`, { label: `review:${l.key}`, phase: 'Review', schema: FINDINGS })))
const all = reviews.filter(Boolean).flatMap(r => r.findings.map(f => ({ ...f, lens: r.lens })))
log(`${all.length} findings`)

phase('Fix')
const fixed = await agent(`${CONTEXT}\n\nBuilders' reports:\n${b1}\n\n${b2}\n\nAll the findings, as JSON:\n${JSON.stringify(all, null, 1)}\n\nYOUR JOB: check each finding against the code (some may be wrong -- say so with evidence), fix every real one, highest severity first, each with a test where it can have one, in commits of one thing each. Re-run test_save*.py and a scratch-server check in the browser pane afterwards. Report each finding as fixed / not a defect / left (and why), the commits (the branch tip), and what Paolo will see, in plain words.`, { label: 'fix:editor', phase: 'Fix' })

return { research, b1, b2, reviews: reviews.filter(Boolean), fixed }
