// Template: a save-editor feature with its provenance written up, review lenses, fix (legal moves and abilities, 2026-09-24).
// Kept from .rounds/saveui-legal-moves.js; tools/newgold/rounds/README.md says how a round runs.
export const meta = {
  name: 'saveui-legal-moves',
  description: 'Save editor: moves and abilities limited to what the species can legally have, and a preset loaded on a species change; verified from two angles, then fixed',
  phases: [
    { title: 'Build', detail: 'legal moves and abilities, species preset (moves and ability replaced); then every game datum the editor uses read from the tree' },
    { title: 'Verify', detail: 'legality against the game data and code; everything from the tree; the page as Paolo uses it' },
    { title: 'Fix', detail: 'the confirmed findings' },
  ],
}

// Where things were on the machine these ran on; set them for yours.
const HOME_ = '/home/paolo'
const TREE = `${HOME_}/hgss-newgold`                     // the main tree, branch newgold
const WORKTREES = `${HOME_}/hgss-worktrees`              // one git worktree per agent
const ROUNDS = `${WORKTREES}/.rounds`                    // rows, reports, scratch: on disk, never /tmp
const MEMORY = `${HOME_}/.claude/projects/-home-paolo-Porting-HGSS/memory`
const ENV = `${HOME_}/hgss-build/env.sh`                 // the project's own wine
const SAVES = `${HOME_}/hgss-saves`                      // Paolo's saves: scratch copies only
const REF = `${HOME_}/Porting HGSS/hg-engine-newgold-reference`
const CAPPED = `${TREE}/tools/newgold/devkit/capped`     // every heavy command runs under it
const MERGE_TOOLS = `${TREE}/tools/newgold/rounds`
const CONTEXT = `
PROJECT: ${TREE} is pokeheartgold (the HeartGold decompilation) with hg-engine and konefr's New Gold ported into it; forms are species 1042..1437 (they register and print as their base). Paolo (Italian; UI text in Italian) edits saves with the save editor: tools/newgold/devkit/saveui.py (a local http.server page, saveui.html) over tools/newgold/devkit/savedit.py (the save as a library: describe_mon, edit_mon, build_mon, learnset, the party and boxes, the PC's box-modified flags...). Read both files in full first, and tools/newgold/devkit/README.md. tests/newgold/test_savedit.py and test_saveui.py test them (python3 -m unittest discover -s tests/newgold -p 'test_save*.py').

WORKING RULES: work directly in ${TREE} (branch newgold; other sessions and agents work in other worktrees, not in tools/newgold/devkit or those two tests). Stage files by name only; commits: short lowercase subject 'devkit: ...', plain prose body (what and why), last line 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>'. Do not push. Python standard library only. NEVER modify files in ${SAVES} or any build/*.sav: test on copies in your scratch folder ${ROUNDS}/legal/<role>/, with a server started as: SAVEUI_CONFIG=<scratch>/settings.json SAVEUI_DRY_RUN=1 python3 tools/newgold/devkit/saveui.py --library <scratch copy of ${SAVES}> --port <free port> --no-browser (record its PID and stop it by that PID when done; never use pkill -f with a pattern that appears in your own command line -- it kills your shell). Never run make or wine. Paolo may have his own editor open on port 8765: do not touch it.

PAOLO'S RULE ON DATA (Italian): "tutte queste info devono arrivare direttamente da come è il codice del gioco in quel momento, non devono essere indipendenti sennò non ho mai le cose allineate" -- every piece of game data the editor shows, offers or enforces (learnable moves and their sources, abilities, the preset, types, names, items, pockets, forms, icons, natures, stats...) is READ FROM THE TREE as it is at that moment: the same source files the build compiles into the ROM (headers, .c tables, .json/.csv, the files make packs) -- never a copied table, a generated file committed to the repo, or a list typed into the Python or the page; read at runtime, and re-read when those files change (a cache keyed on their modification times, not one that outlives an edit). Where the only form is a build output, read the one make produced from those sources and say (in the page) when it is older than them. Italian UI words (tab titles, Italian type labels, stat abbreviations) are translations, not game data, and may stay in the page; but which types, moves, abilities exist and their numbers come from the tree.`

const BUILD = `${CONTEXT}

PAOLO'S REQUEST (Italian): "Ora le mosse quando le cambio devo poterle scegliere solo dall'elenco di mosse che quel Pokémon può imparare in modo che non ho Pokémon impossibili, stessa cosa per le abilità. Quando cambio specie deve essere caricato un determinato preset." -- when he changes a Pokemon's moves he must be able to pick only from the moves that Pokemon can learn, so no impossible Pokemon; the same for abilities; and changing the species loads a preset. AND HE ADDED: "Voglio tutte quelle che il Pokémon può imparare in generale" -- every move the species can learn in general, NOT limited by its current level: a level-up move learnt at 70 is offered to a level 5 Pokemon too. AND: "un Pokémon una stessa mossa la può imparare da più fonti, forse affianco conviene mettere più tag" -- the same move often comes from several sources (level-up AND a TM, a tutor AND an egg move, the pre-evolution too): EVERY source is kept and shown, one small tag each, never just the first. AND, ON THE SPECIES CHANGE: "quando cambio specie deve caricarsi un preset di mosse così non c'è mai la possibilità di avere una specie con le mosse sbagliate nel salvataggio" -- a species change REPLACES the moves with the new species' preset; it never keeps the old moves and flags them: nothing the editor writes may leave a species with a move it cannot learn. AND: "Anche l'abilità deve essere sostituita quando cambio specie" -- the ability too is replaced on a species change, never the old species' ability left behind.

YOUR JOB:
1. savedit: learnable_moves(species) -> every move this species can learn by any means, whatever the Pokemon's level, each with EVERY way it is learnt -- a list of sources, not one (level-up at any level, with its level, and every level if it is learnt twice, including the engine's level-0 'on evolution' entries; a TM, HM or TR it is compatible with; a move tutor; an egg move of its evolution line's first stage; and the same for its pre-evolutions, since a move learnt before evolving is kept). The data is the tree's own: the level-up learnsets (tools/newgold/import/wotbl.py reads the built archive; savedit.learnset shows how), personal.json's tms/hms/machines with the machine-to-move table the game uses (find it in src/ -- the TM case's sTMHMMoves or its successor after the 340-machine change, and how 'machines' places are numbered: tools/newgold/import/import_machines.py), the tutor records (files/fielddata/wazaoshie/waza_oshie.json and the TUTOR_ constants; tools/newgold/import/import_tutor_moves.py), the egg moves (files/fielddata/sodateya/kowaza_list.narc; tools/newgold/import/import_egg_moves.py decodes it), and the evolutions (find the data the game's GetMonEvolution reads; a form takes its base's line). species_abilities(species) -> the species' first and second ability and its hidden one, and how the game stores which one a Pokemon has (the personality's low bit for the first two, the engine's hidden-ability bit -- find HIDDEN_ABILITY_BIT and how GetMonData / the engine decide the ability, so that the game keeps the chosen one, including through evolution).
2. The server (saveui.py): the page gets, for a species, the legal moves (with their source, for display) and the legal abilities; op party_edit, box_edit, party_add, box_add refuse a move or an ability the species cannot have (Italian message naming it and the species) -- the one exception: a Pokemon the game made (already in the save) whose species is NOT being changed keeps a move the rules do not list (an event move) as long as that move is left untouched (say so in the page). A species change has no exception: savedit gets preset_moves(species, level) and edit_mon applies it itself -- a species change without moves given writes the new species' preset moves AND replaces the ability with the new species' own (the one the game itself gives a Pokemon of that species with this personality: the slot its personality low bit / the hidden-ability bit selects, with the game's fallback when the new species has no second or hidden ability -- read how the game's creation code sets the ability, and write the ability field(s) the way the game keeps them); an ability given with the species change must be one of the new species'; with moves given, every one must be legal for the NEW species (the old ones sent back unchanged are refused like any other) -- so the CLI, the server and the page all follow the one rule, and no path writes a species with a move it cannot learn or an ability it cannot have. Setting an ability writes it the way the game keeps it (the personality low bit for ability 1/2 -- keep gender, nature (unless a Mint) and shininess as the nature change already does -- or the hidden-ability bit).
3. The page: in the Pokemon dialog, the four move fields offer only the legal moves (a searchable list, each with ALL its sources as separate small tags -- e.g. Flamethrower: 'Lv. 36' 'MT 35' 'Insegnante', or 'Mossa uovo' 'da Ponyta Lv. 20' -- in Italian; the chosen move shows its tags beside it too), refresh when the species changes; the ability is a select of the species' abilities (with '(nascosta)' for the hidden one). THE PRESET: when the species changes in the dialog, the four move fields are REPLACED at once, visibly, by the species' preset at that level (never kept and flagged) (the last four level-up moves it knows by then, as the game gives a wild Pokemon: savedit.learnset / the game's own rule) and the ability is replaced at once, visibly, by the new species' ability as the server rule above picks it (the select refreshes to the new species' abilities); nature, level, IVs, EVs and item stay. A 'Mosse per livello' button already exists: keep it consistent with the preset. The CLI (--party) stays byte-identical in output.
4. Tests in tests/newgold/test_savedit.py and test_saveui.py: learnable_moves on a few species you check by hand against the data (a TM move, a tutor move, an egg move, a pre-evolution move, a level-up move learnt at a level above the Pokemon's accepted, a move the species cannot learn at all refused), species_abilities with a hidden one, the server refusing an illegal move/ability and accepting a legal one, the hidden ability kept by the game's own reading of the Pokemon (decode it back), an existing illegal move kept when untouched.
5. Check in the browser pane if you can (mcp__Claude_Browser__* tools, viewport 1280x900; coordinates are in the screenshot's frame): open a scratch save, edit a Pokemon, change its species, see the preset, see the lists limited. Commit in a few commits of one thing each, and report: commits, the rules you implemented (and anything you could not source), what you tested.`

const PROVENANCE = `${CONTEXT}

The legal-moves feature has just been built in ${TREE}; its builder's report:
BUILT_REPORT

YOUR JOB: apply PAOLO'S RULE ON DATA to the WHOLE save editor, not only the new feature. Read savedit.py, saveui.py and saveui.html in full and list every piece of game data written into them instead of read from the tree -- for example (check each, there are more): savedit's POCKETS sizes, NATURE_MODS, FORM_ROWS, SHUFFLE, MAIL_INIT, the dex sizes, anything in the new learnable_moves/species_abilities/preset code; saveui's ICON_FORMS, SLOTS; the page's TYPES keys, badge counts, stat order, pocket order. For each: find where the game's code or data keeps it (a header define, a .c table, a .json/.csv) and read it from there at runtime, re-read when the file changes; when it is a fixed algorithm of the save format that only exists as code (a switch, not a table), keep it but add a test that reads the tree's code and fails if they ever differ -- and list those. The UI's Italian labels stay (they are translations), keyed by the tree's constant names, and a type or pocket the tree has that the page has no Italian label for still shows (by its name). Keep every existing test passing, the CLI's --party output byte-identical, and nothing slower to start than a couple of seconds (measure). Commits of one thing each. Report: what you moved to the tree (from where), what stays as code with a test, and the commits.`

const FINDINGS = { type: 'object', properties: {
  lens: { type: 'string' },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['critical', 'high', 'medium', 'low'] },
    title: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'title', 'evidence', 'fix'] } },
  checked: { type: 'string' },
}, required: ['lens', 'findings', 'checked'] }

const LENSES = [
  { key: 'legality', prompt: `LENS: IS THE LEGALITY RIGHT? Check savedit's learnable_moves and species_abilities against the game's own data and code, adversarially: pick at least 25 species across the range (retail ones, hg-engine additions, forms past 1041, a baby, a three-stage line, a species with a hidden ability, Arceus/Silvally, Rotom forms, a Pokemon whose pre-evolution learns something the evolved form does not, one with egg moves, one with tutor moves, one with TRs and TMs past HM08) and for each compare every source with the data the game reads -- and check that a move learnt several ways lists every way, not just one -- (the learnset archive, personal.json machines with the game's machine-to-move table, waza_oshie, kowaza_list, the evolution data) -- a move the game would let it have and the editor refuses is as much a defect as the reverse. Check the ability write: after setting the second ability and the hidden one, decode the Pokemon as the game does (GetMonData's ability logic, the hidden bit) and after an evolution (the engine's rule) the ability must be the one chosen. Check the species change: savedit's preset_moves against the game's own rule for a wild Pokemon's moves at a level (the last four level-up moves, the order the game uses), and that a species change through edit_mon never keeps a move the new species cannot learn. Check nothing else in the Pokemon changed (gender, nature, shininess, stats recomputed only as they should).` },
  { key: 'provenance', prompt: `LENS: DOES EVERYTHING COME FROM THE TREE, NOW? Paolo's rule (above) adversarially: grep savedit.py, saveui.py and saveui.html for any list, table, number or name of game data not read from the tree; then PROVE the alignment by changing the tree in a scratch COPY of the files the editor reads (never the real tree: point the editor at a copy if it can be, or monkeypatch the paths in a python session) -- e.g. give a species a new level-up move, a new TM compatibility, a different ability, a new type, a pocket size -- and check the editor (library and a scratch server started after the change, and one already running when the file changes) follows without any other edit. A value that does not follow is a finding.` },
  { key: 'page', prompt: `LENS: THE PAGE AS PAOLO USES IT. Start a scratch server (see the rules above) and use the Pokemon dialog, reading saveui.html's code and driving the API (and the browser pane mcp__Claude_Browser__* if available: viewport 1280x900, coordinates in the screenshot frame): the move fields offer only legal moves, each with every source it has as its own tag (check moves learnt several ways: level-up and TM, tutor and egg, the pre-evolution's), in Italian, typing a name not in the list is refused clearly, changing the species REPLACES the moves with the preset (the last four level-up moves at the level) and REPLACES the ability with the new species' own, and refreshes the lists -- and try to break the rule Paolo set, 'never a species with the wrong moves in the save': through the page and straight through the API (party_edit, box_edit, party_add, box_add with a new species and the old moves sent back, a new species with no moves, a species changed and then a move typed by hand, the CLI's edit), none may store a species with a move it cannot learn or an ability it cannot have, the lists hold every move the species can learn whatever the level (Paolo asked for that explicitly), the ability select shows the species' abilities with the hidden one marked, an existing Pokemon with a move outside the rules keeps it if untouched and the page says why, adding a new Pokemon starts from the preset, the box and party drag and everything else in the editor still work, nothing is slow with a 1438-species list. Report every broken, confusing or slow behaviour with steps.` },
]

phase('Build')
const built = await agent(BUILD, { label: 'build:legal', phase: 'Build' })

const provenance = await agent(PROVENANCE.replace('BUILT_REPORT', () => String(built)), { label: 'build:provenance', phase: 'Build' })

phase('Verify')
const reviews = await parallel(LENSES.map(l => () => agent(
  `${CONTEXT}\n\nThe feature has just been built in ${TREE}; the builders' reports:\n${built}\n\n${provenance}\n\n${l.prompt}\n\nDo NOT fix anything and do NOT commit: report findings only, each with evidence you observed.`,
  { label: `verify:${l.key}`, phase: 'Verify', schema: FINDINGS })))
const all = reviews.filter(Boolean).flatMap(r => r.findings.map(f => ({ ...f, lens: r.lens })))
log(`${all.length} findings`)

phase('Fix')
const fixed = await agent(`${CONTEXT}\n\nThe feature below was built and then reviewed. All the findings, as JSON:\n${JSON.stringify(all, null, 1)}\n\nBuilders' reports:\n${built}\n\n${provenance}\n\nYOUR JOB: check each finding against the code (some may be wrong -- say so with evidence), fix every real one, highest severity first, each with a test where it can have one, in commits of one thing each. Re-run tests/newgold -p 'test_save*.py' and a scratch-server check afterwards. Report each finding as fixed / not a defect / left (and why), the commits, and what Paolo will see.`, { label: 'fix:legal', phase: 'Fix' })

return { built, provenance, reviews: reviews.filter(Boolean), fixed }
