// Template: merge one late branch, then measure and win back the boot-time main arena (round 7, 2026-09-24).
// Kept from .rounds/round7/memory.js; tools/newgold/rounds/README.md says how a round runs.
export const meta = {
  name: 'round7-memory',
  description: 'Merge moves-types into r7-integrate, find where the boot-time main arena can be won back, fix it with a held margin, verify boots, battles and gyms',
  phases: [
    { title: 'Merge', detail: 'moves-types onto r7-integrate with the renumbering map.txt prescribes' },
    { title: 'Investigate', detail: 'heap use by scene; the arena at boot and what fills it; how hg-engine fits its code' },
    { title: 'Budget', detail: 'pick the safest way to win room back, implement it, hold the margin in a test' },
    { title: 'Verify', detail: 'many boots of every ROM, battles, heaps, the gyms, the full suite' },
  ],
}

// Where things were on the machine these ran on; set them for yours.
const HOME_ = '/home/paolo'
const TREE = `${HOME_}/hgss-newgold`                     // the main tree, branch newgold
const WORKTREES = `${HOME_}/hgss-worktrees`              // one git worktree per agent
const ROUNDS = `${WORKTREES}/.rounds`                    // rows, reports, scratch: on disk, never /tmp
const MEMORY = `${HOME_}/.claude/projects/-home-paolo-Porting-HGSS/memory`
const ENV = `${HOME_}/hgss-build/env.sh`                 // the project's own wine
const SAVES = `${HOME_}/hgss-saves`                      // Paolo's saves: scratch copies only
const REF = `${HOME_}/Porting HGSS/hg-engine-newgold-reference`
const CAPPED = `${TREE}/tools/newgold/devkit/capped`     // every heavy command runs under it
const MERGE_TOOLS = `${TREE}/tools/newgold/rounds`
const WT = `${WORKTREES}/extra1`
const R = `${ROUNDS}`
const CONTEXT = `
PROJECT: ${TREE} is pokeheartgold (HeartGold decompilation) with hg-engine (engine layer, reference revision d0380a487) and konefr's New Gold (reference revision 1fa3c9366) ported into it as a real decompilation. Reference repository: ${REF}, read ONLY via git at d0380a487 or 1fa3c9366 ('git -C "${REF}" show d0380a487:<path>'); never hg-engine upstream. Round 7's eight other branches are integrated on branch r7-integrate in the worktree ${WT} (tip 75ecf39d1); ${R}/round7/map.txt is its old->new map and ends with the instructions for merging moves-types; ${R}/round7/results.json has every agent's report (moves-types' is under 'round6:moves-types', its 'found' has the memory analysis). Read ${MEMORY}/hgss-merging-parallel-rounds.md, hgss-build-needs-project-wine.md, hgss-diagnostics-are-a-compile-time-folder.md, hgss-harness-core-raises-no-data-abort.md and hgss-assembly-is-not-a-reason-to-stop.md first; merge tools are in ${MERGE_TOOLS}.

THE PROBLEM: the main arena starts where the last overlay of the chain main->0->6->7->12 ends (overlay 12 is the battle); at boot Heap_InitSystem (src/heap.c, from sub_0201A1B4 in src/system.c: sDefaultHeapSpec 0xD200, 0x30600, 0x10, 0x11D000 plus a random 0..0xFC) takes the heaps from its low end, then the task queues and FS_TryLoadTable's table (0x1B5E) follow; if the arena runs out the pointer is NULL, GF_ASSERT is gated off and the game stays on a white screen. newgold's tip had 0x15CC to spare at boot; the eight merged branches left 0x72C (overlay 12's end +0xF20); moves-types alone moved it +0x1440 (after shrinking its own commits) leaving at worst 0x14C on its own base -- together they cannot boot. The NEWGOLD_DIAG=1 build puts 0x1420 more in the static module and overlay 12 and already takes 0x2000 back from the default heap (r7-integrate's 7415c10f2, measured: the default heap's low water 0xBCFC of 0xD200 through a cold boot, the opening and two wild battles). An earlier change grew heap 1 by 0xD000 for thirty boxes, taking it from the arena, which was measured with 0x1D880 to spare WITH THE GAME RUNNING (tests/newgold/test_heaps.py holds that margin) -- the boot-time margin and the running margin are different numbers; know why. test_boot (tests/newgold) boots the ROMs and is the only check that catches a white screen. Six moves are still to come (the three Pledges, Ally Switch, Sky Drop, Revival Blessing) and will need room in overlay 12 too.

RULES: work only in ${WT} (Merge and Budget stages) -- never touch ${TREE}'s working tree, never merge into newgold, never push. Investigate and Verify stages are read-only on the branch (builds and scratch copies are fine). Build ALWAYS as '. ${ENV} && make -j16 COMPARE=0 <targets>' in ${WT} ('GAME_VERSION=SOULSILVER', 'NEWGOLD_DIAG=1'); build the ROM targets directly. /tmp is almost full (a RAM disk): put logs, dumps and scratch files under ${R}/round7/tmp/ and run tests with TMPDIR=${R}/round7/tmp (test_saveui's fake-ROM test needs the real /tmp; ignore that one failure under this TMPDIR). Never 'pkill -f' a pattern in your own command line. Commits: short lowercase subject 'area: ...', plain prose body (what and why, with the numbers measured), last line 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>'.`

phase('Merge')
const merged = await agent(`${CONTEXT}

YOUR JOB: merge branch r7-moves-types (worktree ${WORKTREES}/moves-types, 51 commits from b64faa566; read-only) into r7-integrate in ${WT}, following map.txt's instructions (its 20 subscripts 439-458 shift by 2 -- use shift_branch.py, whose bug with reference-owned numbers the integrator fixed; the post-move switch renumbered by hand: Steel Beam/Mind Blown step 11, Emergency Exit 12, U-turn 13, end 14; the bitfields unk0_A:12 and unk0_11:14; BattleContext's size measured with mwcc, never added). Resolve every conflict so both sides' behaviour survives; recompute the test lists (test_ability_effects, test_retail_effect_scripts, test_battle_mechanics, test_move_effects' implemented set). Then build HeartGold, SoulSilver and the diagnostics build and run the full suite (with the TMPDIR above). The ROMs are EXPECTED to fail test_boot until the next stage wins room back: record exactly how (white screen, which assert, the arena numbers from a dump) and do not try to fix it here. Append the moves-types lines to map.txt. Report: conflicts and resolutions, the numbers, the build results, the tests (which fail and why), the boot state with its arena numbers, the new tip.`, { label: 'merge:moves-types', phase: 'Merge' })

phase('Investigate')
const LENSES = [
  { key: 'heaps', prompt: `LENS: HOW MUCH OF EACH BOOT HEAP IS EVER USED. With the diagnostics build (its heap low-water markers: gDiagHeapLowWater and 'least left' in markers.describe) measure the low water of each of the four boot heaps -- and of the arena itself while running -- across as many kinds of scene as the harness can reach: cold boot and the opening, the overworld and map changes, the start menu, bag, party, summary, PC (moving Pokemon), Pokedex (list, grid, entry, search), Pokegear, trainer card, saving, a wild battle, a trainer battle, a double battle, an evolution, a catch, the Day-Care, the Bug-Catching Contest if reachable, the Union Room / wireless menus if reachable. Use the tools in tools/newgold/devkit/diag and harness (battle.py, gym.py with scratch copies of ${SAVES}/gyms saves, the species check tools/newgold/devkit/diag/species.py). Grep who allocates from each heap id (HEAP_ID_* and the numbers) to find the scenes that could use the most that the harness cannot reach (Wi-Fi, GTS, Battle Frontier, Pokeathlon, link trades) and estimate their need from the code. Report a table heap x scene of low water, the worst case, and how much each heap could give up with a safety margin you justify. Build the diagnostics ROM from the r7-integrate tip AFTER the merge if it boots; if it does not, from 75ecf39d1 (which boots) -- say which.` },
  { key: 'arena', prompt: `LENS: WHERE THE BOOT-TIME ARENA GOES, AND WHAT CAN MOVE OUT OF IT. From the linker output (the .xMAP / map files of the build, the LCF) and a RAM dump at boot (arena lo/hi at 0x027FFDA0), account for the main arena at boot byte by byte: where each overlay of the chain main->0->6->7->12 ends, the heaps, the random pre-size, the task queues, the FS table and anything else, and why the running margin (0x1D880) differs from the boot margin. Then list what could give room back WITHOUT changing the game's behaviour, each with its size: New Gold / engine code or read-only tables in overlay 12 or the static module that could live in a file loaded into the battle's own heap instead, or in another overlay that is never loaded at the same time (check the overlay groups and addresses: which regions are free while a battle runs), dead code the port left, data duplicated between overlays, debug-only code in the ordinary build, whether the FS table or task queues could come from a heap after it exists, whether any heap is created bigger than its users ever ask. Give the growth of overlay 12 and the static module since b64faa566 and since retail by object file and by function (from the map files).` },
  { key: 'engine', prompt: `LENS: HOW HG-ENGINE FITS ITS CODE. In the reference at d0380a487 (hg-engine, the engine layer this port follows), find how hg-engine makes room for its battle and field code: its synthetic overlays, their load addresses (e.g. anything at 0x023C8000 or other regions), what it changes in the arena, the heaps (their sizes vs retail's 0xD200/0x30600/0x10/0x11D000), the overlay table or the LCF, and what konefr changed of it at 1fa3c9366. Explain the memory map hg-engine's ROM runs with, compared with this port's (read this port's LCF / linker spec and src/system.c), and whether this port could adopt the same arrangement the layered way (an engine-layer commit that reproduces hg-engine's memory decisions, as the port does elsewhere) -- with the concrete steps and risks for a decompilation that must keep retail's own code matching.` },
]
const found = await parallel(LENSES.map(l => () => agent(`${CONTEXT}\n\nThe merge stage's report:\n${merged}\n\n${l.prompt}\n\nRead-only: no commits on r7-integrate. Report your evidence (numbers, addresses, file:line) and your recommendation.`, { label: `investigate:${l.key}`, phase: 'Investigate' })))

phase('Budget')
const budget = await agent(`${CONTEXT}\n\nMerge report:\n${merged}\n\nThe three investigations:\n${found.map((f, i) => `=== ${LENSES[i].key}\n${f}`).join('\n\n')}\n\nYOUR JOB: choose how to win the boot-time arena back, by these criteria in order: (1) the game behaves as before in every scene (no heap may run short anywhere the investigations measured or estimated -- a heap is only shrunk by less than its measured and estimated slack, with a margin you state); (2) it is what the engine layer does, if hg-engine has an arrangement the port can reproduce soundly; (3) enough room for the six moves still to come plus future growth (aim for at least 0x4000 of boot-time margin in the ordinary build and a positive one in the diagnostics build); (4) the smallest change. Implement it on r7-integrate in ${WT} in commits of one thing each (an engine-layer commit if it follows hg-engine), keep the diagnostics build's own adjustment consistent, and add or extend a test (tests/newgold/test_heaps.py or test_boot) that holds the boot-time margin from the build's map so the next growth fails a test instead of the screen. Build the three ROMs; run test_boot many times (the random pre-size varies: at least 20 boots of each ROM, recording the worst margin), a forced wild battle and a trainer battle on the diagnostics build with no assertion and no failed allocation, and the full suite. Report the choice and why, the commits, the margins measured, and anything you did not do.`, { label: 'budget', phase: 'Budget' })

phase('Verify')
const verify = await agent(`${CONTEXT}\n\nThe budget stage's report:\n${budget}\n\nYOUR JOB, adversarially and read-only on the branch (build in ${WT} is fine, commit nothing): (1) rebuild the three ROMs from the r7-integrate tip and boot each at least 30 times with the harness, recording the worst arena margin and any white screen; (2) check every heap the change touched against the investigations' worst cases -- find a scene the budget stage did not consider that uses more (grep the allocators); (3) on the diagnostics build, run battle.py's forced encounter and random encounters, gym.py on scratch copies of ${SAVES}/gyms/falkner.sav, bugsy.sav, whitney.sav and morty.sav: every badge must be won with no assertion and no failed allocation (report the lines that show it; if a gym is lost, say whether it is the fight's luck or a defect, with evidence); (4) the full suite with the TMPDIR above; (5) the new margin test fails if overlay 12 grows past the margin (prove it on a scratch copy). Report findings marked critical/high/medium/low with evidence, or 'none'.`, { label: 'verify', phase: 'Verify' })

return { merged, found, budget, verify }
