#include "pokedex.h"

#include "global.h"

#include "constants/johto_dex.h"
#include "constants/species.h"

#include "pokemon.h"
#include "unk_02091278.h"

#define POKEDEX_MAGIC (0xBEEFCAFE)
#define ASSERT_POKEDEX(pokedex)                       \
    do {                                              \
        GF_ASSERT((pokedex)->magic == POKEDEX_MAGIC); \
    } while (0)

static void Pokedex_InitDeoxysFormOrder(Pokedex *pokedex);
u16 *LoadSpeciesToJohtoDexNoLUT(void);
void Pokedex_SetInternationalViewFlag(Pokedex *pokedex);

u32 Save_Pokedex_sizeof(void) {
    return sizeof(Pokedex);
}

Pokedex *Pokedex_New(enum HeapID heapID) {
    Pokedex *ret = Heap_Alloc(heapID, sizeof(Pokedex));
    Save_Pokedex_Init(ret);
    return ret;
}

void Pokedex_Copy(const Pokedex *src, Pokedex *dest) {
    MI_CpuCopy8(src, dest, sizeof(Pokedex));
}

BOOL DexSpeciesIsInvalid(u16 species) {
    if (species == SPECIES_NONE || species > NUM_SPECIES) {
        GF_ASSERT(FALSE);
        return TRUE;
    }

    // The identifiers between Arceus and the species New Gold adds are the
    // egg and the alternate forms. They have no Dex entry, and meeting one is
    // not an error either, so this must not reach the assertion above, which
    // resets the game.
    // The same goes for the forms after the last Dex species, which have no
    // entry of their own: SpeciesToDexSpecies sends them to their base's.
    return (species >= FIRST_DEX_GAP && species <= LAST_DEX_GAP) || species > NATIONAL_DEX_COUNT;
}

// Each form's base species, which is the Dex entry the form counts for.
// Written by tools/newgold/import/import_species.py from the reference's form
// table; do not edit it by hand.
static const u16 sFormBaseSpecies[NUM_SPECIES - NATIONAL_DEX_COUNT] = {
    [SPECIES_MEGA_VENUSAUR - NATIONAL_DEX_COUNT - 1] = SPECIES_VENUSAUR,
    [SPECIES_MEGA_CHARIZARD_X - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_MEGA_CHARIZARD_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_MEGA_BLASTOISE - NATIONAL_DEX_COUNT - 1] = SPECIES_BLASTOISE,
    [SPECIES_MEGA_BEEDRILL - NATIONAL_DEX_COUNT - 1] = SPECIES_BEEDRILL,
    [SPECIES_MEGA_PIDGEOT - NATIONAL_DEX_COUNT - 1] = SPECIES_PIDGEOT,
    [SPECIES_MEGA_ALAKAZAM - NATIONAL_DEX_COUNT - 1] = SPECIES_ALAKAZAM,
    [SPECIES_MEGA_SLOWBRO - NATIONAL_DEX_COUNT - 1] = SPECIES_SLOWBRO,
    [SPECIES_MEGA_GENGAR - NATIONAL_DEX_COUNT - 1] = SPECIES_GENGAR,
    [SPECIES_MEGA_KANGASKHAN - NATIONAL_DEX_COUNT - 1] = SPECIES_KANGASKHAN,
    [SPECIES_MEGA_PINSIR - NATIONAL_DEX_COUNT - 1] = SPECIES_PINSIR,
    [SPECIES_MEGA_GYARADOS - NATIONAL_DEX_COUNT - 1] = SPECIES_GYARADOS,
    [SPECIES_MEGA_AERODACTYL - NATIONAL_DEX_COUNT - 1] = SPECIES_AERODACTYL,
    [SPECIES_MEGA_MEWTWO_X - NATIONAL_DEX_COUNT - 1] = SPECIES_MEWTWO,
    [SPECIES_MEGA_MEWTWO_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_MEWTWO,
    [SPECIES_MEGA_AMPHAROS - NATIONAL_DEX_COUNT - 1] = SPECIES_AMPHAROS,
    [SPECIES_MEGA_STEELIX - NATIONAL_DEX_COUNT - 1] = SPECIES_STEELIX,
    [SPECIES_MEGA_SCIZOR - NATIONAL_DEX_COUNT - 1] = SPECIES_SCIZOR,
    [SPECIES_MEGA_HERACROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_HERACROSS,
    [SPECIES_MEGA_HOUNDOOM - NATIONAL_DEX_COUNT - 1] = SPECIES_HOUNDOOM,
    [SPECIES_MEGA_TYRANITAR - NATIONAL_DEX_COUNT - 1] = SPECIES_TYRANITAR,
    [SPECIES_MEGA_SCEPTILE - NATIONAL_DEX_COUNT - 1] = SPECIES_SCEPTILE,
    [SPECIES_MEGA_BLAZIKEN - NATIONAL_DEX_COUNT - 1] = SPECIES_BLAZIKEN,
    [SPECIES_MEGA_SWAMPERT - NATIONAL_DEX_COUNT - 1] = SPECIES_SWAMPERT,
    [SPECIES_MEGA_GARDEVOIR - NATIONAL_DEX_COUNT - 1] = SPECIES_GARDEVOIR,
    [SPECIES_MEGA_SABLEYE - NATIONAL_DEX_COUNT - 1] = SPECIES_SABLEYE,
    [SPECIES_MEGA_MAWILE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAWILE,
    [SPECIES_MEGA_AGGRON - NATIONAL_DEX_COUNT - 1] = SPECIES_AGGRON,
    [SPECIES_MEGA_MEDICHAM - NATIONAL_DEX_COUNT - 1] = SPECIES_MEDICHAM,
    [SPECIES_MEGA_MANECTRIC - NATIONAL_DEX_COUNT - 1] = SPECIES_MANECTRIC,
    [SPECIES_MEGA_SHARPEDO - NATIONAL_DEX_COUNT - 1] = SPECIES_SHARPEDO,
    [SPECIES_MEGA_CAMERUPT - NATIONAL_DEX_COUNT - 1] = SPECIES_CAMERUPT,
    [SPECIES_MEGA_ALTARIA - NATIONAL_DEX_COUNT - 1] = SPECIES_ALTARIA,
    [SPECIES_MEGA_BANETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_BANETTE,
    [SPECIES_MEGA_ABSOL - NATIONAL_DEX_COUNT - 1] = SPECIES_ABSOL,
    [SPECIES_MEGA_GLALIE - NATIONAL_DEX_COUNT - 1] = SPECIES_GLALIE,
    [SPECIES_MEGA_SALAMENCE - NATIONAL_DEX_COUNT - 1] = SPECIES_SALAMENCE,
    [SPECIES_MEGA_METAGROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_METAGROSS,
    [SPECIES_MEGA_LATIAS - NATIONAL_DEX_COUNT - 1] = SPECIES_LATIAS,
    [SPECIES_MEGA_LATIOS - NATIONAL_DEX_COUNT - 1] = SPECIES_LATIOS,
    [SPECIES_MEGA_RAYQUAZA - NATIONAL_DEX_COUNT - 1] = SPECIES_RAYQUAZA,
    [SPECIES_MEGA_LOPUNNY - NATIONAL_DEX_COUNT - 1] = SPECIES_LOPUNNY,
    [SPECIES_MEGA_GARCHOMP - NATIONAL_DEX_COUNT - 1] = SPECIES_GARCHOMP,
    [SPECIES_MEGA_LUCARIO - NATIONAL_DEX_COUNT - 1] = SPECIES_LUCARIO,
    [SPECIES_MEGA_ABOMASNOW - NATIONAL_DEX_COUNT - 1] = SPECIES_ABOMASNOW,
    [SPECIES_MEGA_GALLADE - NATIONAL_DEX_COUNT - 1] = SPECIES_GALLADE,
    [SPECIES_MEGA_AUDINO - NATIONAL_DEX_COUNT - 1] = SPECIES_AUDINO,
    [SPECIES_MEGA_DIANCIE - NATIONAL_DEX_COUNT - 1] = SPECIES_DIANCIE,
    [SPECIES_KYOGRE_PRIMAL - NATIONAL_DEX_COUNT - 1] = SPECIES_KYOGRE,
    [SPECIES_GROUDON_PRIMAL - NATIONAL_DEX_COUNT - 1] = SPECIES_GROUDON,
    [SPECIES_RATTATA_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RATTATA,
    [SPECIES_RATICATE_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RATICATE,
    [SPECIES_RAICHU_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_SANDSHREW_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDSHREW,
    [SPECIES_SANDSLASH_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDSLASH,
    [SPECIES_VULPIX_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VULPIX,
    [SPECIES_NINETALES_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_NINETALES,
    [SPECIES_DIGLETT_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DIGLETT,
    [SPECIES_DUGTRIO_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DUGTRIO,
    [SPECIES_MEOWTH_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_PERSIAN_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_PERSIAN,
    [SPECIES_GEODUDE_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GEODUDE,
    [SPECIES_GRAVELER_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GRAVELER,
    [SPECIES_GOLEM_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLEM,
    [SPECIES_GRIMER_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GRIMER,
    [SPECIES_MUK_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MUK,
    [SPECIES_EXEGGUTOR_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_EXEGGUTOR,
    [SPECIES_MAROWAK_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MAROWAK,
    [SPECIES_RATICATE_ALOLAN_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_RATICATE,
    [SPECIES_MAROWAK_ALOLAN_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAROWAK,
    [SPECIES_GUMSHOOS_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_GUMSHOOS,
    [SPECIES_VIKAVOLT_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIKAVOLT,
    [SPECIES_RIBOMBEE_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_RIBOMBEE,
    [SPECIES_ARAQUANID_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_ARAQUANID,
    [SPECIES_LURANTIS_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_LURANTIS,
    [SPECIES_SALAZZLE_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SALAZZLE,
    [SPECIES_TOGEDEMARU_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_TOGEDEMARU,
    [SPECIES_MIMIKYU_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_MIMIKYU_BUSTED_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_KOMMO_O_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_KOMMO_O,
    [SPECIES_MEOWTH_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_PONYTA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_PONYTA,
    [SPECIES_RAPIDASH_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RAPIDASH,
    [SPECIES_FARFETCHD_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_FARFETCHD,
    [SPECIES_WEEZING_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_WEEZING,
    [SPECIES_MR_MIME_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MR_MIME,
    [SPECIES_ARTICUNO_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ARTICUNO,
    [SPECIES_ZAPDOS_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZAPDOS,
    [SPECIES_MOLTRES_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MOLTRES,
    [SPECIES_SLOWKING_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SLOWKING,
    [SPECIES_CORSOLA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_CORSOLA,
    [SPECIES_ZIGZAGOON_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZIGZAGOON,
    [SPECIES_LINOONE_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LINOONE,
    [SPECIES_DARUMAKA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARUMAKA,
    [SPECIES_DARMANITAN_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_YAMASK_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_YAMASK,
    [SPECIES_STUNFISK_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_STUNFISK,
    [SPECIES_PIKACHU_COSPLAY - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ROCK_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_BELLE - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_POP_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_PH_D - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_LIBRE - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ORIGINAL_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_HOENN_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_SINNOH_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_UNOVA_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_KALOS_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ALOLA_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_PARTNER_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_WORLD_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_CASTFORM_SUNNY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CASTFORM_RAINY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CASTFORM_SNOWY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CHERRIM_SUNSHINE - NATIONAL_DEX_COUNT - 1] = SPECIES_CHERRIM,
    [SPECIES_SHELLOS_EAST_SEA - NATIONAL_DEX_COUNT - 1] = SPECIES_SHELLOS,
    [SPECIES_GASTRODON_EAST_SEA - NATIONAL_DEX_COUNT - 1] = SPECIES_GASTRODON,
    [SPECIES_DIALGA_ORIGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_DIALGA,
    [SPECIES_PALKIA_ORIGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_PALKIA,
    [SPECIES_BASCULIN_BLUE_STRIPED - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULIN,
    [SPECIES_BASCULIN_WHITE_STRIPED - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULIN,
    [SPECIES_DARMANITAN_ZEN_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_DARMANITAN_ZEN_MODE_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_DEERLING_SUMMER - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_DEERLING_AUTUMN - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_DEERLING_WINTER - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_SAWSBUCK_SUMMER - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_SAWSBUCK_AUTUMN - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_SAWSBUCK_WINTER - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_TORNADUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_TORNADUS,
    [SPECIES_THUNDURUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_THUNDURUS,
    [SPECIES_LANDORUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LANDORUS,
    [SPECIES_KYUREM_WHITE - NATIONAL_DEX_COUNT - 1] = SPECIES_KYUREM,
    [SPECIES_KYUREM_BLACK - NATIONAL_DEX_COUNT - 1] = SPECIES_KYUREM,
    [SPECIES_KELDEO_RESOLUTE - NATIONAL_DEX_COUNT - 1] = SPECIES_KELDEO,
    [SPECIES_MELOETTA_PIROUETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_MELOETTA,
    [SPECIES_GENESECT_DOUSE_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_SHOCK_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_BURN_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_CHILL_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GRENINJA_BATTLE_BOND - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_GRENINJA_ASH - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_VIVILLON_POLAR - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_TUNDRA - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_CONTINENTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_GARDEN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_ELEGANT - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MEADOW - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MODERN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MARINE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_ARCHIPELAGO - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_HIGH_PLAINS - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SANDSTORM - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_RIVER - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MONSOON - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SAVANNA - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SUN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_OCEAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_JUNGLE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_FANCY - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_POKE_BALL - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_FLABEBE_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLOETTE_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_ETERNAL_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLORGES_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FURFROU_HEART - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DIAMOND - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DEBUTANTE - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_MATRON - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DANDY - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_LA_REINE - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_KABUKI - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_PHARAOH - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_AEGISLASH_BLADE - NATIONAL_DEX_COUNT - 1] = SPECIES_AEGISLASH,
    [SPECIES_PUMPKABOO_SMALL - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_PUMPKABOO_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_PUMPKABOO_SUPER - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_GOURGEIST_SMALL - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_GOURGEIST_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_GOURGEIST_SUPER - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_XERNEAS_ACTIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_XERNEAS,
    [SPECIES_ZYGARDE_10 - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_10_POWER_CONSTRUCT - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_50_POWER_CONSTRUCT - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_10_COMPLETE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_50_COMPLETE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_HOOPA_UNBOUND - NATIONAL_DEX_COUNT - 1] = SPECIES_HOOPA,
    [SPECIES_ORICORIO_POM_POM - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ORICORIO_PAU - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ORICORIO_SENSU - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ROCKRUFF_OWN_TEMPO - NATIONAL_DEX_COUNT - 1] = SPECIES_ROCKRUFF,
    [SPECIES_LYCANROC_MIDNIGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_LYCANROC,
    [SPECIES_LYCANROC_DUSK - NATIONAL_DEX_COUNT - 1] = SPECIES_LYCANROC,
    [SPECIES_WISHIWASHI_SCHOOL - NATIONAL_DEX_COUNT - 1] = SPECIES_WISHIWASHI,
    [SPECIES_MINIOR_METEOR_ORANGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_YELLOW - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_GREEN - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_BLUE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_INDIGO - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_VIOLET - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_RED - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_ORANGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_YELLOW - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_GREEN - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_BLUE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_INDIGO - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_VIOLET - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MIMIKYU_BUSTED - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_NECROZMA_DUSK_MANE - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_DAWN_WINGS - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_ULTRA_DUSK_MANE - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_ULTRA_DAWN_WINGS - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_MAGEARNA_ORIGINAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_PIKACHU_PARTNER - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_EEVEE_PARTNER - NATIONAL_DEX_COUNT - 1] = SPECIES_EEVEE,
    [SPECIES_CRAMORANT_GULPING - NATIONAL_DEX_COUNT - 1] = SPECIES_CRAMORANT,
    [SPECIES_CRAMORANT_GORGING - NATIONAL_DEX_COUNT - 1] = SPECIES_CRAMORANT,
    [SPECIES_TOXTRICITY_LOW_KEY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_SINISTEA_ANTIQUE - NATIONAL_DEX_COUNT - 1] = SPECIES_SINISTEA,
    [SPECIES_POLTEAGEIST_ANTIQUE - NATIONAL_DEX_COUNT - 1] = SPECIES_POLTEAGEIST,
    [SPECIES_ALCREMIE_BERRY_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_LOVE_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_STAR_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_CLOVER_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_FLOWER_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_RIBBON_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_EISCUE_NOICE_FACE - NATIONAL_DEX_COUNT - 1] = SPECIES_EISCUE,
    [SPECIES_MORPEKO_HANGRY - NATIONAL_DEX_COUNT - 1] = SPECIES_MORPEKO,
    [SPECIES_ZACIAN_CROWNED - NATIONAL_DEX_COUNT - 1] = SPECIES_ZACIAN,
    [SPECIES_ZAMAZENTA_CROWNED - NATIONAL_DEX_COUNT - 1] = SPECIES_ZAMAZENTA,
    [SPECIES_ETERNATUS_ETERNAMAX - NATIONAL_DEX_COUNT - 1] = SPECIES_ETERNATUS,
    [SPECIES_URSHIFU_RAPID_STRIKE - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_ZARUDE_DADA - NATIONAL_DEX_COUNT - 1] = SPECIES_ZARUDE,
    [SPECIES_CALYREX_ICE_RIDER - NATIONAL_DEX_COUNT - 1] = SPECIES_CALYREX,
    [SPECIES_CALYREX_SHADOW_RIDER - NATIONAL_DEX_COUNT - 1] = SPECIES_CALYREX,
    [SPECIES_ENAMORUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ENAMORUS,
    [SPECIES_GROWLITHE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GROWLITHE,
    [SPECIES_ARCANINE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ARCANINE,
    [SPECIES_VOLTORB_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VOLTORB,
    [SPECIES_ELECTRODE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ELECTRODE,
    [SPECIES_TYPHLOSION_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_TYPHLOSION,
    [SPECIES_QWILFISH_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_QWILFISH,
    [SPECIES_SNEASEL_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SNEASEL,
    [SPECIES_SAMUROTT_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SAMUROTT,
    [SPECIES_LILLIGANT_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LILLIGANT,
    [SPECIES_ZORUA_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZORUA,
    [SPECIES_ZOROARK_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZOROARK,
    [SPECIES_BRAVIARY_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_BRAVIARY,
    [SPECIES_SLIGGOO_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SLIGGOO,
    [SPECIES_GOODRA_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GOODRA,
    [SPECIES_AVALUGG_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_AVALUGG,
    [SPECIES_DECIDUEYE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DECIDUEYE,
    [SPECIES_KLEAVOR_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_KLEAVOR,
    [SPECIES_LILLIGANT_LADY - NATIONAL_DEX_COUNT - 1] = SPECIES_LILLIGANT,
    [SPECIES_ARCANINE_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_ARCANINE,
    [SPECIES_ELECTRODE_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_ELECTRODE,
    [SPECIES_AVALUGG_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_AVALUGG,
    [SPECIES_UNFEZANT_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_UNFEZANT,
    [SPECIES_FRILLISH_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_FRILLISH,
    [SPECIES_JELLICENT_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_JELLICENT,
    [SPECIES_PYROAR_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_PYROAR,
    [SPECIES_MEOWSTIC_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_INDEEDEE_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_INDEEDEE,
    [SPECIES_BASCULEGION_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULEGION,
    [SPECIES_MAUSHOLD_FAMILY_OF_THREE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAUSHOLD,
    [SPECIES_SQUAWKABILLY_BLUE_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_SQUAWKABILLY_WHITE_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_PALAFIN_HERO - NATIONAL_DEX_COUNT - 1] = SPECIES_PALAFIN,
    [SPECIES_TATSUGIRI_DROOPY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_TATSUGIRI_STRETCHY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_DUDUNSPARCE_THREE_SEGMENT - NATIONAL_DEX_COUNT - 1] = SPECIES_DUDUNSPARCE,
    [SPECIES_GIMMIGHOUL_ROAMING - NATIONAL_DEX_COUNT - 1] = SPECIES_GIMMIGHOUL,
    [SPECIES_WOOPER_PALDEAN - NATIONAL_DEX_COUNT - 1] = SPECIES_WOOPER,
    [SPECIES_TAUROS_COMBAT - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_TAUROS_BLAZE - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_TAUROS_AQUA - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_OINKOLOGNE_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_OINKOLOGNE,
    [SPECIES_REVAVROOM_SEGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_SCHEDAR - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_NAVI - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_RUCHBAH - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_CAPH - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_KORAIDON_LIMITED_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_SPRINTING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_SWIMMING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_GLIDING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_MIRAIDON_LOW_POWER_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_DRIVE_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_AQUATIC_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_GLIDE_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_POLTCHAGEIST_MASTERPIECE - NATIONAL_DEX_COUNT - 1] = SPECIES_POLTCHAGEIST,
    [SPECIES_SINISTCHA_MASTERPIECE - NATIONAL_DEX_COUNT - 1] = SPECIES_SINISTCHA,
    [SPECIES_OGERPON_WELLSPRING_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_HEARTHFLAME_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_CORNERSTONE_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_TEAL_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_WELLSPRING_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_HEARTHFLAME_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_CORNERSTONE_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_URSALUNA_BLOODMOON - NATIONAL_DEX_COUNT - 1] = SPECIES_URSALUNA,
    [SPECIES_TERAPAGOS_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_TERAPAGOS,
    [SPECIES_TERAPAGOS_STELLAR - NATIONAL_DEX_COUNT - 1] = SPECIES_TERAPAGOS,
    [SPECIES_GIGANTAMAX_VENUSAUR - NATIONAL_DEX_COUNT - 1] = SPECIES_VENUSAUR,
    [SPECIES_GIGANTAMAX_CHARIZARD - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_GIGANTAMAX_BLASTOISE - NATIONAL_DEX_COUNT - 1] = SPECIES_BLASTOISE,
    [SPECIES_GIGANTAMAX_BUTTERFREE - NATIONAL_DEX_COUNT - 1] = SPECIES_BUTTERFREE,
    [SPECIES_GIGANTAMAX_PIKACHU - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_GIGANTAMAX_MEOWTH - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_GIGANTAMAX_MACHAMP - NATIONAL_DEX_COUNT - 1] = SPECIES_MACHAMP,
    [SPECIES_GIGANTAMAX_GENGAR - NATIONAL_DEX_COUNT - 1] = SPECIES_GENGAR,
    [SPECIES_GIGANTAMAX_KINGLER - NATIONAL_DEX_COUNT - 1] = SPECIES_KINGLER,
    [SPECIES_GIGANTAMAX_LAPRAS - NATIONAL_DEX_COUNT - 1] = SPECIES_LAPRAS,
    [SPECIES_GIGANTAMAX_EEVEE - NATIONAL_DEX_COUNT - 1] = SPECIES_EEVEE,
    [SPECIES_GIGANTAMAX_SNORLAX - NATIONAL_DEX_COUNT - 1] = SPECIES_SNORLAX,
    [SPECIES_GIGANTAMAX_GARBODOR - NATIONAL_DEX_COUNT - 1] = SPECIES_GARBODOR,
    [SPECIES_GIGANTAMAX_MELMETAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MELMETAL,
    [SPECIES_GIGANTAMAX_RILLABOOM - NATIONAL_DEX_COUNT - 1] = SPECIES_RILLABOOM,
    [SPECIES_GIGANTAMAX_CINDERACE - NATIONAL_DEX_COUNT - 1] = SPECIES_CINDERACE,
    [SPECIES_GIGANTAMAX_INTELEON - NATIONAL_DEX_COUNT - 1] = SPECIES_INTELEON,
    [SPECIES_GIGANTAMAX_CORVIKNIGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_CORVIKNIGHT,
    [SPECIES_GIGANTAMAX_ORBEETLE - NATIONAL_DEX_COUNT - 1] = SPECIES_ORBEETLE,
    [SPECIES_GIGANTAMAX_DREDNAW - NATIONAL_DEX_COUNT - 1] = SPECIES_DREDNAW,
    [SPECIES_GIGANTAMAX_COALOSSAL - NATIONAL_DEX_COUNT - 1] = SPECIES_COALOSSAL,
    [SPECIES_GIGANTAMAX_FLAPPLE - NATIONAL_DEX_COUNT - 1] = SPECIES_FLAPPLE,
    [SPECIES_GIGANTAMAX_APPLETUN - NATIONAL_DEX_COUNT - 1] = SPECIES_APPLETUN,
    [SPECIES_GIGANTAMAX_SANDACONDA - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDACONDA,
    [SPECIES_GIGANTAMAX_TOXTRICITY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_GIGANTAMAX_TOXTRICITY_LOW_KEY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_GIGANTAMAX_CENTISKORCH - NATIONAL_DEX_COUNT - 1] = SPECIES_CENTISKORCH,
    [SPECIES_GIGANTAMAX_HATTERENE - NATIONAL_DEX_COUNT - 1] = SPECIES_HATTERENE,
    [SPECIES_GIGANTAMAX_GRIMMSNARL - NATIONAL_DEX_COUNT - 1] = SPECIES_GRIMMSNARL,
    [SPECIES_GIGANTAMAX_ALCREMIE - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_GIGANTAMAX_COPPERAJAH - NATIONAL_DEX_COUNT - 1] = SPECIES_COPPERAJAH,
    [SPECIES_GIGANTAMAX_DURALUDON - NATIONAL_DEX_COUNT - 1] = SPECIES_DURALUDON,
    [SPECIES_GIGANTAMAX_URSHIFU - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_GIGANTAMAX_URSHIFU_RAPID_STRIKE - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_MEGA_RAICHU_X - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_MEGA_RAICHU_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_MEGA_CLEFABLE - NATIONAL_DEX_COUNT - 1] = SPECIES_CLEFABLE,
    [SPECIES_MEGA_VICTREEBEL - NATIONAL_DEX_COUNT - 1] = SPECIES_VICTREEBEL,
    [SPECIES_MEGA_STARMIE - NATIONAL_DEX_COUNT - 1] = SPECIES_STARMIE,
    [SPECIES_MEGA_DRAGONITE - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAGONITE,
    [SPECIES_MEGA_MEGANIUM - NATIONAL_DEX_COUNT - 1] = SPECIES_MEGANIUM,
    [SPECIES_MEGA_FERALIGATR - NATIONAL_DEX_COUNT - 1] = SPECIES_FERALIGATR,
    [SPECIES_MEGA_SKARMORY - NATIONAL_DEX_COUNT - 1] = SPECIES_SKARMORY,
    [SPECIES_MEGA_CHIMECHO - NATIONAL_DEX_COUNT - 1] = SPECIES_CHIMECHO,
    [SPECIES_MEGA_ABSOL_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_ABSOL,
    [SPECIES_MEGA_STARAPTOR - NATIONAL_DEX_COUNT - 1] = SPECIES_STARAPTOR,
    [SPECIES_MEGA_GARCHOMP_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_GARCHOMP,
    [SPECIES_MEGA_LUCARIO_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_LUCARIO,
    [SPECIES_MEGA_FROSLASS - NATIONAL_DEX_COUNT - 1] = SPECIES_FROSLASS,
    [SPECIES_MEGA_HEATRAN - NATIONAL_DEX_COUNT - 1] = SPECIES_HEATRAN,
    [SPECIES_MEGA_DARKRAI - NATIONAL_DEX_COUNT - 1] = SPECIES_DARKRAI,
    [SPECIES_MEGA_EMBOAR - NATIONAL_DEX_COUNT - 1] = SPECIES_EMBOAR,
    [SPECIES_MEGA_EXCADRILL - NATIONAL_DEX_COUNT - 1] = SPECIES_EXCADRILL,
    [SPECIES_MEGA_SCOLIPEDE - NATIONAL_DEX_COUNT - 1] = SPECIES_SCOLIPEDE,
    [SPECIES_MEGA_SCRAFTY - NATIONAL_DEX_COUNT - 1] = SPECIES_SCRAFTY,
    [SPECIES_MEGA_EELEKTROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_EELEKTROSS,
    [SPECIES_MEGA_CHANDELURE - NATIONAL_DEX_COUNT - 1] = SPECIES_CHANDELURE,
    [SPECIES_MEGA_GOLURK - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLURK,
    [SPECIES_MEGA_CHESNAUGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_CHESNAUGHT,
    [SPECIES_MEGA_DELPHOX - NATIONAL_DEX_COUNT - 1] = SPECIES_DELPHOX,
    [SPECIES_MEGA_GRENINJA - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_MEGA_PYROAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PYROAR,
    [SPECIES_MEGA_FLOETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_MEGA_MEOWSTIC - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_MEGA_MEOWSTIC_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_MEGA_MALAMAR - NATIONAL_DEX_COUNT - 1] = SPECIES_MALAMAR,
    [SPECIES_MEGA_BARBARACLE - NATIONAL_DEX_COUNT - 1] = SPECIES_BARBARACLE,
    [SPECIES_MEGA_DRAGALGE - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAGALGE,
    [SPECIES_MEGA_HAWLUCHA - NATIONAL_DEX_COUNT - 1] = SPECIES_HAWLUCHA,
    [SPECIES_MEGA_ZYGARDE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_MEGA_CRABOMINABLE - NATIONAL_DEX_COUNT - 1] = SPECIES_CRABOMINABLE,
    [SPECIES_MEGA_GOLISOPOD - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLISOPOD,
    [SPECIES_MEGA_DRAMPA - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAMPA,
    [SPECIES_MEGA_MAGEARNA - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_MEGA_MAGEARNA_ORIGINAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_MEGA_ZERAORA - NATIONAL_DEX_COUNT - 1] = SPECIES_ZERAORA,
    [SPECIES_MEGA_FALINKS - NATIONAL_DEX_COUNT - 1] = SPECIES_FALINKS,
    [SPECIES_MEGA_SCOVILLAIN - NATIONAL_DEX_COUNT - 1] = SPECIES_SCOVILLAIN,
    [SPECIES_MEGA_GLIMMORA - NATIONAL_DEX_COUNT - 1] = SPECIES_GLIMMORA,
    [SPECIES_MEGA_TATSUGIRI - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_TATSUGIRI_DROOPY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_TATSUGIRI_STRETCHY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_BAXCALIBUR - NATIONAL_DEX_COUNT - 1] = SPECIES_BAXCALIBUR,
};

// Every species past the last Dex species is a form here, a female Pyroar or
// a Mega Venusaur. hg-engine stores a form as its base species and a form
// number, so its Dex credits and numbers the base; this is how ours does.
u16 SpeciesToDexSpecies(u16 species) {
    if (species > NATIONAL_DEX_COUNT && species <= NUM_SPECIES) {
        return sFormBaseSpecies[species - NATIONAL_DEX_COUNT - 1];
    }
    return species;
}

static inline BOOL CheckDexFlag(const u8 *array, u16 flagId) {
    flagId--;
    return (array[flagId >> 3] & (1 << (flagId & 7))) != 0;
}

static inline void SetDexFlag(u8 *array, u16 flagId) {
    flagId--;
    array[flagId >> 3] |= (1 << (flagId & 7));
}

static inline void SetDexFlagState(u8 *array, u8 state, u16 flagId) {
    GF_ASSERT(state < 2);
    flagId--;
    array[flagId >> 3] &= ~(1 << (flagId & 7));
    array[flagId >> 3] |= (state << (flagId & 7));
}

static inline int CheckDex2Flag(const u8 *array, u16 _2flagId) {
    return (array[_2flagId >> 2] >> (2 * (_2flagId % 4u))) & 3;
}

static inline void SetDex2FlagState(u8 *array, u8 state, u16 _2flagId) {
    GF_ASSERT(state < 4);
    array[_2flagId >> 2] &= ~(3 << (2 * (_2flagId % 4u)));
    array[_2flagId >> 2] |= (state << (2 * (_2flagId % 4u)));
}

// Deoxys's form order lives in the top byte of the last flag word, which the
// + 8 in NUM_DEX_FLAG_WORDS keeps past the last Dex species. Retail wrote word
// 15, the last word at 493; with the Dex wider, word 15 holds real species.
static inline int CheckDex4Flag(u32 *flags, u8 idx) {
    return (flags[NUM_DEX_FLAG_WORDS - 1] >> (24 + 4 * idx)) & 15;
}

static inline void SetDex4Flag(u32 *flags, u8 form, u8 idx) {
    flags[NUM_DEX_FLAG_WORDS - 1] &= ~(15 << (24 + 4 * idx));
    flags[NUM_DEX_FLAG_WORDS - 1] |= (form << (24 + 4 * idx));
}

static inline int CheckDex3Flag(const u32 *arr, u32 idx) {
    return ((*arr) >> (3 * idx)) & 7;
}

static inline void SetDex3Flag(u32 *arr, u32 idx, u32 form) {
    GF_ASSERT(form < 7);
    *arr &= ~(7 << (3 * idx));
    *arr |= (form << (3 * idx));
}

static inline u8 CheckDexGender(const u8 *arr, u16 species) {
    if (CheckDexFlag(arr, species)) {
        return MON_FEMALE;
    } else {
        return MON_MALE;
    }
}

static void Pokedex_SetSeenGenderFlagInternal(Pokedex *pokeDex, u8 state, u8 num, u16 flagId) {
    if (num == 0) {
        SetDexFlagState((u8 *)pokeDex->seenGenders[1], state, flagId);
    }
    SetDexFlagState((u8 *)pokeDex->seenGenders[num], state, flagId);
}

static void Pokedex_SetSeenGenderFlag(Pokedex *pokeDex, u8 state, u8 num, u16 flagId) {
    GF_ASSERT(state <= 2);
    if (state == 2) {
        state = 0;
    }
    Pokedex_SetSeenGenderFlagInternal(pokeDex, state, num, flagId);
}

static u8 *Pokedex_GetFormOrderAddr(Pokedex *pokedex, u32 species) {
    switch (species) {
    case SPECIES_SHELLOS:
        return &pokedex->shellosFormOrder; // + 264;
    case SPECIES_GASTRODON:
        return &pokedex->gastrodonFormOrder; // + 265;
    case SPECIES_SHAYMIN:
        return &pokedex->shayminFormOrder; // + 828;
    case SPECIES_GIRATINA:
        return &pokedex->giratinaFormOrder; // + 829;
    case SPECIES_BURMY:
        return &pokedex->burmyFormOrder; // + 266;
    case SPECIES_WORMADAM:
        return &pokedex->wormadamFormOrder; // + 267;
    case SPECIES_PICHU:
        return &pokedex->pichuFormOrder; // + 830;
    default:
        GF_ASSERT(FALSE);
        return NULL;
    }
}

static int Pokedex_CountRegisteredUnownLetters(const Pokedex *pokedex, BOOL caught) {
    int i, j = 0;
    const u8 *arr;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    for (i = 0; i < UNOWN_FORM_MAX; i++, j++) {
        if (arr[i] == 0xFF) {
            break;
        }
    }
    return j;
}

static BOOL Pokedex_HasAlreadyAddedUnownLetter(const Pokedex *pokedex, u8 letter, BOOL caught) {
    int i;
    const u8 *arr;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    for (i = 0; i < UNOWN_FORM_MAX; i++) {
        if (arr[i] == letter) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_TryAppendUnownLetter(Pokedex *pokedex, int letter, BOOL caught) {
    u8 *arr;
    int idx;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    if (!Pokedex_HasAlreadyAddedUnownLetter(pokedex, letter, caught)) {
        idx = Pokedex_CountRegisteredUnownLetters(pokedex, caught);
        if (idx < UNOWN_FORM_MAX) {
            arr[idx] = letter;
        }
    }
}

static int Pokedex_GetSeenFormNum_2max(Pokedex *pokedex, u32 species) {
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    if (CheckDexFlag(flag_p, 1) == CheckDexFlag(flag_p, 2)) {
        return 1;
    } else {
        return 2;
    }
}

static BOOL Pokedex_CheckSeenForm_2max(Pokedex *pokedex, u32 species, u8 form) {
    u8 *flag_p;
    u32 n;
    int i;
    BOOL flag;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return FALSE;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    n = Pokedex_GetSeenFormNum_2max(pokedex, species);
    for (i = 0; i < n; i++) {
        flag = CheckDexFlag(flag_p, i + 1);
        if (flag == form) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenForm_2max(Pokedex *pokedex, u32 species, BOOL state) {
    int r4;
    u8 *r5;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckSeenForm_2max(pokedex, species, state)) {
        r5 = Pokedex_GetFormOrderAddr(pokedex, species);
        r4 = Pokedex_GetSeenFormNum_2max(pokedex, species);
        if (r4 < 2) {
            SetDexFlagState(r5, state, r4 + 1);
            if (r4 == 0) {
                SetDexFlagState(r5, state, r4 + 2);
            }
        }
    }
}

static int Pokedex_CountSeenForms_3max(Pokedex *pokedex, u32 species) {
    int i;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    for (i = 0; i < 3; i++) {
        if (CheckDex2Flag(flag_p, i) == 3) {
            break;
        }
    }
    return i;
}

static BOOL Pokedex_CheckSeenForm_3max(Pokedex *pokedex, u32 species, u8 state) {
    int i;
    u32 flag;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return FALSE;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    for (i = 0; i < 3; i++) {
        flag = CheckDex2Flag(flag_p, i);
        if (flag == state) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenForm_3max(Pokedex *pokedex, u32 species, u32 state) {
    int n;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckSeenForm_3max(pokedex, species, state)) {
        flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
        n = Pokedex_CountSeenForms_3max(pokedex, species);
        if (n < 3) {
            SetDex2FlagState(flag_p, state, n);
        }
    }
}

static void Pokedex_DeoxysFormFlagActionInternal(u32 *flags, u8 form, u8 idx) {
    SetDex4Flag(flags, form, idx);
}

static void Pokedex_DeoxysFormFlagAction(Pokedex *pokedex, u8 form, u8 idx) {
    GF_ASSERT(idx < 4);
    GF_ASSERT(form <= 15);
    if (idx < 2) {
        Pokedex_DeoxysFormFlagActionInternal(pokedex->caughtSpecies, form, idx);
    } else {
        Pokedex_DeoxysFormFlagActionInternal(pokedex->seenSpecies, form, idx - 2);
    }
}

static u32 Pokedex_GetSeenDeoxysFormByIndex(Pokedex *pokedex, u8 form) {
    if (form < 2) {
        return CheckDex4Flag(pokedex->caughtSpecies, form);
    } else {
        return CheckDex4Flag(pokedex->seenSpecies, form - 2);
    }
}

static int Pokedex_CountSeenDeoxysForms(Pokedex *pokedex) {
    int i;
    for (i = 0; i < 4; i++) {
        if (Pokedex_GetSeenDeoxysFormByIndex(pokedex, i) == 15) {
            break;
        }
    }
    return i;
}

static BOOL Pokedex_CheckSeenDeoxysForm(Pokedex *pokedex, u32 form) {
    int i;
    u32 val;
    for (i = 0; i < 4; i++) {
        val = Pokedex_GetSeenDeoxysFormByIndex(pokedex, i);
        if (form == val) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenDeoxysForm(Pokedex *pokedex, u16 species, Pokemon *mon) {
    u8 form;

    form = GetMonData(mon, MON_DATA_FORM, NULL);
    if (species == SPECIES_DEOXYS) {
        if (!Pokedex_CheckSeenDeoxysForm(pokedex, form)) {
            Pokedex_DeoxysFormFlagAction(pokedex, form, Pokedex_CountSeenDeoxysForms(pokedex));
        }
    }
}

static void Pokedex_InitDeoxysFormOrder(Pokedex *pokedex) {
    int i;
    for (i = 0; i < 4; i++) {
        Pokedex_DeoxysFormFlagAction(pokedex, 15, i);
    }
}

static int Pokedex_GetSeenFormNum_Rotom(const Pokedex *pokedex, u32 species) {
    int i, n;

    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    n = 0;
    for (i = 0; i < 6; i++, n++) {
        if (CheckDex3Flag(&pokedex->rotomFormOrder, i) == 7) {
            break;
        }
    }
    return n;
}

static BOOL Pokedex_CheckSeenRotomForm(Pokedex *pokedex, u32 species, u8 form) {
    int i, val;
    u32 n;

    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    n = Pokedex_GetSeenFormNum_Rotom(pokedex, species);
    for (i = 0; i < n; i++) {
        val = CheckDex3Flag(&pokedex->rotomFormOrder, i);
        if (val == form) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenRotomForm(Pokedex *pokedex, u32 species, u32 form) {
    int i;
    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckSeenRotomForm(pokedex, species, form)) {
        i = Pokedex_GetSeenFormNum_Rotom(pokedex, species);
        if (i < 6) {
            SetDex3Flag(&pokedex->rotomFormOrder, i, form);
        }
    }
}

static void Pokedex_TryAppendSeenForm(Pokedex *pokedex, u16 species, Pokemon *mon) {
    u32 form;

    form = GetMonData(mon, MON_DATA_FORM, NULL);
    // An East Sea Shellos or Gastrodon is a species of its own here, with form
    // 0; the Dex keeps it as its base's form 1, as the reference stores it.
    switch (GetMonData(mon, MON_DATA_SPECIES, NULL)) {
    case SPECIES_SHELLOS_EAST_SEA:
    case SPECIES_GASTRODON_EAST_SEA:
        form = SHELLOS_EAST;
        break;
    }
    switch (species) {
    case SPECIES_UNOWN:
        Pokedex_TryAppendUnownLetter(pokedex, form, FALSE);
        break;
    case SPECIES_BURMY:
    case SPECIES_WORMADAM:
        Pokedex_SetSeenForm_3max(pokedex, species, form);
        break;
    case SPECIES_PICHU:
        if (form == 0) {
            if (GetMonGender(mon) == MON_MALE) {
                form = 0;
            } else {
                form = 1;
            }
        } else {
            form = 2;
        }
        Pokedex_SetSeenForm_3max(pokedex, species, form);
        break;
    case SPECIES_SHELLOS:
    case SPECIES_GASTRODON:
        Pokedex_SetSeenForm_2max(pokedex, species, form);
        break;
    case SPECIES_DEOXYS:
        Pokedex_SetSeenDeoxysForm(pokedex, species, mon);
        break;
    case SPECIES_SHAYMIN:
    case SPECIES_GIRATINA:
        Pokedex_SetSeenForm_2max(pokedex, species, form);
        break;
    case SPECIES_ROTOM:
        Pokedex_SetSeenRotomForm(pokedex, species, form);
        break;
    }
}

static void Pokedex_SetCaughtLanguage(Pokedex *pokedex, u32 species, u32 language) {
    int shift;

    shift = LanguageToDexFlag(language);
    if (shift != 6) {
        pokedex->caughtLanguages[species] |= (1 << shift);
    }
}

static int Pokedex_SpeciesGetLastSeenGender_Internal(Pokedex *pokedex, u16 species, u32 idx) {
    u8 gender1, gender2;

    if (GetMonBaseStat(species, BASE_GENDER_RATIO) == MON_RATIO_UNKNOWN) {
        if (idx == 0) {
            return 2;
        } else {
            return -1;
        }
    }
    gender1 = CheckDexFlag((u8 *)pokedex->seenGenders[0], species);
    if (idx == 1) {
        gender2 = CheckDexFlag((u8 *)pokedex->seenGenders[1], species);
        if (gender2 == gender1) {
            return -1;
        }
        return gender2;
    }
    return gender1;
}

static BOOL Pokedex_GetSeenFormByIdx_2max(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    GF_ASSERT(idx < 2);
    return CheckDexFlag(Pokedex_GetFormOrderAddr(pokedex, species), idx + 1);
}

static int Pokedex_GetSeenFormByIdx_Rotom(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_ROTOM);
    GF_ASSERT(idx < 6);
    return CheckDex3Flag(&pokedex->rotomFormOrder, idx);
}

static int Pokedex_GetSeenFormByIdx_3max(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    GF_ASSERT(idx < 3);
    return CheckDex2Flag(Pokedex_GetFormOrderAddr(pokedex, species), idx);
}

static const u16 sNationalMythicals[] = {
    SPECIES_MEW,
    SPECIES_CELEBI,
    SPECIES_JIRACHI,
    SPECIES_DEOXYS,
    SPECIES_PHIONE,
    SPECIES_MANAPHY,
    SPECIES_DARKRAI,
    SPECIES_SHAYMIN,
    SPECIES_ARCEUS,
};

static BOOL SpeciesIsNotNationalMythical(u16 species) {
    int i;
    BOOL result;

    for (i = 0, result = TRUE; i < (s32)NELEMS(sNationalMythicals); i++) {
        if (species == sNationalMythicals[i]) {
            result = FALSE;
        }
    }
    return result;
}

static const u16 sJohtoMythicals[] = {
    SPECIES_MEW,
    SPECIES_CELEBI,
};

static BOOL SpeciesIsNotJohtoMythical(u16 species) {
    int i;
    BOOL result;

    for (i = 0, result = TRUE; i < (s32)NELEMS(sJohtoMythicals); i++) {
        if (species == sJohtoMythicals[i]) {
            result = FALSE;
        }
    }
    return result;
}

void Save_Pokedex_Init(Pokedex *pokedex) {
    memset(pokedex, 0, sizeof(Pokedex));
    pokedex->magic = POKEDEX_MAGIC;
    pokedex->nationalDex = 0;
    memset(pokedex->unownSeenOrder, 0xFF, 28);
    memset(pokedex->unownCaughtOrder, 0xFF, 28);
    pokedex->shellosFormOrder = 0xFF;
    pokedex->gastrodonFormOrder = 0xFF;
    pokedex->burmyFormOrder = 0xFF;
    pokedex->wormadamFormOrder = 0xFF;
    pokedex->rotomFormOrder = -1;
    pokedex->shayminFormOrder = 0xFF;
    pokedex->giratinaFormOrder = 0xFF;
    pokedex->pichuFormOrder = 0xFF;
    Pokedex_InitDeoxysFormOrder(pokedex);
}

u16 Pokedex_CountNationalDexOwned(Pokedex *pokedex) {
    int i, n;
    ASSERT_POKEDEX(pokedex);
    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountNationalDexSeen(Pokedex *pokedex) {
    int i, n;
    ASSERT_POKEDEX(pokedex);
    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_CheckMonSeenFlag(pokedex, i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountDexOwned(Pokedex *pokedex) {
    if (Pokedex_GetNatDexFlag(pokedex)) {
        return Pokedex_CountNationalDexOwned(pokedex);
    } else {
        return Pokedex_CountJohtoDexOwned(pokedex);
    }
}

// The Johto table (LoadSpeciesToJohtoDexNoLUT) is retail's, one entry a
// species up to Arceus, and the Johto Dex holds no species past it. The three
// Johto counts walk that table, not the National Dex.
u16 Pokedex_CountJohtoDexOwned(Pokedex *pokedex) {
    u16 *johto_species;
    u16 i, n;
    ASSERT_POKEDEX(pokedex);
    johto_species = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && johto_species[i] != J_SPECIES_NONE) {
            n++;
        }
    }
    Heap_Free(johto_species);
    return n;
}

u16 Pokedex_CountJohtoDexSeen(Pokedex *pokedex) {
    u16 *johto_species;
    u16 i, n;
    ASSERT_POKEDEX(pokedex);
    johto_species = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonSeenFlag(pokedex, i) == TRUE && johto_species[i] != J_SPECIES_NONE) {
            n++;
        }
    }
    Heap_Free(johto_species);
    return n;
}

// Retail's 484, which the engine keeps while counting past Arceus: the same
// number at which Oak's rating (GetOakNationalDexRating) calls the Dex done.
BOOL Pokedex_NationalDexIsComplete(Pokedex *pokedex) {
    return Pokedex_CountNationalOwned_ExcludeMythical(pokedex) >= (MAX_SPECIES - NELEMS(sNationalMythicals));
}

BOOL Pokedex_JohtoDexIsComplete(Pokedex *pokedex) {
    return Pokedex_CountJohtoOwned_ExcludeMythical(pokedex) >= (J_NUM_SPECIES - NELEMS(sJohtoMythicals));
}

u16 Pokedex_CountNationalOwned_ExcludeMythical(Pokedex *pokedex) {
    int i;
    u16 n;

    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && SpeciesIsNotNationalMythical(i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountJohtoOwned_ExcludeMythical(Pokedex *pokedex) {
    u16 i;
    u16 n;
    u16 *johto_dex;

    johto_dex = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && johto_dex[i] != J_SPECIES_NONE && SpeciesIsNotJohtoMythical(i) == TRUE) {
            n++;
        }
    }
    Heap_Free(johto_dex);
    return n;
}

BOOL Pokedex_CheckMonCaughtFlag(const Pokedex *pokedex, u16 species) {
    ASSERT_POKEDEX(pokedex);
    species = SpeciesToDexSpecies(species);
    if (DexSpeciesIsInvalid(species)) {
        return FALSE;
    }
    if (CheckDexFlag((const u8 *)pokedex->caughtSpecies, species) && CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

BOOL Pokedex_CheckMonSeenFlag(const Pokedex *pokedex, u16 species) {
    ASSERT_POKEDEX(pokedex);
    species = SpeciesToDexSpecies(species);
    if (DexSpeciesIsInvalid(species)) {
        return FALSE;
    }
    if (CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

u32 Pokedex_GetSeenSpindaPersonality(Pokedex *pokedex, u32 arg) {
    u32 personality;
    ASSERT_POKEDEX(pokedex);
    if (arg == 0) {
        personality = pokedex->spindaPersonality;
    } else {
        GF_ASSERT(FALSE);
    }
    return personality;
}

int Pokedex_SpeciesGetLastSeenGender(Pokedex *pokedex, u16 species, u32 idx) {
    ASSERT_POKEDEX(pokedex);
    if (DexSpeciesIsInvalid(species)) {
        return -1;
    }
    if (CheckDexFlag((u8 *)pokedex->seenSpecies, species)) {
        return Pokedex_SpeciesGetLastSeenGender_Internal(pokedex, species, idx);
    }
    return -1;
}

int Pokedex_GetSeenFormByIdx_Unown(Pokedex *pokedex, int idx, u32 caught) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountRegisteredUnownLetters(pokedex, caught) <= idx) {
        return -1;
    }
    if (caught) {
        return pokedex->unownCaughtOrder[idx];
    } else {
        return pokedex->unownSeenOrder[idx];
    }
}

u32 Pokedex_GetSeenFormNum_Unown(Pokedex *pokedex, BOOL caught) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountRegisteredUnownLetters(pokedex, caught);
}

int Pokedex_GetSeenFormByIdx_Shellos(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHELLOS) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_2max(pokedex, SPECIES_SHELLOS, a1);
}

static u32 Pokedex_GetSeenFormNum_Shellos(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHELLOS);
}

static int Pokedex_GetSeenFormByIdx_Gastrodon(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GASTRODON) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_2max(pokedex, SPECIES_GASTRODON, a1);
}

static u32 Pokedex_GetSeenFormNum_Gastrodon(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GASTRODON);
}

static int Pokedex_GetSeenFormByIdx_Burmy(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_BURMY) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_BURMY, a1);
}

static u32 Pokedex_GetSeenFormNum_Burmy(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_BURMY);
}

static int Pokedex_GetSeenFormByIdx_Wormadam(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_WORMADAM) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_WORMADAM, a1);
}

static u32 Pokedex_GetSeenFormNum_Wormadam(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_WORMADAM);
}

static int Pokedex_GetSeenFormByIdx_Pichu(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_PICHU) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_PICHU, a1);
}

static u32 Pokedex_GetSeenFormNum_Pichu(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_PICHU);
}

static u32 Pokedex_GetSeenFormByIdx_Deoxys(Pokedex *pokedex, u32 a1) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenDeoxysFormByIndex(pokedex, a1);
}

static u32 Pokedex_GetSeenFormNum_Deoxys(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenDeoxysForms(pokedex);
}

void Pokedex_SetMonSeenFlag(Pokedex *pokedex, Pokemon *mon) {
    u16 species;
    u32 personality;
    u32 gender;
    u8 seenGender;

    species = SpeciesToDexSpecies(GetMonData(mon, MON_DATA_SPECIES, NULL));
    personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    gender = GetMonGender(mon);

    ASSERT_POKEDEX(pokedex);
    if (!DexSpeciesIsInvalid(species)) {
        if (!CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
            if (species == SPECIES_SPINDA) {
                pokedex->spindaPersonality = personality;
            }
            Pokedex_SetSeenGenderFlag(pokedex, gender, 0, species);
        } else {
            seenGender = CheckDexFlag((const u8 *)pokedex->seenGenders[0], species);
            if (seenGender != gender) {
                Pokedex_SetSeenGenderFlag(pokedex, gender, 1, species);
            }
        }
        Pokedex_TryAppendSeenForm(pokedex, species, mon);
        SetDexFlag((u8 *)pokedex->seenSpecies, species);
    }
}

void Pokedex_SetMonCaughtFlag(Pokedex *pokedex, Pokemon *mon) {
    u16 species;
    u32 language;
    u32 personality;
    u32 gender;
    u32 gender_ct;

    species = SpeciesToDexSpecies(GetMonData(mon, MON_DATA_SPECIES, NULL));
    language = GetMonData(mon, MON_DATA_LANGUAGE, NULL);
    personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    gender = GetMonGender(mon);

    ASSERT_POKEDEX(pokedex);
    if (!DexSpeciesIsInvalid(species)) {
        if (!CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
            if (species == SPECIES_SPINDA) {
                pokedex->spindaPersonality = personality;
            }
            Pokedex_SetSeenGenderFlag(pokedex, gender, 0, species);
        } else {
            gender_ct = CheckDexGender((const u8 *)pokedex->seenGenders[0], species);
            if (gender_ct != gender) {
                Pokedex_SetSeenGenderFlag(pokedex, gender, 1, species);
            }
        }
        Pokedex_TryAppendSeenForm(pokedex, species, mon);
        if (species == SPECIES_UNOWN) {
            Pokedex_TryAppendUnownLetter(pokedex, GetMonUnownLetter(mon), TRUE);
        }
        Pokedex_SetCaughtLanguage(pokedex, species, language);
        if (language != GAME_LANGUAGE) {
            Pokedex_SetInternationalViewFlag(pokedex);
        }
        SetDexFlag((u8 *)pokedex->caughtSpecies, species);
        SetDexFlag((u8 *)pokedex->seenSpecies, species);
    }
}

void Pokedex_SetNatDexFlag(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->nationalDex = TRUE;
}

BOOL Pokedex_GetNatDexFlag(const Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return pokedex->nationalDex;
}

void Pokedex_EnableFormDetection(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->canDetectForms = TRUE;
}

BOOL Pokedex_HasCaughtMonWithLanguage(Pokedex *pokedex, u32 species, u32 language) {
    int shift;
    GF_ASSERT(language <= 8);
    ASSERT_POKEDEX(pokedex);
    shift = LanguageToDexFlag(language);
    if (pokedex->caughtLanguages[species] & (1 << shift)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

void Pokedex_SetInternationalViewFlag(Pokedex *pokedex) {
    pokedex->enabledInternational = TRUE;
}

BOOL Pokedex_GetInternationalViewFlag(const Pokedex *pokedex) {
    return pokedex->enabledInternational;
}

BOOL Pokedex_IsEnabled(const Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return pokedex->dexEnabled;
}

void Pokedex_Enable(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->dexEnabled = TRUE;
}

Pokedex *Save_Pokedex_Get(SaveData *saveData) {
    return SaveArray_Get(saveData, SAVE_POKEDEX);
}

int Pokedex_GetSeenFormByIdx(Pokedex *pokedex, int species, int idx) {
    ASSERT_POKEDEX(pokedex);
    switch (species) {
    case SPECIES_UNOWN:
        if (idx < Pokedex_GetSeenFormNum_Unown(pokedex, 0)) {
            return Pokedex_GetSeenFormByIdx_Unown(pokedex, idx, 0);
        }
        break;
    case SPECIES_SHELLOS:
        if (idx < Pokedex_GetSeenFormNum_Shellos(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Shellos(pokedex, idx);
        }
        break;
    case SPECIES_GASTRODON:
        if (idx < Pokedex_GetSeenFormNum_Gastrodon(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Gastrodon(pokedex, idx);
        }
        break;
    case SPECIES_BURMY:
        if (idx < Pokedex_GetSeenFormNum_Burmy(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Burmy(pokedex, idx);
        }
        break;
    case SPECIES_WORMADAM:
        if (idx < Pokedex_GetSeenFormNum_Wormadam(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Wormadam(pokedex, idx);
        }
        break;
    case SPECIES_PICHU:
        if (idx < Pokedex_GetSeenFormNum_Pichu(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Pichu(pokedex, idx);
        }
        break;
    case SPECIES_DEOXYS:
        if (idx < Pokedex_GetSeenFormNum_Deoxys(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Deoxys(pokedex, idx);
        }
        break;
    case SPECIES_SHAYMIN:
    case SPECIES_GIRATINA:
        if (idx < Pokedex_GetSeenFormNum_2max(pokedex, species)) {
            return Pokedex_GetSeenFormByIdx_2max(pokedex, species, idx);
        }
        break;
    case SPECIES_ROTOM:
        if (idx < Pokedex_GetSeenFormNum_Rotom(pokedex, SPECIES_ROTOM)) {
            return Pokedex_GetSeenFormByIdx_Rotom(pokedex, SPECIES_ROTOM, idx);
        }
        break;
    }
    return 0;
}

int Pokedex_GetSeenFormNum(Pokedex *pokedex, int species) {
    ASSERT_POKEDEX(pokedex);
    switch (species) {
    case SPECIES_UNOWN:
        return Pokedex_GetSeenFormNum_Unown(pokedex, 0);
    case SPECIES_SHELLOS:
        return Pokedex_GetSeenFormNum_Shellos(pokedex);
    case SPECIES_GASTRODON:
        return Pokedex_GetSeenFormNum_Gastrodon(pokedex);
    case SPECIES_BURMY:
        return Pokedex_GetSeenFormNum_Burmy(pokedex);
    case SPECIES_WORMADAM:
        return Pokedex_GetSeenFormNum_Wormadam(pokedex);
    case SPECIES_PICHU:
        return Pokedex_GetSeenFormNum_Pichu(pokedex);
    case SPECIES_DEOXYS:
        return Pokedex_GetSeenFormNum_Deoxys(pokedex);
    case SPECIES_SHAYMIN:
        return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHAYMIN);
    case SPECIES_GIRATINA:
        return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GIRATINA);
    case SPECIES_ROTOM:
        return Pokedex_GetSeenFormNum_Rotom(pokedex, SPECIES_ROTOM);
    }
    return 1;
}
