#include "pokemon_icon_idx.h"

#include "global.h"

#include "constants/species.h"

#include "pokemon.h"

// HGSS reads a species' icon at species + 7, and the entries just past the
// last species are taken by the alternate form icons, so the species New Gold
// adds are given the range after all of them. Their palette numbers follow the
// form entries in the table below for the same reason.
#define FIRST_ADDED_ICON    551
#define FIRST_ADDED_PALETTE 544

static u16 BoxMonGetForm(BoxPokemon *boxMon);

u32 Boxmon_GetIconNaix(BoxPokemon *boxMon) {
    BOOL encry;
    int species;
    BOOL isEgg;
    int form;
    u32 ret;

    encry = AcquireBoxMonLock(boxMon);
    species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    isEgg = GetBoxMonData(boxMon, MON_DATA_IS_EGG, NULL);
    form = BoxMonGetForm(boxMon);
    ret = GetMonIconNaixEx(species, isEgg, form);
    ReleaseBoxMonLock(boxMon, encry);
    return ret;
}

u32 Pokemon_GetIconNaix(Pokemon *mon) {
    return Boxmon_GetIconNaix(Mon_GetBoxMon(mon));
}

u32 GetMonIconNaixEx(u32 species, BOOL isEgg, u32 form) {
    if (isEgg == TRUE) {
        if (species == SPECIES_MANAPHY) {
            return 502;
        } else {
            return 501;
        }
    }

    form = sub_02070438(species, form);
    if (form != 0) {
        if (species == SPECIES_DEOXYS) {
            return form + 503 - 1;
        } else if (species == SPECIES_UNOWN) {
            return form + 507 - 1;
        } else if (species == SPECIES_BURMY) {
            return form + 534 - 1;
        } else if (species == SPECIES_WORMADAM) {
            return form + 536 - 1;
        } else if (species == SPECIES_SHELLOS) {
            return form + 538 - 1;
        } else if (species == SPECIES_GASTRODON) {
            return form + 539 - 1;
        } else if (species == SPECIES_GIRATINA) {
            return form + 540 - 1;
        } else if (species == SPECIES_SHAYMIN) {
            return form + 541 - 1;
        } else if (species == SPECIES_ROTOM) {
            return form + 542 - 1;
        }
    }
    if (species > MAX_SPECIES) {
        if (species >= SPECIES_LILLIPUP && species <= NUM_SPECIES) {
            return species - SPECIES_LILLIPUP + FIRST_ADDED_ICON;
        }
        species = 0;
    }
    return species + 7;
}

u32 GetBattleMonIconNaixEx(u32 species, BOOL isEgg, u32 form) {
    if (!isEgg) {
        if (species == SPECIES_CASTFORM) {
            form = sub_02070438(species, form);
            if (form != 0) {
                return form + 547 - 1;
            }
        } else if (species == SPECIES_CHERRIM) {
            form = sub_02070438(species, form);
            if (form != 0) {
                return form + 550 - 1;
            }
        }
    }
    return GetMonIconNaixEx(species, isEgg, form);
}

static u16 BoxMonGetForm(BoxPokemon *boxMon) {
    switch (GetBoxMonData(boxMon, MON_DATA_SPECIES_OR_EGG, NULL)) {
    case SPECIES_UNOWN:
        return GetBoxMonUnownLetter(boxMon);
    case SPECIES_DEOXYS:
    case SPECIES_SHELLOS:
    case SPECIES_GASTRODON:
    case SPECIES_BURMY:
    case SPECIES_WORMADAM:
    case SPECIES_GIRATINA:
    case SPECIES_SHAYMIN:
    case SPECIES_ROTOM:
        return GetBoxMonData(boxMon, MON_DATA_FORM, NULL);
    default:
        return 0;
    }
}

static const u8 sPokemonPalNoBySpeciesAndForm[] = {
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    2,
    2,
    1,
    1,
    0,
    1,
    2,
    2,
    0,
    0,
    0,
    2,
    1,
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    2,
    1,
    0,
    0,
    2,
    2,
    1,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    1,
    1,
    1,
    2,
    1,
    2,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    0,
    1,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    1,
    2,
    2,
    0,
    0,
    0,
    1,
    1,
    1,
    2,
    2,
    1,
    2,
    2,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    2,
    1,
    0,
    2,
    2,
    0,
    0,
    2,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    1,
    2,
    2,
    0,
    0,
    2,
    0,
    0,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    0,
    0,
    2,
    2,
    2,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    2,
    2,
    0,
    0,
    2,
    0,
    0,
    1,
    2,
    0,
    0,
    2,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    0,
    2,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    2,
    0,
    2,
    0,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    2,
    2,
    0,
    0,
    1,
    1,
    1,
    2,
    0,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    0,
    2,
    2,
    2,
    1,
    2,
    0,
    0,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    2,
    0,
    1,
    2,
    0,
    0,
    2,
    0,
    1,
    0,
    1,
    0,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    2,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    0,
    0,
    0,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    2,
    2,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    2,
    2,
    2,
    2,
    0,
    1,
    0,
    2,
    0,
    2,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    1,
    1,
    0,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    2,
    1,
    0,
    2,
    1,
    1,
    0,
    2,
    2,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    // The species New Gold adds, in identifier order from 508.
    2, // LILLIPUP,
    2, // HERDIER,
    2, // STOUTLAND,
    0, // PURRLOIN,
    0, // LIEPARD,
    2, // TYMPOLE,
    2, // PALPITOAD,
    0, // SEISMITOAD,
    1, // SEWADDLE,
    1, // SWADLOON,
    1, // LEAVANNY,
    0, // YAMASK,
    0, // COFAGRIGUS,
    1, // TRUBBISH,
    1, // GARBODOR,
    2, // EMOLGA,
    0, // KARRABLAST,
    0, // ESCAVALIER,
    0, // FOONGUS,
    0, // AMOONGUSS,
    0, // JOLTIK,
    2, // GALVANTULA,
    1, // FERROSEED,
    1, // FERROTHORN,
    0, // KLINK,
    0, // KLANG,
    0, // KLINKLANG,
    0, // ELGYEM,
    2, // BEHEEYEM,
    2, // LITWICK,
    2, // LAMPENT,
    2, // CHANDELURE,
    1, // SHELMET,
    1, // ACCELGOR,
    2, // BOUFFALANT,
    2, // BUNNELBY,
    2, // DIGGERSBY,
    0, // FLETCHLING,
    0, // FLETCHINDER,
    0, // TALONFLAME,
    2, // LITLEO,
    2, // PYROAR,
    2, // ESPURR,
    0, // MEOWSTIC,
    0, // SYLVEON,
    0, // DEDENNE,
    1, // PHANTUMP,
    1, // TREVENANT,
    2, // PUMPKABOO,
    2, // GOURGEIST,
    2, // NOIBAT,
    2, // NOIVERN,
    1, // APPLIN,
    1, // FLAPPLE,
    1, // APPLETUN,
    0, // SIZZLIPEDE,
    0, // CENTISKORCH,
    0, // WYRDEER,
    2, // KLEAVOR,
    2, // URSALUNA,
    0, // ANNIHILAPE,
    0, // FARIGIRAF,
    0, // DUDUNSPARCE,
    1, // DIPPLIN,
    1, // HYDRAPPLE,
    1, // SLOWPOKE_GALARIAN,
    0, // SLOWBRO_GALARIAN,
    0, // VICTINI,
    1, // SNIVY,
    1, // SERVINE,
    1, // SERPERIOR,
    0, // TEPIG,
    0, // PIGNITE,
    0, // EMBOAR,
    0, // OSHAWOTT,
    0, // DEWOTT,
    2, // SAMUROTT,
    2, // PATRAT,
    2, // WATCHOG,
    1, // PANSAGE,
    1, // SIMISAGE,
    2, // PANSEAR,
    2, // SIMISEAR,
    2, // PANPOUR,
    2, // SIMIPOUR,
    0, // MUNNA,
    0, // MUSHARNA,
    0, // PIDOVE,
    0, // TRANQUILL,
    1, // UNFEZANT,
    2, // BLITZLE,
    2, // ZEBSTRIKA,
    2, // ROGGENROLA,
    0, // BOLDORE,
    0, // GIGALITH,
    0, // WOOBAT,
    0, // SWOOBAT,
    0, // DRILBUR,
    0, // EXCADRILL,
    1, // AUDINO,
    1, // TIMBURR,
    1, // GURDURR,
    1, // CONKELDURR,
    0, // THROH,
    0, // SAWK,
    1, // VENIPEDE,
    2, // WHIRLIPEDE,
    2, // SCOLIPEDE,
    1, // COTTONEE,
    1, // WHIMSICOTT,
    1, // PETILIL,
    1, // LILLIGANT,
    1, // BASCULIN,
    1, // SANDILE,
    1, // KROKOROK,
    0, // KROOKODILE,
    0, // DARUMAKA,
    0, // DARMANITAN,
    1, // MARACTUS,
    0, // DWEBBLE,
    2, // CRUSTLE,
    2, // SCRAGGY,
    0, // SCRAFTY,
    0, // SIGILYPH,
    2, // TIRTOUGA,
    2, // CARRACOSTA,
    0, // ARCHEN,
    0, // ARCHEOPS,
    0, // ZORUA,
    0, // ZOROARK,
    0, // MINCCINO,
    0, // CINCCINO,
    2, // GOTHITA,
    2, // GOTHORITA,
    2, // GOTHITELLE,
    1, // SOLOSIS,
    1, // DUOSION,
    1, // REUNICLUS,
    0, // DUCKLETT,
    2, // SWANNA,
    0, // VANILLITE,
    2, // VANILLISH,
    2, // VANILLUXE,
    1, // DEERLING,
    1, // SAWSBUCK,
    0, // FRILLISH,
    0, // JELLICENT,
    0, // ALOMOMOLA,
    0, // TYNAMO,
    0, // EELEKTRIK,
    0, // EELEKTROSS,
    1, // AXEW,
    1, // FRAXURE,
    2, // HAXORUS,
    0, // CUBCHOO,
    0, // BEARTIC,
    0, // CRYOGONAL,
    2, // STUNFISK,
    1, // MIENFOO,
    2, // MIENSHAO,
    0, // DRUDDIGON,
    0, // GOLETT,
    0, // GOLURK,
    0, // PAWNIARD,
    0, // BISHARP,
    2, // RUFFLET,
    0, // BRAVIARY,
    0, // VULLABY,
    1, // MANDIBUZZ,
    2, // HEATMOR,
    0, // DURANT,
    2, // DEINO,
    2, // ZWEILOUS,
    2, // HYDREIGON,
    0, // LARVESTA,
    0, // VOLCARONA,
    0, // COBALION,
    2, // TERRAKION,
    1, // VIRIZION,
    1, // TORNADUS,
    0, // THUNDURUS,
    0, // RESHIRAM,
    2, // ZEKROM,
    0, // LANDORUS,
    0, // KYUREM,
    0, // KELDEO,
    1, // MELOETTA,
    2, // GENESECT,
    1, // CHESPIN,
    1, // QUILLADIN,
    1, // CHESNAUGHT,
    0, // FENNEKIN,
    0, // BRAIXEN,
    0, // DELPHOX,
    0, // FROAKIE,
    0, // FROGADIER,
    0, // GRENINJA,
    0, // SCATTERBUG,
    1, // SPEWPA,
    0, // VIVILLON,
    1, // FLABEBE,
    1, // FLOETTE,
    0, // FLORGES,
    1, // SKIDDO,
    1, // GOGOAT,
    1, // PANCHAM,
    0, // PANGORO,
    0, // FURFROU,
    2, // HONEDGE,
    2, // DOUBLADE,
    2, // AEGISLASH,
    0, // SPRITZEE,
    0, // AROMATISSE,
    1, // SWIRLIX,
    1, // SLURPUFF,
    0, // INKAY,
    2, // MALAMAR,
    2, // BINACLE,
    2, // BARBARACLE,
    2, // SKRELP,
    2, // DRAGALGE,
    0, // CLAUNCHER,
    0, // CLAWITZER,
    0, // HELIOPTILE,
    0, // HELIOLISK,
    2, // TYRUNT,
    0, // TYRANTRUM,
    0, // AMAURA,
    0, // AURORUS,
    0, // HAWLUCHA,
    0, // CARBINK,
    2, // GOOMY,
    2, // SLIGGOO,
    2, // GOODRA,
    0, // KLEFKI,
    0, // BERGMITE,
    0, // AVALUGG,
    0, // XERNEAS,
    0, // YVELTAL,
    1, // ZYGARDE,
    0, // DIANCIE,
    0, // HOOPA,
    0, // VOLCANION,
    0, // ROWLET,
    1, // DARTRIX,
    1, // DECIDUEYE,
    0, // LITTEN,
    0, // TORRACAT,
    0, // INCINEROAR,
    0, // POPPLIO,
    0, // BRIONNE,
    0, // PRIMARINA,
    2, // PIKIPEK,
    0, // TRUMBEAK,
    0, // TOUCANNON,
    2, // YUNGOOS,
    2, // GUMSHOOS,
    0, // GRUBBIN,
    1, // CHARJABUG,
    0, // VIKAVOLT,
    2, // CRABRAWLER,
    2, // CRABOMINABLE,
    0, // ORICORIO,
    2, // CUTIEFLY,
    2, // RIBOMBEE,
    2, // ROCKRUFF,
    2, // LYCANROC,
    2, // WISHIWASHI,
    2, // MAREANIE,
    0, // TOXAPEX,
    2, // MUDBRAY,
    0, // MUDSDALE,
    0, // DEWPIDER,
    2, // ARAQUANID,
    1, // FOMANTIS,
    1, // LURANTIS,
    0, // MORELULL,
    1, // SHIINOTIC,
    2, // SALANDIT,
    0, // SALAZZLE,
    0, // STUFFUL,
    0, // BEWEAR,
    1, // BOUNSWEET,
    1, // STEENEE,
    1, // TSAREENA,
    1, // COMFEY,
    0, // ORANGURU,
    1, // PASSIMIAN,
    2, // WIMPOD,
    2, // GOLISOPOD,
    1, // SANDYGAST,
    2, // PALOSSAND,
    0, // PYUKUMUKU,
    0, // TYPE_NULL,
    0, // SILVALLY,
    2, // MINIOR,
    2, // KOMALA,
    0, // TURTONATOR,
    2, // TOGEDEMARU,
    1, // MIMIKYU,
    0, // BRUXISH,
    0, // DRAMPA,
    1, // DHELMISE,
    2, // JANGMO_O,
    2, // HAKAMO_O,
    2, // KOMMO_O,
    0, // TAPU_KOKO,
    0, // TAPU_LELE,
    2, // TAPU_BULU,
    2, // TAPU_FINI,
    2, // COSMOG,
    0, // COSMOEM,
    0, // SOLGALEO,
    0, // LUNALA,
    0, // NIHILEGO,
    0, // BUZZWOLE,
    2, // PHEROMOSA,
    0, // XURKITREE,
    0, // CELESTEELA,
    0, // KARTANA,
    0, // GUZZLORD,
    2, // NECROZMA,
    1, // MAGEARNA,
    0, // MARSHADOW,
    0, // POIPOLE,
    0, // NAGANADEL,
    0, // STAKATAKA,
    2, // BLACEPHALON,
    0, // ZERAORA,
    2, // MELTAN,
    2, // MELMETAL,
    1, // GROOKEY,
    1, // THWACKEY,
    1, // RILLABOOM,
    0, // SCORBUNNY,
    0, // RABOOT,
    0, // CINDERACE,
    2, // SOBBLE,
    2, // DRIZZILE,
    0, // INTELEON,
    2, // SKWOVET,
    0, // GREEDENT,
    0, // ROOKIDEE,
    0, // CORVISQUIRE,
    0, // CORVIKNIGHT,
    0, // BLIPBUG,
    2, // DOTTLER,
    0, // ORBEETLE,
    2, // NICKIT,
    2, // THIEVUL,
    1, // GOSSIFLEUR,
    1, // ELDEGOSS,
    2, // WOOLOO,
    2, // DUBWOOL,
    0, // CHEWTLE,
    0, // DREDNAW,
    1, // YAMPER,
    1, // BOLTUND,
    0, // ROLYCOLY,
    0, // CARKOL,
    0, // COALOSSAL,
    1, // SILICOBRA,
    1, // SANDACONDA,
    0, // CRAMORANT,
    2, // ARROKUDA,
    2, // BARRASKEWDA,
    2, // TOXEL,
    2, // TOXTRICITY,
    0, // CLOBBOPUS,
    2, // GRAPPLOCT,
    2, // SINISTEA,
    2, // POLTEAGEIST,
    0, // HATENNA,
    0, // HATTREM,
    0, // HATTERENE,
    0, // IMPIDIMP,
    0, // MORGREM,
    0, // GRIMMSNARL,
    0, // OBSTAGOON,
    0, // PERRSERKER,
    0, // CURSOLA,
    1, // SIRFETCHD,
    0, // MR_RIME,
    2, // RUNERIGUS,
    1, // MILCERY,
    1, // ALCREMIE,
    0, // FALINKS,
    0, // PINCURCHIN,
    0, // SNOM,
    0, // FROSMOTH,
    0, // STONJOURNER,
    0, // EISCUE,
    2, // INDEEDEE,
    2, // MORPEKO,
    0, // CUFANT,
    0, // COPPERAJAH,
    1, // DRACOZOLT,
    2, // ARCTOZOLT,
    0, // DRACOVISH,
    0, // ARCTOVISH,
    0, // DURALUDON,
    0, // DREEPY,
    0, // DRAKLOAK,
    0, // DRAGAPULT,
    2, // ZACIAN,
    2, // ZAMAZENTA,
    0, // ETERNATUS,
    2, // KUBFU,
    2, // URSHIFU,
    1, // ZARUDE,
    0, // REGIELEKI,
    2, // REGIDRAGO,
    0, // GLASTRIER,
    0, // SPECTRIER,
    0, // CALYREX,
    1, // BASCULEGION,
    2, // SNEASLER,
    2, // OVERQWIL,
    1, // ENAMORUS,
    1, // SPRIGATITO,
    1, // FLORAGATO,
    1, // MEOWSCARADA,
    2, // FUECOCO,
    0, // CROCALOR,
    0, // SKELEDIRGE,
    0, // QUAXLY,
    0, // QUAXWELL,
    0, // QUAQUAVAL,
    1, // LECHONK,
    0, // OINKOLOGNE,
    1, // TAROUNTULA,
    1, // SPIDOPS,
    0, // NYMBLE,
    0, // LOKIX,
    0, // PAWMI,
    0, // PAWMO,
    0, // PAWMOT,
    0, // TANDEMAUS,
    0, // MAUSHOLD,
    1, // FIDOUGH,
    0, // DACHSBUN,
    1, // SMOLIV,
    1, // DOLLIV,
    1, // ARBOLIVA,
    1, // SQUAWKABILLY,
    2, // NACLI,
    0, // NACLSTACK,
    2, // GARGANACL,
    0, // CHARCADET,
    0, // ARMAROUGE,
    0, // CERULEDGE,
    2, // TADBULB,
    0, // BELLIBOLT,
    0, // WATTREL,
    0, // KILOWATTREL,
    0, // MASCHIFF,
    0, // MABOSSTIFF,
    0, // SHROODLE,
    0, // GRAFAIAI,
    0, // BRAMBLIN,
    2, // BRAMBLEGHAST,
    0, // TOEDSCOOL,
    0, // TOEDSCRUEL,
    0, // KLAWF,
    1, // CAPSAKID,
    1, // SCOVILLAIN,
    0, // RELLOR,
    0, // RABSCA,
    0, // FLITTLE,
    0, // ESPATHRA,
    1, // TINKATINK,
    1, // TINKATUFF,
    1, // TINKATON,
    0, // WIGLETT,
    0, // WUGTRIO,
    0, // BOMBIRDIER,
    0, // FINIZEN,
    0, // PALAFIN,
    0, // VAROOM,
    0, // REVAVROOM,
    1, // CYCLIZAR,
    0, // ORTHWORM,
    0, // GLIMMET,
    0, // GLIMMORA,
    0, // GREAVARD,
    2, // HOUNDSTONE,
    0, // FLAMIGO,
    0, // CETODDLE,
    0, // CETITAN,
    1, // VELUZA,
    0, // DONDOZO,
    0, // TATSUGIRI,
    0, // CLODSIRE,
    0, // KINGAMBIT,
    0, // GREAT_TUSK,
    0, // SCREAM_TAIL,
    0, // BRUTE_BONNET,
    2, // FLUTTER_MANE,
    2, // SLITHER_WING,
    0, // SANDY_SHOCKS,
    0, // IRON_TREADS,
    0, // IRON_BUNDLE,
    0, // IRON_HANDS,
    0, // IRON_JUGULIS,
    0, // IRON_MOTH,
    1, // IRON_THORNS,
    0, // FRIGIBAX,
    0, // ARCTIBAX,
    0, // BAXCALIBUR,
    0, // GIMMIGHOUL,
    0, // GHOLDENGO,
    1, // WO_CHIEN,
    0, // CHIEN_PAO,
    0, // TING_LU,
    0, // CHI_YU,
    0, // ROARING_MOON,
    1, // IRON_VALIANT,
    0, // KORAIDON,
    2, // MIRAIDON,
    2, // WALKING_WAKE,
    0, // IRON_LEAVES,
    0, // POLTCHAGEIST,
    1, // SINISTCHA,
    1, // OKIDOGI,
    0, // MUNKIDORI,
    0, // FEZANDIPITI,
    1, // OGERPON,
    0, // ARCHALUDON,
    2, // GOUGING_FIRE,
    2, // RAGING_BOLT,
    0, // IRON_BOULDER,
    0, // IRON_CROWN,
    0, // TERAPAGOS,
    0, // PECHARUNT
};

const u8 GetMonIconPaletteEx(u32 species, u32 form, u32 isEgg) {
    if (isEgg == TRUE) {
        if (species == SPECIES_MANAPHY) {
            species = 495;
        } else {
            species = 494;
        }
    } else if (species > MAX_SPECIES) {
        if (species >= SPECIES_LILLIPUP && species <= NUM_SPECIES) {
            species = species - SPECIES_LILLIPUP + FIRST_ADDED_PALETTE;
        } else {
            species = 0;
        }
    } else if (form != 0) {
        if (species == SPECIES_DEOXYS) {
            species = 496 + form - 1;
        } else if (species == SPECIES_UNOWN) {
            species = 499 + form - 1;
        } else if (species == SPECIES_BURMY) {
            species = 527 + form - 1;
        } else if (species == SPECIES_WORMADAM) {
            species = 529 + form - 1;
        } else if (species == SPECIES_SHELLOS) {
            species = 531 + form - 1;
        } else if (species == SPECIES_GASTRODON) {
            species = 532 + form - 1;
        } else if (species == SPECIES_GIRATINA) {
            species = 533 + form - 1;
        } else if (species == SPECIES_SHAYMIN) {
            species = 534 + form - 1;
        } else if (species == SPECIES_ROTOM) {
            species = 535 + form - 1;
        }
    }
    return sPokemonPalNoBySpeciesAndForm[species];
}

const u8 GetBattleMonIconPaletteEx(u32 species, u32 form, BOOL isEgg) {
    if (!isEgg) {
        if (species == SPECIES_CASTFORM) {
            if (form != 0) {
                return sPokemonPalNoBySpeciesAndForm[540 + form - 1];
            }
        } else if (species == SPECIES_CHERRIM) {
            if (form != 0) {
                return sPokemonPalNoBySpeciesAndForm[543 + form - 1];
            }
        }
    }
    return GetMonIconPaletteEx(species, form, isEgg);
}

const u8 Boxmon_GetIconPalette(BoxPokemon *boxMon) {
    BOOL encry;
    u32 species;
    u32 form;
    BOOL isEgg;

    encry = AcquireBoxMonLock(boxMon);
    form = BoxMonGetForm(boxMon);
    species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    isEgg = GetBoxMonData(boxMon, MON_DATA_IS_EGG, NULL);
    ReleaseBoxMonLock(boxMon, encry);
    return GetMonIconPaletteEx(species, form, isEgg);
}

const u8 Pokemon_GetIconPalette(Pokemon *mon) {
    return Boxmon_GetIconPalette(Mon_GetBoxMon(mon));
}

u32 sub_02074490(void) {
    return 0;
}

u32 sub_02074494(void) {
    return 2;
}

u32 sub_02074498(void) {
    return 4;
}

u32 sub_0207449C(void) {
    return 6;
}

u32 sub_020744A0(void) {
    return 1;
}

u32 sub_020744A4(void) {
    return 3;
}

u32 sub_020744A8(void) {
    return 5;
}
