#include "pokedex.h"

#include "global.h"

#include "constants/johto_dex.h"
#include "constants/species.h"

#include "pokemon.h"
#include "unk_02091278.h"

#define POKEDEX_MAGIC (0xBEEFCAFE)
#define ASSERT_POKEDEX(pokedex)                       \
    do {                                              \
        GF_ASSERT((pokedex)->magic == POKEDEX_MAGIC); \
    } while (0)

static void Pokedex_InitDeoxysFormOrder(Pokedex *pokedex);
u16 *LoadSpeciesToJohtoDexNoLUT(void);
void Pokedex_SetInternationalViewFlag(Pokedex *pokedex);

u32 Save_Pokedex_sizeof(void) {
    return sizeof(Pokedex);
}

Pokedex *Pokedex_New(enum HeapID heapID) {
    Pokedex *ret = Heap_Alloc(heapID, sizeof(Pokedex));
    Save_Pokedex_Init(ret);
    return ret;
}

void Pokedex_Copy(const Pokedex *src, Pokedex *dest) {
    MI_CpuCopy8(src, dest, sizeof(Pokedex));
}

BOOL DexSpeciesIsInvalid(u16 species) {
    if (species == SPECIES_NONE || species > NUM_SPECIES) {
        GF_ASSERT(FALSE);
        return TRUE;
    }

    // The identifiers between Arceus and the species New Gold adds are the
    // egg and the alternate forms. They have no Dex entry, and meeting one is
    // not an error either, so this must not reach the assertion above, which
    // resets the game.
    // The same goes for the forms after the last Dex species, which have no
    // entry of their own: SpeciesToDexSpecies sends them to their base's.
    return (species >= FIRST_DEX_GAP && species <= LAST_DEX_GAP) || species > NATIONAL_DEX_COUNT;
}

// Each form's base species, which is the Dex entry the form counts for.
// Written by tools/newgold/import/import_species.py from the reference's form
// table; do not edit it by hand.
static const u16 sFormBaseSpecies[NUM_SPECIES - NATIONAL_DEX_COUNT] = {
    [SPECIES_MEGA_VENUSAUR - NATIONAL_DEX_COUNT - 1] = SPECIES_VENUSAUR,
    [SPECIES_MEGA_CHARIZARD_X - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_MEGA_CHARIZARD_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_MEGA_BLASTOISE - NATIONAL_DEX_COUNT - 1] = SPECIES_BLASTOISE,
    [SPECIES_MEGA_BEEDRILL - NATIONAL_DEX_COUNT - 1] = SPECIES_BEEDRILL,
    [SPECIES_MEGA_PIDGEOT - NATIONAL_DEX_COUNT - 1] = SPECIES_PIDGEOT,
    [SPECIES_MEGA_ALAKAZAM - NATIONAL_DEX_COUNT - 1] = SPECIES_ALAKAZAM,
    [SPECIES_MEGA_SLOWBRO - NATIONAL_DEX_COUNT - 1] = SPECIES_SLOWBRO,
    [SPECIES_MEGA_GENGAR - NATIONAL_DEX_COUNT - 1] = SPECIES_GENGAR,
    [SPECIES_MEGA_KANGASKHAN - NATIONAL_DEX_COUNT - 1] = SPECIES_KANGASKHAN,
    [SPECIES_MEGA_PINSIR - NATIONAL_DEX_COUNT - 1] = SPECIES_PINSIR,
    [SPECIES_MEGA_GYARADOS - NATIONAL_DEX_COUNT - 1] = SPECIES_GYARADOS,
    [SPECIES_MEGA_AERODACTYL - NATIONAL_DEX_COUNT - 1] = SPECIES_AERODACTYL,
    [SPECIES_MEGA_MEWTWO_X - NATIONAL_DEX_COUNT - 1] = SPECIES_MEWTWO,
    [SPECIES_MEGA_MEWTWO_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_MEWTWO,
    [SPECIES_MEGA_AMPHAROS - NATIONAL_DEX_COUNT - 1] = SPECIES_AMPHAROS,
    [SPECIES_MEGA_STEELIX - NATIONAL_DEX_COUNT - 1] = SPECIES_STEELIX,
    [SPECIES_MEGA_SCIZOR - NATIONAL_DEX_COUNT - 1] = SPECIES_SCIZOR,
    [SPECIES_MEGA_HERACROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_HERACROSS,
    [SPECIES_MEGA_HOUNDOOM - NATIONAL_DEX_COUNT - 1] = SPECIES_HOUNDOOM,
    [SPECIES_MEGA_TYRANITAR - NATIONAL_DEX_COUNT - 1] = SPECIES_TYRANITAR,
    [SPECIES_MEGA_SCEPTILE - NATIONAL_DEX_COUNT - 1] = SPECIES_SCEPTILE,
    [SPECIES_MEGA_BLAZIKEN - NATIONAL_DEX_COUNT - 1] = SPECIES_BLAZIKEN,
    [SPECIES_MEGA_SWAMPERT - NATIONAL_DEX_COUNT - 1] = SPECIES_SWAMPERT,
    [SPECIES_MEGA_GARDEVOIR - NATIONAL_DEX_COUNT - 1] = SPECIES_GARDEVOIR,
    [SPECIES_MEGA_SABLEYE - NATIONAL_DEX_COUNT - 1] = SPECIES_SABLEYE,
    [SPECIES_MEGA_MAWILE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAWILE,
    [SPECIES_MEGA_AGGRON - NATIONAL_DEX_COUNT - 1] = SPECIES_AGGRON,
    [SPECIES_MEGA_MEDICHAM - NATIONAL_DEX_COUNT - 1] = SPECIES_MEDICHAM,
    [SPECIES_MEGA_MANECTRIC - NATIONAL_DEX_COUNT - 1] = SPECIES_MANECTRIC,
    [SPECIES_MEGA_SHARPEDO - NATIONAL_DEX_COUNT - 1] = SPECIES_SHARPEDO,
    [SPECIES_MEGA_CAMERUPT - NATIONAL_DEX_COUNT - 1] = SPECIES_CAMERUPT,
    [SPECIES_MEGA_ALTARIA - NATIONAL_DEX_COUNT - 1] = SPECIES_ALTARIA,
    [SPECIES_MEGA_BANETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_BANETTE,
    [SPECIES_MEGA_ABSOL - NATIONAL_DEX_COUNT - 1] = SPECIES_ABSOL,
    [SPECIES_MEGA_GLALIE - NATIONAL_DEX_COUNT - 1] = SPECIES_GLALIE,
    [SPECIES_MEGA_SALAMENCE - NATIONAL_DEX_COUNT - 1] = SPECIES_SALAMENCE,
    [SPECIES_MEGA_METAGROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_METAGROSS,
    [SPECIES_MEGA_LATIAS - NATIONAL_DEX_COUNT - 1] = SPECIES_LATIAS,
    [SPECIES_MEGA_LATIOS - NATIONAL_DEX_COUNT - 1] = SPECIES_LATIOS,
    [SPECIES_MEGA_RAYQUAZA - NATIONAL_DEX_COUNT - 1] = SPECIES_RAYQUAZA,
    [SPECIES_MEGA_LOPUNNY - NATIONAL_DEX_COUNT - 1] = SPECIES_LOPUNNY,
    [SPECIES_MEGA_GARCHOMP - NATIONAL_DEX_COUNT - 1] = SPECIES_GARCHOMP,
    [SPECIES_MEGA_LUCARIO - NATIONAL_DEX_COUNT - 1] = SPECIES_LUCARIO,
    [SPECIES_MEGA_ABOMASNOW - NATIONAL_DEX_COUNT - 1] = SPECIES_ABOMASNOW,
    [SPECIES_MEGA_GALLADE - NATIONAL_DEX_COUNT - 1] = SPECIES_GALLADE,
    [SPECIES_MEGA_AUDINO - NATIONAL_DEX_COUNT - 1] = SPECIES_AUDINO,
    [SPECIES_MEGA_DIANCIE - NATIONAL_DEX_COUNT - 1] = SPECIES_DIANCIE,
    [SPECIES_KYOGRE_PRIMAL - NATIONAL_DEX_COUNT - 1] = SPECIES_KYOGRE,
    [SPECIES_GROUDON_PRIMAL - NATIONAL_DEX_COUNT - 1] = SPECIES_GROUDON,
    [SPECIES_RATTATA_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RATTATA,
    [SPECIES_RATICATE_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RATICATE,
    [SPECIES_RAICHU_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_SANDSHREW_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDSHREW,
    [SPECIES_SANDSLASH_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDSLASH,
    [SPECIES_VULPIX_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VULPIX,
    [SPECIES_NINETALES_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_NINETALES,
    [SPECIES_DIGLETT_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DIGLETT,
    [SPECIES_DUGTRIO_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DUGTRIO,
    [SPECIES_MEOWTH_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_PERSIAN_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_PERSIAN,
    [SPECIES_GEODUDE_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GEODUDE,
    [SPECIES_GRAVELER_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GRAVELER,
    [SPECIES_GOLEM_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLEM,
    [SPECIES_GRIMER_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GRIMER,
    [SPECIES_MUK_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MUK,
    [SPECIES_EXEGGUTOR_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_EXEGGUTOR,
    [SPECIES_MAROWAK_ALOLAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MAROWAK,
    [SPECIES_RATICATE_ALOLAN_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_RATICATE,
    [SPECIES_MAROWAK_ALOLAN_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAROWAK,
    [SPECIES_GUMSHOOS_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_GUMSHOOS,
    [SPECIES_VIKAVOLT_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIKAVOLT,
    [SPECIES_RIBOMBEE_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_RIBOMBEE,
    [SPECIES_ARAQUANID_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_ARAQUANID,
    [SPECIES_LURANTIS_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_LURANTIS,
    [SPECIES_SALAZZLE_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SALAZZLE,
    [SPECIES_TOGEDEMARU_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_TOGEDEMARU,
    [SPECIES_MIMIKYU_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_MIMIKYU_BUSTED_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_KOMMO_O_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_KOMMO_O,
    [SPECIES_MEOWTH_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_PONYTA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_PONYTA,
    [SPECIES_RAPIDASH_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_RAPIDASH,
    [SPECIES_FARFETCHD_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_FARFETCHD,
    [SPECIES_WEEZING_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_WEEZING,
    [SPECIES_MR_MIME_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MR_MIME,
    [SPECIES_ARTICUNO_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ARTICUNO,
    [SPECIES_ZAPDOS_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZAPDOS,
    [SPECIES_MOLTRES_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_MOLTRES,
    [SPECIES_SLOWKING_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SLOWKING,
    [SPECIES_CORSOLA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_CORSOLA,
    [SPECIES_ZIGZAGOON_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZIGZAGOON,
    [SPECIES_LINOONE_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LINOONE,
    [SPECIES_DARUMAKA_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARUMAKA,
    [SPECIES_DARMANITAN_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_YAMASK_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_YAMASK,
    [SPECIES_STUNFISK_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_STUNFISK,
    [SPECIES_PIKACHU_COSPLAY - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ROCK_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_BELLE - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_POP_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_PH_D - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_LIBRE - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ORIGINAL_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_HOENN_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_SINNOH_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_UNOVA_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_KALOS_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_ALOLA_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_PARTNER_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_PIKACHU_WORLD_CAP - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_CASTFORM_SUNNY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CASTFORM_RAINY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CASTFORM_SNOWY - NATIONAL_DEX_COUNT - 1] = SPECIES_CASTFORM,
    [SPECIES_CHERRIM_SUNSHINE - NATIONAL_DEX_COUNT - 1] = SPECIES_CHERRIM,
    [SPECIES_SHELLOS_EAST_SEA - NATIONAL_DEX_COUNT - 1] = SPECIES_SHELLOS,
    [SPECIES_GASTRODON_EAST_SEA - NATIONAL_DEX_COUNT - 1] = SPECIES_GASTRODON,
    [SPECIES_DIALGA_ORIGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_DIALGA,
    [SPECIES_PALKIA_ORIGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_PALKIA,
    [SPECIES_BASCULIN_BLUE_STRIPED - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULIN,
    [SPECIES_BASCULIN_WHITE_STRIPED - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULIN,
    [SPECIES_DARMANITAN_ZEN_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_DARMANITAN_ZEN_MODE_GALARIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DARMANITAN,
    [SPECIES_DEERLING_SUMMER - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_DEERLING_AUTUMN - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_DEERLING_WINTER - NATIONAL_DEX_COUNT - 1] = SPECIES_DEERLING,
    [SPECIES_SAWSBUCK_SUMMER - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_SAWSBUCK_AUTUMN - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_SAWSBUCK_WINTER - NATIONAL_DEX_COUNT - 1] = SPECIES_SAWSBUCK,
    [SPECIES_TORNADUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_TORNADUS,
    [SPECIES_THUNDURUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_THUNDURUS,
    [SPECIES_LANDORUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LANDORUS,
    [SPECIES_KYUREM_WHITE - NATIONAL_DEX_COUNT - 1] = SPECIES_KYUREM,
    [SPECIES_KYUREM_BLACK - NATIONAL_DEX_COUNT - 1] = SPECIES_KYUREM,
    [SPECIES_KELDEO_RESOLUTE - NATIONAL_DEX_COUNT - 1] = SPECIES_KELDEO,
    [SPECIES_MELOETTA_PIROUETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_MELOETTA,
    [SPECIES_GENESECT_DOUSE_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_SHOCK_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_BURN_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GENESECT_CHILL_DRIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_GENESECT,
    [SPECIES_GRENINJA_BATTLE_BOND - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_GRENINJA_ASH - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_VIVILLON_POLAR - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_TUNDRA - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_CONTINENTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_GARDEN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_ELEGANT - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MEADOW - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MODERN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MARINE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_ARCHIPELAGO - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_HIGH_PLAINS - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SANDSTORM - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_RIVER - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_MONSOON - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SAVANNA - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_SUN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_OCEAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_JUNGLE - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_FANCY - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_VIVILLON_POKE_BALL - NATIONAL_DEX_COUNT - 1] = SPECIES_VIVILLON,
    [SPECIES_FLABEBE_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLABEBE_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLABEBE,
    [SPECIES_FLOETTE_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLOETTE_ETERNAL_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_FLORGES_YELLOW_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_ORANGE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_BLUE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FLORGES_WHITE_FLOWER - NATIONAL_DEX_COUNT - 1] = SPECIES_FLORGES,
    [SPECIES_FURFROU_HEART - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_STAR - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DIAMOND - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DEBUTANTE - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_MATRON - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_DANDY - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_LA_REINE - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_KABUKI - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_FURFROU_PHARAOH - NATIONAL_DEX_COUNT - 1] = SPECIES_FURFROU,
    [SPECIES_AEGISLASH_BLADE - NATIONAL_DEX_COUNT - 1] = SPECIES_AEGISLASH,
    [SPECIES_PUMPKABOO_SMALL - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_PUMPKABOO_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_PUMPKABOO_SUPER - NATIONAL_DEX_COUNT - 1] = SPECIES_PUMPKABOO,
    [SPECIES_GOURGEIST_SMALL - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_GOURGEIST_LARGE - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_GOURGEIST_SUPER - NATIONAL_DEX_COUNT - 1] = SPECIES_GOURGEIST,
    [SPECIES_XERNEAS_ACTIVE - NATIONAL_DEX_COUNT - 1] = SPECIES_XERNEAS,
    [SPECIES_ZYGARDE_10 - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_10_POWER_CONSTRUCT - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_50_POWER_CONSTRUCT - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_10_COMPLETE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_ZYGARDE_50_COMPLETE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_HOOPA_UNBOUND - NATIONAL_DEX_COUNT - 1] = SPECIES_HOOPA,
    [SPECIES_ORICORIO_POM_POM - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ORICORIO_PAU - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ORICORIO_SENSU - NATIONAL_DEX_COUNT - 1] = SPECIES_ORICORIO,
    [SPECIES_ROCKRUFF_OWN_TEMPO - NATIONAL_DEX_COUNT - 1] = SPECIES_ROCKRUFF,
    [SPECIES_LYCANROC_MIDNIGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_LYCANROC,
    [SPECIES_LYCANROC_DUSK - NATIONAL_DEX_COUNT - 1] = SPECIES_LYCANROC,
    [SPECIES_WISHIWASHI_SCHOOL - NATIONAL_DEX_COUNT - 1] = SPECIES_WISHIWASHI,
    [SPECIES_MINIOR_METEOR_ORANGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_YELLOW - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_GREEN - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_BLUE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_INDIGO - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_METEOR_VIOLET - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_RED - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_ORANGE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_YELLOW - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_GREEN - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_BLUE - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_INDIGO - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MINIOR_CORE_VIOLET - NATIONAL_DEX_COUNT - 1] = SPECIES_MINIOR,
    [SPECIES_MIMIKYU_BUSTED - NATIONAL_DEX_COUNT - 1] = SPECIES_MIMIKYU,
    [SPECIES_NECROZMA_DUSK_MANE - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_DAWN_WINGS - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_ULTRA_DUSK_MANE - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_NECROZMA_ULTRA_DAWN_WINGS - NATIONAL_DEX_COUNT - 1] = SPECIES_NECROZMA,
    [SPECIES_MAGEARNA_ORIGINAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_PIKACHU_PARTNER - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_EEVEE_PARTNER - NATIONAL_DEX_COUNT - 1] = SPECIES_EEVEE,
    [SPECIES_CRAMORANT_GULPING - NATIONAL_DEX_COUNT - 1] = SPECIES_CRAMORANT,
    [SPECIES_CRAMORANT_GORGING - NATIONAL_DEX_COUNT - 1] = SPECIES_CRAMORANT,
    [SPECIES_TOXTRICITY_LOW_KEY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_SINISTEA_ANTIQUE - NATIONAL_DEX_COUNT - 1] = SPECIES_SINISTEA,
    [SPECIES_POLTEAGEIST_ANTIQUE - NATIONAL_DEX_COUNT - 1] = SPECIES_POLTEAGEIST,
    [SPECIES_ALCREMIE_BERRY_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_LOVE_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_STAR_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_CLOVER_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_FLOWER_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_ALCREMIE_RIBBON_SWEET - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_EISCUE_NOICE_FACE - NATIONAL_DEX_COUNT - 1] = SPECIES_EISCUE,
    [SPECIES_MORPEKO_HANGRY - NATIONAL_DEX_COUNT - 1] = SPECIES_MORPEKO,
    [SPECIES_ZACIAN_CROWNED - NATIONAL_DEX_COUNT - 1] = SPECIES_ZACIAN,
    [SPECIES_ZAMAZENTA_CROWNED - NATIONAL_DEX_COUNT - 1] = SPECIES_ZAMAZENTA,
    [SPECIES_ETERNATUS_ETERNAMAX - NATIONAL_DEX_COUNT - 1] = SPECIES_ETERNATUS,
    [SPECIES_URSHIFU_RAPID_STRIKE - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_ZARUDE_DADA - NATIONAL_DEX_COUNT - 1] = SPECIES_ZARUDE,
    [SPECIES_CALYREX_ICE_RIDER - NATIONAL_DEX_COUNT - 1] = SPECIES_CALYREX,
    [SPECIES_CALYREX_SHADOW_RIDER - NATIONAL_DEX_COUNT - 1] = SPECIES_CALYREX,
    [SPECIES_ENAMORUS_THERIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ENAMORUS,
    [SPECIES_GROWLITHE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GROWLITHE,
    [SPECIES_ARCANINE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ARCANINE,
    [SPECIES_VOLTORB_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_VOLTORB,
    [SPECIES_ELECTRODE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ELECTRODE,
    [SPECIES_TYPHLOSION_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_TYPHLOSION,
    [SPECIES_QWILFISH_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_QWILFISH,
    [SPECIES_SNEASEL_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SNEASEL,
    [SPECIES_SAMUROTT_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SAMUROTT,
    [SPECIES_LILLIGANT_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_LILLIGANT,
    [SPECIES_ZORUA_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZORUA,
    [SPECIES_ZOROARK_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_ZOROARK,
    [SPECIES_BRAVIARY_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_BRAVIARY,
    [SPECIES_SLIGGOO_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_SLIGGOO,
    [SPECIES_GOODRA_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_GOODRA,
    [SPECIES_AVALUGG_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_AVALUGG,
    [SPECIES_DECIDUEYE_HISUIAN - NATIONAL_DEX_COUNT - 1] = SPECIES_DECIDUEYE,
    [SPECIES_KLEAVOR_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_KLEAVOR,
    [SPECIES_LILLIGANT_LADY - NATIONAL_DEX_COUNT - 1] = SPECIES_LILLIGANT,
    [SPECIES_ARCANINE_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_ARCANINE,
    [SPECIES_ELECTRODE_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_ELECTRODE,
    [SPECIES_AVALUGG_LORD - NATIONAL_DEX_COUNT - 1] = SPECIES_AVALUGG,
    [SPECIES_UNFEZANT_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_UNFEZANT,
    [SPECIES_FRILLISH_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_FRILLISH,
    [SPECIES_JELLICENT_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_JELLICENT,
    [SPECIES_PYROAR_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_PYROAR,
    [SPECIES_MEOWSTIC_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_INDEEDEE_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_INDEEDEE,
    [SPECIES_BASCULEGION_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_BASCULEGION,
    [SPECIES_MAUSHOLD_FAMILY_OF_THREE - NATIONAL_DEX_COUNT - 1] = SPECIES_MAUSHOLD,
    [SPECIES_SQUAWKABILLY_BLUE_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_SQUAWKABILLY_WHITE_PLUMAGE - NATIONAL_DEX_COUNT - 1] = SPECIES_SQUAWKABILLY,
    [SPECIES_PALAFIN_HERO - NATIONAL_DEX_COUNT - 1] = SPECIES_PALAFIN,
    [SPECIES_TATSUGIRI_DROOPY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_TATSUGIRI_STRETCHY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_DUDUNSPARCE_THREE_SEGMENT - NATIONAL_DEX_COUNT - 1] = SPECIES_DUDUNSPARCE,
    [SPECIES_GIMMIGHOUL_ROAMING - NATIONAL_DEX_COUNT - 1] = SPECIES_GIMMIGHOUL,
    [SPECIES_WOOPER_PALDEAN - NATIONAL_DEX_COUNT - 1] = SPECIES_WOOPER,
    [SPECIES_TAUROS_COMBAT - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_TAUROS_BLAZE - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_TAUROS_AQUA - NATIONAL_DEX_COUNT - 1] = SPECIES_TAUROS,
    [SPECIES_OINKOLOGNE_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_OINKOLOGNE,
    [SPECIES_REVAVROOM_SEGIN - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_SCHEDAR - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_NAVI - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_RUCHBAH - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_REVAVROOM_CAPH - NATIONAL_DEX_COUNT - 1] = SPECIES_REVAVROOM,
    [SPECIES_KORAIDON_LIMITED_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_SPRINTING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_SWIMMING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_KORAIDON_GLIDING_BUILD - NATIONAL_DEX_COUNT - 1] = SPECIES_KORAIDON,
    [SPECIES_MIRAIDON_LOW_POWER_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_DRIVE_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_AQUATIC_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_MIRAIDON_GLIDE_MODE - NATIONAL_DEX_COUNT - 1] = SPECIES_MIRAIDON,
    [SPECIES_POLTCHAGEIST_MASTERPIECE - NATIONAL_DEX_COUNT - 1] = SPECIES_POLTCHAGEIST,
    [SPECIES_SINISTCHA_MASTERPIECE - NATIONAL_DEX_COUNT - 1] = SPECIES_SINISTCHA,
    [SPECIES_OGERPON_WELLSPRING_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_HEARTHFLAME_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_CORNERSTONE_MASK - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_TEAL_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_WELLSPRING_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_HEARTHFLAME_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_OGERPON_CORNERSTONE_MASK_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_OGERPON,
    [SPECIES_URSALUNA_BLOODMOON - NATIONAL_DEX_COUNT - 1] = SPECIES_URSALUNA,
    [SPECIES_TERAPAGOS_TERASTAL - NATIONAL_DEX_COUNT - 1] = SPECIES_TERAPAGOS,
    [SPECIES_TERAPAGOS_STELLAR - NATIONAL_DEX_COUNT - 1] = SPECIES_TERAPAGOS,
    [SPECIES_GIGANTAMAX_VENUSAUR - NATIONAL_DEX_COUNT - 1] = SPECIES_VENUSAUR,
    [SPECIES_GIGANTAMAX_CHARIZARD - NATIONAL_DEX_COUNT - 1] = SPECIES_CHARIZARD,
    [SPECIES_GIGANTAMAX_BLASTOISE - NATIONAL_DEX_COUNT - 1] = SPECIES_BLASTOISE,
    [SPECIES_GIGANTAMAX_BUTTERFREE - NATIONAL_DEX_COUNT - 1] = SPECIES_BUTTERFREE,
    [SPECIES_GIGANTAMAX_PIKACHU - NATIONAL_DEX_COUNT - 1] = SPECIES_PIKACHU,
    [SPECIES_GIGANTAMAX_MEOWTH - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWTH,
    [SPECIES_GIGANTAMAX_MACHAMP - NATIONAL_DEX_COUNT - 1] = SPECIES_MACHAMP,
    [SPECIES_GIGANTAMAX_GENGAR - NATIONAL_DEX_COUNT - 1] = SPECIES_GENGAR,
    [SPECIES_GIGANTAMAX_KINGLER - NATIONAL_DEX_COUNT - 1] = SPECIES_KINGLER,
    [SPECIES_GIGANTAMAX_LAPRAS - NATIONAL_DEX_COUNT - 1] = SPECIES_LAPRAS,
    [SPECIES_GIGANTAMAX_EEVEE - NATIONAL_DEX_COUNT - 1] = SPECIES_EEVEE,
    [SPECIES_GIGANTAMAX_SNORLAX - NATIONAL_DEX_COUNT - 1] = SPECIES_SNORLAX,
    [SPECIES_GIGANTAMAX_GARBODOR - NATIONAL_DEX_COUNT - 1] = SPECIES_GARBODOR,
    [SPECIES_GIGANTAMAX_MELMETAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MELMETAL,
    [SPECIES_GIGANTAMAX_RILLABOOM - NATIONAL_DEX_COUNT - 1] = SPECIES_RILLABOOM,
    [SPECIES_GIGANTAMAX_CINDERACE - NATIONAL_DEX_COUNT - 1] = SPECIES_CINDERACE,
    [SPECIES_GIGANTAMAX_INTELEON - NATIONAL_DEX_COUNT - 1] = SPECIES_INTELEON,
    [SPECIES_GIGANTAMAX_CORVIKNIGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_CORVIKNIGHT,
    [SPECIES_GIGANTAMAX_ORBEETLE - NATIONAL_DEX_COUNT - 1] = SPECIES_ORBEETLE,
    [SPECIES_GIGANTAMAX_DREDNAW - NATIONAL_DEX_COUNT - 1] = SPECIES_DREDNAW,
    [SPECIES_GIGANTAMAX_COALOSSAL - NATIONAL_DEX_COUNT - 1] = SPECIES_COALOSSAL,
    [SPECIES_GIGANTAMAX_FLAPPLE - NATIONAL_DEX_COUNT - 1] = SPECIES_FLAPPLE,
    [SPECIES_GIGANTAMAX_APPLETUN - NATIONAL_DEX_COUNT - 1] = SPECIES_APPLETUN,
    [SPECIES_GIGANTAMAX_SANDACONDA - NATIONAL_DEX_COUNT - 1] = SPECIES_SANDACONDA,
    [SPECIES_GIGANTAMAX_TOXTRICITY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_GIGANTAMAX_TOXTRICITY_LOW_KEY - NATIONAL_DEX_COUNT - 1] = SPECIES_TOXTRICITY,
    [SPECIES_GIGANTAMAX_CENTISKORCH - NATIONAL_DEX_COUNT - 1] = SPECIES_CENTISKORCH,
    [SPECIES_GIGANTAMAX_HATTERENE - NATIONAL_DEX_COUNT - 1] = SPECIES_HATTERENE,
    [SPECIES_GIGANTAMAX_GRIMMSNARL - NATIONAL_DEX_COUNT - 1] = SPECIES_GRIMMSNARL,
    [SPECIES_GIGANTAMAX_ALCREMIE - NATIONAL_DEX_COUNT - 1] = SPECIES_ALCREMIE,
    [SPECIES_GIGANTAMAX_COPPERAJAH - NATIONAL_DEX_COUNT - 1] = SPECIES_COPPERAJAH,
    [SPECIES_GIGANTAMAX_DURALUDON - NATIONAL_DEX_COUNT - 1] = SPECIES_DURALUDON,
    [SPECIES_GIGANTAMAX_URSHIFU - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_GIGANTAMAX_URSHIFU_RAPID_STRIKE - NATIONAL_DEX_COUNT - 1] = SPECIES_URSHIFU,
    [SPECIES_MEGA_RAICHU_X - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_MEGA_RAICHU_Y - NATIONAL_DEX_COUNT - 1] = SPECIES_RAICHU,
    [SPECIES_MEGA_CLEFABLE - NATIONAL_DEX_COUNT - 1] = SPECIES_CLEFABLE,
    [SPECIES_MEGA_VICTREEBEL - NATIONAL_DEX_COUNT - 1] = SPECIES_VICTREEBEL,
    [SPECIES_MEGA_STARMIE - NATIONAL_DEX_COUNT - 1] = SPECIES_STARMIE,
    [SPECIES_MEGA_DRAGONITE - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAGONITE,
    [SPECIES_MEGA_MEGANIUM - NATIONAL_DEX_COUNT - 1] = SPECIES_MEGANIUM,
    [SPECIES_MEGA_FERALIGATR - NATIONAL_DEX_COUNT - 1] = SPECIES_FERALIGATR,
    [SPECIES_MEGA_SKARMORY - NATIONAL_DEX_COUNT - 1] = SPECIES_SKARMORY,
    [SPECIES_MEGA_CHIMECHO - NATIONAL_DEX_COUNT - 1] = SPECIES_CHIMECHO,
    [SPECIES_MEGA_ABSOL_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_ABSOL,
    [SPECIES_MEGA_STARAPTOR - NATIONAL_DEX_COUNT - 1] = SPECIES_STARAPTOR,
    [SPECIES_MEGA_GARCHOMP_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_GARCHOMP,
    [SPECIES_MEGA_LUCARIO_Z - NATIONAL_DEX_COUNT - 1] = SPECIES_LUCARIO,
    [SPECIES_MEGA_FROSLASS - NATIONAL_DEX_COUNT - 1] = SPECIES_FROSLASS,
    [SPECIES_MEGA_HEATRAN - NATIONAL_DEX_COUNT - 1] = SPECIES_HEATRAN,
    [SPECIES_MEGA_DARKRAI - NATIONAL_DEX_COUNT - 1] = SPECIES_DARKRAI,
    [SPECIES_MEGA_EMBOAR - NATIONAL_DEX_COUNT - 1] = SPECIES_EMBOAR,
    [SPECIES_MEGA_EXCADRILL - NATIONAL_DEX_COUNT - 1] = SPECIES_EXCADRILL,
    [SPECIES_MEGA_SCOLIPEDE - NATIONAL_DEX_COUNT - 1] = SPECIES_SCOLIPEDE,
    [SPECIES_MEGA_SCRAFTY - NATIONAL_DEX_COUNT - 1] = SPECIES_SCRAFTY,
    [SPECIES_MEGA_EELEKTROSS - NATIONAL_DEX_COUNT - 1] = SPECIES_EELEKTROSS,
    [SPECIES_MEGA_CHANDELURE - NATIONAL_DEX_COUNT - 1] = SPECIES_CHANDELURE,
    [SPECIES_MEGA_GOLURK - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLURK,
    [SPECIES_MEGA_CHESNAUGHT - NATIONAL_DEX_COUNT - 1] = SPECIES_CHESNAUGHT,
    [SPECIES_MEGA_DELPHOX - NATIONAL_DEX_COUNT - 1] = SPECIES_DELPHOX,
    [SPECIES_MEGA_GRENINJA - NATIONAL_DEX_COUNT - 1] = SPECIES_GRENINJA,
    [SPECIES_MEGA_PYROAR - NATIONAL_DEX_COUNT - 1] = SPECIES_PYROAR,
    [SPECIES_MEGA_FLOETTE - NATIONAL_DEX_COUNT - 1] = SPECIES_FLOETTE,
    [SPECIES_MEGA_MEOWSTIC - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_MEGA_MEOWSTIC_FEMALE - NATIONAL_DEX_COUNT - 1] = SPECIES_MEOWSTIC,
    [SPECIES_MEGA_MALAMAR - NATIONAL_DEX_COUNT - 1] = SPECIES_MALAMAR,
    [SPECIES_MEGA_BARBARACLE - NATIONAL_DEX_COUNT - 1] = SPECIES_BARBARACLE,
    [SPECIES_MEGA_DRAGALGE - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAGALGE,
    [SPECIES_MEGA_HAWLUCHA - NATIONAL_DEX_COUNT - 1] = SPECIES_HAWLUCHA,
    [SPECIES_MEGA_ZYGARDE - NATIONAL_DEX_COUNT - 1] = SPECIES_ZYGARDE,
    [SPECIES_MEGA_CRABOMINABLE - NATIONAL_DEX_COUNT - 1] = SPECIES_CRABOMINABLE,
    [SPECIES_MEGA_GOLISOPOD - NATIONAL_DEX_COUNT - 1] = SPECIES_GOLISOPOD,
    [SPECIES_MEGA_DRAMPA - NATIONAL_DEX_COUNT - 1] = SPECIES_DRAMPA,
    [SPECIES_MEGA_MAGEARNA - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_MEGA_MAGEARNA_ORIGINAL - NATIONAL_DEX_COUNT - 1] = SPECIES_MAGEARNA,
    [SPECIES_MEGA_ZERAORA - NATIONAL_DEX_COUNT - 1] = SPECIES_ZERAORA,
    [SPECIES_MEGA_FALINKS - NATIONAL_DEX_COUNT - 1] = SPECIES_FALINKS,
    [SPECIES_MEGA_SCOVILLAIN - NATIONAL_DEX_COUNT - 1] = SPECIES_SCOVILLAIN,
    [SPECIES_MEGA_GLIMMORA - NATIONAL_DEX_COUNT - 1] = SPECIES_GLIMMORA,
    [SPECIES_MEGA_TATSUGIRI - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_TATSUGIRI_DROOPY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_TATSUGIRI_STRETCHY - NATIONAL_DEX_COUNT - 1] = SPECIES_TATSUGIRI,
    [SPECIES_MEGA_BAXCALIBUR - NATIONAL_DEX_COUNT - 1] = SPECIES_BAXCALIBUR,
};

// Every species past the last Dex species is a form here, a female Pyroar or
// a Mega Venusaur. hg-engine stores a form as its base species and a form
// number, so its Dex credits and numbers the base; this is how ours does.
// Galarian Slowpoke and Slowbro are forms in hg-engine too, kept here as
// species inside the Dex's range (the trainer table names them): they are
// credited to Slowpoke and Slowbro in the same way, and have no Dex entry of
// their own to count (Pokedex_IsOwnDexEntry).
u16 SpeciesToDexSpecies(u16 species) {
    if (species > NATIONAL_DEX_COUNT && species <= NUM_SPECIES) {
        return sFormBaseSpecies[species - NATIONAL_DEX_COUNT - 1];
    }
    if (species == SPECIES_SLOWPOKE_GALARIAN) {
        return SPECIES_SLOWPOKE;
    }
    if (species == SPECIES_SLOWBRO_GALARIAN) {
        return SPECIES_SLOWBRO;
    }
    return species;
}

// The National Dex counts walk the species up to the last Dex species; a
// species credited to another is counted as that one, not again.
static BOOL Pokedex_IsOwnDexEntry(u16 species) {
    return SpeciesToDexSpecies(species) == species;
}

// The National Dex number of each species after the Dex gap. Those species
// were appended rather than placed at their numbers, so Lillipup is species
// 508 and No. 506 (and the two Galarian forms kept as species of their own
// are Slowpoke's and Slowbro's numbers). Written by
// tools/newgold/import/import_species.py from the reference's numbering; do
// not edit it by hand.
static const u16 sNationalDexNumbers[NATIONAL_DEX_COUNT - LAST_DEX_GAP] = {
    [SPECIES_LILLIPUP - LAST_DEX_GAP - 1] = 506,
    [SPECIES_HERDIER - LAST_DEX_GAP - 1] = 507,
    [SPECIES_STOUTLAND - LAST_DEX_GAP - 1] = 508,
    [SPECIES_PURRLOIN - LAST_DEX_GAP - 1] = 509,
    [SPECIES_LIEPARD - LAST_DEX_GAP - 1] = 510,
    [SPECIES_TYMPOLE - LAST_DEX_GAP - 1] = 535,
    [SPECIES_PALPITOAD - LAST_DEX_GAP - 1] = 536,
    [SPECIES_SEISMITOAD - LAST_DEX_GAP - 1] = 537,
    [SPECIES_SEWADDLE - LAST_DEX_GAP - 1] = 540,
    [SPECIES_SWADLOON - LAST_DEX_GAP - 1] = 541,
    [SPECIES_LEAVANNY - LAST_DEX_GAP - 1] = 542,
    [SPECIES_YAMASK - LAST_DEX_GAP - 1] = 562,
    [SPECIES_COFAGRIGUS - LAST_DEX_GAP - 1] = 563,
    [SPECIES_TRUBBISH - LAST_DEX_GAP - 1] = 568,
    [SPECIES_GARBODOR - LAST_DEX_GAP - 1] = 569,
    [SPECIES_EMOLGA - LAST_DEX_GAP - 1] = 587,
    [SPECIES_KARRABLAST - LAST_DEX_GAP - 1] = 588,
    [SPECIES_ESCAVALIER - LAST_DEX_GAP - 1] = 589,
    [SPECIES_FOONGUS - LAST_DEX_GAP - 1] = 590,
    [SPECIES_AMOONGUSS - LAST_DEX_GAP - 1] = 591,
    [SPECIES_JOLTIK - LAST_DEX_GAP - 1] = 595,
    [SPECIES_GALVANTULA - LAST_DEX_GAP - 1] = 596,
    [SPECIES_FERROSEED - LAST_DEX_GAP - 1] = 597,
    [SPECIES_FERROTHORN - LAST_DEX_GAP - 1] = 598,
    [SPECIES_KLINK - LAST_DEX_GAP - 1] = 599,
    [SPECIES_KLANG - LAST_DEX_GAP - 1] = 600,
    [SPECIES_KLINKLANG - LAST_DEX_GAP - 1] = 601,
    [SPECIES_ELGYEM - LAST_DEX_GAP - 1] = 605,
    [SPECIES_BEHEEYEM - LAST_DEX_GAP - 1] = 606,
    [SPECIES_LITWICK - LAST_DEX_GAP - 1] = 607,
    [SPECIES_LAMPENT - LAST_DEX_GAP - 1] = 608,
    [SPECIES_CHANDELURE - LAST_DEX_GAP - 1] = 609,
    [SPECIES_SHELMET - LAST_DEX_GAP - 1] = 616,
    [SPECIES_ACCELGOR - LAST_DEX_GAP - 1] = 617,
    [SPECIES_BOUFFALANT - LAST_DEX_GAP - 1] = 626,
    [SPECIES_BUNNELBY - LAST_DEX_GAP - 1] = 659,
    [SPECIES_DIGGERSBY - LAST_DEX_GAP - 1] = 660,
    [SPECIES_FLETCHLING - LAST_DEX_GAP - 1] = 661,
    [SPECIES_FLETCHINDER - LAST_DEX_GAP - 1] = 662,
    [SPECIES_TALONFLAME - LAST_DEX_GAP - 1] = 663,
    [SPECIES_LITLEO - LAST_DEX_GAP - 1] = 667,
    [SPECIES_PYROAR - LAST_DEX_GAP - 1] = 668,
    [SPECIES_ESPURR - LAST_DEX_GAP - 1] = 677,
    [SPECIES_MEOWSTIC - LAST_DEX_GAP - 1] = 678,
    [SPECIES_SYLVEON - LAST_DEX_GAP - 1] = 700,
    [SPECIES_DEDENNE - LAST_DEX_GAP - 1] = 702,
    [SPECIES_PHANTUMP - LAST_DEX_GAP - 1] = 708,
    [SPECIES_TREVENANT - LAST_DEX_GAP - 1] = 709,
    [SPECIES_PUMPKABOO - LAST_DEX_GAP - 1] = 710,
    [SPECIES_GOURGEIST - LAST_DEX_GAP - 1] = 711,
    [SPECIES_NOIBAT - LAST_DEX_GAP - 1] = 714,
    [SPECIES_NOIVERN - LAST_DEX_GAP - 1] = 715,
    [SPECIES_APPLIN - LAST_DEX_GAP - 1] = 840,
    [SPECIES_FLAPPLE - LAST_DEX_GAP - 1] = 841,
    [SPECIES_APPLETUN - LAST_DEX_GAP - 1] = 842,
    [SPECIES_SIZZLIPEDE - LAST_DEX_GAP - 1] = 850,
    [SPECIES_CENTISKORCH - LAST_DEX_GAP - 1] = 851,
    [SPECIES_WYRDEER - LAST_DEX_GAP - 1] = 899,
    [SPECIES_KLEAVOR - LAST_DEX_GAP - 1] = 900,
    [SPECIES_URSALUNA - LAST_DEX_GAP - 1] = 901,
    [SPECIES_ANNIHILAPE - LAST_DEX_GAP - 1] = 979,
    [SPECIES_FARIGIRAF - LAST_DEX_GAP - 1] = 981,
    [SPECIES_DUDUNSPARCE - LAST_DEX_GAP - 1] = 982,
    [SPECIES_DIPPLIN - LAST_DEX_GAP - 1] = 1011,
    [SPECIES_HYDRAPPLE - LAST_DEX_GAP - 1] = 1019,
    [SPECIES_SLOWPOKE_GALARIAN - LAST_DEX_GAP - 1] = 79,
    [SPECIES_SLOWBRO_GALARIAN - LAST_DEX_GAP - 1] = 80,
    [SPECIES_VICTINI - LAST_DEX_GAP - 1] = 494,
    [SPECIES_SNIVY - LAST_DEX_GAP - 1] = 495,
    [SPECIES_SERVINE - LAST_DEX_GAP - 1] = 496,
    [SPECIES_SERPERIOR - LAST_DEX_GAP - 1] = 497,
    [SPECIES_TEPIG - LAST_DEX_GAP - 1] = 498,
    [SPECIES_PIGNITE - LAST_DEX_GAP - 1] = 499,
    [SPECIES_EMBOAR - LAST_DEX_GAP - 1] = 500,
    [SPECIES_OSHAWOTT - LAST_DEX_GAP - 1] = 501,
    [SPECIES_DEWOTT - LAST_DEX_GAP - 1] = 502,
    [SPECIES_SAMUROTT - LAST_DEX_GAP - 1] = 503,
    [SPECIES_PATRAT - LAST_DEX_GAP - 1] = 504,
    [SPECIES_WATCHOG - LAST_DEX_GAP - 1] = 505,
    [SPECIES_PANSAGE - LAST_DEX_GAP - 1] = 511,
    [SPECIES_SIMISAGE - LAST_DEX_GAP - 1] = 512,
    [SPECIES_PANSEAR - LAST_DEX_GAP - 1] = 513,
    [SPECIES_SIMISEAR - LAST_DEX_GAP - 1] = 514,
    [SPECIES_PANPOUR - LAST_DEX_GAP - 1] = 515,
    [SPECIES_SIMIPOUR - LAST_DEX_GAP - 1] = 516,
    [SPECIES_MUNNA - LAST_DEX_GAP - 1] = 517,
    [SPECIES_MUSHARNA - LAST_DEX_GAP - 1] = 518,
    [SPECIES_PIDOVE - LAST_DEX_GAP - 1] = 519,
    [SPECIES_TRANQUILL - LAST_DEX_GAP - 1] = 520,
    [SPECIES_UNFEZANT - LAST_DEX_GAP - 1] = 521,
    [SPECIES_BLITZLE - LAST_DEX_GAP - 1] = 522,
    [SPECIES_ZEBSTRIKA - LAST_DEX_GAP - 1] = 523,
    [SPECIES_ROGGENROLA - LAST_DEX_GAP - 1] = 524,
    [SPECIES_BOLDORE - LAST_DEX_GAP - 1] = 525,
    [SPECIES_GIGALITH - LAST_DEX_GAP - 1] = 526,
    [SPECIES_WOOBAT - LAST_DEX_GAP - 1] = 527,
    [SPECIES_SWOOBAT - LAST_DEX_GAP - 1] = 528,
    [SPECIES_DRILBUR - LAST_DEX_GAP - 1] = 529,
    [SPECIES_EXCADRILL - LAST_DEX_GAP - 1] = 530,
    [SPECIES_AUDINO - LAST_DEX_GAP - 1] = 531,
    [SPECIES_TIMBURR - LAST_DEX_GAP - 1] = 532,
    [SPECIES_GURDURR - LAST_DEX_GAP - 1] = 533,
    [SPECIES_CONKELDURR - LAST_DEX_GAP - 1] = 534,
    [SPECIES_THROH - LAST_DEX_GAP - 1] = 538,
    [SPECIES_SAWK - LAST_DEX_GAP - 1] = 539,
    [SPECIES_VENIPEDE - LAST_DEX_GAP - 1] = 543,
    [SPECIES_WHIRLIPEDE - LAST_DEX_GAP - 1] = 544,
    [SPECIES_SCOLIPEDE - LAST_DEX_GAP - 1] = 545,
    [SPECIES_COTTONEE - LAST_DEX_GAP - 1] = 546,
    [SPECIES_WHIMSICOTT - LAST_DEX_GAP - 1] = 547,
    [SPECIES_PETILIL - LAST_DEX_GAP - 1] = 548,
    [SPECIES_LILLIGANT - LAST_DEX_GAP - 1] = 549,
    [SPECIES_BASCULIN - LAST_DEX_GAP - 1] = 550,
    [SPECIES_SANDILE - LAST_DEX_GAP - 1] = 551,
    [SPECIES_KROKOROK - LAST_DEX_GAP - 1] = 552,
    [SPECIES_KROOKODILE - LAST_DEX_GAP - 1] = 553,
    [SPECIES_DARUMAKA - LAST_DEX_GAP - 1] = 554,
    [SPECIES_DARMANITAN - LAST_DEX_GAP - 1] = 555,
    [SPECIES_MARACTUS - LAST_DEX_GAP - 1] = 556,
    [SPECIES_DWEBBLE - LAST_DEX_GAP - 1] = 557,
    [SPECIES_CRUSTLE - LAST_DEX_GAP - 1] = 558,
    [SPECIES_SCRAGGY - LAST_DEX_GAP - 1] = 559,
    [SPECIES_SCRAFTY - LAST_DEX_GAP - 1] = 560,
    [SPECIES_SIGILYPH - LAST_DEX_GAP - 1] = 561,
    [SPECIES_TIRTOUGA - LAST_DEX_GAP - 1] = 564,
    [SPECIES_CARRACOSTA - LAST_DEX_GAP - 1] = 565,
    [SPECIES_ARCHEN - LAST_DEX_GAP - 1] = 566,
    [SPECIES_ARCHEOPS - LAST_DEX_GAP - 1] = 567,
    [SPECIES_ZORUA - LAST_DEX_GAP - 1] = 570,
    [SPECIES_ZOROARK - LAST_DEX_GAP - 1] = 571,
    [SPECIES_MINCCINO - LAST_DEX_GAP - 1] = 572,
    [SPECIES_CINCCINO - LAST_DEX_GAP - 1] = 573,
    [SPECIES_GOTHITA - LAST_DEX_GAP - 1] = 574,
    [SPECIES_GOTHORITA - LAST_DEX_GAP - 1] = 575,
    [SPECIES_GOTHITELLE - LAST_DEX_GAP - 1] = 576,
    [SPECIES_SOLOSIS - LAST_DEX_GAP - 1] = 577,
    [SPECIES_DUOSION - LAST_DEX_GAP - 1] = 578,
    [SPECIES_REUNICLUS - LAST_DEX_GAP - 1] = 579,
    [SPECIES_DUCKLETT - LAST_DEX_GAP - 1] = 580,
    [SPECIES_SWANNA - LAST_DEX_GAP - 1] = 581,
    [SPECIES_VANILLITE - LAST_DEX_GAP - 1] = 582,
    [SPECIES_VANILLISH - LAST_DEX_GAP - 1] = 583,
    [SPECIES_VANILLUXE - LAST_DEX_GAP - 1] = 584,
    [SPECIES_DEERLING - LAST_DEX_GAP - 1] = 585,
    [SPECIES_SAWSBUCK - LAST_DEX_GAP - 1] = 586,
    [SPECIES_FRILLISH - LAST_DEX_GAP - 1] = 592,
    [SPECIES_JELLICENT - LAST_DEX_GAP - 1] = 593,
    [SPECIES_ALOMOMOLA - LAST_DEX_GAP - 1] = 594,
    [SPECIES_TYNAMO - LAST_DEX_GAP - 1] = 602,
    [SPECIES_EELEKTRIK - LAST_DEX_GAP - 1] = 603,
    [SPECIES_EELEKTROSS - LAST_DEX_GAP - 1] = 604,
    [SPECIES_AXEW - LAST_DEX_GAP - 1] = 610,
    [SPECIES_FRAXURE - LAST_DEX_GAP - 1] = 611,
    [SPECIES_HAXORUS - LAST_DEX_GAP - 1] = 612,
    [SPECIES_CUBCHOO - LAST_DEX_GAP - 1] = 613,
    [SPECIES_BEARTIC - LAST_DEX_GAP - 1] = 614,
    [SPECIES_CRYOGONAL - LAST_DEX_GAP - 1] = 615,
    [SPECIES_STUNFISK - LAST_DEX_GAP - 1] = 618,
    [SPECIES_MIENFOO - LAST_DEX_GAP - 1] = 619,
    [SPECIES_MIENSHAO - LAST_DEX_GAP - 1] = 620,
    [SPECIES_DRUDDIGON - LAST_DEX_GAP - 1] = 621,
    [SPECIES_GOLETT - LAST_DEX_GAP - 1] = 622,
    [SPECIES_GOLURK - LAST_DEX_GAP - 1] = 623,
    [SPECIES_PAWNIARD - LAST_DEX_GAP - 1] = 624,
    [SPECIES_BISHARP - LAST_DEX_GAP - 1] = 625,
    [SPECIES_RUFFLET - LAST_DEX_GAP - 1] = 627,
    [SPECIES_BRAVIARY - LAST_DEX_GAP - 1] = 628,
    [SPECIES_VULLABY - LAST_DEX_GAP - 1] = 629,
    [SPECIES_MANDIBUZZ - LAST_DEX_GAP - 1] = 630,
    [SPECIES_HEATMOR - LAST_DEX_GAP - 1] = 631,
    [SPECIES_DURANT - LAST_DEX_GAP - 1] = 632,
    [SPECIES_DEINO - LAST_DEX_GAP - 1] = 633,
    [SPECIES_ZWEILOUS - LAST_DEX_GAP - 1] = 634,
    [SPECIES_HYDREIGON - LAST_DEX_GAP - 1] = 635,
    [SPECIES_LARVESTA - LAST_DEX_GAP - 1] = 636,
    [SPECIES_VOLCARONA - LAST_DEX_GAP - 1] = 637,
    [SPECIES_COBALION - LAST_DEX_GAP - 1] = 638,
    [SPECIES_TERRAKION - LAST_DEX_GAP - 1] = 639,
    [SPECIES_VIRIZION - LAST_DEX_GAP - 1] = 640,
    [SPECIES_TORNADUS - LAST_DEX_GAP - 1] = 641,
    [SPECIES_THUNDURUS - LAST_DEX_GAP - 1] = 642,
    [SPECIES_RESHIRAM - LAST_DEX_GAP - 1] = 643,
    [SPECIES_ZEKROM - LAST_DEX_GAP - 1] = 644,
    [SPECIES_LANDORUS - LAST_DEX_GAP - 1] = 645,
    [SPECIES_KYUREM - LAST_DEX_GAP - 1] = 646,
    [SPECIES_KELDEO - LAST_DEX_GAP - 1] = 647,
    [SPECIES_MELOETTA - LAST_DEX_GAP - 1] = 648,
    [SPECIES_GENESECT - LAST_DEX_GAP - 1] = 649,
    [SPECIES_CHESPIN - LAST_DEX_GAP - 1] = 650,
    [SPECIES_QUILLADIN - LAST_DEX_GAP - 1] = 651,
    [SPECIES_CHESNAUGHT - LAST_DEX_GAP - 1] = 652,
    [SPECIES_FENNEKIN - LAST_DEX_GAP - 1] = 653,
    [SPECIES_BRAIXEN - LAST_DEX_GAP - 1] = 654,
    [SPECIES_DELPHOX - LAST_DEX_GAP - 1] = 655,
    [SPECIES_FROAKIE - LAST_DEX_GAP - 1] = 656,
    [SPECIES_FROGADIER - LAST_DEX_GAP - 1] = 657,
    [SPECIES_GRENINJA - LAST_DEX_GAP - 1] = 658,
    [SPECIES_SCATTERBUG - LAST_DEX_GAP - 1] = 664,
    [SPECIES_SPEWPA - LAST_DEX_GAP - 1] = 665,
    [SPECIES_VIVILLON - LAST_DEX_GAP - 1] = 666,
    [SPECIES_FLABEBE - LAST_DEX_GAP - 1] = 669,
    [SPECIES_FLOETTE - LAST_DEX_GAP - 1] = 670,
    [SPECIES_FLORGES - LAST_DEX_GAP - 1] = 671,
    [SPECIES_SKIDDO - LAST_DEX_GAP - 1] = 672,
    [SPECIES_GOGOAT - LAST_DEX_GAP - 1] = 673,
    [SPECIES_PANCHAM - LAST_DEX_GAP - 1] = 674,
    [SPECIES_PANGORO - LAST_DEX_GAP - 1] = 675,
    [SPECIES_FURFROU - LAST_DEX_GAP - 1] = 676,
    [SPECIES_HONEDGE - LAST_DEX_GAP - 1] = 679,
    [SPECIES_DOUBLADE - LAST_DEX_GAP - 1] = 680,
    [SPECIES_AEGISLASH - LAST_DEX_GAP - 1] = 681,
    [SPECIES_SPRITZEE - LAST_DEX_GAP - 1] = 682,
    [SPECIES_AROMATISSE - LAST_DEX_GAP - 1] = 683,
    [SPECIES_SWIRLIX - LAST_DEX_GAP - 1] = 684,
    [SPECIES_SLURPUFF - LAST_DEX_GAP - 1] = 685,
    [SPECIES_INKAY - LAST_DEX_GAP - 1] = 686,
    [SPECIES_MALAMAR - LAST_DEX_GAP - 1] = 687,
    [SPECIES_BINACLE - LAST_DEX_GAP - 1] = 688,
    [SPECIES_BARBARACLE - LAST_DEX_GAP - 1] = 689,
    [SPECIES_SKRELP - LAST_DEX_GAP - 1] = 690,
    [SPECIES_DRAGALGE - LAST_DEX_GAP - 1] = 691,
    [SPECIES_CLAUNCHER - LAST_DEX_GAP - 1] = 692,
    [SPECIES_CLAWITZER - LAST_DEX_GAP - 1] = 693,
    [SPECIES_HELIOPTILE - LAST_DEX_GAP - 1] = 694,
    [SPECIES_HELIOLISK - LAST_DEX_GAP - 1] = 695,
    [SPECIES_TYRUNT - LAST_DEX_GAP - 1] = 696,
    [SPECIES_TYRANTRUM - LAST_DEX_GAP - 1] = 697,
    [SPECIES_AMAURA - LAST_DEX_GAP - 1] = 698,
    [SPECIES_AURORUS - LAST_DEX_GAP - 1] = 699,
    [SPECIES_HAWLUCHA - LAST_DEX_GAP - 1] = 701,
    [SPECIES_CARBINK - LAST_DEX_GAP - 1] = 703,
    [SPECIES_GOOMY - LAST_DEX_GAP - 1] = 704,
    [SPECIES_SLIGGOO - LAST_DEX_GAP - 1] = 705,
    [SPECIES_GOODRA - LAST_DEX_GAP - 1] = 706,
    [SPECIES_KLEFKI - LAST_DEX_GAP - 1] = 707,
    [SPECIES_BERGMITE - LAST_DEX_GAP - 1] = 712,
    [SPECIES_AVALUGG - LAST_DEX_GAP - 1] = 713,
    [SPECIES_XERNEAS - LAST_DEX_GAP - 1] = 716,
    [SPECIES_YVELTAL - LAST_DEX_GAP - 1] = 717,
    [SPECIES_ZYGARDE - LAST_DEX_GAP - 1] = 718,
    [SPECIES_DIANCIE - LAST_DEX_GAP - 1] = 719,
    [SPECIES_HOOPA - LAST_DEX_GAP - 1] = 720,
    [SPECIES_VOLCANION - LAST_DEX_GAP - 1] = 721,
    [SPECIES_ROWLET - LAST_DEX_GAP - 1] = 722,
    [SPECIES_DARTRIX - LAST_DEX_GAP - 1] = 723,
    [SPECIES_DECIDUEYE - LAST_DEX_GAP - 1] = 724,
    [SPECIES_LITTEN - LAST_DEX_GAP - 1] = 725,
    [SPECIES_TORRACAT - LAST_DEX_GAP - 1] = 726,
    [SPECIES_INCINEROAR - LAST_DEX_GAP - 1] = 727,
    [SPECIES_POPPLIO - LAST_DEX_GAP - 1] = 728,
    [SPECIES_BRIONNE - LAST_DEX_GAP - 1] = 729,
    [SPECIES_PRIMARINA - LAST_DEX_GAP - 1] = 730,
    [SPECIES_PIKIPEK - LAST_DEX_GAP - 1] = 731,
    [SPECIES_TRUMBEAK - LAST_DEX_GAP - 1] = 732,
    [SPECIES_TOUCANNON - LAST_DEX_GAP - 1] = 733,
    [SPECIES_YUNGOOS - LAST_DEX_GAP - 1] = 734,
    [SPECIES_GUMSHOOS - LAST_DEX_GAP - 1] = 735,
    [SPECIES_GRUBBIN - LAST_DEX_GAP - 1] = 736,
    [SPECIES_CHARJABUG - LAST_DEX_GAP - 1] = 737,
    [SPECIES_VIKAVOLT - LAST_DEX_GAP - 1] = 738,
    [SPECIES_CRABRAWLER - LAST_DEX_GAP - 1] = 739,
    [SPECIES_CRABOMINABLE - LAST_DEX_GAP - 1] = 740,
    [SPECIES_ORICORIO - LAST_DEX_GAP - 1] = 741,
    [SPECIES_CUTIEFLY - LAST_DEX_GAP - 1] = 742,
    [SPECIES_RIBOMBEE - LAST_DEX_GAP - 1] = 743,
    [SPECIES_ROCKRUFF - LAST_DEX_GAP - 1] = 744,
    [SPECIES_LYCANROC - LAST_DEX_GAP - 1] = 745,
    [SPECIES_WISHIWASHI - LAST_DEX_GAP - 1] = 746,
    [SPECIES_MAREANIE - LAST_DEX_GAP - 1] = 747,
    [SPECIES_TOXAPEX - LAST_DEX_GAP - 1] = 748,
    [SPECIES_MUDBRAY - LAST_DEX_GAP - 1] = 749,
    [SPECIES_MUDSDALE - LAST_DEX_GAP - 1] = 750,
    [SPECIES_DEWPIDER - LAST_DEX_GAP - 1] = 751,
    [SPECIES_ARAQUANID - LAST_DEX_GAP - 1] = 752,
    [SPECIES_FOMANTIS - LAST_DEX_GAP - 1] = 753,
    [SPECIES_LURANTIS - LAST_DEX_GAP - 1] = 754,
    [SPECIES_MORELULL - LAST_DEX_GAP - 1] = 755,
    [SPECIES_SHIINOTIC - LAST_DEX_GAP - 1] = 756,
    [SPECIES_SALANDIT - LAST_DEX_GAP - 1] = 757,
    [SPECIES_SALAZZLE - LAST_DEX_GAP - 1] = 758,
    [SPECIES_STUFFUL - LAST_DEX_GAP - 1] = 759,
    [SPECIES_BEWEAR - LAST_DEX_GAP - 1] = 760,
    [SPECIES_BOUNSWEET - LAST_DEX_GAP - 1] = 761,
    [SPECIES_STEENEE - LAST_DEX_GAP - 1] = 762,
    [SPECIES_TSAREENA - LAST_DEX_GAP - 1] = 763,
    [SPECIES_COMFEY - LAST_DEX_GAP - 1] = 764,
    [SPECIES_ORANGURU - LAST_DEX_GAP - 1] = 765,
    [SPECIES_PASSIMIAN - LAST_DEX_GAP - 1] = 766,
    [SPECIES_WIMPOD - LAST_DEX_GAP - 1] = 767,
    [SPECIES_GOLISOPOD - LAST_DEX_GAP - 1] = 768,
    [SPECIES_SANDYGAST - LAST_DEX_GAP - 1] = 769,
    [SPECIES_PALOSSAND - LAST_DEX_GAP - 1] = 770,
    [SPECIES_PYUKUMUKU - LAST_DEX_GAP - 1] = 771,
    [SPECIES_TYPE_NULL - LAST_DEX_GAP - 1] = 772,
    [SPECIES_SILVALLY - LAST_DEX_GAP - 1] = 773,
    [SPECIES_MINIOR - LAST_DEX_GAP - 1] = 774,
    [SPECIES_KOMALA - LAST_DEX_GAP - 1] = 775,
    [SPECIES_TURTONATOR - LAST_DEX_GAP - 1] = 776,
    [SPECIES_TOGEDEMARU - LAST_DEX_GAP - 1] = 777,
    [SPECIES_MIMIKYU - LAST_DEX_GAP - 1] = 778,
    [SPECIES_BRUXISH - LAST_DEX_GAP - 1] = 779,
    [SPECIES_DRAMPA - LAST_DEX_GAP - 1] = 780,
    [SPECIES_DHELMISE - LAST_DEX_GAP - 1] = 781,
    [SPECIES_JANGMO_O - LAST_DEX_GAP - 1] = 782,
    [SPECIES_HAKAMO_O - LAST_DEX_GAP - 1] = 783,
    [SPECIES_KOMMO_O - LAST_DEX_GAP - 1] = 784,
    [SPECIES_TAPU_KOKO - LAST_DEX_GAP - 1] = 785,
    [SPECIES_TAPU_LELE - LAST_DEX_GAP - 1] = 786,
    [SPECIES_TAPU_BULU - LAST_DEX_GAP - 1] = 787,
    [SPECIES_TAPU_FINI - LAST_DEX_GAP - 1] = 788,
    [SPECIES_COSMOG - LAST_DEX_GAP - 1] = 789,
    [SPECIES_COSMOEM - LAST_DEX_GAP - 1] = 790,
    [SPECIES_SOLGALEO - LAST_DEX_GAP - 1] = 791,
    [SPECIES_LUNALA - LAST_DEX_GAP - 1] = 792,
    [SPECIES_NIHILEGO - LAST_DEX_GAP - 1] = 793,
    [SPECIES_BUZZWOLE - LAST_DEX_GAP - 1] = 794,
    [SPECIES_PHEROMOSA - LAST_DEX_GAP - 1] = 795,
    [SPECIES_XURKITREE - LAST_DEX_GAP - 1] = 796,
    [SPECIES_CELESTEELA - LAST_DEX_GAP - 1] = 797,
    [SPECIES_KARTANA - LAST_DEX_GAP - 1] = 798,
    [SPECIES_GUZZLORD - LAST_DEX_GAP - 1] = 799,
    [SPECIES_NECROZMA - LAST_DEX_GAP - 1] = 800,
    [SPECIES_MAGEARNA - LAST_DEX_GAP - 1] = 801,
    [SPECIES_MARSHADOW - LAST_DEX_GAP - 1] = 802,
    [SPECIES_POIPOLE - LAST_DEX_GAP - 1] = 803,
    [SPECIES_NAGANADEL - LAST_DEX_GAP - 1] = 804,
    [SPECIES_STAKATAKA - LAST_DEX_GAP - 1] = 805,
    [SPECIES_BLACEPHALON - LAST_DEX_GAP - 1] = 806,
    [SPECIES_ZERAORA - LAST_DEX_GAP - 1] = 807,
    [SPECIES_MELTAN - LAST_DEX_GAP - 1] = 808,
    [SPECIES_MELMETAL - LAST_DEX_GAP - 1] = 809,
    [SPECIES_GROOKEY - LAST_DEX_GAP - 1] = 810,
    [SPECIES_THWACKEY - LAST_DEX_GAP - 1] = 811,
    [SPECIES_RILLABOOM - LAST_DEX_GAP - 1] = 812,
    [SPECIES_SCORBUNNY - LAST_DEX_GAP - 1] = 813,
    [SPECIES_RABOOT - LAST_DEX_GAP - 1] = 814,
    [SPECIES_CINDERACE - LAST_DEX_GAP - 1] = 815,
    [SPECIES_SOBBLE - LAST_DEX_GAP - 1] = 816,
    [SPECIES_DRIZZILE - LAST_DEX_GAP - 1] = 817,
    [SPECIES_INTELEON - LAST_DEX_GAP - 1] = 818,
    [SPECIES_SKWOVET - LAST_DEX_GAP - 1] = 819,
    [SPECIES_GREEDENT - LAST_DEX_GAP - 1] = 820,
    [SPECIES_ROOKIDEE - LAST_DEX_GAP - 1] = 821,
    [SPECIES_CORVISQUIRE - LAST_DEX_GAP - 1] = 822,
    [SPECIES_CORVIKNIGHT - LAST_DEX_GAP - 1] = 823,
    [SPECIES_BLIPBUG - LAST_DEX_GAP - 1] = 824,
    [SPECIES_DOTTLER - LAST_DEX_GAP - 1] = 825,
    [SPECIES_ORBEETLE - LAST_DEX_GAP - 1] = 826,
    [SPECIES_NICKIT - LAST_DEX_GAP - 1] = 827,
    [SPECIES_THIEVUL - LAST_DEX_GAP - 1] = 828,
    [SPECIES_GOSSIFLEUR - LAST_DEX_GAP - 1] = 829,
    [SPECIES_ELDEGOSS - LAST_DEX_GAP - 1] = 830,
    [SPECIES_WOOLOO - LAST_DEX_GAP - 1] = 831,
    [SPECIES_DUBWOOL - LAST_DEX_GAP - 1] = 832,
    [SPECIES_CHEWTLE - LAST_DEX_GAP - 1] = 833,
    [SPECIES_DREDNAW - LAST_DEX_GAP - 1] = 834,
    [SPECIES_YAMPER - LAST_DEX_GAP - 1] = 835,
    [SPECIES_BOLTUND - LAST_DEX_GAP - 1] = 836,
    [SPECIES_ROLYCOLY - LAST_DEX_GAP - 1] = 837,
    [SPECIES_CARKOL - LAST_DEX_GAP - 1] = 838,
    [SPECIES_COALOSSAL - LAST_DEX_GAP - 1] = 839,
    [SPECIES_SILICOBRA - LAST_DEX_GAP - 1] = 843,
    [SPECIES_SANDACONDA - LAST_DEX_GAP - 1] = 844,
    [SPECIES_CRAMORANT - LAST_DEX_GAP - 1] = 845,
    [SPECIES_ARROKUDA - LAST_DEX_GAP - 1] = 846,
    [SPECIES_BARRASKEWDA - LAST_DEX_GAP - 1] = 847,
    [SPECIES_TOXEL - LAST_DEX_GAP - 1] = 848,
    [SPECIES_TOXTRICITY - LAST_DEX_GAP - 1] = 849,
    [SPECIES_CLOBBOPUS - LAST_DEX_GAP - 1] = 852,
    [SPECIES_GRAPPLOCT - LAST_DEX_GAP - 1] = 853,
    [SPECIES_SINISTEA - LAST_DEX_GAP - 1] = 854,
    [SPECIES_POLTEAGEIST - LAST_DEX_GAP - 1] = 855,
    [SPECIES_HATENNA - LAST_DEX_GAP - 1] = 856,
    [SPECIES_HATTREM - LAST_DEX_GAP - 1] = 857,
    [SPECIES_HATTERENE - LAST_DEX_GAP - 1] = 858,
    [SPECIES_IMPIDIMP - LAST_DEX_GAP - 1] = 859,
    [SPECIES_MORGREM - LAST_DEX_GAP - 1] = 860,
    [SPECIES_GRIMMSNARL - LAST_DEX_GAP - 1] = 861,
    [SPECIES_OBSTAGOON - LAST_DEX_GAP - 1] = 862,
    [SPECIES_PERRSERKER - LAST_DEX_GAP - 1] = 863,
    [SPECIES_CURSOLA - LAST_DEX_GAP - 1] = 864,
    [SPECIES_SIRFETCHD - LAST_DEX_GAP - 1] = 865,
    [SPECIES_MR_RIME - LAST_DEX_GAP - 1] = 866,
    [SPECIES_RUNERIGUS - LAST_DEX_GAP - 1] = 867,
    [SPECIES_MILCERY - LAST_DEX_GAP - 1] = 868,
    [SPECIES_ALCREMIE - LAST_DEX_GAP - 1] = 869,
    [SPECIES_FALINKS - LAST_DEX_GAP - 1] = 870,
    [SPECIES_PINCURCHIN - LAST_DEX_GAP - 1] = 871,
    [SPECIES_SNOM - LAST_DEX_GAP - 1] = 872,
    [SPECIES_FROSMOTH - LAST_DEX_GAP - 1] = 873,
    [SPECIES_STONJOURNER - LAST_DEX_GAP - 1] = 874,
    [SPECIES_EISCUE - LAST_DEX_GAP - 1] = 875,
    [SPECIES_INDEEDEE - LAST_DEX_GAP - 1] = 876,
    [SPECIES_MORPEKO - LAST_DEX_GAP - 1] = 877,
    [SPECIES_CUFANT - LAST_DEX_GAP - 1] = 878,
    [SPECIES_COPPERAJAH - LAST_DEX_GAP - 1] = 879,
    [SPECIES_DRACOZOLT - LAST_DEX_GAP - 1] = 880,
    [SPECIES_ARCTOZOLT - LAST_DEX_GAP - 1] = 881,
    [SPECIES_DRACOVISH - LAST_DEX_GAP - 1] = 882,
    [SPECIES_ARCTOVISH - LAST_DEX_GAP - 1] = 883,
    [SPECIES_DURALUDON - LAST_DEX_GAP - 1] = 884,
    [SPECIES_DREEPY - LAST_DEX_GAP - 1] = 885,
    [SPECIES_DRAKLOAK - LAST_DEX_GAP - 1] = 886,
    [SPECIES_DRAGAPULT - LAST_DEX_GAP - 1] = 887,
    [SPECIES_ZACIAN - LAST_DEX_GAP - 1] = 888,
    [SPECIES_ZAMAZENTA - LAST_DEX_GAP - 1] = 889,
    [SPECIES_ETERNATUS - LAST_DEX_GAP - 1] = 890,
    [SPECIES_KUBFU - LAST_DEX_GAP - 1] = 891,
    [SPECIES_URSHIFU - LAST_DEX_GAP - 1] = 892,
    [SPECIES_ZARUDE - LAST_DEX_GAP - 1] = 893,
    [SPECIES_REGIELEKI - LAST_DEX_GAP - 1] = 894,
    [SPECIES_REGIDRAGO - LAST_DEX_GAP - 1] = 895,
    [SPECIES_GLASTRIER - LAST_DEX_GAP - 1] = 896,
    [SPECIES_SPECTRIER - LAST_DEX_GAP - 1] = 897,
    [SPECIES_CALYREX - LAST_DEX_GAP - 1] = 898,
    [SPECIES_BASCULEGION - LAST_DEX_GAP - 1] = 902,
    [SPECIES_SNEASLER - LAST_DEX_GAP - 1] = 903,
    [SPECIES_OVERQWIL - LAST_DEX_GAP - 1] = 904,
    [SPECIES_ENAMORUS - LAST_DEX_GAP - 1] = 905,
    [SPECIES_SPRIGATITO - LAST_DEX_GAP - 1] = 906,
    [SPECIES_FLORAGATO - LAST_DEX_GAP - 1] = 907,
    [SPECIES_MEOWSCARADA - LAST_DEX_GAP - 1] = 908,
    [SPECIES_FUECOCO - LAST_DEX_GAP - 1] = 909,
    [SPECIES_CROCALOR - LAST_DEX_GAP - 1] = 910,
    [SPECIES_SKELEDIRGE - LAST_DEX_GAP - 1] = 911,
    [SPECIES_QUAXLY - LAST_DEX_GAP - 1] = 912,
    [SPECIES_QUAXWELL - LAST_DEX_GAP - 1] = 913,
    [SPECIES_QUAQUAVAL - LAST_DEX_GAP - 1] = 914,
    [SPECIES_LECHONK - LAST_DEX_GAP - 1] = 915,
    [SPECIES_OINKOLOGNE - LAST_DEX_GAP - 1] = 916,
    [SPECIES_TAROUNTULA - LAST_DEX_GAP - 1] = 917,
    [SPECIES_SPIDOPS - LAST_DEX_GAP - 1] = 918,
    [SPECIES_NYMBLE - LAST_DEX_GAP - 1] = 919,
    [SPECIES_LOKIX - LAST_DEX_GAP - 1] = 920,
    [SPECIES_PAWMI - LAST_DEX_GAP - 1] = 921,
    [SPECIES_PAWMO - LAST_DEX_GAP - 1] = 922,
    [SPECIES_PAWMOT - LAST_DEX_GAP - 1] = 923,
    [SPECIES_TANDEMAUS - LAST_DEX_GAP - 1] = 924,
    [SPECIES_MAUSHOLD - LAST_DEX_GAP - 1] = 925,
    [SPECIES_FIDOUGH - LAST_DEX_GAP - 1] = 926,
    [SPECIES_DACHSBUN - LAST_DEX_GAP - 1] = 927,
    [SPECIES_SMOLIV - LAST_DEX_GAP - 1] = 928,
    [SPECIES_DOLLIV - LAST_DEX_GAP - 1] = 929,
    [SPECIES_ARBOLIVA - LAST_DEX_GAP - 1] = 930,
    [SPECIES_SQUAWKABILLY - LAST_DEX_GAP - 1] = 931,
    [SPECIES_NACLI - LAST_DEX_GAP - 1] = 932,
    [SPECIES_NACLSTACK - LAST_DEX_GAP - 1] = 933,
    [SPECIES_GARGANACL - LAST_DEX_GAP - 1] = 934,
    [SPECIES_CHARCADET - LAST_DEX_GAP - 1] = 935,
    [SPECIES_ARMAROUGE - LAST_DEX_GAP - 1] = 936,
    [SPECIES_CERULEDGE - LAST_DEX_GAP - 1] = 937,
    [SPECIES_TADBULB - LAST_DEX_GAP - 1] = 938,
    [SPECIES_BELLIBOLT - LAST_DEX_GAP - 1] = 939,
    [SPECIES_WATTREL - LAST_DEX_GAP - 1] = 940,
    [SPECIES_KILOWATTREL - LAST_DEX_GAP - 1] = 941,
    [SPECIES_MASCHIFF - LAST_DEX_GAP - 1] = 942,
    [SPECIES_MABOSSTIFF - LAST_DEX_GAP - 1] = 943,
    [SPECIES_SHROODLE - LAST_DEX_GAP - 1] = 944,
    [SPECIES_GRAFAIAI - LAST_DEX_GAP - 1] = 945,
    [SPECIES_BRAMBLIN - LAST_DEX_GAP - 1] = 946,
    [SPECIES_BRAMBLEGHAST - LAST_DEX_GAP - 1] = 947,
    [SPECIES_TOEDSCOOL - LAST_DEX_GAP - 1] = 948,
    [SPECIES_TOEDSCRUEL - LAST_DEX_GAP - 1] = 949,
    [SPECIES_KLAWF - LAST_DEX_GAP - 1] = 950,
    [SPECIES_CAPSAKID - LAST_DEX_GAP - 1] = 951,
    [SPECIES_SCOVILLAIN - LAST_DEX_GAP - 1] = 952,
    [SPECIES_RELLOR - LAST_DEX_GAP - 1] = 953,
    [SPECIES_RABSCA - LAST_DEX_GAP - 1] = 954,
    [SPECIES_FLITTLE - LAST_DEX_GAP - 1] = 955,
    [SPECIES_ESPATHRA - LAST_DEX_GAP - 1] = 956,
    [SPECIES_TINKATINK - LAST_DEX_GAP - 1] = 957,
    [SPECIES_TINKATUFF - LAST_DEX_GAP - 1] = 958,
    [SPECIES_TINKATON - LAST_DEX_GAP - 1] = 959,
    [SPECIES_WIGLETT - LAST_DEX_GAP - 1] = 960,
    [SPECIES_WUGTRIO - LAST_DEX_GAP - 1] = 961,
    [SPECIES_BOMBIRDIER - LAST_DEX_GAP - 1] = 962,
    [SPECIES_FINIZEN - LAST_DEX_GAP - 1] = 963,
    [SPECIES_PALAFIN - LAST_DEX_GAP - 1] = 964,
    [SPECIES_VAROOM - LAST_DEX_GAP - 1] = 965,
    [SPECIES_REVAVROOM - LAST_DEX_GAP - 1] = 966,
    [SPECIES_CYCLIZAR - LAST_DEX_GAP - 1] = 967,
    [SPECIES_ORTHWORM - LAST_DEX_GAP - 1] = 968,
    [SPECIES_GLIMMET - LAST_DEX_GAP - 1] = 969,
    [SPECIES_GLIMMORA - LAST_DEX_GAP - 1] = 970,
    [SPECIES_GREAVARD - LAST_DEX_GAP - 1] = 971,
    [SPECIES_HOUNDSTONE - LAST_DEX_GAP - 1] = 972,
    [SPECIES_FLAMIGO - LAST_DEX_GAP - 1] = 973,
    [SPECIES_CETODDLE - LAST_DEX_GAP - 1] = 974,
    [SPECIES_CETITAN - LAST_DEX_GAP - 1] = 975,
    [SPECIES_VELUZA - LAST_DEX_GAP - 1] = 976,
    [SPECIES_DONDOZO - LAST_DEX_GAP - 1] = 977,
    [SPECIES_TATSUGIRI - LAST_DEX_GAP - 1] = 978,
    [SPECIES_CLODSIRE - LAST_DEX_GAP - 1] = 980,
    [SPECIES_KINGAMBIT - LAST_DEX_GAP - 1] = 983,
    [SPECIES_GREAT_TUSK - LAST_DEX_GAP - 1] = 984,
    [SPECIES_SCREAM_TAIL - LAST_DEX_GAP - 1] = 985,
    [SPECIES_BRUTE_BONNET - LAST_DEX_GAP - 1] = 986,
    [SPECIES_FLUTTER_MANE - LAST_DEX_GAP - 1] = 987,
    [SPECIES_SLITHER_WING - LAST_DEX_GAP - 1] = 988,
    [SPECIES_SANDY_SHOCKS - LAST_DEX_GAP - 1] = 989,
    [SPECIES_IRON_TREADS - LAST_DEX_GAP - 1] = 990,
    [SPECIES_IRON_BUNDLE - LAST_DEX_GAP - 1] = 991,
    [SPECIES_IRON_HANDS - LAST_DEX_GAP - 1] = 992,
    [SPECIES_IRON_JUGULIS - LAST_DEX_GAP - 1] = 993,
    [SPECIES_IRON_MOTH - LAST_DEX_GAP - 1] = 994,
    [SPECIES_IRON_THORNS - LAST_DEX_GAP - 1] = 995,
    [SPECIES_FRIGIBAX - LAST_DEX_GAP - 1] = 996,
    [SPECIES_ARCTIBAX - LAST_DEX_GAP - 1] = 997,
    [SPECIES_BAXCALIBUR - LAST_DEX_GAP - 1] = 998,
    [SPECIES_GIMMIGHOUL - LAST_DEX_GAP - 1] = 999,
    [SPECIES_GHOLDENGO - LAST_DEX_GAP - 1] = 1000,
    [SPECIES_WO_CHIEN - LAST_DEX_GAP - 1] = 1001,
    [SPECIES_CHIEN_PAO - LAST_DEX_GAP - 1] = 1002,
    [SPECIES_TING_LU - LAST_DEX_GAP - 1] = 1003,
    [SPECIES_CHI_YU - LAST_DEX_GAP - 1] = 1004,
    [SPECIES_ROARING_MOON - LAST_DEX_GAP - 1] = 1005,
    [SPECIES_IRON_VALIANT - LAST_DEX_GAP - 1] = 1006,
    [SPECIES_KORAIDON - LAST_DEX_GAP - 1] = 1007,
    [SPECIES_MIRAIDON - LAST_DEX_GAP - 1] = 1008,
    [SPECIES_WALKING_WAKE - LAST_DEX_GAP - 1] = 1009,
    [SPECIES_IRON_LEAVES - LAST_DEX_GAP - 1] = 1010,
    [SPECIES_POLTCHAGEIST - LAST_DEX_GAP - 1] = 1012,
    [SPECIES_SINISTCHA - LAST_DEX_GAP - 1] = 1013,
    [SPECIES_OKIDOGI - LAST_DEX_GAP - 1] = 1014,
    [SPECIES_MUNKIDORI - LAST_DEX_GAP - 1] = 1015,
    [SPECIES_FEZANDIPITI - LAST_DEX_GAP - 1] = 1016,
    [SPECIES_OGERPON - LAST_DEX_GAP - 1] = 1017,
    [SPECIES_ARCHALUDON - LAST_DEX_GAP - 1] = 1018,
    [SPECIES_GOUGING_FIRE - LAST_DEX_GAP - 1] = 1020,
    [SPECIES_RAGING_BOLT - LAST_DEX_GAP - 1] = 1021,
    [SPECIES_IRON_BOULDER - LAST_DEX_GAP - 1] = 1022,
    [SPECIES_IRON_CROWN - LAST_DEX_GAP - 1] = 1023,
    [SPECIES_TERAPAGOS - LAST_DEX_GAP - 1] = 1024,
    [SPECIES_PECHARUNT - LAST_DEX_GAP - 1] = 1025,
};

// A Dex species' National Dex number. HeartGold's own species are their
// number; the identifiers in the gap are not Dex species and stay as they are.
u16 SpeciesToNationalDexNo(u16 species) {
    if (species > LAST_DEX_GAP && species <= NATIONAL_DEX_COUNT) {
        return sNationalDexNumbers[species - LAST_DEX_GAP - 1];
    }
    return species;
}

static inline BOOL CheckDexFlag(const u8 *array, u16 flagId) {
    flagId--;
    return (array[flagId >> 3] & (1 << (flagId & 7))) != 0;
}

static inline void SetDexFlag(u8 *array, u16 flagId) {
    flagId--;
    array[flagId >> 3] |= (1 << (flagId & 7));
}

static inline void SetDexFlagState(u8 *array, u8 state, u16 flagId) {
    GF_ASSERT(state < 2);
    flagId--;
    array[flagId >> 3] &= ~(1 << (flagId & 7));
    array[flagId >> 3] |= (state << (flagId & 7));
}

static inline int CheckDex2Flag(const u8 *array, u16 _2flagId) {
    return (array[_2flagId >> 2] >> (2 * (_2flagId % 4u))) & 3;
}

static inline void SetDex2FlagState(u8 *array, u8 state, u16 _2flagId) {
    GF_ASSERT(state < 4);
    array[_2flagId >> 2] &= ~(3 << (2 * (_2flagId % 4u)));
    array[_2flagId >> 2] |= (state << (2 * (_2flagId % 4u)));
}

// Deoxys's form order lives in the top byte of the last flag word, which the
// + 8 in NUM_DEX_FLAG_WORDS keeps past the last Dex species. Retail wrote word
// 15, the last word at 493; with the Dex wider, word 15 holds real species.
static inline int CheckDex4Flag(u32 *flags, u8 idx) {
    return (flags[NUM_DEX_FLAG_WORDS - 1] >> (24 + 4 * idx)) & 15;
}

static inline void SetDex4Flag(u32 *flags, u8 form, u8 idx) {
    flags[NUM_DEX_FLAG_WORDS - 1] &= ~(15 << (24 + 4 * idx));
    flags[NUM_DEX_FLAG_WORDS - 1] |= (form << (24 + 4 * idx));
}

static inline int CheckDex3Flag(const u32 *arr, u32 idx) {
    return ((*arr) >> (3 * idx)) & 7;
}

static inline void SetDex3Flag(u32 *arr, u32 idx, u32 form) {
    GF_ASSERT(form < 7);
    *arr &= ~(7 << (3 * idx));
    *arr |= (form << (3 * idx));
}

static inline u8 CheckDexGender(const u8 *arr, u16 species) {
    if (CheckDexFlag(arr, species)) {
        return MON_FEMALE;
    } else {
        return MON_MALE;
    }
}

static void Pokedex_SetSeenGenderFlagInternal(Pokedex *pokeDex, u8 state, u8 num, u16 flagId) {
    if (num == 0) {
        SetDexFlagState((u8 *)pokeDex->seenGenders[1], state, flagId);
    }
    SetDexFlagState((u8 *)pokeDex->seenGenders[num], state, flagId);
}

static void Pokedex_SetSeenGenderFlag(Pokedex *pokeDex, u8 state, u8 num, u16 flagId) {
    GF_ASSERT(state <= 2);
    if (state == 2) {
        state = 0;
    }
    Pokedex_SetSeenGenderFlagInternal(pokeDex, state, num, flagId);
}

static u8 *Pokedex_GetFormOrderAddr(Pokedex *pokedex, u32 species) {
    switch (species) {
    case SPECIES_SHELLOS:
        return &pokedex->shellosFormOrder; // + 264;
    case SPECIES_GASTRODON:
        return &pokedex->gastrodonFormOrder; // + 265;
    case SPECIES_SHAYMIN:
        return &pokedex->shayminFormOrder; // + 828;
    case SPECIES_GIRATINA:
        return &pokedex->giratinaFormOrder; // + 829;
    case SPECIES_BURMY:
        return &pokedex->burmyFormOrder; // + 266;
    case SPECIES_WORMADAM:
        return &pokedex->wormadamFormOrder; // + 267;
    case SPECIES_PICHU:
        return &pokedex->pichuFormOrder; // + 830;
    default:
        GF_ASSERT(FALSE);
        return NULL;
    }
}

static int Pokedex_CountRegisteredUnownLetters(const Pokedex *pokedex, BOOL caught) {
    int i, j = 0;
    const u8 *arr;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    for (i = 0; i < UNOWN_FORM_MAX; i++, j++) {
        if (arr[i] == 0xFF) {
            break;
        }
    }
    return j;
}

static BOOL Pokedex_HasAlreadyAddedUnownLetter(const Pokedex *pokedex, u8 letter, BOOL caught) {
    int i;
    const u8 *arr;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    for (i = 0; i < UNOWN_FORM_MAX; i++) {
        if (arr[i] == letter) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_TryAppendUnownLetter(Pokedex *pokedex, int letter, BOOL caught) {
    u8 *arr;
    int idx;
    if (caught) {
        arr = pokedex->unownCaughtOrder;
    } else {
        arr = pokedex->unownSeenOrder;
    }
    if (!Pokedex_HasAlreadyAddedUnownLetter(pokedex, letter, caught)) {
        idx = Pokedex_CountRegisteredUnownLetters(pokedex, caught);
        if (idx < UNOWN_FORM_MAX) {
            arr[idx] = letter;
        }
    }
}

static int Pokedex_GetSeenFormNum_2max(Pokedex *pokedex, u32 species) {
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    if (CheckDexFlag(flag_p, 1) == CheckDexFlag(flag_p, 2)) {
        return 1;
    } else {
        return 2;
    }
}

static BOOL Pokedex_CheckSeenForm_2max(Pokedex *pokedex, u32 species, u8 form) {
    u8 *flag_p;
    u32 n;
    int i;
    BOOL flag;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return FALSE;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    n = Pokedex_GetSeenFormNum_2max(pokedex, species);
    for (i = 0; i < n; i++) {
        flag = CheckDexFlag(flag_p, i + 1);
        if (flag == form) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenForm_2max(Pokedex *pokedex, u32 species, BOOL state) {
    int r4;
    u8 *r5;
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    if (!Pokedex_CheckSeenForm_2max(pokedex, species, state)) {
        r5 = Pokedex_GetFormOrderAddr(pokedex, species);
        r4 = Pokedex_GetSeenFormNum_2max(pokedex, species);
        if (r4 < 2) {
            SetDexFlagState(r5, state, r4 + 1);
            if (r4 == 0) {
                SetDexFlagState(r5, state, r4 + 2);
            }
        }
    }
}

static int Pokedex_CountSeenForms_3max(Pokedex *pokedex, u32 species) {
    int i;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    for (i = 0; i < 3; i++) {
        if (CheckDex2Flag(flag_p, i) == 3) {
            break;
        }
    }
    return i;
}

static BOOL Pokedex_CheckSeenForm_3max(Pokedex *pokedex, u32 species, u8 state) {
    int i;
    u32 flag;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return FALSE;
    }
    flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
    for (i = 0; i < 3; i++) {
        flag = CheckDex2Flag(flag_p, i);
        if (flag == state) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenForm_3max(Pokedex *pokedex, u32 species, u32 state) {
    int n;
    u8 *flag_p;
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    if (!Pokedex_CheckSeenForm_3max(pokedex, species, state)) {
        flag_p = Pokedex_GetFormOrderAddr(pokedex, species);
        n = Pokedex_CountSeenForms_3max(pokedex, species);
        if (n < 3) {
            SetDex2FlagState(flag_p, state, n);
        }
    }
}

static void Pokedex_DeoxysFormFlagActionInternal(u32 *flags, u8 form, u8 idx) {
    SetDex4Flag(flags, form, idx);
}

static void Pokedex_DeoxysFormFlagAction(Pokedex *pokedex, u8 form, u8 idx) {
    GF_ASSERT(idx < 4);
    GF_ASSERT(form <= 15);
    if (idx < 2) {
        Pokedex_DeoxysFormFlagActionInternal(pokedex->caughtSpecies, form, idx);
    } else {
        Pokedex_DeoxysFormFlagActionInternal(pokedex->seenSpecies, form, idx - 2);
    }
}

static u32 Pokedex_GetSeenDeoxysFormByIndex(Pokedex *pokedex, u8 form) {
    if (form < 2) {
        return CheckDex4Flag(pokedex->caughtSpecies, form);
    } else {
        return CheckDex4Flag(pokedex->seenSpecies, form - 2);
    }
}

static int Pokedex_CountSeenDeoxysForms(Pokedex *pokedex) {
    int i;
    for (i = 0; i < 4; i++) {
        if (Pokedex_GetSeenDeoxysFormByIndex(pokedex, i) == 15) {
            break;
        }
    }
    return i;
}

static BOOL Pokedex_CheckSeenDeoxysForm(Pokedex *pokedex, u32 form) {
    int i;
    u32 val;
    for (i = 0; i < 4; i++) {
        val = Pokedex_GetSeenDeoxysFormByIndex(pokedex, i);
        if (form == val) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenDeoxysForm(Pokedex *pokedex, u16 species, Pokemon *mon) {
    u8 form;

    form = GetMonData(mon, MON_DATA_FORM, NULL);
    if (species == SPECIES_DEOXYS) {
        if (!Pokedex_CheckSeenDeoxysForm(pokedex, form)) {
            Pokedex_DeoxysFormFlagAction(pokedex, form, Pokedex_CountSeenDeoxysForms(pokedex));
        }
    }
}

static void Pokedex_InitDeoxysFormOrder(Pokedex *pokedex) {
    int i;
    for (i = 0; i < 4; i++) {
        Pokedex_DeoxysFormFlagAction(pokedex, 15, i);
    }
}

static int Pokedex_GetSeenFormNum_Rotom(const Pokedex *pokedex, u32 species) {
    int i, n;

    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    n = 0;
    for (i = 0; i < 6; i++, n++) {
        if (CheckDex3Flag(&pokedex->rotomFormOrder, i) == 7) {
            break;
        }
    }
    return n;
}

static BOOL Pokedex_CheckSeenRotomForm(Pokedex *pokedex, u32 species, u8 form) {
    int i, val;
    u32 n;

    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckMonSeenFlag(pokedex, species)) {
        return 0;
    }
    n = Pokedex_GetSeenFormNum_Rotom(pokedex, species);
    for (i = 0; i < n; i++) {
        val = CheckDex3Flag(&pokedex->rotomFormOrder, i);
        if (val == form) {
            return TRUE;
        }
    }
    return FALSE;
}

static void Pokedex_SetSeenRotomForm(Pokedex *pokedex, u32 species, u32 form) {
    int i;
    GF_ASSERT(species == SPECIES_ROTOM);
    if (!Pokedex_CheckSeenRotomForm(pokedex, species, form)) {
        i = Pokedex_GetSeenFormNum_Rotom(pokedex, species);
        if (i < 6) {
            SetDex3Flag(&pokedex->rotomFormOrder, i, form);
        }
    }
}

static void Pokedex_TryAppendSeenForm(Pokedex *pokedex, u16 species, Pokemon *mon) {
    u32 form;

    form = GetMonData(mon, MON_DATA_FORM, NULL);
    // An East Sea Shellos or Gastrodon is a species of its own here, with form
    // 0; the Dex keeps it as its base's form 1, as the reference stores it.
    switch (GetMonData(mon, MON_DATA_SPECIES, NULL)) {
    case SPECIES_SHELLOS_EAST_SEA:
    case SPECIES_GASTRODON_EAST_SEA:
        form = SHELLOS_EAST;
        break;
    }
    switch (species) {
    case SPECIES_UNOWN:
        Pokedex_TryAppendUnownLetter(pokedex, form, FALSE);
        break;
    case SPECIES_BURMY:
    case SPECIES_WORMADAM:
        Pokedex_SetSeenForm_3max(pokedex, species, form);
        break;
    case SPECIES_PICHU:
        if (form == 0) {
            if (GetMonGender(mon) == MON_MALE) {
                form = 0;
            } else {
                form = 1;
            }
        } else {
            form = 2;
        }
        Pokedex_SetSeenForm_3max(pokedex, species, form);
        break;
    case SPECIES_SHELLOS:
    case SPECIES_GASTRODON:
        Pokedex_SetSeenForm_2max(pokedex, species, form);
        break;
    case SPECIES_DEOXYS:
        Pokedex_SetSeenDeoxysForm(pokedex, species, mon);
        break;
    case SPECIES_SHAYMIN:
    case SPECIES_GIRATINA:
        Pokedex_SetSeenForm_2max(pokedex, species, form);
        break;
    case SPECIES_ROTOM:
        Pokedex_SetSeenRotomForm(pokedex, species, form);
        break;
    }
}

static void Pokedex_SetCaughtLanguage(Pokedex *pokedex, u32 species, u32 language) {
    int shift;

    shift = LanguageToDexFlag(language);
    if (shift != 6) {
        pokedex->caughtLanguages[species] |= (1 << shift);
    }
}

static int Pokedex_SpeciesGetLastSeenGender_Internal(Pokedex *pokedex, u16 species, u32 idx) {
    u8 gender1, gender2;

    if (GetMonBaseStat(species, BASE_GENDER_RATIO) == MON_RATIO_UNKNOWN) {
        if (idx == 0) {
            return 2;
        } else {
            return -1;
        }
    }
    gender1 = CheckDexFlag((u8 *)pokedex->seenGenders[0], species);
    if (idx == 1) {
        gender2 = CheckDexFlag((u8 *)pokedex->seenGenders[1], species);
        if (gender2 == gender1) {
            return -1;
        }
        return gender2;
    }
    return gender1;
}

static BOOL Pokedex_GetSeenFormByIdx_2max(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_SHELLOS || species == SPECIES_GASTRODON || species == SPECIES_SHAYMIN || species == SPECIES_GIRATINA);
    GF_ASSERT(idx < 2);
    return CheckDexFlag(Pokedex_GetFormOrderAddr(pokedex, species), idx + 1);
}

static int Pokedex_GetSeenFormByIdx_Rotom(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_ROTOM);
    GF_ASSERT(idx < 6);
    return CheckDex3Flag(&pokedex->rotomFormOrder, idx);
}

static int Pokedex_GetSeenFormByIdx_3max(Pokedex *pokedex, u32 species, int idx) {
    GF_ASSERT(species == SPECIES_BURMY || species == SPECIES_WORMADAM || species == SPECIES_PICHU);
    GF_ASSERT(idx < 3);
    return CheckDex2Flag(Pokedex_GetFormOrderAddr(pokedex, species), idx);
}

static const u16 sNationalMythicals[] = {
    SPECIES_MEW,
    SPECIES_CELEBI,
    SPECIES_JIRACHI,
    SPECIES_DEOXYS,
    SPECIES_PHIONE,
    SPECIES_MANAPHY,
    SPECIES_DARKRAI,
    SPECIES_SHAYMIN,
    SPECIES_ARCEUS,
};

static BOOL SpeciesIsNotNationalMythical(u16 species) {
    int i;
    BOOL result;

    for (i = 0, result = TRUE; i < (s32)NELEMS(sNationalMythicals); i++) {
        if (species == sNationalMythicals[i]) {
            result = FALSE;
        }
    }
    return result;
}

static const u16 sJohtoMythicals[] = {
    SPECIES_MEW,
    SPECIES_CELEBI,
};

static BOOL SpeciesIsNotJohtoMythical(u16 species) {
    int i;
    BOOL result;

    for (i = 0, result = TRUE; i < (s32)NELEMS(sJohtoMythicals); i++) {
        if (species == sJohtoMythicals[i]) {
            result = FALSE;
        }
    }
    return result;
}

void Save_Pokedex_Init(Pokedex *pokedex) {
    memset(pokedex, 0, sizeof(Pokedex));
    pokedex->magic = POKEDEX_MAGIC;
    pokedex->nationalDex = 0;
    memset(pokedex->unownSeenOrder, 0xFF, 28);
    memset(pokedex->unownCaughtOrder, 0xFF, 28);
    pokedex->shellosFormOrder = 0xFF;
    pokedex->gastrodonFormOrder = 0xFF;
    pokedex->burmyFormOrder = 0xFF;
    pokedex->wormadamFormOrder = 0xFF;
    pokedex->rotomFormOrder = -1;
    pokedex->shayminFormOrder = 0xFF;
    pokedex->giratinaFormOrder = 0xFF;
    pokedex->pichuFormOrder = 0xFF;
    Pokedex_InitDeoxysFormOrder(pokedex);
}

u16 Pokedex_CountNationalDexOwned(Pokedex *pokedex) {
    int i, n;
    ASSERT_POKEDEX(pokedex);
    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_IsOwnDexEntry(i) && Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountNationalDexSeen(Pokedex *pokedex) {
    int i, n;
    ASSERT_POKEDEX(pokedex);
    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_IsOwnDexEntry(i) && Pokedex_CheckMonSeenFlag(pokedex, i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountDexOwned(Pokedex *pokedex) {
    if (Pokedex_GetNatDexFlag(pokedex)) {
        return Pokedex_CountNationalDexOwned(pokedex);
    } else {
        return Pokedex_CountJohtoDexOwned(pokedex);
    }
}

// The Johto table (LoadSpeciesToJohtoDexNoLUT) is retail's, one entry a
// species up to Arceus, and the Johto Dex holds no species past it. The three
// Johto counts walk that table, not the National Dex.
u16 Pokedex_CountJohtoDexOwned(Pokedex *pokedex) {
    u16 *johto_species;
    u16 i, n;
    ASSERT_POKEDEX(pokedex);
    johto_species = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && johto_species[i] != J_SPECIES_NONE) {
            n++;
        }
    }
    Heap_Free(johto_species);
    return n;
}

u16 Pokedex_CountJohtoDexSeen(Pokedex *pokedex) {
    u16 *johto_species;
    u16 i, n;
    ASSERT_POKEDEX(pokedex);
    johto_species = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonSeenFlag(pokedex, i) == TRUE && johto_species[i] != J_SPECIES_NONE) {
            n++;
        }
    }
    Heap_Free(johto_species);
    return n;
}

// Retail's 484, which the engine keeps while counting past Arceus: the same
// number at which Oak's rating (GetOakNationalDexRating) calls the Dex done.
BOOL Pokedex_NationalDexIsComplete(Pokedex *pokedex) {
    return Pokedex_CountNationalOwned_ExcludeMythical(pokedex) >= (MAX_SPECIES - NELEMS(sNationalMythicals));
}

BOOL Pokedex_JohtoDexIsComplete(Pokedex *pokedex) {
    return Pokedex_CountJohtoOwned_ExcludeMythical(pokedex) >= (J_NUM_SPECIES - NELEMS(sJohtoMythicals));
}

u16 Pokedex_CountNationalOwned_ExcludeMythical(Pokedex *pokedex) {
    int i;
    u16 n;

    n = 0;
    for (i = 1; i <= NATIONAL_DEX_COUNT; i++) {
        if (Pokedex_IsOwnDexEntry(i) && Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && SpeciesIsNotNationalMythical(i) == TRUE) {
            n++;
        }
    }
    return n;
}

u16 Pokedex_CountJohtoOwned_ExcludeMythical(Pokedex *pokedex) {
    u16 i;
    u16 n;
    u16 *johto_dex;

    johto_dex = LoadSpeciesToJohtoDexNoLUT();
    n = 0;
    for (i = 1; i <= MAX_SPECIES; i++) {
        if (Pokedex_CheckMonCaughtFlag(pokedex, i) == TRUE && johto_dex[i] != J_SPECIES_NONE && SpeciesIsNotJohtoMythical(i) == TRUE) {
            n++;
        }
    }
    Heap_Free(johto_dex);
    return n;
}

BOOL Pokedex_CheckMonCaughtFlag(const Pokedex *pokedex, u16 species) {
    ASSERT_POKEDEX(pokedex);
    species = SpeciesToDexSpecies(species);
    if (DexSpeciesIsInvalid(species)) {
        return FALSE;
    }
    if (CheckDexFlag((const u8 *)pokedex->caughtSpecies, species) && CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

BOOL Pokedex_CheckMonSeenFlag(const Pokedex *pokedex, u16 species) {
    ASSERT_POKEDEX(pokedex);
    species = SpeciesToDexSpecies(species);
    if (DexSpeciesIsInvalid(species)) {
        return FALSE;
    }
    if (CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

u32 Pokedex_GetSeenSpindaPersonality(Pokedex *pokedex, u32 arg) {
    u32 personality;
    ASSERT_POKEDEX(pokedex);
    if (arg == 0) {
        personality = pokedex->spindaPersonality;
    } else {
        GF_ASSERT(FALSE);
    }
    return personality;
}

int Pokedex_SpeciesGetLastSeenGender(Pokedex *pokedex, u16 species, u32 idx) {
    ASSERT_POKEDEX(pokedex);
    if (DexSpeciesIsInvalid(species)) {
        return -1;
    }
    if (CheckDexFlag((u8 *)pokedex->seenSpecies, species)) {
        return Pokedex_SpeciesGetLastSeenGender_Internal(pokedex, species, idx);
    }
    return -1;
}

int Pokedex_GetSeenFormByIdx_Unown(Pokedex *pokedex, int idx, u32 caught) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountRegisteredUnownLetters(pokedex, caught) <= idx) {
        return -1;
    }
    if (caught) {
        return pokedex->unownCaughtOrder[idx];
    } else {
        return pokedex->unownSeenOrder[idx];
    }
}

u32 Pokedex_GetSeenFormNum_Unown(Pokedex *pokedex, BOOL caught) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountRegisteredUnownLetters(pokedex, caught);
}

int Pokedex_GetSeenFormByIdx_Shellos(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHELLOS) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_2max(pokedex, SPECIES_SHELLOS, a1);
}

static u32 Pokedex_GetSeenFormNum_Shellos(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHELLOS);
}

static int Pokedex_GetSeenFormByIdx_Gastrodon(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GASTRODON) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_2max(pokedex, SPECIES_GASTRODON, a1);
}

static u32 Pokedex_GetSeenFormNum_Gastrodon(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GASTRODON);
}

static int Pokedex_GetSeenFormByIdx_Burmy(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_BURMY) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_BURMY, a1);
}

static u32 Pokedex_GetSeenFormNum_Burmy(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_BURMY);
}

static int Pokedex_GetSeenFormByIdx_Wormadam(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_WORMADAM) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_WORMADAM, a1);
}

static u32 Pokedex_GetSeenFormNum_Wormadam(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_WORMADAM);
}

static int Pokedex_GetSeenFormByIdx_Pichu(Pokedex *pokedex, int a1) {
    ASSERT_POKEDEX(pokedex);
    if (Pokedex_CountSeenForms_3max(pokedex, SPECIES_PICHU) <= a1) {
        return -1;
    }
    return Pokedex_GetSeenFormByIdx_3max(pokedex, SPECIES_PICHU, a1);
}

static u32 Pokedex_GetSeenFormNum_Pichu(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenForms_3max(pokedex, SPECIES_PICHU);
}

static u32 Pokedex_GetSeenFormByIdx_Deoxys(Pokedex *pokedex, u32 a1) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_GetSeenDeoxysFormByIndex(pokedex, a1);
}

static u32 Pokedex_GetSeenFormNum_Deoxys(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return Pokedex_CountSeenDeoxysForms(pokedex);
}

void Pokedex_SetMonSeenFlag(Pokedex *pokedex, Pokemon *mon) {
    u16 species;
    u32 personality;
    u32 gender;
    u8 seenGender;

    species = SpeciesToDexSpecies(GetMonData(mon, MON_DATA_SPECIES, NULL));
    personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    gender = GetMonGender(mon);

    ASSERT_POKEDEX(pokedex);
    if (!DexSpeciesIsInvalid(species)) {
        if (!CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
            if (species == SPECIES_SPINDA) {
                pokedex->spindaPersonality = personality;
            }
            Pokedex_SetSeenGenderFlag(pokedex, gender, 0, species);
        } else {
            seenGender = CheckDexFlag((const u8 *)pokedex->seenGenders[0], species);
            if (seenGender != gender) {
                Pokedex_SetSeenGenderFlag(pokedex, gender, 1, species);
            }
        }
        Pokedex_TryAppendSeenForm(pokedex, species, mon);
        SetDexFlag((u8 *)pokedex->seenSpecies, species);
    }
}

void Pokedex_SetMonCaughtFlag(Pokedex *pokedex, Pokemon *mon) {
    u16 species;
    u32 language;
    u32 personality;
    u32 gender;
    u32 gender_ct;

    species = SpeciesToDexSpecies(GetMonData(mon, MON_DATA_SPECIES, NULL));
    language = GetMonData(mon, MON_DATA_LANGUAGE, NULL);
    personality = GetMonData(mon, MON_DATA_PERSONALITY, NULL);
    gender = GetMonGender(mon);

    ASSERT_POKEDEX(pokedex);
    if (!DexSpeciesIsInvalid(species)) {
        if (!CheckDexFlag((const u8 *)pokedex->seenSpecies, species)) {
            if (species == SPECIES_SPINDA) {
                pokedex->spindaPersonality = personality;
            }
            Pokedex_SetSeenGenderFlag(pokedex, gender, 0, species);
        } else {
            gender_ct = CheckDexGender((const u8 *)pokedex->seenGenders[0], species);
            if (gender_ct != gender) {
                Pokedex_SetSeenGenderFlag(pokedex, gender, 1, species);
            }
        }
        Pokedex_TryAppendSeenForm(pokedex, species, mon);
        if (species == SPECIES_UNOWN) {
            Pokedex_TryAppendUnownLetter(pokedex, GetMonUnownLetter(mon), TRUE);
        }
        Pokedex_SetCaughtLanguage(pokedex, species, language);
        if (language != GAME_LANGUAGE) {
            Pokedex_SetInternationalViewFlag(pokedex);
        }
        SetDexFlag((u8 *)pokedex->caughtSpecies, species);
        SetDexFlag((u8 *)pokedex->seenSpecies, species);
    }
}

void Pokedex_SetNatDexFlag(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->nationalDex = TRUE;
}

BOOL Pokedex_GetNatDexFlag(const Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return pokedex->nationalDex;
}

void Pokedex_EnableFormDetection(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->canDetectForms = TRUE;
}

BOOL Pokedex_HasCaughtMonWithLanguage(Pokedex *pokedex, u32 species, u32 language) {
    int shift;
    GF_ASSERT(language <= 8);
    ASSERT_POKEDEX(pokedex);
    shift = LanguageToDexFlag(language);
    if (pokedex->caughtLanguages[species] & (1 << shift)) {
        return TRUE;
    } else {
        return FALSE;
    }
}

void Pokedex_SetInternationalViewFlag(Pokedex *pokedex) {
    pokedex->enabledInternational = TRUE;
}

BOOL Pokedex_GetInternationalViewFlag(const Pokedex *pokedex) {
    return pokedex->enabledInternational;
}

BOOL Pokedex_IsEnabled(const Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    return pokedex->dexEnabled;
}

void Pokedex_Enable(Pokedex *pokedex) {
    ASSERT_POKEDEX(pokedex);
    pokedex->dexEnabled = TRUE;
}

Pokedex *Save_Pokedex_Get(SaveData *saveData) {
    return SaveArray_Get(saveData, SAVE_POKEDEX);
}

int Pokedex_GetSeenFormByIdx(Pokedex *pokedex, int species, int idx) {
    ASSERT_POKEDEX(pokedex);
    switch (species) {
    case SPECIES_UNOWN:
        if (idx < Pokedex_GetSeenFormNum_Unown(pokedex, 0)) {
            return Pokedex_GetSeenFormByIdx_Unown(pokedex, idx, 0);
        }
        break;
    case SPECIES_SHELLOS:
        if (idx < Pokedex_GetSeenFormNum_Shellos(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Shellos(pokedex, idx);
        }
        break;
    case SPECIES_GASTRODON:
        if (idx < Pokedex_GetSeenFormNum_Gastrodon(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Gastrodon(pokedex, idx);
        }
        break;
    case SPECIES_BURMY:
        if (idx < Pokedex_GetSeenFormNum_Burmy(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Burmy(pokedex, idx);
        }
        break;
    case SPECIES_WORMADAM:
        if (idx < Pokedex_GetSeenFormNum_Wormadam(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Wormadam(pokedex, idx);
        }
        break;
    case SPECIES_PICHU:
        if (idx < Pokedex_GetSeenFormNum_Pichu(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Pichu(pokedex, idx);
        }
        break;
    case SPECIES_DEOXYS:
        if (idx < Pokedex_GetSeenFormNum_Deoxys(pokedex)) {
            return Pokedex_GetSeenFormByIdx_Deoxys(pokedex, idx);
        }
        break;
    case SPECIES_SHAYMIN:
    case SPECIES_GIRATINA:
        if (idx < Pokedex_GetSeenFormNum_2max(pokedex, species)) {
            return Pokedex_GetSeenFormByIdx_2max(pokedex, species, idx);
        }
        break;
    case SPECIES_ROTOM:
        if (idx < Pokedex_GetSeenFormNum_Rotom(pokedex, SPECIES_ROTOM)) {
            return Pokedex_GetSeenFormByIdx_Rotom(pokedex, SPECIES_ROTOM, idx);
        }
        break;
    }
    return 0;
}

int Pokedex_GetSeenFormNum(Pokedex *pokedex, int species) {
    ASSERT_POKEDEX(pokedex);
    switch (species) {
    case SPECIES_UNOWN:
        return Pokedex_GetSeenFormNum_Unown(pokedex, 0);
    case SPECIES_SHELLOS:
        return Pokedex_GetSeenFormNum_Shellos(pokedex);
    case SPECIES_GASTRODON:
        return Pokedex_GetSeenFormNum_Gastrodon(pokedex);
    case SPECIES_BURMY:
        return Pokedex_GetSeenFormNum_Burmy(pokedex);
    case SPECIES_WORMADAM:
        return Pokedex_GetSeenFormNum_Wormadam(pokedex);
    case SPECIES_PICHU:
        return Pokedex_GetSeenFormNum_Pichu(pokedex);
    case SPECIES_DEOXYS:
        return Pokedex_GetSeenFormNum_Deoxys(pokedex);
    case SPECIES_SHAYMIN:
        return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_SHAYMIN);
    case SPECIES_GIRATINA:
        return Pokedex_GetSeenFormNum_2max(pokedex, SPECIES_GIRATINA);
    case SPECIES_ROTOM:
        return Pokedex_GetSeenFormNum_Rotom(pokedex, SPECIES_ROTOM);
    }
    return 1;
}
