#include "pokemon_icon_idx.h"

#include "global.h"

#include "constants/species.h"

#include "pokemon.h"

static u16 BoxMonGetForm(BoxPokemon *boxMon);

u32 Boxmon_GetIconNaix(BoxPokemon *boxMon) {
    BOOL encry;
    int species;
    BOOL isEgg;
    int form;
    u32 ret;

    encry = AcquireBoxMonLock(boxMon);
    species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    isEgg = GetBoxMonData(boxMon, MON_DATA_IS_EGG, NULL);
    form = BoxMonGetForm(boxMon);
    ret = GetMonIconNaixEx(species, isEgg, form);
    ReleaseBoxMonLock(boxMon, encry);
    return ret;
}

u32 Pokemon_GetIconNaix(Pokemon *mon) {
    return Boxmon_GetIconNaix(Mon_GetBoxMon(mon));
}

u32 GetMonIconNaixEx(u32 species, BOOL isEgg, u32 form) {
    if (isEgg == TRUE) {
        if (species == SPECIES_MANAPHY) {
            return 502;
        } else {
            return 501;
        }
    }

    form = sub_02070438(species, form);
    if (form != 0) {
        if (species == SPECIES_DEOXYS) {
            return form + 503 - 1;
        } else if (species == SPECIES_UNOWN) {
            return form + 507 - 1;
        } else if (species == SPECIES_BURMY) {
            return form + 534 - 1;
        } else if (species == SPECIES_WORMADAM) {
            return form + 536 - 1;
        } else if (species == SPECIES_SHELLOS) {
            return form + 538 - 1;
        } else if (species == SPECIES_GASTRODON) {
            return form + 539 - 1;
        } else if (species == SPECIES_GIRATINA) {
            return form + 540 - 1;
        } else if (species == SPECIES_SHAYMIN) {
            return form + 541 - 1;
        } else if (species == SPECIES_ROTOM) {
            return form + 542 - 1;
        }
    }
    if (species > MAX_SPECIES) {
        if (species >= SPECIES_LILLIPUP && species <= NUM_SPECIES) {
            return species - SPECIES_LILLIPUP + FIRST_ADDED_ICON;
        }
        species = 0;
    }
    return species + 7;
}

u32 GetBattleMonIconNaixEx(u32 species, BOOL isEgg, u32 form) {
    if (!isEgg) {
        if (species == SPECIES_CASTFORM) {
            form = sub_02070438(species, form);
            if (form != 0) {
                return form + 547 - 1;
            }
        } else if (species == SPECIES_CHERRIM) {
            form = sub_02070438(species, form);
            if (form != 0) {
                return form + 550 - 1;
            }
        }
    }
    return GetMonIconNaixEx(species, isEgg, form);
}

static u16 BoxMonGetForm(BoxPokemon *boxMon) {
    switch (GetBoxMonData(boxMon, MON_DATA_SPECIES_OR_EGG, NULL)) {
    case SPECIES_UNOWN:
        return GetBoxMonUnownLetter(boxMon);
    case SPECIES_DEOXYS:
    case SPECIES_SHELLOS:
    case SPECIES_GASTRODON:
    case SPECIES_BURMY:
    case SPECIES_WORMADAM:
    case SPECIES_GIRATINA:
    case SPECIES_SHAYMIN:
    case SPECIES_ROTOM:
        return GetBoxMonData(boxMon, MON_DATA_FORM, NULL);
    default:
        return 0;
    }
}

static const u8 sPokemonPalNoBySpeciesAndForm[] = {
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    2,
    2,
    1,
    1,
    0,
    1,
    2,
    2,
    0,
    0,
    0,
    2,
    1,
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    2,
    1,
    0,
    0,
    2,
    2,
    1,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    1,
    1,
    1,
    2,
    1,
    2,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    0,
    2,
    0,
    1,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    1,
    2,
    2,
    0,
    0,
    0,
    1,
    1,
    1,
    2,
    2,
    1,
    2,
    2,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    2,
    1,
    0,
    2,
    2,
    0,
    0,
    2,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    1,
    2,
    2,
    0,
    0,
    2,
    0,
    0,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    0,
    0,
    2,
    2,
    2,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    2,
    2,
    0,
    0,
    2,
    0,
    0,
    1,
    2,
    0,
    0,
    2,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    0,
    2,
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    2,
    0,
    2,
    0,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    2,
    2,
    0,
    0,
    1,
    1,
    1,
    2,
    0,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    0,
    2,
    2,
    2,
    1,
    2,
    0,
    0,
    2,
    2,
    2,
    2,
    2,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    2,
    0,
    1,
    2,
    0,
    0,
    2,
    0,
    1,
    0,
    1,
    0,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    2,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    0,
    0,
    0,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    2,
    2,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    2,
    2,
    2,
    2,
    0,
    1,
    0,
    2,
    0,
    2,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    2,
    1,
    1,
    0,
    2,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    2,
    1,
    0,
    2,
    1,
    1,
    0,
    2,
    2,
    0,
    1,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    2,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    2,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    // The species New Gold adds, in identifier order from 508.
    2, // LILLIPUP,
    2, // HERDIER,
    2, // STOUTLAND,
    0, // PURRLOIN,
    0, // LIEPARD,
    2, // TYMPOLE,
    2, // PALPITOAD,
    0, // SEISMITOAD,
    1, // SEWADDLE,
    1, // SWADLOON,
    1, // LEAVANNY,
    0, // YAMASK,
    0, // COFAGRIGUS,
    1, // TRUBBISH,
    1, // GARBODOR,
    2, // EMOLGA,
    0, // KARRABLAST,
    0, // ESCAVALIER,
    0, // FOONGUS,
    0, // AMOONGUSS,
    0, // JOLTIK,
    2, // GALVANTULA,
    1, // FERROSEED,
    1, // FERROTHORN,
    0, // KLINK,
    0, // KLANG,
    0, // KLINKLANG,
    0, // ELGYEM,
    2, // BEHEEYEM,
    2, // LITWICK,
    2, // LAMPENT,
    2, // CHANDELURE,
    1, // SHELMET,
    1, // ACCELGOR,
    2, // BOUFFALANT,
    2, // BUNNELBY,
    2, // DIGGERSBY,
    0, // FLETCHLING,
    0, // FLETCHINDER,
    0, // TALONFLAME,
    2, // LITLEO,
    2, // PYROAR,
    2, // ESPURR,
    0, // MEOWSTIC,
    0, // SYLVEON,
    0, // DEDENNE,
    1, // PHANTUMP,
    1, // TREVENANT,
    2, // PUMPKABOO,
    2, // GOURGEIST,
    2, // NOIBAT,
    2, // NOIVERN,
    1, // APPLIN,
    1, // FLAPPLE,
    1, // APPLETUN,
    0, // SIZZLIPEDE,
    0, // CENTISKORCH,
    0, // WYRDEER,
    2, // KLEAVOR,
    2, // URSALUNA,
    0, // ANNIHILAPE,
    0, // FARIGIRAF,
    0, // DUDUNSPARCE,
    1, // DIPPLIN,
    1, // HYDRAPPLE,
    1, // SLOWPOKE_GALARIAN,
    0, // SLOWBRO_GALARIAN,
    0, // VICTINI,
    1, // SNIVY,
    1, // SERVINE,
    1, // SERPERIOR,
    0, // TEPIG,
    0, // PIGNITE,
    0, // EMBOAR,
    0, // OSHAWOTT,
    0, // DEWOTT,
    2, // SAMUROTT,
    2, // PATRAT,
    2, // WATCHOG,
    1, // PANSAGE,
    1, // SIMISAGE,
    2, // PANSEAR,
    2, // SIMISEAR,
    2, // PANPOUR,
    2, // SIMIPOUR,
    0, // MUNNA,
    0, // MUSHARNA,
    0, // PIDOVE,
    0, // TRANQUILL,
    1, // UNFEZANT,
    2, // BLITZLE,
    2, // ZEBSTRIKA,
    2, // ROGGENROLA,
    0, // BOLDORE,
    0, // GIGALITH,
    0, // WOOBAT,
    0, // SWOOBAT,
    0, // DRILBUR,
    0, // EXCADRILL,
    1, // AUDINO,
    1, // TIMBURR,
    1, // GURDURR,
    1, // CONKELDURR,
    0, // THROH,
    0, // SAWK,
    1, // VENIPEDE,
    2, // WHIRLIPEDE,
    2, // SCOLIPEDE,
    1, // COTTONEE,
    1, // WHIMSICOTT,
    1, // PETILIL,
    1, // LILLIGANT,
    1, // BASCULIN,
    1, // SANDILE,
    1, // KROKOROK,
    0, // KROOKODILE,
    0, // DARUMAKA,
    0, // DARMANITAN,
    1, // MARACTUS,
    0, // DWEBBLE,
    2, // CRUSTLE,
    2, // SCRAGGY,
    0, // SCRAFTY,
    0, // SIGILYPH,
    2, // TIRTOUGA,
    2, // CARRACOSTA,
    0, // ARCHEN,
    0, // ARCHEOPS,
    0, // ZORUA,
    0, // ZOROARK,
    0, // MINCCINO,
    0, // CINCCINO,
    2, // GOTHITA,
    2, // GOTHORITA,
    2, // GOTHITELLE,
    1, // SOLOSIS,
    1, // DUOSION,
    1, // REUNICLUS,
    0, // DUCKLETT,
    2, // SWANNA,
    0, // VANILLITE,
    2, // VANILLISH,
    2, // VANILLUXE,
    1, // DEERLING,
    1, // SAWSBUCK,
    0, // FRILLISH,
    0, // JELLICENT,
    0, // ALOMOMOLA,
    0, // TYNAMO,
    0, // EELEKTRIK,
    0, // EELEKTROSS,
    1, // AXEW,
    1, // FRAXURE,
    2, // HAXORUS,
    0, // CUBCHOO,
    0, // BEARTIC,
    0, // CRYOGONAL,
    2, // STUNFISK,
    1, // MIENFOO,
    2, // MIENSHAO,
    0, // DRUDDIGON,
    0, // GOLETT,
    0, // GOLURK,
    0, // PAWNIARD,
    0, // BISHARP,
    2, // RUFFLET,
    0, // BRAVIARY,
    0, // VULLABY,
    1, // MANDIBUZZ,
    2, // HEATMOR,
    0, // DURANT,
    2, // DEINO,
    2, // ZWEILOUS,
    2, // HYDREIGON,
    0, // LARVESTA,
    0, // VOLCARONA,
    0, // COBALION,
    2, // TERRAKION,
    1, // VIRIZION,
    1, // TORNADUS,
    0, // THUNDURUS,
    0, // RESHIRAM,
    2, // ZEKROM,
    0, // LANDORUS,
    0, // KYUREM,
    0, // KELDEO,
    1, // MELOETTA,
    2, // GENESECT,
    1, // CHESPIN,
    1, // QUILLADIN,
    1, // CHESNAUGHT,
    0, // FENNEKIN,
    0, // BRAIXEN,
    0, // DELPHOX,
    0, // FROAKIE,
    0, // FROGADIER,
    0, // GRENINJA,
    0, // SCATTERBUG,
    1, // SPEWPA,
    0, // VIVILLON,
    1, // FLABEBE,
    1, // FLOETTE,
    0, // FLORGES,
    1, // SKIDDO,
    1, // GOGOAT,
    1, // PANCHAM,
    0, // PANGORO,
    0, // FURFROU,
    2, // HONEDGE,
    2, // DOUBLADE,
    2, // AEGISLASH,
    0, // SPRITZEE,
    0, // AROMATISSE,
    1, // SWIRLIX,
    1, // SLURPUFF,
    0, // INKAY,
    2, // MALAMAR,
    2, // BINACLE,
    2, // BARBARACLE,
    2, // SKRELP,
    2, // DRAGALGE,
    0, // CLAUNCHER,
    0, // CLAWITZER,
    0, // HELIOPTILE,
    0, // HELIOLISK,
    2, // TYRUNT,
    0, // TYRANTRUM,
    0, // AMAURA,
    0, // AURORUS,
    0, // HAWLUCHA,
    0, // CARBINK,
    2, // GOOMY,
    2, // SLIGGOO,
    2, // GOODRA,
    0, // KLEFKI,
    0, // BERGMITE,
    0, // AVALUGG,
    0, // XERNEAS,
    0, // YVELTAL,
    1, // ZYGARDE,
    0, // DIANCIE,
    0, // HOOPA,
    0, // VOLCANION,
    0, // ROWLET,
    1, // DARTRIX,
    1, // DECIDUEYE,
    0, // LITTEN,
    0, // TORRACAT,
    0, // INCINEROAR,
    0, // POPPLIO,
    0, // BRIONNE,
    0, // PRIMARINA,
    2, // PIKIPEK,
    0, // TRUMBEAK,
    0, // TOUCANNON,
    2, // YUNGOOS,
    2, // GUMSHOOS,
    0, // GRUBBIN,
    1, // CHARJABUG,
    0, // VIKAVOLT,
    2, // CRABRAWLER,
    2, // CRABOMINABLE,
    0, // ORICORIO,
    2, // CUTIEFLY,
    2, // RIBOMBEE,
    2, // ROCKRUFF,
    2, // LYCANROC,
    2, // WISHIWASHI,
    2, // MAREANIE,
    0, // TOXAPEX,
    2, // MUDBRAY,
    0, // MUDSDALE,
    0, // DEWPIDER,
    2, // ARAQUANID,
    1, // FOMANTIS,
    1, // LURANTIS,
    0, // MORELULL,
    1, // SHIINOTIC,
    2, // SALANDIT,
    0, // SALAZZLE,
    0, // STUFFUL,
    0, // BEWEAR,
    1, // BOUNSWEET,
    1, // STEENEE,
    1, // TSAREENA,
    1, // COMFEY,
    0, // ORANGURU,
    1, // PASSIMIAN,
    2, // WIMPOD,
    2, // GOLISOPOD,
    1, // SANDYGAST,
    2, // PALOSSAND,
    0, // PYUKUMUKU,
    0, // TYPE_NULL,
    0, // SILVALLY,
    2, // MINIOR,
    2, // KOMALA,
    0, // TURTONATOR,
    2, // TOGEDEMARU,
    1, // MIMIKYU,
    0, // BRUXISH,
    0, // DRAMPA,
    1, // DHELMISE,
    2, // JANGMO_O,
    2, // HAKAMO_O,
    2, // KOMMO_O,
    0, // TAPU_KOKO,
    0, // TAPU_LELE,
    2, // TAPU_BULU,
    2, // TAPU_FINI,
    2, // COSMOG,
    0, // COSMOEM,
    0, // SOLGALEO,
    2, // LUNALA,
    0, // NIHILEGO,
    0, // BUZZWOLE,
    2, // PHEROMOSA,
    0, // XURKITREE,
    0, // CELESTEELA,
    0, // KARTANA,
    0, // GUZZLORD,
    0, // NECROZMA,
    0, // MAGEARNA,
    0, // MARSHADOW,
    0, // POIPOLE,
    0, // NAGANADEL,
    0, // STAKATAKA,
    0, // BLACEPHALON,
    0, // ZERAORA,
    2, // MELTAN,
    2, // MELMETAL,
    1, // GROOKEY,
    1, // THWACKEY,
    1, // RILLABOOM,
    0, // SCORBUNNY,
    0, // RABOOT,
    0, // CINDERACE,
    2, // SOBBLE,
    2, // DRIZZILE,
    0, // INTELEON,
    2, // SKWOVET,
    0, // GREEDENT,
    0, // ROOKIDEE,
    0, // CORVISQUIRE,
    0, // CORVIKNIGHT,
    0, // BLIPBUG,
    2, // DOTTLER,
    0, // ORBEETLE,
    2, // NICKIT,
    2, // THIEVUL,
    1, // GOSSIFLEUR,
    1, // ELDEGOSS,
    0, // WOOLOO,
    2, // DUBWOOL,
    0, // CHEWTLE,
    0, // DREDNAW,
    1, // YAMPER,
    1, // BOLTUND,
    0, // ROLYCOLY,
    0, // CARKOL,
    0, // COALOSSAL,
    1, // SILICOBRA,
    1, // SANDACONDA,
    0, // CRAMORANT,
    2, // ARROKUDA,
    2, // BARRASKEWDA,
    2, // TOXEL,
    2, // TOXTRICITY,
    0, // CLOBBOPUS,
    2, // GRAPPLOCT,
    2, // SINISTEA,
    2, // POLTEAGEIST,
    0, // HATENNA,
    0, // HATTREM,
    0, // HATTERENE,
    0, // IMPIDIMP,
    0, // MORGREM,
    0, // GRIMMSNARL,
    0, // OBSTAGOON,
    2, // PERRSERKER,
    0, // CURSOLA,
    1, // SIRFETCHD,
    0, // MR_RIME,
    2, // RUNERIGUS,
    1, // MILCERY,
    1, // ALCREMIE,
    0, // FALINKS,
    0, // PINCURCHIN,
    0, // SNOM,
    0, // FROSMOTH,
    0, // STONJOURNER,
    0, // EISCUE,
    2, // INDEEDEE,
    2, // MORPEKO,
    0, // CUFANT,
    0, // COPPERAJAH,
    1, // DRACOZOLT,
    2, // ARCTOZOLT,
    0, // DRACOVISH,
    0, // ARCTOVISH,
    0, // DURALUDON,
    0, // DREEPY,
    0, // DRAKLOAK,
    0, // DRAGAPULT,
    2, // ZACIAN,
    2, // ZAMAZENTA,
    0, // ETERNATUS,
    2, // KUBFU,
    2, // URSHIFU,
    1, // ZARUDE,
    0, // REGIELEKI,
    2, // REGIDRAGO,
    0, // GLASTRIER,
    0, // SPECTRIER,
    0, // CALYREX,
    1, // BASCULEGION,
    2, // SNEASLER,
    2, // OVERQWIL,
    1, // ENAMORUS,
    1, // SPRIGATITO,
    1, // FLORAGATO,
    1, // MEOWSCARADA,
    2, // FUECOCO,
    0, // CROCALOR,
    0, // SKELEDIRGE,
    0, // QUAXLY,
    0, // QUAXWELL,
    0, // QUAQUAVAL,
    1, // LECHONK,
    0, // OINKOLOGNE,
    1, // TAROUNTULA,
    1, // SPIDOPS,
    0, // NYMBLE,
    0, // LOKIX,
    0, // PAWMI,
    0, // PAWMO,
    0, // PAWMOT,
    0, // TANDEMAUS,
    0, // MAUSHOLD,
    1, // FIDOUGH,
    0, // DACHSBUN,
    1, // SMOLIV,
    1, // DOLLIV,
    1, // ARBOLIVA,
    1, // SQUAWKABILLY,
    2, // NACLI,
    2, // NACLSTACK,
    2, // GARGANACL,
    0, // CHARCADET,
    0, // ARMAROUGE,
    0, // CERULEDGE,
    2, // TADBULB,
    0, // BELLIBOLT,
    0, // WATTREL,
    0, // KILOWATTREL,
    0, // MASCHIFF,
    0, // MABOSSTIFF,
    0, // SHROODLE,
    0, // GRAFAIAI,
    1, // BRAMBLIN,
    2, // BRAMBLEGHAST,
    0, // TOEDSCOOL,
    0, // TOEDSCRUEL,
    0, // KLAWF,
    1, // CAPSAKID,
    1, // SCOVILLAIN,
    0, // RELLOR,
    0, // RABSCA,
    1, // FLITTLE,
    0, // ESPATHRA,
    1, // TINKATINK,
    1, // TINKATUFF,
    1, // TINKATON,
    0, // WIGLETT,
    0, // WUGTRIO,
    0, // BOMBIRDIER,
    0, // FINIZEN,
    0, // PALAFIN,
    0, // VAROOM,
    0, // REVAVROOM,
    1, // CYCLIZAR,
    0, // ORTHWORM,
    0, // GLIMMET,
    0, // GLIMMORA,
    0, // GREAVARD,
    2, // HOUNDSTONE,
    0, // FLAMIGO,
    0, // CETODDLE,
    0, // CETITAN,
    1, // VELUZA,
    0, // DONDOZO,
    0, // TATSUGIRI,
    0, // CLODSIRE,
    0, // KINGAMBIT,
    0, // GREAT_TUSK,
    0, // SCREAM_TAIL,
    1, // BRUTE_BONNET,
    2, // FLUTTER_MANE,
    2, // SLITHER_WING,
    0, // SANDY_SHOCKS,
    1, // IRON_TREADS,
    0, // IRON_BUNDLE,
    0, // IRON_HANDS,
    0, // IRON_JUGULIS,
    0, // IRON_MOTH,
    1, // IRON_THORNS,
    0, // FRIGIBAX,
    0, // ARCTIBAX,
    0, // BAXCALIBUR,
    0, // GIMMIGHOUL,
    0, // GHOLDENGO,
    1, // WO_CHIEN,
    0, // CHIEN_PAO,
    0, // TING_LU,
    0, // CHI_YU,
    0, // ROARING_MOON,
    1, // IRON_VALIANT,
    0, // KORAIDON,
    2, // MIRAIDON,
    2, // WALKING_WAKE,
    1, // IRON_LEAVES,
    0, // POLTCHAGEIST,
    1, // SINISTCHA,
    1, // OKIDOGI,
    0, // MUNKIDORI,
    0, // FEZANDIPITI,
    1, // OGERPON,
    0, // ARCHALUDON,
    2, // GOUGING_FIRE,
    2, // RAGING_BOLT,
    0, // IRON_BOULDER,
    0, // IRON_CROWN,
    0, // TERAPAGOS,
    0, // PECHARUNT,
    1, // MEGA_VENUSAUR,
    0, // MEGA_CHARIZARD_X,
    0, // MEGA_CHARIZARD_Y,
    2, // MEGA_BLASTOISE,
    2, // MEGA_BEEDRILL,
    0, // MEGA_PIDGEOT,
    2, // MEGA_ALAKAZAM,
    0, // MEGA_SLOWBRO,
    2, // MEGA_GENGAR,
    2, // MEGA_KANGASKHAN,
    2, // MEGA_PINSIR,
    0, // MEGA_GYARADOS,
    2, // MEGA_AERODACTYL,
    2, // MEGA_MEWTWO_X,
    2, // MEGA_MEWTWO_Y,
    0, // MEGA_AMPHAROS,
    0, // MEGA_STEELIX,
    2, // MEGA_SCIZOR,
    0, // MEGA_HERACROSS,
    0, // MEGA_HOUNDOOM,
    1, // MEGA_TYRANITAR,
    1, // MEGA_SCEPTILE,
    0, // MEGA_BLAZIKEN,
    0, // MEGA_SWAMPERT,
    1, // MEGA_GARDEVOIR,
    2, // MEGA_SABLEYE,
    0, // MEGA_MAWILE,
    2, // MEGA_AGGRON,
    0, // MEGA_MEDICHAM,
    0, // MEGA_MANECTRIC,
    0, // MEGA_SHARPEDO,
    0, // MEGA_CAMERUPT,
    0, // MEGA_ALTARIA,
    0, // MEGA_BANETTE,
    0, // MEGA_ABSOL,
    0, // MEGA_GLALIE,
    0, // MEGA_SALAMENCE,
    0, // MEGA_METAGROSS,
    2, // MEGA_LATIAS,
    2, // MEGA_LATIOS,
    1, // MEGA_RAYQUAZA,
    2, // MEGA_LOPUNNY,
    0, // MEGA_GARCHOMP,
    2, // MEGA_LUCARIO,
    1, // MEGA_ABOMASNOW,
    1, // MEGA_GALLADE,
    1, // MEGA_AUDINO,
    0, // MEGA_DIANCIE,
    0, // KYOGRE_PRIMAL,
    1, // GROUDON_PRIMAL,
    2, // RATTATA_ALOLAN,
    2, // RATICATE_ALOLAN,
    2, // RAICHU_ALOLAN,
    0, // SANDSHREW_ALOLAN,
    0, // SANDSLASH_ALOLAN,
    0, // VULPIX_ALOLAN,
    2, // NINETALES_ALOLAN,
    2, // DIGLETT_ALOLAN,
    2, // DUGTRIO_ALOLAN,
    2, // MEOWTH_ALOLAN,
    2, // PERSIAN_ALOLAN,
    2, // GEODUDE_ALOLAN,
    2, // GRAVELER_ALOLAN,
    2, // GOLEM_ALOLAN,
    1, // GRIMER_ALOLAN,
    0, // MUK_ALOLAN,
    1, // EXEGGUTOR_ALOLAN,
    1, // MAROWAK_ALOLAN,
    2, // RATICATE_ALOLAN_LARGE,
    1, // MAROWAK_ALOLAN_LARGE,
    2, // GUMSHOOS_LARGE,
    0, // VIKAVOLT_LARGE,
    2, // RIBOMBEE_LARGE,
    2, // ARAQUANID_LARGE,
    1, // LURANTIS_LARGE,
    0, // SALAZZLE_LARGE,
    2, // TOGEDEMARU_LARGE,
    1, // MIMIKYU_LARGE,
    1, // MIMIKYU_BUSTED_LARGE,
    2, // KOMMO_O_LARGE,
    2, // MEOWTH_GALARIAN,
    2, // PONYTA_GALARIAN,
    2, // RAPIDASH_GALARIAN,
    1, // FARFETCHD_GALARIAN,
    1, // WEEZING_GALARIAN,
    0, // MR_MIME_GALARIAN,
    2, // ARTICUNO_GALARIAN,
    0, // ZAPDOS_GALARIAN,
    1, // MOLTRES_GALARIAN,
    2, // SLOWKING_GALARIAN,
    0, // CORSOLA_GALARIAN,
    0, // ZIGZAGOON_GALARIAN,
    0, // LINOONE_GALARIAN,
    0, // DARUMAKA_GALARIAN,
    0, // DARMANITAN_GALARIAN,
    2, // YAMASK_GALARIAN,
    1, // STUNFISK_GALARIAN,
    2, // PIKACHU_COSPLAY,
    1, // PIKACHU_ROCK_STAR,
    0, // PIKACHU_BELLE,
    0, // PIKACHU_POP_STAR,
    1, // PIKACHU_PH_D,
    0, // PIKACHU_LIBRE,
    0, // PIKACHU_ORIGINAL_CAP,
    0, // PIKACHU_HOENN_CAP,
    0, // PIKACHU_SINNOH_CAP,
    0, // PIKACHU_UNOVA_CAP,
    0, // PIKACHU_KALOS_CAP,
    0, // PIKACHU_ALOLA_CAP,
    0, // PIKACHU_PARTNER_CAP,
    0, // PIKACHU_WORLD_CAP,
    0, // CASTFORM_SUNNY,
    0, // CASTFORM_RAINY,
    0, // CASTFORM_SNOWY,
    1, // CHERRIM_SUNSHINE,
    0, // SHELLOS_EAST_SEA,
    0, // GASTRODON_EAST_SEA,
    0, // DIALGA_ORIGIN,
    2, // PALKIA_ORIGIN,
    0, // BASCULIN_BLUE_STRIPED,
    0, // BASCULIN_WHITE_STRIPED,
    0, // DARMANITAN_ZEN_MODE,
    0, // DARMANITAN_ZEN_MODE_GALARIAN,
    1, // DEERLING_SUMMER,
    0, // DEERLING_AUTUMN,
    2, // DEERLING_WINTER,
    1, // SAWSBUCK_SUMMER,
    1, // SAWSBUCK_AUTUMN,
    1, // SAWSBUCK_WINTER,
    1, // TORNADUS_THERIAN,
    0, // THUNDURUS_THERIAN,
    0, // LANDORUS_THERIAN,
    0, // KYUREM_WHITE,
    0, // KYUREM_BLACK,
    0, // KELDEO_RESOLUTE,
    0, // MELOETTA_PIROUETTE,
    2, // GENESECT_DOUSE_DRIVE,
    2, // GENESECT_SHOCK_DRIVE,
    2, // GENESECT_BURN_DRIVE,
    2, // GENESECT_CHILL_DRIVE,
    0, // GRENINJA_BATTLE_BOND,
    0, // GRENINJA_ASH,
    0, // VIVILLON_POLAR,
    0, // VIVILLON_TUNDRA,
    2, // VIVILLON_CONTINENTAL,
    1, // VIVILLON_GARDEN,
    0, // VIVILLON_ELEGANT,
    0, // VIVILLON_MEADOW,
    2, // VIVILLON_MODERN,
    0, // VIVILLON_MARINE,
    0, // VIVILLON_ARCHIPELAGO,
    0, // VIVILLON_HIGH_PLAINS,
    1, // VIVILLON_SANDSTORM,
    2, // VIVILLON_RIVER,
    0, // VIVILLON_MONSOON,
    0, // VIVILLON_SAVANNA,
    0, // VIVILLON_SUN,
    0, // VIVILLON_OCEAN,
    0, // VIVILLON_JUNGLE,
    1, // VIVILLON_FANCY,
    2, // VIVILLON_POKE_BALL,
    1, // FLABEBE_YELLOW_FLOWER,
    0, // FLABEBE_ORANGE_FLOWER,
    0, // FLABEBE_BLUE_FLOWER,
    1, // FLABEBE_WHITE_FLOWER,
    1, // FLOETTE_YELLOW_FLOWER,
    0, // FLOETTE_ORANGE_FLOWER,
    0, // FLOETTE_BLUE_FLOWER,
    1, // FLOETTE_WHITE_FLOWER,
    0, // FLOETTE_ETERNAL_FLOWER,
    1, // FLORGES_YELLOW_FLOWER,
    0, // FLORGES_ORANGE_FLOWER,
    0, // FLORGES_BLUE_FLOWER,
    0, // FLORGES_WHITE_FLOWER,
    0, // FURFROU_HEART,
    0, // FURFROU_STAR,
    0, // FURFROU_DIAMOND,
    2, // FURFROU_DEBUTANTE,
    2, // FURFROU_MATRON,
    1, // FURFROU_DANDY,
    0, // FURFROU_LA_REINE,
    0, // FURFROU_KABUKI,
    0, // FURFROU_PHARAOH,
    2, // AEGISLASH_BLADE,
    2, // PUMPKABOO_SMALL,
    2, // PUMPKABOO_LARGE,
    2, // PUMPKABOO_SUPER,
    2, // GOURGEIST_SMALL,
    2, // GOURGEIST_LARGE,
    2, // GOURGEIST_SUPER,
    0, // XERNEAS_ACTIVE,
    1, // ZYGARDE_10,
    1, // ZYGARDE_10_POWER_CONSTRUCT,
    1, // ZYGARDE_50_POWER_CONSTRUCT,
    1, // ZYGARDE_10_COMPLETE,
    1, // ZYGARDE_50_COMPLETE,
    0, // HOOPA_UNBOUND,
    1, // ORICORIO_POM_POM,
    1, // ORICORIO_PAU,
    0, // ORICORIO_SENSU,
    2, // ROCKRUFF_OWN_TEMPO,
    0, // LYCANROC_MIDNIGHT,
    0, // LYCANROC_DUSK,
    0, // WISHIWASHI_SCHOOL,
    2, // MINIOR_METEOR_ORANGE,
    2, // MINIOR_METEOR_YELLOW,
    2, // MINIOR_METEOR_GREEN,
    2, // MINIOR_METEOR_BLUE,
    2, // MINIOR_METEOR_INDIGO,
    2, // MINIOR_METEOR_VIOLET,
    0, // MINIOR_CORE_RED,
    0, // MINIOR_CORE_ORANGE,
    0, // MINIOR_CORE_YELLOW,
    1, // MINIOR_CORE_GREEN,
    0, // MINIOR_CORE_BLUE,
    0, // MINIOR_CORE_INDIGO,
    2, // MINIOR_CORE_VIOLET,
    1, // MIMIKYU_BUSTED,
    0, // NECROZMA_DUSK_MANE,
    0, // NECROZMA_DAWN_WINGS,
    2, // NECROZMA_ULTRA_DUSK_MANE,
    2, // NECROZMA_ULTRA_DAWN_WINGS,
    0, // MAGEARNA_ORIGINAL,
    2, // PIKACHU_PARTNER,
    2, // EEVEE_PARTNER,
    0, // CRAMORANT_GULPING,
    0, // CRAMORANT_GORGING,
    2, // TOXTRICITY_LOW_KEY,
    2, // SINISTEA_ANTIQUE,
    2, // POLTEAGEIST_ANTIQUE,
    0, // ALCREMIE_BERRY_SWEET,
    0, // ALCREMIE_LOVE_SWEET,
    0, // ALCREMIE_STAR_SWEET,
    0, // ALCREMIE_CLOVER_SWEET,
    0, // ALCREMIE_FLOWER_SWEET,
    0, // ALCREMIE_RIBBON_SWEET,
    0, // EISCUE_NOICE_FACE,
    2, // MORPEKO_HANGRY,
    2, // ZACIAN_CROWNED,
    2, // ZAMAZENTA_CROWNED,
    0, // ETERNATUS_ETERNAMAX,
    2, // URSHIFU_RAPID_STRIKE,
    1, // ZARUDE_DADA,
    0, // CALYREX_ICE_RIDER,
    0, // CALYREX_SHADOW_RIDER,
    1, // ENAMORUS_THERIAN,
    0, // GROWLITHE_HISUIAN,
    0, // ARCANINE_HISUIAN,
    0, // VOLTORB_HISUIAN,
    2, // ELECTRODE_HISUIAN,
    1, // TYPHLOSION_HISUIAN,
    0, // QWILFISH_HISUIAN,
    2, // SNEASEL_HISUIAN,
    0, // SAMUROTT_HISUIAN,
    1, // LILLIGANT_HISUIAN,
    0, // ZORUA_HISUIAN,
    0, // ZOROARK_HISUIAN,
    2, // BRAVIARY_HISUIAN,
    2, // SLIGGOO_HISUIAN,
    2, // GOODRA_HISUIAN,
    2, // AVALUGG_HISUIAN,
    0, // DECIDUEYE_HISUIAN,
    0, // KLEAVOR_LORD,
    1, // LILLIGANT_LADY,
    0, // ARCANINE_LORD,
    2, // ELECTRODE_LORD,
    2, // AVALUGG_LORD,
    1, // UNFEZANT_FEMALE,
    0, // FRILLISH_FEMALE,
    0, // JELLICENT_FEMALE,
    2, // PYROAR_FEMALE,
    0, // MEOWSTIC_FEMALE,
    2, // INDEEDEE_FEMALE,
    0, // BASCULEGION_FEMALE,
    0, // MAUSHOLD_FAMILY_OF_THREE,
    0, // SQUAWKABILLY_BLUE_PLUMAGE,
    0, // SQUAWKABILLY_YELLOW_PLUMAGE,
    0, // SQUAWKABILLY_WHITE_PLUMAGE,
    0, // PALAFIN_HERO,
    0, // TATSUGIRI_DROOPY,
    1, // TATSUGIRI_STRETCHY,
    0, // DUDUNSPARCE_THREE_SEGMENT,
    1, // GIMMIGHOUL_ROAMING,
    2, // WOOPER_PALDEAN,
    0, // TAUROS_COMBAT,
    0, // TAUROS_BLAZE,
    0, // TAUROS_AQUA,
    0, // OINKOLOGNE_FEMALE,
    0, // REVAVROOM_SEGIN,
    0, // REVAVROOM_SCHEDAR,
    0, // REVAVROOM_NAVI,
    0, // REVAVROOM_RUCHBAH,
    0, // REVAVROOM_CAPH,
    0, // KORAIDON_LIMITED_BUILD,
    0, // KORAIDON_SPRINTING_BUILD,
    0, // KORAIDON_SWIMMING_BUILD,
    0, // KORAIDON_GLIDING_BUILD,
    2, // MIRAIDON_LOW_POWER_MODE,
    2, // MIRAIDON_DRIVE_MODE,
    2, // MIRAIDON_AQUATIC_MODE,
    2, // MIRAIDON_GLIDE_MODE,
    0, // POLTCHAGEIST_MASTERPIECE,
    0, // SINISTCHA_MASTERPIECE,
    0, // OGERPON_WELLSPRING_MASK,
    0, // OGERPON_HEARTHFLAME_MASK,
    0, // OGERPON_CORNERSTONE_MASK,
    1, // OGERPON_TEAL_MASK_TERASTAL,
    0, // OGERPON_WELLSPRING_MASK_TERASTAL,
    0, // OGERPON_HEARTHFLAME_MASK_TERASTAL,
    0, // OGERPON_CORNERSTONE_MASK_TERASTAL,
    2, // URSALUNA_BLOODMOON,
    0, // TERAPAGOS_TERASTAL,
    0, // TERAPAGOS_STELLAR,
    0, // GIGANTAMAX_VENUSAUR,
    0, // GIGANTAMAX_CHARIZARD,
    0, // GIGANTAMAX_BLASTOISE,
    0, // GIGANTAMAX_BUTTERFREE,
    0, // GIGANTAMAX_PIKACHU,
    0, // GIGANTAMAX_MEOWTH,
    0, // GIGANTAMAX_MACHAMP,
    0, // GIGANTAMAX_GENGAR,
    0, // GIGANTAMAX_KINGLER,
    0, // GIGANTAMAX_LAPRAS,
    0, // GIGANTAMAX_EEVEE,
    0, // GIGANTAMAX_SNORLAX,
    0, // GIGANTAMAX_GARBODOR,
    0, // GIGANTAMAX_MELMETAL,
    0, // GIGANTAMAX_RILLABOOM,
    0, // GIGANTAMAX_CINDERACE,
    0, // GIGANTAMAX_INTELEON,
    0, // GIGANTAMAX_CORVIKNIGHT,
    0, // GIGANTAMAX_ORBEETLE,
    0, // GIGANTAMAX_DREDNAW,
    0, // GIGANTAMAX_COALOSSAL,
    0, // GIGANTAMAX_FLAPPLE,
    0, // GIGANTAMAX_APPLETUN,
    0, // GIGANTAMAX_SANDACONDA,
    0, // GIGANTAMAX_TOXTRICITY,
    0, // GIGANTAMAX_TOXTRICITY_LOW_KEY,
    0, // GIGANTAMAX_CENTISKORCH,
    0, // GIGANTAMAX_HATTERENE,
    0, // GIGANTAMAX_GRIMMSNARL,
    0, // GIGANTAMAX_ALCREMIE,
    0, // GIGANTAMAX_COPPERAJAH,
    0, // GIGANTAMAX_DURALUDON,
    0, // GIGANTAMAX_URSHIFU,
    0, // GIGANTAMAX_URSHIFU_RAPID_STRIKE,
    0, // MEGA_RAICHU_X,
    0, // MEGA_RAICHU_Y,
    0, // MEGA_CLEFABLE,
    1, // MEGA_VICTREEBEL,
    2, // MEGA_STARMIE,
    2, // MEGA_DRAGONITE,
    1, // MEGA_MEGANIUM,
    0, // MEGA_FERALIGATR,
    0, // MEGA_SKARMORY,
    0, // MEGA_CHIMECHO,
    0, // MEGA_ABSOL_Z,
    0, // MEGA_STARAPTOR,
    0, // MEGA_GARCHOMP_Z,
    0, // MEGA_LUCARIO_Z,
    0, // MEGA_FROSLASS,
    0, // MEGA_HEATRAN,
    0, // MEGA_DARKRAI,
    0, // MEGA_EMBOAR,
    0, // MEGA_EXCADRILL,
    2, // MEGA_SCOLIPEDE,
    0, // MEGA_SCRAFTY,
    0, // MEGA_EELEKTROSS,
    2, // MEGA_CHANDELURE,
    2, // MEGA_GOLURK,
    1, // MEGA_CHESNAUGHT,
    2, // MEGA_DELPHOX,
    0, // MEGA_GRENINJA,
    2, // MEGA_PYROAR,
    0, // MEGA_FLOETTE,
    0, // MEGA_MEOWSTIC,
    0, // MEGA_MEOWSTIC_FEMALE,
    0, // MEGA_MALAMAR,
    2, // MEGA_BARBARACLE,
    2, // MEGA_DRAGALGE,
    0, // MEGA_HAWLUCHA,
    0, // MEGA_ZYGARDE,
    2, // MEGA_CRABOMINABLE,
    2, // MEGA_GOLISOPOD,
    0, // MEGA_DRAMPA,
    0, // MEGA_MAGEARNA,
    0, // MEGA_MAGEARNA_ORIGINAL,
    0, // MEGA_ZERAORA,
    0, // MEGA_FALINKS,
    1, // MEGA_SCOVILLAIN,
    0, // MEGA_GLIMMORA,
    0, // MEGA_TATSUGIRI,
    0, // MEGA_TATSUGIRI_DROOPY,
    0, // MEGA_TATSUGIRI_STRETCHY,
    0, // MEGA_BAXCALIBUR
};

const u8 GetMonIconPaletteEx(u32 species, u32 form, u32 isEgg) {
    if (isEgg == TRUE) {
        if (species == SPECIES_MANAPHY) {
            species = 495;
        } else {
            species = 494;
        }
    } else if (species > MAX_SPECIES) {
        if (species >= SPECIES_LILLIPUP && species <= NUM_SPECIES) {
            species = species - SPECIES_LILLIPUP + FIRST_ADDED_PALETTE;
        } else {
            species = 0;
        }
    } else if (form != 0) {
        if (species == SPECIES_DEOXYS) {
            species = 496 + form - 1;
        } else if (species == SPECIES_UNOWN) {
            species = 499 + form - 1;
        } else if (species == SPECIES_BURMY) {
            species = 527 + form - 1;
        } else if (species == SPECIES_WORMADAM) {
            species = 529 + form - 1;
        } else if (species == SPECIES_SHELLOS) {
            species = 531 + form - 1;
        } else if (species == SPECIES_GASTRODON) {
            species = 532 + form - 1;
        } else if (species == SPECIES_GIRATINA) {
            species = 533 + form - 1;
        } else if (species == SPECIES_SHAYMIN) {
            species = 534 + form - 1;
        } else if (species == SPECIES_ROTOM) {
            species = 535 + form - 1;
        }
    }
    return sPokemonPalNoBySpeciesAndForm[species];
}

const u8 GetBattleMonIconPaletteEx(u32 species, u32 form, BOOL isEgg) {
    if (!isEgg) {
        if (species == SPECIES_CASTFORM) {
            if (form != 0) {
                return sPokemonPalNoBySpeciesAndForm[540 + form - 1];
            }
        } else if (species == SPECIES_CHERRIM) {
            if (form != 0) {
                return sPokemonPalNoBySpeciesAndForm[543 + form - 1];
            }
        }
    }
    return GetMonIconPaletteEx(species, form, isEgg);
}

const u8 Boxmon_GetIconPalette(BoxPokemon *boxMon) {
    BOOL encry;
    u32 species;
    u32 form;
    BOOL isEgg;

    encry = AcquireBoxMonLock(boxMon);
    form = BoxMonGetForm(boxMon);
    species = GetBoxMonData(boxMon, MON_DATA_SPECIES, NULL);
    isEgg = GetBoxMonData(boxMon, MON_DATA_IS_EGG, NULL);
    ReleaseBoxMonLock(boxMon, encry);
    return GetMonIconPaletteEx(species, form, isEgg);
}

const u8 Pokemon_GetIconPalette(Pokemon *mon) {
    return Boxmon_GetIconPalette(Mon_GetBoxMon(mon));
}

u32 sub_02074490(void) {
    return 0;
}

u32 sub_02074494(void) {
    return 2;
}

u32 sub_02074498(void) {
    return 4;
}

u32 sub_0207449C(void) {
    return 6;
}

u32 sub_020744A0(void) {
    return 1;
}

u32 sub_020744A4(void) {
    return 3;
}

u32 sub_020744A8(void) {
    return 5;
}
