#include "global.h"

#include "constants/trainer_class.h"

// The trainer classes the Hall's opponent comes from a third of the time, by
// the type board's category (the other two thirds by the rank: ov80_022372D8).
const u16 gBattleHallTypeTrainerClasses[18][4] = {
    { TRAINERCLASS_POKEFAN_M,       TRAINERCLASS_POKEFAN,         TRAINERCLASS_YOUNGSTER,       TRAINERCLASS_LASS            }, // Normal
    { TRAINERCLASS_VETERAN,         TRAINERCLASS_VETERAN,         TRAINERCLASS_POLICEMAN,       TRAINERCLASS_POLICEMAN       }, // Fire
    { TRAINERCLASS_TUBER_M,         TRAINERCLASS_TUBER_F,         TRAINERCLASS_SAILOR,          TRAINERCLASS_FISHERMAN       }, // Water
    { TRAINERCLASS_POKE_KID,        TRAINERCLASS_POKE_KID,        TRAINERCLASS_WORKER,          TRAINERCLASS_WORKER          }, // Electric
    { TRAINERCLASS_AROMA_LADY,      TRAINERCLASS_AROMA_LADY,      TRAINERCLASS_CAMPER,          TRAINERCLASS_PICNICKER       }, // Grass
    { TRAINERCLASS_ACE_TRAINER_M_GS, TRAINERCLASS_ACE_TRAINER_M_GS, TRAINERCLASS_ACE_TRAINER_F_GS, TRAINERCLASS_ACE_TRAINER_F_GS }, // Ice
    { TRAINERCLASS_BLACK_BELT,      TRAINERCLASS_BLACK_BELT,      TRAINERCLASS_BATTLE_GIRL,     TRAINERCLASS_BATTLE_GIRL     }, // Fighting
    { TRAINERCLASS_NINJA_BOY,       TRAINERCLASS_NINJA_BOY,       TRAINERCLASS_SUPER_NERD,      TRAINERCLASS_SUPER_NERD      }, // Poison
    { TRAINERCLASS_HIKER,           TRAINERCLASS_HIKER,           TRAINERCLASS_RUIN_MANIAC,     TRAINERCLASS_RUIN_MANIAC     }, // Ground
    { TRAINERCLASS_BIRD_KEEPER_GS,  TRAINERCLASS_BIRD_KEEPER_GS,  TRAINERCLASS_BIRD_KEEPER_GS,  TRAINERCLASS_BIRD_KEEPER_GS  }, // Flying
    { TRAINERCLASS_PSYCHIC_M,       TRAINERCLASS_PSYCHIC_M,       TRAINERCLASS_PSYCHIC_F,       TRAINERCLASS_PSYCHIC_F       }, // Psychic
    { TRAINERCLASS_BUG_CATCHER,     TRAINERCLASS_BUG_CATCHER,     TRAINERCLASS_BUG_CATCHER,     TRAINERCLASS_BUG_CATCHER     }, // Bug
    { TRAINERCLASS_HIKER,           TRAINERCLASS_HIKER,           TRAINERCLASS_RUIN_MANIAC,     TRAINERCLASS_RUIN_MANIAC     }, // Rock
    { TRAINERCLASS_PSYCHIC_M,       TRAINERCLASS_PSYCHIC_M,       TRAINERCLASS_PSYCHIC_F,       TRAINERCLASS_PSYCHIC_F       }, // Ghost
    { TRAINERCLASS_DRAGON_TAMER,    TRAINERCLASS_DRAGON_TAMER,    TRAINERCLASS_DRAGON_TAMER,    TRAINERCLASS_DRAGON_TAMER    }, // Dragon
    { TRAINERCLASS_ROUGHNECK,       TRAINERCLASS_ROUGHNECK,       TRAINERCLASS_GUITARIST,       TRAINERCLASS_GUITARIST       }, // Dark
    { TRAINERCLASS_REPORTER,        TRAINERCLASS_CAMERAMAN,       TRAINERCLASS_CYCLIST_M,       TRAINERCLASS_CYCLIST_F       }, // Steel
    { TRAINERCLASS_LASS,            TRAINERCLASS_POKEFAN,         TRAINERCLASS_BEAUTY,          TRAINERCLASS_LADY            }, // Fairy
};
